### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by telly-tubby** [EddieHubCommunity/support#1008]
Please invite me to the GitHub Community Organisation.

- #### Name: Garima Ghosh

- #### Discord Username(if exists): Garima Ghosh(P)#2008

- #### Additional Context: Found your channel on youtube

:nerd_face:

**Comment by chryzcodez** [comment]
@eddiejaoude, a bot was meant to reply him. I'm not seeing anything here!

**Comment by eddiejaoude** [comment]
@chryzcodez oh you are right 🤔 something went wrong. Let me take a look. Thanks for raising 🤓

**Comment by eddiejaoude** [comment]
Looks like they are part of the org already and I can see it on their profile. I will close the issue.

```
Validation Failed: {"resource":"OrganizationInvitation","code":"unprocessable","field":"data","message":"Invitee is already a part of this org"}
```

https://github.com/EddieHubCommunity/support/actions/runs/632304942
