### ISSUE TITLE
Please review my Resume

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#1014]
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- Link to [Resume](https://drive.google.com/file/d/1YRwuhduHqcPFRP0WhORFJ1Qptvu0Sx2g/view?usp=sharing)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by DevCassie** [comment]
Not sure if you've seen it in the YouTube comments, but this is what I would do:
* Vertical align the text with the circles and minimize the circles.
* Move the dates to underneath the experience for Education, Work Experience, and Voluntary Experience and add a little description of what the job was/is.
* It's hard to mention how good you are, so I would suggest removing the progress bars and use lists for example:
 ```
Languages
- Bulgarian
- English
```
or 
```
Languages
Bulgarian, English
```

* I suggest moving the socials like Github, Linkedin, etc to underneath the mail (underneath your photo).
* Under the socials section add the skills section so it comes in front of the languages block.
* Add a bit more contrast. For example, the yellow on the light grey background is harder to read. 
* As seen in the assets block I assume those are competencies, so perhaps change assets to competencies and add a bit more, like motivated, eager to learn?

**Comment by SashoStoichkov** [comment]
Thank you @DevCassie for the suggestions 😍  I'll take a look at them later

**Comment by DevCassie** [comment]
> Thank you @DevCassie for the suggestions 😍 I'll take a look at them later

Of course Sasho!

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by eddiejaoude** [comment]
Thanks for submitting @SashoStoichkov  and thank you @nhcarrigan for logging the live stream link and closing 👍
