### ISSUE TITLE
Review my Resume

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/support#1015]
Items we can review on a live stream: *I have added some other links too xD*

- [Resume](https://jai-dewani.github.io/tempFiles/Resume_Jai-3-2021.pdf)

Some extra links xD
- GitHub profile - [jai-dewani](https://github.com/jai-dewani)
- Portfolio - [jaid.tech](https://jaid.tech/)  *Still have to add the project's secton*

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by DevCassie** [comment]
I would suggest the following:
* Use a modern font in a modern age. Sans-serif fonts.
* Maybe add an accent color to headlines. Example: Education red.
* I'm not sure if it's possible to reduce text? It's quite a lot of text to read.

**Comment by jai-dewani** [comment]
Thanks a lot, @DevCassie ;) 
I have written them down and have also made a list of suggestions I got from the steam [here](https://twitter.com/jai_dewani/status/1366469192715657218)
