### ISSUE TITLE
Akshat Rana Resume

### ISSUE THREAD

**Issue by Akshat511716** [EddieHubCommunity/support#1016]
[Akshat's Resume.pdf](https://github.com/EddieHubCommunity/support/files/6063076/Akshat.s.Resume.pdf)
Items we can review on a live stream:

- GitHub profile
- Open-source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by DevCassie** [comment]
Things I would suggest are:

* Add the mail and phone number behind the icons, not underneath them.
![image](https://user-images.githubusercontent.com/19227530/109540677-1c7b8300-7ac3-11eb-8507-bfd95f86e266.png)
* Use your border-radius consistent. At the top dark blue rectangle, it's no border-radius, but in the skills and interests section, it has a border-radius.
* Perhaps change the width of your short introduction?
![image](https://user-images.githubusercontent.com/19227530/109540900-68c6c300-7ac3-11eb-9c2f-deea68b33e16.png)
* Use a variety of 2 - 3 colors. The text seems to always have the same color. To make some more visual hierarchy try recoloring the body text to a darker grey, something like #696969 or #303030 perhaps? But that's easier when you're working on it yourself.
