### ISSUE TITLE
Khushi Sharma Resume

### ISSUE THREAD

**Issue by KhushiSharma22** [EddieHubCommunity/support#1017]
[Khushi_Resume.pdf](https://github.com/EddieHubCommunity/support/files/6063081/Khushi_Resume.pdf)
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

https://www.youtube.com/watch?v=yoqm0K_V_1c

**Comment by DevCassie** [comment]
I would suggest the following:
* Add a bit of accent colour perhaps on the grey rectangles behind each section.
![image](https://user-images.githubusercontent.com/19227530/109556097-a5e88080-7ad6-11eb-8499-7df5d04646e8.png)
* Perhaps add a tagline of what you are/what job type you are applying for? Example: Software engineer
* Use a modern font. Preferably a Sans-Serif font. The image below is a older type font, which isn't a Sans-Serif font.
![image](https://user-images.githubusercontent.com/19227530/109556240-daf4d300-7ad6-11eb-863a-afde907a79fd.png)

**Comment by eddiejaoude** [comment]
Awesome the community are still giving feedback 🎉  thank you @DevCassie 💥
