### ISSUE TITLE
Review It Please.

### ISSUE THREAD

**Issue by govindtomariiit** [EddieHubCommunity/support#1019]
[govind_generated_resume.pdf](https://github.com/EddieHubCommunity/support/files/6063237/govind_generated_resume.pdf)
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
@govindtomariiit did you close this intentionally?

**Comment by eddiejaoude** [comment]
@404fixer please see @nhcarrigan question above ☝️ . If you would like it reviewed in a live stream, please re-open the issue
