### ISSUE TITLE
Review my resume

### ISSUE THREAD

**Issue by ritik307** [EddieHubCommunity/support#1020]
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile: https://github.com/ritik307
- Portfolio: https://ritik307.github.io/portfolio/#/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by rootritesh** [comment]
- Ur Github Profile is great
- In ur Portfolio, there is a gap between icons on the left side. Try to fix that.
![image](https://user-images.githubusercontent.com/57373623/109602109-e9c69e80-7b45-11eb-927c-297f7b70d720.png)
- Apart from this All Good.

**Comment by ritik307** [comment]
Sure will do that. thanks for the review🎉

**Comment by eddiejaoude** [comment]
Thanks for sharing, I will review in a future live stream. Great to see you are already getting community feedback 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/ugEJ8LBb1r0

Looks good, some thoughts...
- GitHub profile picture would be better if you or at least a unique cartoon character and the same on all social platforms
- great profile description and badges
- the graphs take up a lot of space
- banner text is missing `the` should be `...in the making`

**Comment by schmelto** [comment]
Like the profile may one suggestion from my side.

may remove the visit count, repos, commits -> already shown from github and most of the times inaccurate in the readmes

**Comment by ritik307** [comment]
@eddiejaoude @schmelto  Thanks for the review and I will surely work on the suggestions provided
