### ISSUE TITLE
Resume review

### ISSUE THREAD

**Issue by khushab** [EddieHubCommunity/support#1021]
[Mohammed_Khushab Alam_Resume_01-03-2021-22-59-59.pdf](https://github.com/EddieHubCommunity/support/files/6063363/Mohammed_Khushab.Alam_Resume_01-03-2021-22-59-59.pdf)
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by DevCassie** [comment]
I would suggest the following:
* Add a bit of an accent color don't overuse it though. Perhaps change the color of the grey rectangle behind the section headline.
![image](https://user-images.githubusercontent.com/19227530/109556933-b6e5c180-7ad7-11eb-9e7f-be97cc8fa097.png)
* Add a headline/tagline of what kind of job you are applying to? Example: Software engineer

**Comment by khushab** [comment]
> I would suggest the following:
> 
> * Add a bit of an accent color don't overuse it though. Perhaps change the color of the grey rectangle behind the section headline.
>   ![image](https://user-images.githubusercontent.com/19227530/109556933-b6e5c180-7ad7-11eb-9e7f-be97cc8fa097.png)
> * Add a headline/tagline of what kind of job you are applying to? Example: Software engineer

Thanks for suggestions. will do the changes accordingly :)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 - I will review in a live stream soon. I see you are already getting great community feedback 🎉

**Comment by schmelto** [comment]
I really like the link icons 
![image](https://user-images.githubusercontent.com/30869493/116906882-1fb8f980-ac41-11eb-9136-8969b76b1e4c.png)
may I will copy that from you 🚀

**Comment by rohank2502** [comment]
Education section can be improved !! Everything can be taken to one side because the right side will get ignore or far from reach of the left one and IF you like to keep it on the right only Do write the P of present capital!

**Comment by sreekaransrinath** [comment]
1. Change portfolio link to something that has your name - portfolio-3f554.web.app feels like a temp link.
2. Include start date and expected end date for education.
3. Personal preference, but remove schooling.

**Comment by rohank2502** [comment]
> Education section can be improved !! Everything can be taken to one side because the right side will get ignore or far from reach of the left one and IF you like to keep it on the right only Do write the P of present capital!

Skills section can  be improved by adding logos of tech that might look eye-catchy

**Comment by sreekaransrinath** [comment]
Love that email, github, and linkedin usernames are all the same

**Comment by sreekaransrinath** [comment]
![image](https://user-images.githubusercontent.com/50989977/116907244-f6a76180-ac5e-11eb-91c7-e97febceeb7b.png)
This bit of experience seems irrelevant if you're applying to SDE roles

**Comment by eddiejaoude** [comment]
Reviewed in live stream https://youtu.be/ugEJ8LBb1r0

Looks greats, some suggestions
- yay GitHub link 🎉 
- possibly add colours (but check how it looks printed in grayscale)
- great to have `personal projects` section and with links is super useful, but when printed the links are not visible, suggestion showing full links
- `interests` section is great 💪 
- tech skills might look better not in italics
- 1 page long is great 👍 
- portfolio url would be better if didn't have the random characters
- education to have start and end date

**Comment by rohank2502** [comment]
You can add colorful logo in header section

**Comment by khushab** [comment]
> I really like the link icons
> ![image](https://user-images.githubusercontent.com/30869493/116906882-1fb8f980-ac41-11eb-9136-8969b76b1e4c.png)
> may I will copy that from you 🚀

Absolutely :)

**Comment by khushab** [comment]
Thank you so much everyone <3
