### ISSUE TITLE
Review my Resume

### ISSUE THREAD

**Issue by touhidulShawan** [EddieHubCommunity/support#1023]
**Remove all personal data, otherwise, the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile : [Touhidul Shawan](https://github.com/touhidulshawan)
- Portfolio: [https://touhidulshawan.github.io/touhidulshawan](https://touhidulshawan.github.io/touhidulshawan/#/)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 . I will review on a live stream soon 🤓

**Comment by eddiejaoude** [comment]
@touhidulShawan did you mean to close this?

**Comment by touhidulShawan** [comment]
Sorry. @eddiejaoude I had to close this for some problem of mine 🙂
