### ISSUE TITLE
Here I go .Review my resume please.

### ISSUE THREAD

**Issue by suubh** [EddieHubCommunity/support#1024]
**Remove all personal data, otherwise the resume will be deleted.**
Review my resume [here](https://drive.google.com/file/d/1QJUUG_dWD8gmSGS7f_rMtWCwp6zrsKlj/view?usp=sharing).
(Edited)
Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by DevCassie** [comment]
As a designer, I see a lot of text with barely any differences between the sections, headlines, etc.
List of things I would suggest:
* Add color to headlines and bolder text for example Education could be red or blue.
* Use a modern font. Sans-serif fonts are used for modern times. But that's also personal preference.
* Perhaps add a tagline of what you are. Something like Software engineer.

**Comment by suubh** [comment]
Thank you @DevCassie  . Will work on the headlines and make it better and update the link .

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon. It looks like you are getting great feedback from the community already 🎉

**Comment by suubh** [comment]
I have updated the feedback . Will be great to know your review too . And awesome community 🔥.

**Comment by Prathamesh-Shanbhag** [comment]
### Things to consider!

**Comment by sreekaransrinath** [comment]
![image](https://user-images.githubusercontent.com/50989977/116908063-1723eb80-ac60-11eb-91f3-23b2ac72d4c6.png)
If your LinkedIn is not linkedin.com/in/shubham, don't write Linkedin: shubham

Remove schooling, it's unnecessary.
Love the single-column template.

![image](https://user-images.githubusercontent.com/50989977/116908416-81d52700-ac60-11eb-829b-e326355dc646.png)
This line in the header is unnecessary.

Portfolio link is a typo.

**Comment by rohank2502** [comment]
Links to your  Certificates can be added !! & you can also link hackerrank or such platform profile to the names where you added those !!

**Comment by eddiejaoude** [comment]
Reviewed in live stream https://youtu.be/ugEJ8LBb1r0

Looks good, some thoughts...
- great layout 👍 
- links are better written in full, so it is still viewable when printed
- project sections is great 👍 
- additional experience & achievements are awesome, try to make these stand out more
- after `,` a space is needed

**Comment by imabp** [comment]
Hello Eddie
I hope you are doing great.
Last time, my friend @ksdkamesh99 and me, were doing peer resume reviews...

Just wanted to know your views and feedback on the resume.
Here is the link: https://drive.google.com/file/d/10s2okbZm3IxofGVVFtOIbBVZnPfZysfU/view?usp=sharing

**Comment by sreekaransrinath** [comment]
- Personal preference but use a sans-serif font.
- Spacing before and after commas and periods is off.
-

**Comment by sreekaransrinath** [comment]
> Hello Eddie
> I hope you are doing great.
> Last time, my friend @ksdkamesh99 and me, were doing peer resume reviews...
> 
> Just wanted to know your views and feedback on the resume.
> Here is the link: https://drive.google.com/file/d/10s2okbZm3IxofGVVFtOIbBVZnPfZysfU/view?usp=sharing

Create a new issue Abir, that's the easiest way to get noticed :)

**Comment by eddiejaoude** [comment]
Yes each project/resume etc should be its own issue
