### ISSUE TITLE
Resume Review

### ISSUE THREAD

**Issue by adarshaacharya** [EddieHubCommunity/support#1028]
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile [link](https://github.com/adarshaacharya)
- Open source project [link](https://github.com/adarshaacharya/states-nepal)
- Portfolio [link](http://adarshaacharya.com.np/)
- Resume [link](https://drive.google.com/file/d/1hg8WQ0go6RrxXbVTUuq_MDQTnT8GtHDA/view?usp=sharing)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by adhavalboy** [comment]
remove the blank page and front should bold

**Comment by schmelto** [comment]
love your github profile 🤟🏼 
at your website I would remove the sound effects could be a little bit to much
as @adhavalboy mention remove the second page on your resume.

And I like the cat image at your github profile but to be recognized you can use the picture from your portfolio website

**Comment by adarshaacharya** [comment]
@adhavalboy  sure.

@schmelto  thank you for review. That sound effect is kinda crazy as when I saw that library I put it everywhere. I need to remove it on most parts. && ABout project links I will make them bold !!

Thank you guys for review. Other feedback would be much appreciated.

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon. It looks like you are getting great feedback from the community already 🎉

**Comment by adarshaacharya** [comment]
@eddiejaoude thank you ! It will be fun livestream to watch, especially this is the first time I'm reviewing my resume ! Please take a look at my portfolio site too.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions
- great releases, description, topics and link 
- suggest using GitHub actions for releases and releasing to npm
- possibly use a README in the `docs` directory to share more info about the docs
- suggest using issues
