### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by CreaTorAlexander** [EddieHubCommunity/support#1034]
**Description**

When getting invited to the community the link the bot is sending doesn't work

https://github.com/orgs/EddieJaoudeCommunity/people

I think the link should be

https://github.com/orgs/EddieHubCommunity/people

Raised a PR to fix this issue.https://github.com/EddieHubCommunity/support/pull/1036

**Comment by eddiejaoude** [comment]
Thank you for raising 👍
