### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Abhishek-kumar09** [EddieHubCommunity/support#1037]
Please invite me to the GitHub Community Organisation.

- #### Name: Abhishek Kumar

- #### Discord Username(if exists): `Abhishek Kumar#8177`

- #### Additional Context:
 

I met Eddie and the whole community during LiveStream on youtube, I am following them for more than  a month or two. Always inspired by the community and the collaboration work done by the whole.

:nerd_face:
There are many things I like specially about this community:
- No matter coder or not you can be the part of this.
- Really welcoming
- The vocal sound of Eddie
- The community members are really very helpful
- Love watching the youtube streams with different people as guests
- Specially loving the resume review

**Comment by eddiejaoude** [comment]
> No matter coder or not you can be the part of this.
Really welcoming
The vocal sound of Eddie
The community members are really very helpful
Love watching the youtube streams with different people as guests
Specially loving the resume review

Wow thank you @Abhishek-kumar09 for the amazing feedback 💥

**Comment by Vyvy-vi** [comment]
<3
