### ISSUE TITLE
Review my Resume

### ISSUE THREAD

**Issue by HariAcidReign** [EddieHubCommunity/support#1041]
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile : https://github.com/HariAcidReign
- Open source project : https://github.com/Team-ThreatLevelMidnight/Kanbanize
- Portfolio : https://hariacidreign.github.io/
- Resume : On the portfolio website

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by varghesejose2020** [comment]
great one @HariAcidReign

**Comment by HariAcidReign** [comment]
Thank you! Any scope for improvement in any of these links?

**Comment by rohank2502** [comment]
Really Impressed me a lot !! For a beginner like me, it's magic seriously !!

**Comment by HariAcidReign** [comment]
@rohank2502 @varghesejose2020 Thanks guys! :)

**Comment by varghesejose2020** [comment]
welcome  :blush:

**Comment by eddiejaoude** [comment]
@HariAcidReign did you mean to close the issue? I would still like to review on a live stream and give you a shout out for sharing

**Comment by HariAcidReign** [comment]
@eddiejaoude 100%! I would be honored if you could review my stuff on your stream. Thank you! 🙌🏻

**Comment by eddiejaoude** [comment]
Thanks for re-opening 👍 I will review on a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions
- suggest adding releases
- suggest using issues
- screenshots in readme are great but would look better if align
- suggest using GitHub Actions for automation
