### ISSUE TITLE
Resume Review

### ISSUE THREAD

**Issue by DevCassie** [EddieHubCommunity/support#1062]
Note that the email in my resume is my Github collaboration email. So it's not private.

The following items can be reviewed:

- [GitHub profile](https://github.com/DevCassie)
- [Resume](https://drive.google.com/file/d/1v8T6PmYNzHj1u886xHw8x0d5FDKpPG3k/view?usp=sharing)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by SashoStoichkov** [comment]
Hey @DevCassie 👋🏻 Finally the time has come ⌛
-

First of all 🚀 Great GH profile 💯 I really like it

I have just one comment regarding your resume:
-
The links that you have put there doesn't really stand out. I found that they are indeed links accidentally by hovering the cursor all over the page. Maybe you should indicate in some way that these are links OR to be separated from the title. (Here I'm not referring to the social links)

Thank you 👍🏻

**Comment by srinath1412001** [comment]
Your resume template looks nice!
It would be good to have the links to your projects (GitHub repo/ Demonstrations if any ) so that people could have a quick look at them.

**Comment by srinath1412001** [comment]
> Your resume template looks nice!
> It would be good to have the links to your projects (GitHub repo/ Demonstrations if any ) so that people could have a quick look at them.
Just realized you have already attached links

**Comment by srinath1412001** [comment]
> Your resume template looks nice!
> It would be good to have the links to your projects (GitHub repo/ Demonstrations if any ) so that people could have a quick look at them.

Just realized the links are attached

**Comment by DevCassie** [comment]
> > Your resume template looks nice!
> > It would be good to have the links to your projects (GitHub repo/ Demonstrations if any ) so that people could have a quick look at them.
> Just realized you have already attached links 

Agreed, I do indeed have links attached. It's just not visible yet. Not sure what I could do to make it visually look attractive haha. 

Any ideas @srinath1412001 ? 🤔

**Comment by SashoStoichkov** [comment]
> > ## Hey @DevCassie 👋🏻 Finally the time has come hourglass
> > First of all rocket Great GH profile 100 I really like it
> > ## I have just one comment regarding your resume:
> > The links that you have put there doesn't really stand out. I found that they are indeed links accidentally by hovering the cursor all over the page. Maybe you should indicate in some way that these are links OR to be separated from the title. (Here I'm not referring to the social links)
> > Thank you 👍🏻
> 
> I know. It sucks I used a design tool which doesn't allow hyperlinks sadly, so I had to do a manual workaround in another program.
> 
> So I was thinking of using a different kind of style. Not sure what yet though . Thanks for the insights.
> 
> Do you have an idea for the links perhaps @SashoStoichkov ?

Maybe adding a line which states something like: `Link for the project (or whatever)` and underlining it manually

**Comment by srinath1412001** [comment]
> > > Your resume template looks nice!
> > > It would be good to have the links to your projects (GitHub repo/ Demonstrations if any ) so that people could have a quick look at them.
> > > Just realized you have already attached links
> 
> Agreed, I do indeed have links attached. It's just not visible yet. Not sure what I could do to make it visually look attractive haha.
> 
> Any ideas @srinath1412001 ? 🤔

Maybe you could try underlining them / Have the headings in blue/ Have the whole link present (Example: https://github.com/username/repo)

**Comment by srinath1412001** [comment]
@SashoStoichkov stole my words lol

**Comment by DevCassie** [comment]
> > > ## Hey @DevCassie 👋🏻 Finally the time has come hourglass
> > > First of all rocket Great GH profile 100 I really like it
> > > ## I have just one comment regarding your resume:
> > > The links that you have put there doesn't really stand out. I found that they are indeed links accidentally by hovering the cursor all over the page. Maybe you should indicate in some way that these are links OR to be separated from the title. (Here I'm not referring to the social links)
> > > Thank you 👍🏻
> > 
> > I know. It sucks I used a design tool which doesn't allow hyperlinks sadly, so I had to do a manual workaround in another program.
> > 
> > So I was thinking of using a different kind of style. Not sure what yet though . Thanks for the insights.
> > 
> > Do you have an idea for the links perhaps @SashoStoichkov ?
> 
> Maybe adding a line which states something like: `Link for the project (or whatever)` and underlining it manually

Hmm, I'll take a look at it. Thank you!

**Comment by galahad42** [comment]
**Resume** : Looks awesome after the updates. Love the template design!

**GitHub profile** : Again looks awesome. There's one minor grammatical error I guess in the [Personal](https://github.com/DevCassie#personal) section.

>👨 -> Pronounces are he and him

I think you meant `Pronouns`. Maybe someone can raise an issue for it?

**Comment by DevCassie** [comment]
> **Resume** : Looks awesome after the updates. Love the template design!
> 
> **GitHub profile** : Again looks awesome. There's one minor grammatical error I guess in the [Personal](https://github.com/DevCassie#personal) section.
> 
> > 👨 -> Pronounces are he and him
> 
> I think you meant `Pronouns`. Maybe someone can raise an issue for it?

Oh right. Thanks for that! Someone could raise an issue. Or I'll just change it now 🤔

**Comment by galahad42** [comment]
> 
> 
> > **Resume** : Looks awesome after the updates. Love the template design!
> > **GitHub profile** : Again looks awesome. There's one minor grammatical error I guess in the [Personal](https://github.com/DevCassie#personal) section.
> > > 👨 -> Pronounces are he and him
> > 
> > 
> > I think you meant `Pronouns`. Maybe someone can raise an issue for it?
> 
> Oh right. Thanks for that! Someone could raise an issue. Or I'll just change it now 🤔

I raised an issue, so you can update it faster and I'm already behind on my green squares anyways 😄

**Comment by eddiejaoude** [comment]
Thanks for sharing, I will review on a live stream soon 👍 - looks like you got some good feedback already, great collaboration everyone  💪

**Comment by Rahma-AlWadhahi** [comment]
Really awesome resume @DevCassie. I would guess that you wrote your resume in Dutch first then translated it to English. I think that you might have missed translating `heden` to `present` in the first part of Education section as I saw all the others have `year-“present”` in them.

**Comment by DevCassie** [comment]
> Really awesome resume @DevCassie. I would guess that you wrote your resume in Dutch first then translated it to English. I think that you might have missed translating `heden` to `present` in the first part of Education section as I saw all the others have `year-“present”` in them.

Yep I did wrote it in Dutch first. Thanks for the spot 😁
