### ISSUE TITLE
Please review my project :)

### ISSUE THREAD

**Issue by SamDev98** [EddieHubCommunity/support#1075]
Items we can review on a live stream:

- GitHub profile: [SamDev98](https://github.com/samdev98)
- Open source project: [Password Manager - Python](https://github.com/SamDev98/password-manager-py)
- (If time permits I would be really thankful for a review on): [My portfolio website](https://www.sambhavrakhe.com)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)
   -  Done! :) **SweetPotato#0983**

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)
   - And done! :))

**Comment by Nitesh-thapliyal** [comment]
Little suggestion from my end: 

-  Add Screenshots of your project in the readme
-  Add a working demo of your Project in the readme

**Comment by SamDev98** [comment]
Thanks for the suggestions,
* The screenshots are present in the documentation.
* As for the working demo, it being a desktop application, I cannot deploy it.

**Comment by Nitesh-thapliyal** [comment]
I mean you can record a video of your application working and then make a gif which you can show in the readme

**Comment by SamDev98** [comment]
Will do, thanks!

**Comment by schmelto** [comment]
The link to your GitHub Profile in this issue does not work :(

## Profile

Find it a little bit confusing that you pin the project in the readme and in your pinned repositories.
Maybe you can do only one of those things.

## Project

Like the others submitted a gif / demo of the application would be nice in the readme.
I love the style of your documentation. But its little bit hidden and should be more present in the main readme.

Think there is a little styling issue.
![image](https://user-images.githubusercontent.com/30869493/111213660-49568c80-85d1-11eb-90f4-62bc663f2299.png)

Maybe you can also add a link on where to install Python3 (https://www.python.org/download/releases/3.0/) in the documentation.

**Comment by SamDev98** [comment]
@schmelto  Thanks for the detailed review! 
* I fixed the link, I didn't know it wasn't working before.
* I pinned the repo because I will be adding a lot more soon and I wanted this one to be on top separately so I've added it in my readme.
* The reason why the documentation seems a little hidden is because this repo will have multiple implementations and so I will have multiple docs linked to the main one soon, but I will keep this in mind for sure.
* About the styling issue, It's just how the tkinter grid system scales. I don't like the idea of absolute positioning. The search button is to search based on the tag selected so that was the workflow there. Tag -> Search. But I'm no UI/UX expert, i will see if there is something I can do here. 
* I will add the link to install python3 for sure. Thanks!

Thank you for all your suggestions!

Also, if you want to contribute by fixing any of these code or documentation issues you are welcome to create an issue and PRs on them.

**Comment by schmelto** [comment]
> * I fixed the link, I didn't know it wasn't working before.

🚀🚀🚀

> * About the styling issue, It's just how the tkinter grid system scales. I don't like the idea of absolute positioning. The search button is to search based on the tag selected so that was the workflow there. Tag -> Search. But I'm no UI/UX expert, i will see if there is something I can do here.

Yeah with this explanation this looks correct for me 🙈


> Also, if you want to contribute by fixing any of these code or documentation issues you are welcome to create an issue and PRs on them.

I will do that

**Comment by SamDev98** [comment]
@schmelto Can you check out my repo now? I merged some beta updates to main and changed the documentation as well. :)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓 - looks like you got great community feedback already 💥

**Comment by SamDev98** [comment]
Hey @eddiejaoude thanks so much, I'd really appreciate your review! And yes, I've love that people had suggestions for me :) I had one small favour to ask, would you please just take a quick look at my new [portfolio website](www.sambhavrakhe.com) as well? I would really like suggestions on that as well, if you have some time. It is very basic and won't take long to have a quick look!

**Comment by SamDev98** [comment]
And thanks again @schmelto for checking my repo out! :D

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions
- great first impressions, love the releases, description, topics etc
- suggest using conventional commit messages
- I feel there are too many badges at the top of the repo
-
