### ISSUE TITLE
Invalid-Channel Name in ReadMe File for EddieHub Discord Android UI

### ISSUE THREAD

**Issue by meenal21** [EddieHubCommunity/support#1079]
**Description**

Channel Name is removed but still referenced so it is being referenced as Invalid Channel Name in Discord Android UI.

**Screenshots**

![Screenshot_2021-03-14-16-39-25-476_com discord](https://user-images.githubusercontent.com/13515337/111066610-e805bf00-84e5-11eb-9e8c-46fb24a44068.jpg)

Also, I think this bug or issue is just in the Discord App on Android as in the Windows Discord it is being shown as <#deleted-channel>

**Comment by kcoder63** [comment]
thank you for raising the issue @meenal21 :)

**Comment by eddiejaoude** [comment]
Thank you 👍
