### ISSUE TITLE
Review my Resume and Open Source Project

### ISSUE THREAD

**Issue by cmulay** [EddieHubCommunity/support#1090]
Hello Folks !

Thought I could get some suggestions from our community can someone provide me genuine feedback/review  ?

- GitHub profile: [cmulay](https://github.com/cmulay/cmulay-v1)
- Portfolio: [here](https://cmulay.is-a.dev) 
- Portfolio Repo: [here](https://github.com/cmulay/cmulay.github.io)
- Open Source Project: [python-aio](https://github.com/cmulay/python-aio)

@eddiejaoude may be you could look and provide your thoughts / review as well ?

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

Thanks !

**Comment by schmelto** [comment]
## Portfolio

Looks really sick!

* The Point for the Mouse Pointer doesn't work very well (I would remove it) -> seems a little bit slow.
* I like the Idea of Links at the bottom, personally I would add a hover effect on the links to clarify those are links. I only got it the second time :)
* I really like you Projects side. Refreshing design 👍🏼 
* Your socials I would make the whole image clickable not only the blue name

Overall I really love your profile! Nice Work!

**Comment by cmulay** [comment]
I totally agree regarding the mouse pointer it really seems a bit slow, until you pointed I didn't noticed that much..thanks for the feedback I'll take all your suggestions in consideration and work on them.

Thanks @schmelto !!

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon - great to see you are getting community feedback already 🤓

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks great some thoughts:
- repo has `-v1` so not displayed on your profile
- love the banner
- firebase icon does not match
- icons in the banner are mis-leading
