### ISSUE TITLE
[REVIEW] Open source client project

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/support#1111]
Please review my open source project 

https://github.com/eddiejaoude/stargate

**Comment by schmelto** [comment]
* love the issues with emojis maybe I will rob this idea :)
* maybe add a contributing.md to the project (but think this is on the way https://github.com/eddiejaoude/stargate/pull/28)
* I think the installation instructions should be more at the top of the readme

**Comment by eddiejaoude** [comment]
Thanks for the feedback!

> love the issues with emojis maybe I will rob this idea :)

I stole this from @nhcarrigan 😂 

> I think the installation instructions should be more at the top of the readme

Good idea 👍

**Comment by nhcarrigan** [comment]
@schmelto I migrated the issue labels from the [Creative Commons standard](https://opensource.creativecommons.org/contributing-code/repo-labels/).

**Comment by eddiejaoude** [comment]
Thanks @schmelto . I am going to close this
