### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Simar05519** [EddieHubCommunity/support#1112]
Please invite me to the GitHub Community Organisation.

- #### Name:   Simarpreet Kaur

- #### Discord Username(if exists):   Simar(P)#7905

- #### Additional Context:
I met Eddie in code for cause livestream

 To gain experience, share knowledge and learn 

:nerd_face:

**Comment by rohank2502** [comment]
Welcome @Simar05519
