### ISSUE TITLE
Please review my project

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [EddieHubCommunity/support#1114]
Items we can review on a live stream:

- https://github.com/kaiwalyakoparkar
- https://github.com/kaiwalyakoparkar/sense-hacker
- https://kaiwalyakoparkar.github.io/
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓

**Comment by kaiwalyakoparkar** [comment]
Thank you very much @eddiejaoude :+1:

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks really great, some thoughts:
- hide the wiki tab
- hide packages
- use GitHub Actions for automation: stale issues, releases, changelog etc
- suggest having a introduction/overview video (you have a YouTuber in your @starlightknown )
- maybe reduce the screenshots, move to `docs` folder or create an animated gif
