### ISSUE TITLE
Please review my chatting application

### ISSUE THREAD

**Issue by Creatoon** [EddieHubCommunity/support#1118]
Items we can review on a live stream:

- Open source project - https://github.com/Creatoon/Jar-web-app

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓

**Comment by schmelto** [comment]
Lol 
![image](https://user-images.githubusercontent.com/30869493/119170047-026a9480-ba63-11eb-8939-53a95eae5b90.png)
There is eddies video

**Comment by Creatoon** [comment]
@schmelto so what ?

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks really great, some thoughts:
- use the repo link + description
- great you are using releases
- hide packages if not being used
- I think this file `{` is not needed
- great to have the screenshots in the readme
- if not using the wiki suggest hiding
- suggest having a lint command in `package.json` and running this as a GitHub action 
- use GitHub Action to create a release
