### ISSUE TITLE
Would love to know  how I can improve my opensoruce work and impact

### ISSUE THREAD

**Issue by anushkrishnav** [EddieHubCommunity/support#1141]
Items we can review on a live stream:

- GitHub profile :  https://github.com/anushkrishnav
- Open-source projects :  https://github.com/TesseractCoding/NeoAlgo and  https://github.com/TesseractCoding/Issue_Watcher
- Resume: https://anushkrishnav.rocks/assets/AnushKrishnaResume.pdf

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon 🤓

**Comment by anushkrishnav** [comment]
waiting for it !!

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks really great, some thoughts:
- GitHub/linkedin icons are not consistent, suggest having both in color or grey scale
- if the resume is printed github/linkedin/project links are not visible
- great to see the open source projects on your resume
- is there a link for `Mentor at Girl Script Summer of Code 2021`
-
