### ISSUE TITLE
A favorite project of mine for review

### ISSUE THREAD

**Issue by aleks-ivanov** [EddieHubCommunity/support#1142]
Name: Notepads
GitHub repo: https://github.com/JasonStein/Notepads

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks really great, some thoughts:
- Project roadmap is `TBD` from May 2020
- If wiki is not being used, suggest removing it
- great screenshots
- suggest hiding packages if not used
- suggest using issue labels
