### ISSUE TITLE
Data sciene mashup

### ISSUE THREAD

**Issue by Jayshah6699** [EddieHubCommunity/support#1143]
Items we can review on a live stream:

- GitHub profile
- Open source project : https://github.com/Jayshah6699/datascience-mashup
- Portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon 🤓

**Comment by Jayshah6699** [comment]
Any suggestions?

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- potentially group folders together in to sub folders
- folder naming convention is inconsistent, some are spaces, some have `-` and others with `_`
- looks great, over 1k commits, but suggest creating some releases
