### ISSUE TITLE
Please review my open-source project!

### ISSUE THREAD

**Issue by adarshaacharya** [EddieHubCommunity/support#1144]
Items we can review on a live stream:

- Open source project : http://github.com/adarshaacharya/states-nepal

**Please review my github workflow too.**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Love it! Nothing to complain from my side 🚀

**Comment by adarshaacharya** [comment]
Thank you @schmelto .

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon - great to see you are getting community feedback already 🤓

**Comment by kaiwalyakoparkar** [comment]
- Remove project/wiki if not using
- Add PR template

**Comment by rohank2502** [comment]
###  You can add badges with the social media link will reduce space and look attractive just a suggestion 
![Screenshot 2021-05-28 213827](https://user-images.githubusercontent.com/76584243/120012502-37e02680-bffd-11eb-943a-cc0d76e63154.png)

## Liked that you are using actions great !! 
![Screenshot 2021-05-28 213912](https://user-images.githubusercontent.com/76584243/120012540-42022500-bffd-11eb-8cb3-10a9e24258ce.png)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- suggest using issues with labels, great way to get people involved and discovering the project 
- if not using the wiki, suggest hiding
- if not using packages, suggest hiding
- possible running the linter in a GitHub Action

**Comment by adarshaacharya** [comment]
Thank you guys !
