### ISSUE TITLE
Review my project

### ISSUE THREAD

**Issue by sakshi-1604** [EddieHubCommunity/support#1145]
https://github.com/sakshi-1604/InstagramClone

**Comment by schmelto** [comment]
Hey @sakshi-1604 some thoughts :

- add a license
- add a contributing.md
- add a first release
- maybe make the signin and login button the same style (screenshots)
- maybe a how to start / build the project would be nice
- nice that you use screenshots

**Comment by sakshi-1604** [comment]
@schmelto  thanks for your advice...I will surely implement them

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon - great to see you are getting community feedback already 🤓

**Comment by kaiwalyakoparkar** [comment]
- Hide release/packages section
- Add the following
  - Code of conduct
  - Contributing
  - Writing contributing guidelines
  - License
  - Issue templates
  - Pull request template
  - Remove wiki/ project if not using
  -

**Comment by rohank2502** [comment]
You can include some of your experience or projects in readme !! 
Add Eddiehub to organization in Github profile 

Read me of the project can be more better as you have only added ss but there should be some details like info about project releases etc !!

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- join EddieHub GitHub Org 😉 
- Suggest having a GitHub profile picture
- hide releases, packages, wiki if not being used
- Readme could benefit from quickstart guide
- Also using the issues section will help people discover and get involved in the project
