### ISSUE TITLE
Review my robot-perception open-source repo 

### ISSUE THREAD

**Issue by oarriaga** [EddieHubCommunity/support#1147]
https://github.com/oarriaga/paz

thank you! :)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 I will review on a live stream soon  🤓

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- great to see issues and pull requests used
- suggest removing stale branches
- code of conduct
- table of contents is not needed anymore as GitHub has this as a feature now
PS. great README 💥
