### ISSUE TITLE
Resume Review

### ISSUE THREAD

**Issue by Rishit-dagli** [EddieHubCommunity/support#1158]
**Remove all personal data, otherwise the resume will be deleted.**

This is the first time I am building a resume and I would really appreciate it if you could review it!

Items we can review on a live stream:

- [GitHub profile](https://github.com/Rishit-dagli)
- [Resume](https://github.com/EddieHubCommunity/support/files/6201242/Rishit.Dagli.Resume.pdf)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 , I will review on a live stream soon 🤓

**Comment by Prince-Shaikh** [comment]
I suggest you change the colors on the squared banner, It's not really readable.

**Comment by Rishit-dagli** [comment]
Hi @Prince-Shaikh ,
Thanks for pointing these out
- Replied in https://github.com/Rishit-dagli/Rishit-dagli/issues/5
- Yeah, the spacing might be a little less, but I wasn't able to fit all the content with increasing the spacing in 2 pages. Do you have any ideasfor it?

**Comment by Prince-Shaikh** [comment]
-> Maybe add some visual representations for skills? (Something like a bar chart)
-> Try reducing the font sizes a bit of the current version, that should give other text some breathing room.
-> also use a different font, this one is light so it gets harder to read it.

Hope I was able to help 🙂

**Comment by khushab** [comment]
My suggestion is to move the experience section on the first page. Also, I think 3-4 projects is enough in a resume, so maybe list only your top 4 projects,

**Comment by Rishit-dagli** [comment]
Thanks, @Prince-Shaikh , sure I could try doing 2nd and 3rd however I was a bit reluctant about adding a chart since it poses the question how do you calculate a percentage or some numeric quantity for your skills?

**Comment by Rishit-dagli** [comment]
> My suggestion is to move the experience section on the first page. Also, I think 3-4 projects is enough in a resume, so maybe list only your top 4 projects,

Thanks @khushab , I could definitely try to reduce the number of projects. I should have been clearer about this, but I am planning to send this over to universities so I might remove the "Experience" section too.

**Comment by schmelto** [comment]
Love it maybe on thing in dark mode take a look at the technologies badges
![image](https://user-images.githubusercontent.com/30869493/120016039-69002d00-bfe4-11eb-9862-3f459a1198ad.png)
there is some white space

**Comment by rohank2502** [comment]
![Screenshot 2021-05-28 221147](https://user-images.githubusercontent.com/76584243/120015999-b17a1380-c001-11eb-867b-467b63b82aa9.png)

A small Description of 1-2 lines can be added ! That will make people to jump more people on blog !

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- maybe remove the link for the google maps as it is another call to action that could be distracting
- badge styles do not match
- GitHub followers badge is a duplicate, might be distracting
- possible put blog post links and GitHub stats graph next to each other to save space
