### ISSUE TITLE
[REVIEW] Open Source Project Review

### ISSUE THREAD

**Issue by Rishit-dagli** [EddieHubCommunity/support#1172]
Items we can review on a live stream:

I have been working on these two open-source projects in the past month and half or so, as Eddie mentioned it would be better to create an issue here on top of implementing the tips he and Nicholas mentioned on growing open-source projects.

- [GitHub profile](https://github.com/Rishit-dagli)
- Open-source projects:
  * https://github.com/Rishit-dagli/MIRNet-TFJS
  * https://github.com/Rishit-dagli/Gradient-Centralization-TensorFlow

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 , I will review on a live stream soon 🤓

**Comment by schmelto** [comment]
Consider removing the Github badges showing how many forks, stars, etc there are cause those are duplicate with what github already shows

![image](https://user-images.githubusercontent.com/30869493/122218626-eb2a9580-ceae-11eb-94a5-501941d578c1.png)

**Comment by eddiejaoude** [comment]
Thank you for sharing, reviewed on live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts....
- Love the quote about the contribution graph, suggest putting above badges
- Next to the GitHub stats, suggest making use of the white space to right
- It is not too long, which I really like
-
