### ISSUE TITLE
Cross guild collab video 💥 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/support#1215]
Lets create a video like this across guilds https://www.youtube.com/watch?v=WX98l9rBHiE

1. Write big and clearly on a **white** A4 paper 1 - 3 words to describe the MLH Hackathon

**video steps to record**
1. catch paper
2. open paper
3. hold up paper
4. crumble paper
5. throw paper

**specs**
- landscape

*note: video will be edited, so do not worry about making it perfect*

Original discussion https://github.com/EddieHubCommunity/support/discussions/1160#discussioncomment-538380 (great suggestion @Nitesh-thapliyal )

**Drop a link to your video below by 11pm BST to be included** 👇

**Comment by kaiwalyakoparkar** [comment]
Is there any demo video :question:

**Comment by kcoder63** [comment]
[YouTube video](https://youtu.be/WX98l9rBHiE) here

**Comment by KhushiSharma22** [comment]
Here is the link to my video - https://drive.google.com/file/d/1ORheEQPpzvCKtCRrLBRwuvsMLHGRpBQl/view?usp=drivesdk

**Comment by PranavTheChampKataria** [comment]
Here's my video link : https://drive.google.com/file/d/15J-ArOgLCUUs4tGDfNwW0VxNeKp53DtQ/view?usp=sharing

**Comment by siddharthdayalwal** [comment]
Here is a link to my video: https://drive.google.com/file/d/1Hpu9YkiNEXycDxStWJdV8GQo7AS7GIzC/view?usp=sharing

My Camera was on for the entire video-making process, see if you want to use it somewhere! 

Shot various elements
- Searching on the Internet
- Thinking while shooting
- Writing the message
- Actual Video which was asked

Best.

**Comment by HarshitAditya27** [comment]
Here's the link to my video : https://drive.google.com/file/d/1AnxBknP7300x_GKQ_PTFiMCVZ-IbnLYl/view?usp=sharing

**Comment by sudiptog81** [comment]
Here is my video: https://drive.google.com/drive/folders/1drHG9ozldykjcXzoKVMMwBqIuGe4mTFc?usp=sharing

**Comment by nishant-rajput** [comment]
Here's my video link:
https://drive.google.com/file/d/1pMectXnnjQ8Q-jnLrpktshy77MV1Swo2/view?usp=drivesdk

With ♥️ from CodXCrypt

**Comment by saumya66** [comment]
No one was up so bounced it off the wall and cut it 😄
Hope it works  : https://drive.google.com/file/d/1cjycBb5qygmvgDpEmlTslSjUOyqDgxs6/view?usp=drivesdk

**Comment by lipishagupta** [comment]
Here's the link to my video : https://drive.google.com/file/d/1UoHQcorL8GsZLv8mgTS2Cdgp93wxuUaU/view?usp=sharing
#CodXCrypt

**Comment by datta-soumil** [comment]
Here is my video https://drive.google.com/file/d/1gCJIiqDLLR8pj9Aq0CD1pa4ZQrT-Zw4C/view?usp=sharing
#CodXCrypt

**Comment by anushkrishnav** [comment]
Veideo link is [here](https://drive.google.com/file/d/10zQ1srSNUbwBNSuACaDlK9CbP8oS-GBt/view?usp=sharing)

**Comment by nishant-rajput** [comment]
Here's my video:
https://drive.google.com/file/d/1pc4yJ-bopMQCpwn9rP_xs4BWcKHPvk2h/view?usp=sharing

**Comment by dj107** [comment]
Here is my video:  [Cross Community Collab Video](https://drive.google.com/file/d/1LNzpDUUNi63ErnTnu3DSDlyKCMzoCWBK/view?usp=sharing)
#DeveloperStudentCommunity

**Comment by kcoder63** [comment]
Link to my video, please don't laugh at it challenge 
[Video link](https://drive.google.com/file/d/1Lhg6-vE_roH1ZhAE2U6j0-jxg1ALXoK4/view?usp=drivesdk)

**Comment by kaiwalyakoparkar** [comment]
What message we have to write on paper?

**Comment by Nitesh-thapliyal** [comment]
Here is my video [collab-video](https://drive.google.com/file/d/1PqDtWdwI3AR1eF6GQJF76C-TBv0KbCj0/view?usp=sharing)

**Comment by Nitesh-thapliyal** [comment]
> What message we have to write on paper?
Anything about community, Collaboration, etc

**Comment by unnati914** [comment]
My video 

https://drive.google.com/file/d/15JCvYd_LpFUCFbZq22zEtFzIBp9ZydIf/view?usp=drivesdk

**Comment by eddiejaoude** [comment]
I have locked the issue, the video haas already been created about 1 hour ago, sorry late submissions can not be added

**Comment by Vyvy-vi** [comment]
https://www.dropbox.com/s/418i132zuqkys0e/Eddiehub%20copy.mp4?dl=0
https://www.dropbox.com/s/yhpqgh9tbyq3fyq/Eddiehub_LHD_Reversed_Green.mp4?dl=0
https://www.dropbox.com/s/mhthlbilufr2wap/EddieHub_LHD_Share-Reversed.mp4?dl=0

:P It's bad but hoodie + MLH mask... I thought why not add a green tint

**Comment by eddiejaoude** [comment]
Sorry we could not include everyone - we will do more in the future if people like this idea 🤓

**Comment by eddiejaoude** [comment]
YouTube video https://www.youtube.com/watch?v=O6MYGHrI8VQ
