### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by bhaskarwagatakar** [EddieHubCommunity/support#1228]
**Github Profile Link:**
<https://github.com/bhaskarwagatakar>

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Hi @bhaskarwagatakar , did you mean to close this?

**Comment by bhaskarwagatakar** [comment]
Yes

**Comment by schmelto** [comment]
@bhaskarwagatakar
Oh no that's pity. But maybe one little thig about your profile. Think the point at my accedemic life is wrong. Maybe take a look at this :) 

![Screenshot_20210501_090402.jpg](https://user-images.githubusercontent.com/30869493/116774325-35b99500-aa5c-11eb-90a6-6da3fdc97e5a.jpg)

**Comment by bhaskarwagatakar** [comment]
Sorry, I don't understand, why you mean? May you elaborate, please?

**Comment by schmelto** [comment]
At the end of your profile readme the "My accademic life.here" I think the `.` between `life` and `here` is wrong and should be after `here`

**Comment by bhaskarwagatakar** [comment]
Ok got it, thanks.
