### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by Bryson69** [EddieHubCommunity/support#1232]
**Github Profile Link:**
https://github.com/Bryson69

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by vinzvinci** [comment]
Hi @Bryson69, it's great to see you here.

I have some suggestions that may help you:
- Add cover photo or GIF `(that will help your github profile looks standout) `
- Try add more features in your GitHub profile like `github-streaks` `github-profile-stats` and etc.

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a live stream when time allows :)

**Comment by rohank2502** [comment]
![Screenshot 2021-05-28 222332](https://user-images.githubusercontent.com/76584243/120017293-5a753e00-c003-11eb-8f46-44615ad342ad.png)

I am going to copy this :)  Hope you don't  mind 👍🏻 

You can add few more lines in about me that will be impressive !!

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/h0UN06O4YIc

Looks great, some thoughts...
- really really great 💥 
- small suggestion, maybe reduce the banner high as it takes a lot of the page
- I need to borrow some of your profile ideas 🤓

**Comment by vinzvinci** [comment]
Feel free @rohank2502. Thanks for reviewing @eddiejaoude👍 Finally, I have something to do on my profile.
