### ISSUE TITLE
[REVIEW] Bravecms

### ISSUE THREAD

**Issue by Ajax30** [EddieHubCommunity/support#1236]
**Github Profile Link:**

Please review **[BraveCMS](https://github.com/Ajax30/Bravecms)**. Thank you!

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by schmelto** [comment]
Hey nice project.

some suggestions:
- add a release
- remove packages if not needed
- hide the wiki if not needed/used
- use  badges in the issues

**Comment by Ajax30** [comment]
> Hey nice project.
> 
> some suggestions:
> 
> * add a release
> * remove packages if not needed
> * hide the wiki if not needed/used
> * use  badges in the issues

Hi. I do not think I have unused packages. But if you see any, please let me know. Thanks!

**Comment by schmelto** [comment]
> > Hey nice project.
> > 
> > some suggestions:
> > 
> > * add a release
> > * remove packages if not needed
> > * hide the wiki if not needed/used
> > * use  badges in the issues
> 
> Hi. I do not think I have unused packages. But if you see any, please let me know. Thanks!

![Screenshot_20210616_231129.jpg](https://user-images.githubusercontent.com/30869493/122294328-37e68e80-cef8-11eb-8aef-0bc79f1738e5.jpg)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- Suggest using releases / tags
- If not using packages, suggest hide until ready to use
- If not using the wiki, suggest hiding
- Missing code of conduct
- Suggest having some issue templates, for example bug, feature, ideas
- Great to have screenshots and video in the README!
- Suggest having a QuickStart section in the README
- Suggest using conventional commit log for commit messages
- Suggest using Issue section
