### ISSUE TITLE
[REVIEW] Hey, I am Yash. Please Review my GitHub Profile

### ISSUE THREAD

**Issue by yashsehgal** [EddieHubCommunity/support#1238]
**Github Profile Link:**
https://github.com/yashsehgal

You can also join the discord community [here](https://discord.gg/sjQpXqtF)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Really like it.

Two additions:

1. the social links are not visible in Github Dark mode
![image](https://user-images.githubusercontent.com/30869493/113600878-eccf1600-9640-11eb-8465-98f4208ec5e7.png)
2. I would make the "Headings" with # and not with quotations

**Comment by yashsehgal** [comment]
Yeah, You are right!
I will do the respective changes.

Also. Will, my Profile be reviewed on YouTube??

**Comment by schmelto** [comment]
> Yeah, You are right!
> I will do the respective changes.
 Nice thx


> Also. Will, my Profile be reviewed on YouTube??

Eddie should be review it on a live streem soon I think. But this will take some time I think. 
But if it was reviewed in a Livestream you will get an other comment from Eddie here

**Comment by yashsehgal** [comment]
Oh that's great :)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by yashsehgal** [comment]
I am closing this issue from my side. As my profile has already been reviewed on the live stream. ✅

**Comment by eddiejaoude** [comment]
thanks @yashsehgal 👍
