### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by AbhijithNT** [EddieHubCommunity/support#1248]
**Github Profile Link:**

https://github.com/AbhijithNT

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Think you should add the link to your profile in the description (https://github.com/AbhijithCloud)

I like that you link to your Telegram :)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by schmelto** [comment]
Looks a little bit like mine. Like it! 🚀

**Comment by Sam-Varghese** [comment]
Clicking the Facebook icon shows this on my laptop

![image](https://user-images.githubusercontent.com/79152648/122220109-a95d1780-cecd-11eb-9cfd-8e78a1a35582.png)

Clicking the Instagram icon shows this

![image](https://user-images.githubusercontent.com/79152648/122220279-ceea2100-cecd-11eb-97cd-2a7a0205800b.png)

And clicking the Telegram icon shows this

![image](https://user-images.githubusercontent.com/79152648/122220390-ea552c00-cecd-11eb-9458-85afe9178fa0.png)

**Comment by AbhijithNT** [comment]
@Sam-Varghese  Thank you

**Comment by AbhijithNT** [comment]
> Clicking the Facebook icon shows this on my laptop
> 
> ![image](https://user-images.githubusercontent.com/79152648/122220109-a95d1780-cecd-11eb-9cfd-8e78a1a35582.png)
> 
> Clicking the Instagram icon shows this
> 
> ![image](https://user-images.githubusercontent.com/79152648/122220279-ceea2100-cecd-11eb-97cd-2a7a0205800b.png)
> 
> And clicking the Telegram icon shows this
> 
> ![image](https://user-images.githubusercontent.com/79152648/122220390-ea552c00-cecd-11eb-9458-85afe9178fa0.png)


This is fixed

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- Code in profile looks great, maybe have a bio string added to the method call
- Suggest adding more info about yourself to stand out more
