### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by nikitadudhbhate** [EddieHubCommunity/support#1251]
**Project Link:**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Hey @nikitadudhbhate think you forgot to add the project link. And maybe you can also specify the issue title a little bit more 🚀

**Comment by kcoder63** [comment]
Why's the label missing on this one? 🤔

**Comment by SashoStoichkov** [comment]
@starlightknown The fix is right here #1282 😉

**Comment by starlightknown** [comment]
Awesome!

**Comment by nhcarrigan** [comment]
Hey there @nikitadudhbhate,

Please update your issue body to include the link for the project you would like us to review.

**Comment by kaiwalyakoparkar** [comment]
Hey @nikitadudhbhate, It would be great if you add the link to your project in the issue description by editing it. We would love to see your project :smile:

**Comment by schmelto** [comment]
Hey @nikitadudhbhate I would close this issue now. 
Feel free to reopen it or open a new one when adding a project link etc. and you want to get a livestream review for it :)
