### ISSUE TITLE
[REVIEW] @KKhushhalR2405

### ISSUE THREAD

**Issue by KKhushhalR2405** [EddieHubCommunity/support#1262]
**Github Profile Link:**
[Link](https://github.com/KKhushhalR2405)
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by KKhushhalR2405** [comment]
I want to join your open source community. What should I do for that 😸

**Comment by schmelto** [comment]
> I want to join your open source community. What should I do for that 😸 

Here in the support repo open an issue with type "invite me to the organization"

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- Great bio
- Suggest removing the text editors section as does not really add much value
- Suggest removing the Mario gif, it looks cool, but takes up a lot of space
- Is that really the number of GitHub profiles?
