### ISSUE TITLE
[REVIEW]: Please review my Open Source Project

### ISSUE THREAD

**Issue by yashsehgal** [EddieHubCommunity/support#1263]
**Project Link:**
https://www.github.com/DesignSystemsOSS/eccentrictouch

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by schmelto** [comment]
Nice one. Labels on issues I like it!

some suggestions:

- remove the Version Releases in the Readme due those could be found also in releases https://github.com/DesignSystemsOSS/eccentrictouch/releases
- remove the view of the package due ist not needed
![image](https://user-images.githubusercontent.com/30869493/122219722-02b64e00-ceb0-11eb-8af9-af13ba157a95.png)

**Comment by yashsehgal** [comment]
Sure! Thanks for the suggestions @schmelto 👍🏽

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- You have releases/tags 🎉 
- Suggest hiding packages if not using that section
- Not sure about screenshots from the docs, could there be a screenshot from an example project 
- Suggest using conventional commit messages
