### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by gokulnair2001** [EddieHubCommunity/support#1264]
**Project Link:**

* This is my project Called [Loafjet](https://github.com/Loafjet/Loafjet) , All the details are mentioned in the Readme file.
Have a look and do suggest what changes can I make to bring more contributors!

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
@gokulnair2001 did you mean to close this?

**Comment by gokulnair2001** [comment]
nope, actually I was not getting any response so......sorry for the inconvenience :)
