### ISSUE TITLE
discord-readme.md file update

### ISSUE THREAD

**Issue by guy-patrick** [EddieHubCommunity/support#1266]

**Comment by nhcarrigan** [comment]
Hey there,

Could you update your issue to provide more details? We've recently merged a PR to update this file, so please provide information on anything else that needs updated.

**Comment by kaiwalyakoparkar** [comment]
@guy-patrick It would be great if you provide the information of what needs to be updated in the readme. Kindly edit the description of the issue so that this conversation can go ahead!

**Comment by schmelto** [comment]
Hey @guy-patrick I would close this one due missing details. Feel free to reopen the issue if there is any additional information :)
Hope this is ok for you
