### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by UG-SEP** [EddieHubCommunity/support#1268]
**Github Profile Link:**
[Profile Link](https://github.com/UG-SEP)
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Hey @UG-SEP ,

maybe you can specify the issue title with your name 🚀 

Some thoughts about your profile:

* Personally I would prefer that those are always be visible.
![image](https://user-images.githubusercontent.com/30869493/114264651-66258a80-99ec-11eb-93d1-1696f9300d4d.png) 

* Don't know if this was intent from you but I would remove the line behind the colon.
![image](https://user-images.githubusercontent.com/30869493/114264688-9a00b000-99ec-11eb-94d1-c2b4c5bdbab0.png)

* You have two times connect with me on you profile. Think one time is enough 🤔 

* Overall from my point of view a really solid GitHub profile 💪🏼

**Comment by UG-SEP** [comment]
thanks you i will correct all the request given from you @schmelto
