### ISSUE TITLE
[REVIEW] - Open Source Project

### ISSUE THREAD

**Issue by felixfaisal** [EddieHubCommunity/support#1276]
**Project Link:**
https://github.com/felixfaisal/formica

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Thanks for adding the project review to the issues of the related [discussion ](https://github.com/EddieHubCommunity/support/discussions/1273)

My thougts:

- love the gifs in the readme
- maybe you can add some prerequisites like installed docer etc. To the readme
- maybe add or draft a release
- for an open source project I think it would be nice to have some issue templates. Saw there is a PR template issue (https://github.com/felixfaisal/formica/issues/1) nice 💪🏼
- maybe take a look at the bottom of your Readme there is a broken or missing image ![Screenshot_20210410_231549.jpg](https://user-images.githubusercontent.com/30869493/114284802-bdf6dc80-9a52-11eb-93d3-959262d95721.jpg) I've opened a new issue for that https://github.com/felixfaisal/formica/issues/40

**Comment by vinzvinci** [comment]
I have small suggestion:

- Add tags in your repo
![image](https://user-images.githubusercontent.com/73097560/115110570-b2556980-9fae-11eb-99d6-4a40d2d1d765.png)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- suggest removing old and merged branches
- suggest removing the wiki if not being used
- possible squash commits from PRs to keep history clean
- suggest using conventional commits to have a clean history and to create the changelog in the release
