### ISSUE TITLE
Join Your community

### ISSUE THREAD

**Issue by bereketgodebo** [EddieHubCommunity/support#1290]
I would like to join your community ❤️. Excited to get started ✨

**Comment by schmelto** [comment]
Hey @bereketgodebo

Can you open an issue with this template? 

![Screenshot_20210413_085351.jpg](https://user-images.githubusercontent.com/30869493/114509499-da9f3a00-9c35-11eb-97ce-2c710cb840bd.jpg)

This will automatically add you to the GitHub organization. If you need any help please feel free to ask.

**Comment by schmelto** [comment]
Think you can close this issue now since I saw you have opened the issue with the right template https://github.com/EddieHubCommunity/support/issues/1291

**Comment by bereketgodebo** [comment]
thanks @schmelto
