### ISSUE TITLE
invite me to the GitHub Community Org

### ISSUE THREAD

**Issue by Codedrian** [EddieHubCommunity/support#1295]

**Comment by schmelto** [comment]
Hey @Codedrian can you please open an issue with the type "invite me to the GitHub organization" for this one? Thanks 🙈 if you need any help feel free to ask

**Comment by eddiejaoude** [comment]
Thank you @schmelto 👍 closing this as a new issue was created https://github.com/EddieHubCommunity/support/issues/1297

**Comment by Codedrian** [comment]
Done mate. Am I accepted?

**Comment by Codedrian** [comment]
Thank you @eddiejaoude. Excited to work with y'all!
