### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by GaryNLOL** [EddieHubCommunity/support#1300]
**Github Profile Link:**

[Link](https://github.com/GaryNLOL)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by vinzvinci** [comment]
Cool, I have suggestions:

- Put cover photo or gif below of `GaryNLOL codes his way into the battle!` (see my profile, so u can understand)
- Try to improve the layout design of your GitHub profile
- Keep improving and designing your GitHub profile to standout (^_^ this is what we do as always)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by GaryNLOL** [comment]
Thank you very much for your feedback! I will consider it and continue improving my GitHub profile.

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- banner takes a lot of vertical space, suggest reducing the height
- great use of space in your GitHub profile
- suggest putting one of your connection links in your GitHub bio
