### ISSUE TITLE
[REVIEW] - Portfolio Site

### ISSUE THREAD

**Issue by Harshal0902** [EddieHubCommunity/support#1308]
Portfolio link: https://harshal09.herokuapp.com
My GitHub profile : https://github.com/Harshal0902

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Link to the minecraft game is not right

**Comment by Harshal0902** [comment]
Thank you, @schmelto for telling about this, the links has been added.

**Comment by LoopGlitch26** [comment]
You can have a little bit more distance between Education and Experience column

**Comment by Harshal0902** [comment]
Thank you @LoopGlitch26 for suggestion, I have made the necessary changes.

**Comment by schmelto** [comment]
Some suggestions from my side.

* maybe add a label to the darkmode toggle
* take a look at the navbar (responsive width <= 1000) 
![image](https://user-images.githubusercontent.com/30869493/115141839-baf58080-a03e-11eb-85c8-8ed51283ba6d.png)
* tech I'm familiar with -> maybe center those icons
![image](https://user-images.githubusercontent.com/30869493/115141873-ed9f7900-a03e-11eb-96c9-69737daa8e17.png)
* I think it is a little bit confusing that every card has a different animation. Maybe be here a little bit more consistent
* BTW I really love your heading design!

**Comment by Harshal0902** [comment]
@schmelto thank you for the feedback, I will try to solve this ASAP.

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts

**portfolio**
- section headings are difficult to read with text on text, suggest trying to make the background text closer to the background colour to stand out less

** GitHub profile**
- I am not a fan of profile views
