### ISSUE TITLE
[REVIEW] Recursion Tree Visualizer

### ISSUE THREAD

**Issue by Bishalsarang** [EddieHubCommunity/support#1310]
**Project Name**
Recursion Tree Visualizer

**Description**
A simple python package that helps to visualise any recursive function by adding a single line of code.

**Project Link:**
https://github.com/Bishalsarang/Recursion-Tree-Visualizer

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by kaiwalyakoparkar** [comment]
Thank you for submitting. It's really great project. But I would love to give some suggestion :
- Add the labels in the single line
![bishalSarang1](https://user-images.githubusercontent.com/53310847/117609247-41543c80-b17d-11eb-8d8c-1c6a00ac0121.png)
- Try completing this things
![bishalSarang1](https://user-images.githubusercontent.com/53310847/117610284-18cd4200-b17f-11eb-8979-44808d2bb73f.png)
- Add project board (That helps you in keeping track of your work)

Great project. Eddie will review this in a live stream shortly

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks great, some thoughts:
- suggest moving the to do list to Issues
- suggest removing wiki if not used
- suggest having code of conduct, contributing file and issue template https://github.com/Bishalsarang/Recursion-Tree-Visualizer/community
