### ISSUE TITLE
[REVIEW] taskgo

### ISSUE THREAD

**Issue by singalhimanshu** [EddieHubCommunity/support#1318]
**Project Name:**
Taskgo

**Description:**
Fast and simple terminal based Kanban board manager 

**Project Link:**
https://github.com/singalhimanshu/taskgo

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by nhcarrigan** [comment]
No bot these need to stay.

**Comment by kaiwalyakoparkar** [comment]
Thanks for project, Some suggestions from my side
- You can remove packages section
- Add issue and PR template

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

Looks great, some thoughts
- tags and releases great 👍 
- if not using packages suggest hiding this 
- CI seems to be failing
- Love the animated gif
- if not using the wiki hide this feature
