### ISSUE TITLE
[REVIEW] Laravel Wave

### ISSUE THREAD

**Issue by bobbyiliev** [EddieHubCommunity/support#1319]
**Project Name**
Laravel Wave

**Description**
Wave - The Software as a Service Starter Kit, designed to help you build the SAAS of your dreams 🚀 💰

Project Link:
https://github.com/thedevdojo/wave

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by kaiwalyakoparkar** [comment]
Hey, @bobbyiliev Thanks for sharing I would love to give some suggestion
- I didn't get why the issues section is removed. ( If there is any specific reason do let me know I would love to hear)
- Add Code of conduct & Contributing MD's
- Add issue and PR template
- Add Repository admins accept content reports
- Add actions to your project
- Add more ss of your working project to the readme. As that will help attract more contributors.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

Looks great, some thoughts
- love the banner with the cat
- release name is quite long and truncated
- hide features you are not using like `packages` 
- missing code of conduct and contributing file
- issue tab is not available where are you tracking issues?
