### ISSUE TITLE
[REVIEW]: BlogSite

### ISSUE THREAD

**Issue by Pranav016** [EddieHubCommunity/support#1320]
**Project Link:**
https://github.com/ALPHAVIO/WordNook by [Pranav Mendiratta](https://github.com/Pranav016)

**Do drop a star if you like the project 😄**

Not the most optimized but we are working on it 🙂 
Would love to get more contributors for the project.

<hr>

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by kaiwalyakoparkar** [comment]
Hey, @Pranav016 The project is really good and the readme too. I would love to give you some suggestions 
- Add the tech stack one besides the other
![review Pranav](https://user-images.githubusercontent.com/53310847/117105391-8baf7500-ad9b-11eb-91af-712b00160d9a.png)
- You can write wikis to explain your project more

Otherwise, everything is good! Loved the project overall

**Comment by Pranav016** [comment]
> Hey, @Pranav016 The project is really good and the readme too. I would love to give you some suggestions
> 
> * Add the tech stack one besides the other
>   ![review Pranav](https://user-images.githubusercontent.com/53310847/117105391-8baf7500-ad9b-11eb-91af-712b00160d9a.png)
> * You can write wikis to explain your project more
> 
> Otherwise, everything is good! Loved the project overall

Thank you for such a great feedback @kaiwalyakoparkar 
I'll definitely add more info about the project to the README file and fix the Tech Stack badges.

Do drop a star on the project if you like it 👍 🙂

**Comment by schmelto** [comment]
Love it.

Maybe tow suggestions:

* make a high resolution gif at the beginning. (for me its really blurry)
* remove the badges regarding github PRS issues due those are duplicates with what github already provides
![image](https://user-images.githubusercontent.com/30869493/117130715-ba7c1a00-ada0-11eb-8853-cdaa43f2822d.png)

**Comment by Pranav016** [comment]
> Love it.
> 
> Maybe two suggestions:
> 
> * make a high resolution gif at the beginning. (for me its really blurry)
> * remove the badges regarding github PRS issues due those are duplicates with what github already provides
>   ![image](https://user-images.githubusercontent.com/30869493/117130715-ba7c1a00-ada0-11eb-8853-cdaa43f2822d.png)

Yes, I'll look for an online gif converter that can give better res gifs.
Thank you for the positive feedback though 👍 🙂  I'll keep the suggestions in mind

**Comment by krishdevdb** [comment]
@Pranav016 did you close this by mistake?

**Comment by eddiejaoude** [comment]
I am planning a live stream this week (maybe tomorrow - Tuesday) to catch up on reviews

**Comment by krishdevdb** [comment]
> I am planning a live stream this week (maybe tomorrow - Tuesday) to catch up on reviews

🥳 Wow! My Project is gonna get reviewed tomorrow (as per the list). Really excited and scared 😨
