### ISSUE TITLE
[REVIEW] Introduction to Bash Scripting

### ISSUE THREAD

**Issue by bobbyiliev** [EddieHubCommunity/support#1321]
**Project Name**
Introduction to Bash Scripting eBook

**Description**
Free Introduction to Bash Scripting eBook

Project Link:
https://github.com/bobbyiliev/introduction-to-bash-scripting

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by kaiwalyakoparkar** [comment]
@bobbyiliev The project is great. I would love to suggest small changes.
1. Add Code of Conduct.MD to the project

else the project is very good. You have contributors, a sponsor button, good readme.

Are the releases automated or manual. If they are manual you can try automating them

**Comment by eddiejaoude** [comment]
Oh I can't wait for this one, looks great 👍

**Comment by schmelto** [comment]
Bojaa PDF Download with dark mode 🚀

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- releases looks awesome!
- all badges seem liked duplicated and already displayed by GitHub
- downloads are in light and dark mode 💥 
- chapters do not need to be in bold
- stale branches could be delete
- GitHub Action to create the PDF after merge to `main`
- Missing Code of Conduct
