### ISSUE TITLE
[REVIEW] My Profile!

### ISSUE THREAD

**Issue by Daggy1234** [EddieHubCommunity/support#1322]
**Github Profile Link:**
https://github.com/daggy1234

Projects:

https://github.com/daggy1234/dagbot
https://github.com/daggy1234/dagpi

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
@Daggy1234 did you mean to close this?

**Comment by Daggy1234** [comment]
Oh Whoops @eddiejaoude so sorry, must have been by mistake. Love  your vids btw!

**Comment by schmelto** [comment]
consider removing the profile view count due its inaccurate :)

**Comment by Daggy1234** [comment]
Oh sure thanks

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by mayurchakalasiya1990** [comment]
Please review my repo.

**Comment by eddiejaoude** [comment]
Reviewing profile on live stream https://www.youtube.com/watch?v=XT3_O4jULRE
(please raise new issues for the other projects)

- Bio is funny but could be used better for give a good first impression
- love the list of skills
- love the top projects and that it is collapsable 
- love love the gpg key
- your profile is very commit heavy, try doing pull requests, issues and review
