### ISSUE TITLE
[REVIEW] Portfolio Website

### ISSUE THREAD

**Issue by 0nk3** [EddieHubCommunity/support#1323]
Please kindly review
https://0nk3.github.io/

**Comment by 0nk3** [comment]
https://0nk3.github.io/
My bad
Please see link above

**Comment by nhcarrigan** [comment]
Thank you for updating - we will review on a live stream when the time comes :)

**Comment by eddiejaoude** [comment]
Thanks for sharing, we will review on a live stream soon 🤓

**Comment by schmelto** [comment]
Maybe take a look at the contrast at the buttons 

![image](https://user-images.githubusercontent.com/30869493/119273374-f7eaff00-bc0a-11eb-9bea-4a1ef794fded.png)

green and white is a little bit hard to read

**Comment by 0nk3** [comment]
> Maybe take a look at the contrast at the buttons
> 
> ![image](https://user-images.githubusercontent.com/30869493/119273374-f7eaff00-bc0a-11eb-9bea-4a1ef794fded.png)
> 
> green and white is a little bit hard to read

Okay, yeah you are right. 
I will definitely look into it. Thank you @schmelto

**Comment by krishdevdb** [comment]
**These Lighthouse Metrics Are Really Useful**
![image](https://user-images.githubusercontent.com/76587897/119333040-071f8a80-bca7-11eb-86bb-72cbb0fd878e.png)
They tell you a lot of issues/fixes already consider taking a look.

**Comment by 0nk3** [comment]
> **These Lighthouse Metrics Are Really Useful**
> ![image](https://user-images.githubusercontent.com/76587897/119333040-071f8a80-bca7-11eb-86bb-72cbb0fd878e.png)
> They tell you a lot of issues/fixes consider taking a look.

Thanks a lot Krish. Really appreciate
Which website did you use to measure these measurements for my future refs ?

**Comment by kaiwalyakoparkar** [comment]
> > **These Lighthouse Metrics Are Really Useful**
> > ![image](https://user-images.githubusercontent.com/76587897/119333040-071f8a80-bca7-11eb-86bb-72cbb0fd878e.png)
> > They tell you a lot of issues/fixes consider taking a look.
> 
> Thanks a lot Krish. Really appreciate
> Which website did you use to measure these measurements for my future refs ?

This is the "Lighthouse" extension on the Google Chrome browser. You can install it from here : https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

**Comment by krishdevdb** [comment]
This is built into chrome devtools @kaiwalyakoparkar

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks great
- really nice effect with the floating tech logos
- `get in touch` button has white tech and light green background it is a bit difficult to read

repo feedback https://github.com/0nk3/0nk3.github.io
- project description 
- link to deployed website 
- suggest using release
- suggest hiding packages if not used
- readme is very empty, could have a screenshot and a bit of an overview
- use issues even if just you working on the project
-
