### ISSUE TITLE
Update Labels in Issue Templates

### ISSUE THREAD

**Issue by nhcarrigan** [EddieHubCommunity/support#1325]
We are currently using four issue templates for the four different types of live stream reviews.

In order to streamline the process for filtering and reviewing these, we need to update the templates to apply the current label *and* each of them should apply the `live stream review` label.

An example change would be:

```diff
---
name: Github Profile Review
about: Please review my github profile on a live stream
title: '[REVIEW]'
- labels: gh profile review
+ labels: 'gh profile review, live stream review'
assignees: ''
---
```

## Files to Edit

All of these are within the `.github/ISSUE_TEMPLATE` directory.

- [ ] `gh-profile-review.md` (#1327)
- [ ] `opensource-review.md`
- [ ] `portfolio-review.md`
- [ ] `resume-review.md`

Share the love! Please only change one file and let others get squares too!

**Comment by Jaspreet099** [comment]
is this issue still open?

**Comment by schmelto** [comment]
> is this issue still open?

Unfortunately I think for all four templates PRs were created only one pr is waiting for merge.

**Comment by nhcarrigan** [comment]
Yep. The four PRs have been merged now. Great work everyone!
