### ISSUE TITLE
[REVIEW] - Open Source Projects

### ISSUE THREAD

**Issue by sawravchy** [EddieHubCommunity/support#1326]
**Project Link:**
https://github.com/sawravchy/Flunippet

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by schmelto** [comment]
Take a look at the community tab in your repo https://github.com/sawravchy/Flunippet/community
add code of conduct / conributiong.md

May add some instructions on how to fork, download and developing locally.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- great readme
- suggest using issues with labels to make the project more discoverable 
- great to see description, link and releases being used
- if not using wiki and packages, suggest hiding these
- missing code of conduct
- suggest using convention commit messages

**Comment by sawravchy** [comment]
Thanks, @eddiejaoude  for sharing your feedback.
