### ISSUE TITLE
[REVIEW] Please review my github profile

### ISSUE THREAD

**Issue by annshiv** [EddieHubCommunity/support#1328]
**Github Profile Link:**

https://github.com/annshiv

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by kaiwalyakoparkar** [comment]
Hey @annshiv Greate profile. Loved that gif. I have few suggestions for you
1. You can change the icon color of the contact with me section (They are not visible in dark mode)
2. You can remove the last section (profile visits, years, repo) coz that is already there on your profile.

Greate work btw.

**Comment by annshiv** [comment]
Thank you @kaiwalyakoparkar . I will made those changes

**Comment by annshiv** [comment]
Dear @kaiwalyakoparkar changes updated

**Comment by schmelto** [comment]
May one thing from my side consider making the skills icons consistent as gifs or only as img mixing both looks little bit confusing

**Comment by annshiv** [comment]
Thank you @schmelto . I will update use suggestions

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , we will review on a live stream soon 🤓 . Looks like you got some great community feedback already 💥

**Comment by Sam-Varghese** [comment]
Nice profile, some suggestions from my side:

- Icons under `Connect with me` are still not visible to visitors with dark background

![image](https://user-images.githubusercontent.com/79152648/122489271-e2e07080-cffc-11eb-9961-938754b4188d.png)

- The icon of Amazon Web Services is also not visible

![image](https://user-images.githubusercontent.com/79152648/122489327-0a373d80-cffd-11eb-8bd7-00f85e07dfff.png)

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] The Connect with me headline should be one level up into the context of the other headings.
- [ ] Add some space in between of the sections. (a UX principle)
- [ ] Keep things consistent, some sections your icons are centered, but some they are right-aligned.
- [ ] How about keeping the color theme of the statistic spaces be consistent, by the way you can add custom colors too!
- [ ] Either have a headline for all of the stats or none.

## Feedback
- [x] Looks cool 😎 
- [x] GIF at the top 😍 
- [x] Alignment of stats 🤩 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

looks good, some thoughts...
- great profile picture
- suggest making more use out of the bio
- suggest making use out of the link section under the bio
- some icons are animated, suggest being consistent
