### ISSUE TITLE
[REVIEW] annshiv github profile

### ISSUE THREAD

**Issue by annshiv** [EddieHubCommunity/support#1329]
**Github Profile Link:**
https://github.com/annshiv

**Comment by eddiejaoude** [comment]
@annshiv did you mean to close this?

**Comment by annshiv** [comment]
yes, I closed this. because I gave another pull request to review my profile.

**Comment by schmelto** [comment]
@nhcarrigan i think after reopening the livestream label is missing here as well 🙈

**Comment by schmelto** [comment]
Consider using a consistent style for the icons not one time a gif and the other times a png otherwise I really like your profile 
and wow what a contribution streak 🚀

**Comment by eddiejaoude** [comment]
Reviewed already here https://github.com/EddieHubCommunity/support/issues/1328
