### ISSUE TITLE
[REVIEW] - GitHub profile

### ISSUE THREAD

**Issue by karan-ksrk** [EddieHubCommunity/support#1330]
**Github Profile Link:**
[karan-ksrk](https://github.com/karan-ksrk)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
We did take a look at this on today's live stream - but I think we can leave this open to revisit your profile again when we circle back around :)

**Comment by nhcarrigan** [comment]
No please.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- great profile: picture, bio, link etc
- suggest making the first image smaller and moving to the right so your list can be on the left of it to make better use of space
- 100% are commits, suggest doing pull request, reviews and issues
