### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by mertbozkir** [EddieHubCommunity/support#1332]
**Github Profile Link:**
 https://github.com/mertbozkir 

Thank you Eddie :)

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by kaiwalyakoparkar** [comment]
The profile is really good @mertbozkir !

**Comment by mertbozkir** [comment]
Thank you @kaiwalyakoparkar 🐱‍👤🐱‍👤

**Comment by schmelto** [comment]
Wow i like the gif
![image](https://user-images.githubusercontent.com/30869493/117183296-ac95bb80-add7-11eb-8967-274164b6514c.png)

take a look at the projects section due you collabs it by default there is lot of empty space :D lol empty space and there is a spaceship 🤣 

![image](https://user-images.githubusercontent.com/30869493/117183407-cf27d480-add7-11eb-87fb-6b9d823fa9e5.png)

**Comment by mertbozkir** [comment]
Hahahhaa I changed. 

![image](https://user-images.githubusercontent.com/63906053/117215604-1da09780-ae07-11eb-9621-39d41465e469.png)


**Somebody said to me that if I don't show Projects, people may not see.  What do you think about @schmelto 

Which one is better? 🦸‍♂️🦸‍♂️

**Comment by kaiwalyakoparkar** [comment]
Cool @mertbozkir Just try changing your theme to dark and check if anything breaks (It often happens that some colors are not visible in dark mode)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

looks great 👍 
- maybe list the technologies you use
- maybe try to do more open source 🟩
