### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by kdgyimah** [EddieHubCommunity/support#1338]
**Github Profile Link:**
https://github.com/kdgyimah

Thank you :)

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by kdgyimah** [comment]
Great!

>

**Comment by schmelto** [comment]
Consider adding a sentence like connect with me on (LinkedIn)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

looks great 👍 , some suggestions
- great photo with the laptop
- use bio in the GitHub profile (settings)
- maybe add skills and technologies to the customised GitHub profile

**Comment by kdgyimah** [comment]
@eddiejaoude thanks a ton

**Comment by kdgyimah** [comment]
@schmelto Thanks a ton
