### ISSUE TITLE
[REVIEW]: Open Source Projects

### ISSUE THREAD

**Issue by mihir0699** [EddieHubCommunity/support#1347]
Please review my project:-

Polling Website- https://github.com/mihir0699/Insta-Poll

**Comment by nhcarrigan** [comment]
Thanks for sharing. Please edit your post to include only one project link as we typically review only one per issue.

**Comment by schmelto** [comment]
Some suggestions:

* add a contributing.md
* add a code-of-conduct
* add issue und pr templates
* add a release
* use issues and pull requests may take advantage of the project feature of GitHub to tell others what features are in progress

**Comment by nhcarrigan** [comment]
Thank you for updating your post- we will review on a live stream as time allows :)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks great, love the screenshots in the readme, description and link 👍 
- suggest using releases/tags
- suggest hiding packages and wiki if not used
- use issues with labels even if just you working on the project, so your project can get discovered
- missing code of conduct, check insights-> community link to create using a GitHub template
- there are `build` and `test` commands in the package.json, suggest adding these to a GitHub Action
