### ISSUE TITLE
[REVIEW] nikita-jain-01 

### ISSUE THREAD

**Issue by nikita-jain-01** [EddieHubCommunity/support#1348]
**Github Profile Link:** 
https://github.com/nikita-jain-01

**Comment by schmelto** [comment]
Some suggestions from my side.

- Maybe remove the view counter
- specify the "looking for collaboration on projects" a little bit more what kind of projects languages etc.
- may remove the links of the language and tools or link to the specific websites

**Comment by nikita-jain-01** [comment]
> Some suggestions from my side.
> 
> * Maybe remove the view counter
> * specify the "looking for collaboration on projects" a little bit more what kind of projects languages etc.
> * may remove the links of the language and tools or link to the specific websites

Thanks for your suggestions. I have done some changes.

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by kaiwalyakoparkar** [comment]
I would love to give some suggestions on your profile : 
- Remove the Vs code and Github icons from the Languages and tools section. As vs code doesn't define anything about you coding abilities and github icon because you are already present on the same platform.
- Instead of putting the github stats and streaks one below the other you can put them side by side then will help you optimize your readme file

**Comment by nikita-jain-01** [comment]
> I would love to give some suggestions on your profile :
> 
> * Remove the Vs code and Github icons from the Languages and tools section. As vs code doesn't define anything about you coding abilities and github icon because you are already present on the same platform.
> * Instead of putting the github stats and streaks one below the other you can put them side by side then will help you optimize your readme file

@kaiwalyakoparkar Thanks for your suggestions. I've done the changes.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks great 👍 
- suggest using the GitHub bio and link section (update via settings)
- suggest using some of the white space to the top right and bottom left of the customised GitHub profile, maybe move the last graph to the top right next to the list of bullet points 
- 100% commits, suggest doing pull requests, code reviews and issues
