### ISSUE TITLE
[REVIEW] uzair-ali10

### ISSUE THREAD

**Issue by uzair-ali10** [EddieHubCommunity/support#1349]
**Github Profile Link:** https://github.com/uzair-ali10

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by uzair-ali10** [comment]
@nhcarrigan 
Thanks!!

**Comment by kaiwalyakoparkar** [comment]
Hey @uzair-ali10, I would love to give some suggestions on your profile:
- Make Gmail, Instagram, & LinkedIn button on the same line (I have raised an issue for the same)
- Remove VS code from the languages and tools section
- Remove GitHub from Version Control System and DevOps section as you are on the same platform
- Remove My walkline stats as that should be reflected by your work
- Put Github stats card and Languages card on the same line
- If you want you can remove the profile visit section as well.

**Comment by uzair-ali10** [comment]
Here's my resume if you can review it, would be great!!
[Resume](https://drive.google.com/file/d/1rYyFw38FW3eMZtlt9UPdTN_hYff0f8Zc/view?usp=sharing)

**Comment by schmelto** [comment]
> Here's my resume if you can review it, would be great!!
> [Resume](https://drive.google.com/file/d/1rYyFw38FW3eMZtlt9UPdTN_hYff0f8Zc/view?usp=sharing)

It would be great if you can opening another issue for that. so this will not be lost 🚀

**Comment by kaiwalyakoparkar** [comment]
Yup @uzair-ali10 I agree with @schmelto It would be great if you open a new issue as that will help the moderators segregate the resume's and github profiles

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks good 👍 
- suggest using the bio and link section part of your GitHub profile in settings
- lots of white space wasted in the custom profile, suggest moving important info up, for example; about, links and tech
