### ISSUE TITLE
[REVIEW] - GitHub profile

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/support#1352]
**Github Profile Link:**

<a href="https://github.com/vinzvinci">https://github.com/vinzvinci</a>

I love to hear some insights again 😃 💡 ❤️

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by kaiwalyakoparkar** [comment]
Hey @vinzvinci Your profile got reviewed int the last live stream you can always improve from the suggestions given by Eddie & Nick

**Comment by vinzvinci** [comment]
Yes, thank you @kaiwalyakoparkar :)
I already did some improvement, if you can see on my **GitHub profile**, I removed those things not helping at all. I still keep things updated while the livestream for review isn't on the list this month ♥️.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks great 👍 
- thank you for the shout out section 🎉 
- struggling to find anything constructive, so I have gone into the repo itself, maybe hide `releases` and `packages` if not being used
