### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by Aniketkhote** [EddieHubCommunity/support#1353]
**customize** Flutter UI Package
https://github.com/Aniketkhote/customize

**Comment by schmelto** [comment]
Some thoughts:

* add some content to the https://github.com/Aniketkhote/customize/blob/main/CONTRIBUTING.md
* maybe use conventional commit messages

**Comment by kaiwalyakoparkar** [comment]
I would love to give some suggestions on your project : 
- Add code of conduct and pull request template to the project
- Add actions to your project
- Increase the size of the heading in the readme.md

**Comment by Aniketkhote** [comment]
thnx for the suggestions, I'll make changes.

**Comment by eddiejaoude** [comment]
@Aniketkhote did you want to mean to close the issue? We can review it on a live stream
