### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [EddieHubCommunity/support#1364]
**GitHub Profile Link:**
https://github.com/advaith-unnikrishnan

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by schmelto** [comment]
Love the portfolio only one small suggestion.

May use different emojis here
![Screenshot_20210423_142622.jpg](https://user-images.githubusercontent.com/30869493/115870731-f37ecb00-a43f-11eb-979d-fdeedfbb7a2d.jpg)

**Comment by schmelto** [comment]
> https://github.com/ghulamyazdani-bot

@ghulamyazdani-bot if you want a github profile review please open a new [issue](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=gh+profile+review&template=gh-profile-review.md&title=%5BREVIEW%5D) for that

**Comment by advaith-unnikrishnan** [comment]
@schmelto  Thank you for the suggestion I used different emojis in the profile.

![Screenshot_2021-04-23 advaith-unnikrishnan - Overview](https://user-images.githubusercontent.com/45172876/115905244-75dcae80-a483-11eb-8b91-9409575804bc.png)

**Comment by nhcarrigan** [comment]
I thought I fixed this :(

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- banner looks great 👍 
- 94% commits, suggest doing code reviews, issues etc
- Maybe 1 row too many of graphs, makes it take longer to get down to your repos and green square graph
