### ISSUE TITLE
[REVIEW] Roshaen

### ISSUE THREAD

**Issue by Roshaen** [EddieHubCommunity/support#1370]
**Github Profile Link:**

https://github.com/Roshaen

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by schmelto** [comment]
Take a look at caps Student / learner.
Same at Web developers

**Comment by vinzvinci** [comment]
Suggestion:
- Add more details about you

**Comment by Roshaen** [comment]
@schmelto Hey there! Thanks for the suggestion

**Comment by Roshaen** [comment]
@vinzvinci Thanks for the suggestion. 
I'll add more details about me

**Comment by Roshaen** [comment]
@schmelto @vinzvinci I have added more details about me, kindly have a look...

**Comment by shreyshreyansh** [comment]
## Can resolve this:

![](https://github.com/shreyshreyansh/video/blob/main/Screenshot%202021-06-29%20104155.png?raw=true)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- missing images in the `connect with me` section
- suggest having a bio in your GitHub profile 
- activity graphs have wasted space to the right, suggest doing them on 1 line
