### ISSUE TITLE
[REVIEW] - GitHub profile

### ISSUE THREAD

**Issue by ghulamyazdani** [EddieHubCommunity/support#1380]
**Github Profile Link:**

https://github.com/ghulamyazdani

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Take a look at your 'proleaker.com' badge
This should be the wright code:
`[![Website](https://img.shields.io/website?label=Proleaker.com&style=for-the-badge&url=https%3A%2F%2Fproleaker.com)](https://proleaker.com)`

there was a double .com

**Comment by vinzvinci** [comment]
Hi @ghulamyazdani-bot, please don't remove the issue title `[REVIEW]`. 
You can still edit your issue title and rename it as `[REVIEW] - GitHub profile`
<hr />

By the way
- These icons are not visible to the dark mode 
![image](https://user-images.githubusercontent.com/73097560/115952603-76278900-a519-11eb-9850-892dff65914c.png)

<hr />

- Separate the tools and languages
![image](https://user-images.githubusercontent.com/73097560/115952654-d8808980-a519-11eb-9ad6-e4a081ad77cf.png)

**Comment by annshiv** [comment]
Good profile. 

Here I give some suggestions,

- Post a simple gif of your project demo videos. it gives extra attention to your project.

**Comment by eddiejaoude** [comment]
Thank you for sharing. I will review on a live stream soon, sorry I am a bit behind. Looks like the community has give some great feedback already 💥

**Comment by schmelto** [comment]
@ghulamyazdani the link does not work anymore did you change your username? Kindly adjust the issue description :)

**Comment by ghulamyazdani** [comment]
Yeah i have changed the username!!!
Now its:  https://github.com/ghulamyazdani

**Comment by schmelto** [comment]
Consider using some other icon style for the social icons on dark mode those are nearly invisible

**Comment by annshiv** [comment]
I will update it @schmelto

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- suggest adding a bio to your GitHub profile
- I am not a fan of the Spotify as it is seems to change randomly on page refresh
