### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by coder-tle** [EddieHubCommunity/support#1383]
**Github Profile Link:**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Think you forgot to add the link to your portfolio

**Comment by vinzvinci** [comment]
Hi @coder-tle, you can still edit your issue description, and please link your GitHub profile.

**Comment by kaiwalyakoparkar** [comment]
Ok @coder-tle I visited your profile and there is no customized readme (repo with your username) You can find plenty of resources online to add one to your account.

I would suggest you to refer this : https://awesomegithubprofile.tech/ 

Please add one such to your profile and edit the link in your issue and mention us. We would love to review it then

**Comment by schmelto** [comment]
Hey @coder-tle due there is no link to your custom github profile or a open source project I close this issue now. Kindly adjust the issue description with a link and reopen the issue if you want a livestream review. Hope this is ok for you :)
