### ISSUE TITLE
[REVIEW] Open source project

### ISSUE THREAD

**Issue by j-dogcoder** [EddieHubCommunity/support#1417]
**Project Link:**
<https://github.com/Heptagram-Bot/Heptagram>

The goal is for Heptagram to be the all-in-one, open-source discord bot to be the single needed bot for any server. Check it out, and contribute if you want to!

**Comment by schmelto** [comment]
Nice work already created a PR 😄 

Some suggestions from my side:
* use conventional commit messages
* add some screenshots of the bot
* I personally would include the installation instructions in the readme and not in the contributing.md

**Comment by j-dogcoder** [comment]
Thanks for the feedback @schmelto!

**Comment by j-dogcoder** [comment]
If we miss the live stream will there be a VOD to watch after?

**Comment by schmelto** [comment]
> If we miss the live stream will there be a VOD to watch after?

https://www.youtube.com/c/eddiejaoude

**Comment by j-dogcoder** [comment]
Did this get reviewed @schmelto?

**Comment by schmelto** [comment]
> Did this get reviewed @schmelto?

Not yet. You will get an comment from@eddiejaoude after getting it reviewed in a live-stream. You can estimate the time by checking how many other (older) issues with the label `open source review` are before this one.

**Comment by j-dogcoder** [comment]
Ok!

**Comment by j-dogcoder** [comment]
No review yet! Looking forward to it though!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- clear project description looks great 👍 
- not if the GitHub logo is allowed as part of your logo
- screenshot in the README to demo what it looks like
- great issues and labels 👍 
- using GitHub Actions 🎉 
- use conventional commits for commit style

**Comment by j-dogcoder** [comment]
Thanks!
