### ISSUE TITLE
[REVIEW]-Github profile

### ISSUE THREAD

**Issue by Sam-Varghese** [EddieHubCommunity/support#1420]
**Github Profile Link:** https://github.com/Sam-Varghese

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Really solid profile! 
Some suggestions from my side.

- move the tech u used to the bottom of the profile thi k this is not what a visitor should look first more interesting is the about you section
- maybe also use html and css tags to center those panels and not a table.
- I would remove the view counter cause it is inaccurate
- achievements coming soon looks little bit strange may remove it or say what is coming soon

**Comment by Sam-Varghese** [comment]
@schmelto  Thankyou sir for reviewing my profile and for the appreciation. I have noted all these suggestions, and would be correcting my profile as fast as possible.

**Comment by Sam-Varghese** [comment]
Profile updated as suggested.

**Comment by kaiwalyakoparkar** [comment]
@Sam-Varghese Really nice profile. I would just suggest one thing. 
1. If you are able to cut down things till a certain level that would be great. The sections are very big and that increase the scrolling size. Try to keep it as short as possible

**Comment by Sam-Varghese** [comment]
@kaiwalyakoparkar Thanks for your valuable suggestions. I would surely try to cut down certain non-important contents as fast as possible.

**Comment by vinzvinci** [comment]
Your GitHub profile is too long, you can reduce or remove some pictures. The text is too big for me, you can also reduce it.

**Comment by Sam-Varghese** [comment]
Thankyou for reviewing my GitHub profile. I would surely try to reduce size of the profile.

**Comment by Sam-Varghese** [comment]
@vinzvinci  I have tried to reduce contents as much as I could. Is it looking better now?

Changes I made:-

- Profile picture in README was occupying more space, hence I changed the profile picture.
- Removed a point from `About Myself`.
- Removed 2 graphs from `My GitHub Stats` that were stacked vertically one below the other.
- Table of `Tech I Have Come Across` was too big. Hence I removed that table and simply added the logos.
- Removed some tasks from `My Task List`.
- Removed  Groot's gif. ( Got bored of that)

You said that size of the text is too big. Can you kindly suggest to me what can I do about that; should I put headings inside `h2` tag?

Any more suggestions?

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- I think too much animation 
- Task list in the README is a great idea ❤️ 
- Most of your contributions are commits, suggest doing code reviews, issues and pull requests
- I think the duplicate photo in the README is not required as you have it in your GitHub profile 
-

**Comment by Sam-Varghese** [comment]
Thanks a lot, sir for reviewing my profile on the live stream. I would surely work upon the above-suggested points.
