### ISSUE TITLE
Github not showing any images

### ISSUE THREAD

**Issue by Sam-Varghese** [EddieHubCommunity/support#1424]
Hi , I face a problem every now and then, that my gthub website does not show any image (like profile pictures, images added in repo etc) although my internet connection is fast and only 1 or two tabs are opened. This problems happens randomly at any time, and does not gets sorted out until I shut down the laptop and restart it the next day. I use windows 10 and google chrome as my browser. Here are the screenshots:-

**My profile image**

![image](https://user-images.githubusercontent.com/79152648/116556797-7b227900-a91b-11eb-81cf-cc4ac2e13672.png)

**Eddiehub github page**

![image](https://user-images.githubusercontent.com/79152648/116557013-aefd9e80-a91b-11eb-9f89-e9b502e3d14e.png)

**Even markdown preview appears without any image preview**

![image](https://user-images.githubusercontent.com/79152648/116557214-db191f80-a91b-11eb-9775-1e1914080ce6.png)

It would be very helpful if anybody could help me to sort this problem out

**Comment by schmelto** [comment]
Do you use a VPN or something like this?

**Comment by Sam-Varghese** [comment]
Thanks for showing interest to help me out. No, I don't use VPN or something like that.

**Comment by Sam-Varghese** [comment]
But just to inform, I use chrome extension called `Enhanced Github`. And a few more extensions which are for programs other than github.

**Comment by Sam-Varghese** [comment]
@schmelto Sir as this laptop is a new laptop, I recently discovered that I have an application called `ExpressVPN`

![image](https://user-images.githubusercontent.com/79152648/116575268-1b809980-a92c-11eb-8bac-9e5d0f1be984.png)

Is this what might be causing problem?

**Comment by Sam-Varghese** [comment]
Even using Microsoft edge brings no difference

**Comment by Sam-Varghese** [comment]
I even tried to open github through my old windows 7 laptop and through Samsung tablet, but still github is showing that same problem. I think problem is in github website and not in my laptops or tablets
