### ISSUE TITLE
[REVIEW] Project brainstorming in README.md

### ISSUE THREAD

**Issue by mjbanvard** [EddieHubCommunity/support#1436]
**Project Link:**
https://github.com/mjbanvard/river_modeling

I'm looking for contributors at all levels, but guidance on how to begin a project development flow is also welcome.

**Comment by kaiwalyakoparkar** [comment]
Hey @mjbanvard That's a great project. I would love to give you few suggestions
1. Add contributing.MD to your project
2. Add Issue template & PR templates
3. Try to add GitHub actions
4. Add custom tags (or pre-given tags) to the issue.
5. You can update the readme with emojis & screenshots.
Everything else looks good to me. Your project will be reviewed by Eddie as time permits

**Comment by eddiejaoude** [comment]
Thanks for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- suggest using topics under the project description 
- suggest creating a release/tag
- if not using `packages` and `wiki` suggest hiding 
- README needs a `QuickStart` guide
- suggest having a contributor file so people know where to ask questions etc https://github.com/mjbanvard/river_modeling/community
