### ISSUE TITLE
[REVIEW] GitHub profile

### ISSUE THREAD

**Issue by Pranav016** [EddieHubCommunity/support#1440]
**Github Profile Link:**
https://github.com/Pranav016

**Comment by schmelto** [comment]
Only one suggestion may remove the profile view count cause it's inaccurate

**Comment by Sam-Varghese** [comment]
@Pranav016  One suggestion, that you may change the github icon as it is not visible to visitors with dark github background.

![image](https://user-images.githubusercontent.com/79152648/117521774-2e9b0580-afcd-11eb-81de-7b02e911ad59.png)

**Comment by Pranav016** [comment]
> @Pranav016 One suggestion, that you may change the github icon as it is not visible to visitors with dark github background.
> 
> ![image](https://user-images.githubusercontent.com/79152648/117521774-2e9b0580-afcd-11eb-81de-7b02e911ad59.png)

Thank you for the suggestion 👍☺️

**Comment by Sam-Varghese** [comment]
> > @Pranav016 One suggestion, that you may change the github icon as it is not visible to visitors with dark github background.
> > 
> > ![image](https://user-images.githubusercontent.com/79152648/117521774-2e9b0580-afcd-11eb-81de-7b02e911ad59.png)
> 
> Thank you for the suggestion 👍☺️

Your welcome ☺️

**Comment by vinzvinci** [comment]
Some thoughts:

- The profile views can be fake by refreshing and you'll get easy views, up to you if you want to remove it.
- These two are not the same height, you can use table markdown to balance the height and width, that's what I did.
![image](https://user-images.githubusercontent.com/73097560/120434237-ca424a80-c3ae-11eb-912e-e6044e22eb11.png)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- profile view counter is not a great feature, we can all just refresh the page
- tech skills icons look great, but some people might not know what they are, can you somehow add text to them (think of recruiters, HR etc)
- stats boxes could be the same height
- I think having a different photo in the banner to your GitHub profile would add more value

**Comment by Pranav016** [comment]
> Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk
> 
> Looks good, some thoughts:
> 
> * profile view counter is not a great feature, we can all just refresh the page
> * tech skills icons look great, but some people might not know what they are, can you somehow add text to them (think of recruiters, HR etc)
> * stats boxes could be the same height
> * I think having a different photo in the banner to your GitHub profile would add more value

Thank you for the valueable feedback, will work on these pointers👍
