### ISSUE TITLE
[REVIEW] Awesome Semantic Search

### ISSUE THREAD

**Issue by Agrover112** [EddieHubCommunity/support#1449]
https://github.com/Agrover112/awesome-semantic-search

**Comment by krishdevdb** [comment]
@eddiejaoude and @nhcarrigan I thought this was fixed?

**Comment by eddiejaoude** [comment]
Interesting, I thought it was too, here was the fix https://github.com/EddieHubCommunity/support/blob/main/.github/workflows/stale.yml#L20

**Comment by Agrover112** [comment]
I think my project was reviewed in a live-stream

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- suggest removing the wiki as it is only 1 page and move it to the readme or docs folder
- great to see the project board being used, some items are not converted to issues yet, I suggest being consistent
- suggest having the different languages readmes as links at the top of each
