### ISSUE TITLE
[REVIEW] Blood Donation Diary Review.

### ISSUE THREAD

**Issue by debjit** [EddieHubCommunity/support#1450]
**Project Link:**
[Blood Donation Diary](https://github.com/Alpana-Web-Solution/bddv1)
Hello, I am a jr dev and your review will help me build a more useful Web App.

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Take a look at your community tab (https://github.com/Alpana-Web-Solution/bddv1/community) there are some points missing.
May add a release always looks great.
Add some screenshot or gifs from the app to the readme.

**Comment by debjit** [comment]
Yes and thank you for pointing it out. I am currently working on making this app feature proof and eliminate bugs. 👍

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- highly suggest having a code of conduct (templates available)
- highly suggest having a license http://choosealicense.com
- issues are not used, this will help to get contributors even if it is just you working on it for now
- hide `packages` and `wiki` if not being used
