### ISSUE TITLE
[REVIEW] Resume

### ISSUE THREAD

**Issue by starlightknown** [EddieHubCommunity/support#1454]
**Remove all personal data, otherwise the resume will be deleted.**

Resume link: [Resume](https://drive.google.com/file/d/1CjoMVx0ZMC5a637hvqdwEtNVQGgf9_Ks/view?usp=sharing)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey @starlightknown The design is very good but I would love to suggest you few things
- Keep the resume of 1 page only
- About me is not needed in the resume
- Also the heading is not aligned. It becomes a bit confusing to understand what you are trying to show
![starlightknown1](https://user-images.githubusercontent.com/53310847/117099369-97e10580-ad8e-11eb-8be4-b92db3359604.png)
- Don't add soft skills as they should be reflected in the interview.
- Try to make the resume using a single column resume template
- Also give some structure to the project section.
- ![starlightknown2](https://user-images.githubusercontent.com/53310847/117099534-0cb43f80-ad8f-11eb-9047-54c6f53de91a.png)
- Avoid adding colors and make it black and white (This is personal opinion)
- You can watch Kunal's resume review live stream he has discussed some awesome points there

Hope that helped :heart:

**Comment by starlightknown** [comment]
yep thanks a lot, will update it with the suggestions

**Comment by starlightknown** [comment]
changed a lot of things, hope it's fine now @kaiwalyakoparkar let me know your feedback on this

**Comment by kaiwalyakoparkar** [comment]
Hey @starlightknown I still have some suggestions
- Don't add profile photo
- Make it a single column resume. Refer templates at overleaf.com
- Add more about your projects, give links to them, Tell what did you do, etc
- I will still recommend you to watch Kunal's resume review stream. You will get many points there

**Comment by starlightknown** [comment]
There will be more projects coming and more sections too, description would occupy more space. I did add the links. Going to watch it

**Comment by schmelto** [comment]
Like the resume 👍🏼 one addition why is there a @ by twitter and at the other links not?
![image](https://user-images.githubusercontent.com/30869493/117178839-bec12b00-add2-11eb-83d2-7fcfee833bea.png)

**Comment by kaiwalyakoparkar** [comment]
Good spot @schmelto :clap:

**Comment by starlightknown** [comment]
maybe I should remove @ in that too

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by includestdlibrary** [comment]
Hey @starlightknown ! Thanks for sharing your Resume with us! Some Suggestions from my side are 

1. You should give some information about your projects in your resume  like what you've done in that project and what problem does it solve. 
2. And in volunteering section you should add more about what you have done in that position, how you helped others grow in your college etc. 
3. And some info about what you have build in those competitions or hackathons which you gave.
  
And you have written wrong linkedin username your username should be karuna-tata63 and you have written karuna-tata-63 

[Kunal's Review Part 1](https://www.youtube.com/watch?v=JyPzh69ZCyw)
[Part 2](https://www.youtube.com/watch?v=kk37Q9_8xFg)
[Striver](https://www.youtube.com/watch?v=7lFBBReJ22Q&t=828s)
[Tech Lead](https://www.youtube.com/watch?v=xpaz7nrNmXA)
[Tech Lead](https://www.youtube.com/watch?v=rCOgVQ8a1zs)

These are some of the videos which you can watch . And you can analyse other's resume on LinkedIn who are placed in big tech giants! :)

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] All points from the other folks
- [ ] Visual hierarchy is missing
- [ ] Attention is not parted
- [ ] Headlines should be at the same height
- [ ] Needs a change in the color scheme

## Feedback
- [x] Overall Layout 🤩 
- [x] Sidebar method 😍 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by starlightknown** [comment]
I didn't get `attention is not parted`

**Comment by krishdevdb** [comment]
> I didn't get `attention is not parted`

Contrast, you should keep important text on a more contrasted color and the lesser important on a lesser contrast. That creates a attention to the important text just like bolding something to grap attention

**Comment by starlightknown** [comment]
got it, thanks. I was updating it so glancing at all points

**Comment by schmelto** [comment]
At the website there is a missing `:`

**Comment by starlightknown** [comment]
yes, thanks! I made few changes now. Is it okay? except `:` I'll do it

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- really stands out and is memorable 💥 
- maybe a profile photo at the top left in the space
- achievements maybe to have dates?
- maybe remove the word `website` in the "get in touch section?
- maybe remove the duplicate word `education`
- suggest putting the full GitHub links under each projects, just incase it is printed or imported/exported from another platform and clickable links are lost
