### ISSUE TITLE
[REVIEW] GitHub Profile

### ISSUE THREAD

**Issue by kulendu** [EddieHubCommunity/support#1457]
**Github Profile Link:**
https://github.com/kulendu

**Comment by schmelto** [comment]
Love it! It stands out never seen something like this before

**Comment by kulendu** [comment]
> Love it! It stands out never seen something like this before

Thanks @schmelto . 😄

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , we will review on a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- maybe too many things are animated
- suggest making more use of the bio description in the GitHub profile
- suggest pinning 4 repos to make full use of the space
- animated formula writing is hard to read on white background
