### ISSUE TITLE
[REVIEW] Portfolio Review

### ISSUE THREAD

**Issue by k99sharma** [EddieHubCommunity/support#1461]
Please review my portfolio and github profile

Github Profile: https://github.com/k99sharma

Portfolio Profile: https://www.kalashsharma.me/

**Comment by starlightknown** [comment]
I really like your github profile, as you mentioned `I'm currently working on side projects` how about putting those links in there? If anyone opens your profile and want to contribute to it they can find it and it'll show off what you do.

**Comment by starlightknown** [comment]
Portfolio looks good! 

-  The link for resume doesn't work
- I like the thing you did with rock paper scissor project but maybe add few more like those? you can add a line like currently working or in development if they are not complete

**Comment by k99sharma** [comment]
Thanks! 
Actually, the resume button is disabled because my resume not ready but I will add it. I am working on some more projects right now so I will add them to the portfolio.

**Comment by kaiwalyakoparkar** [comment]
Hey, @k99sharma Really great readme profile. I have a suggestion for you
- You can add the languages, and streak section side by side rather than one below the other. This will optimize the space of your readme profile
- Also try to center the programming profile icons on your website
![Profile](https://user-images.githubusercontent.com/53310847/117099082-e3df7a80-ad8d-11eb-8ed8-3e4f16e171fe.png)
- Else everything is good. Great job

**Comment by schmelto** [comment]
One thing about your portfolio take a look at the mobile view 🚀

**Comment by k99sharma** [comment]
Thanks, everyone for your suggestion
- I will change the readme and add language and streak section side by side.
- Actually, the CP profile icons are on the left because I created that whole column keeping in mind a left layout. You can check other technology icons all are aligned to left. So I think the center is not a good place for the icons. But if you want I can change align them to center!
- I will check the navbar thanks for pointing that out. :)

**Comment by kaiwalyakoparkar** [comment]
You can change the alignment of the technology icon as well. When someone visits that section then much which space is seen at first glance. That fix would be worth it! You can open an issue on your repo and ask some beginner to work on it. That would help both (The beginner and you)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Reviewed your GitHub Profile on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

(please create a new issue for your portfolio)

Looks great some thoughts:
- banner looks great, suggest putting a link on the banner to go to one of your socials
- part of the EddieHub Org 🎉 
- I think with the 3 widgets, 1 should go to save on vertical space
- the diamond graph is very commit heavy, suggest also getting involved in code reviews and issues
