### ISSUE TITLE
[REVIEW] Open Source Project (CGV)

### ISSUE THREAD

**Issue by vigneshshettyin** [EddieHubCommunity/support#1468]
**Project Link:**

https://github.com/vigneshshettyin/Flask-Generate-Certificate
You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
wow not really something I can say about it. It looks great i really love the image/icon at the top!

Maybe consider to remove redundant badges du the information also be provided by github
![image](https://user-images.githubusercontent.com/30869493/116918986-ee482a00-ac50-11eb-9ab7-b4ce37ef1782.png)

and maybe use same badges style through the readme

![image](https://user-images.githubusercontent.com/30869493/116919080-133c9d00-ac51-11eb-98f8-a46026881fc6.png)

**Comment by vigneshshettyin** [comment]
Hey, @schmelto thanks for the review I'll differently work on it.  😄

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by vigneshshettyin** [comment]
Thanks, @eddiejaoude! 
I am waiting for it 😄

**Comment by eddiejaoude** [comment]
Reviewed your GitHub Profile on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- really great banner and repo setup 💥 
- how to deploy, links are in tables, suggestion another format
- maybe move screenshots higher up the page
- suggest removing duplicate information from readme for example: license, contributors, last row of badges that duplicate info from GitHub like issue numbers etc
- remove wiki if not being used
- have a look at the project board to help organise the project issues etc
-
