### ISSUE TITLE
[REVIEW] Can you review my GitHub profile?

### ISSUE THREAD

**Issue by saileshbro** [EddieHubCommunity/support#1469]
**Github Profile Link:**
https://github.com/saileshbro

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Really like your profile!

Some suggestions from my side:

* remove the view counter due its inaccurate
![image](https://user-images.githubusercontent.com/30869493/116918602-695d1080-ac50-11eb-9d07-f2116eab2e5d.png)

* Take a look here think this repo doesn't exist anymore or something else is broken
![image](https://user-images.githubusercontent.com/30869493/116918531-50ecf600-ac50-11eb-8bc2-5d6da5b6adce.png)


Love that you are using the github profile as website (https://sailesh.is-a.dev)

**Comment by saileshbro** [comment]
Hey @schmelto, Thanks for your feedback. I have made changes to the profile based on your suggestions.

**Comment by starlightknown** [comment]
It looks nice, few suggestions in the `hey there` section 

- the name- I'd suggest keep it as the first point, it's kinda lost in all the points of tech and suddenly name comes
- maybe the links for linkedin, facebook, twitter could go too since they are already in contact section

**Comment by saileshbro** [comment]
HI, @starlightknown  Thanks for your feedback I have made suggested changes.

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Reviewed your GitHub Profile on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- the GitHub profile on the left is great 👍 
- highlights badges seem quite busy and I always just skip over these
- suggest having only 4 pinned (definitely an even number)
- suggest removing the project section as a duplicate with the pinned repo section
- diamond activity graph, shows very commit heavy, suggest getting involved in reviews and issues
