### ISSUE TITLE
[REVIEW]  Github Profile

### ISSUE THREAD

**Issue by ashwinexe** [EddieHubCommunity/support#1470]
Github Profile : https://github.com/ashwinexe

**Comment by starlightknown** [comment]
I like your profile, not sure what `C++14` meant , was it just C++?

**Comment by kaiwalyakoparkar** [comment]
@nhcarrigan Could you please add review tags here?

**Comment by ashwinexe** [comment]
> I like your profile, not sure what `C++14` meant , was it just C++?

Thanks for the review karuna. 
Yes both C++ and C++14 are same. I'll make the changes for better understanding.

**Comment by starlightknown** [comment]
Hey @ashwinexe why did you close it? It'll be reviewed by Eddie on livestream. We go in order so please keep it open

**Comment by ashwinexe** [comment]
woops, my bad. ca

**Comment by Sam-Varghese** [comment]
Hi @ashwinexe ; liked your profile.  I have a small suggestion, that you can remove profile view count, as it works incorrectly. Instead of counting number of unique visitors to your profile page, it counts the total number of times your profile has been viewed, which means that even refreshing the github page would increment view count by 1.

**Comment by schmelto** [comment]
Love your profile one thing I would suggest to put git to "your gear" and not at the "build with" section

**Comment by ashwinexe** [comment]
Thanks @Sam-Varghese and @schmelto I've made the corrections.

**Comment by eddiejaoude** [comment]
Thank you for sharing, I will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed your GitHub Profile on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- suggest using the GitHub bio on the left
- the 3 widgets take up a lot of space and leave big white gaps, suggest having 2 on a single row
- the 6 pinned repos could do with descriptions (suggest pinning a max of 4)
- profile picture looks very cool and funny, but might put potential employers/clients off
