### ISSUE TITLE
[REVIEW] Review my Resume

### ISSUE THREAD

**Issue by ksdkamesh99** [EddieHubCommunity/support#1471]
**Remove all personal data, otherwise the resume will be deleted.**

Resume link: https://drive.google.com/file/d/1VfO0HuKCACINaeQQucPIL7lcgtkBV8tf/view?usp=sharing

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
@ksdkamesh99 Kindly remove the phone number for the review purpose :red_circle:

**Comment by kaiwalyakoparkar** [comment]
@ksdkamesh99 Your resume looks good but I would love to suggest some point.
- Add the technical skills section to the second number (Below the education)
- Add the link to your blog site as you mentioned that you posted 15+ blogs on AI
- Little bit more description of your projects will be great.

The resume is really very good!

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- personal preference, but I am not keen on the font
- I would re-order the sections to
   - technical skills
   - experience
   - projects
   - ...
- links to projects to be full links

**Comment by longqua69** [comment]
Hi @ksdkamesh99 , chapter **Acheivements** has a typo mistake. It should be **Achievements**
