### ISSUE TITLE
[REVIEW] RESUME 

### ISSUE THREAD

**Issue by imabp** [EddieHubCommunity/support#1473]
Resume link:https://drive.google.com/file/d/10s2okbZm3IxofGVVFtOIbBVZnPfZysfU/view?usp=sharing

Hello Eddie
I hope you are doing great.
Last time, my friend @ksdkamesh99 and me, were doing peer resume reviews...
Just wanted to know your views and feedback on the resume.
Here is the link: 
You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey, @imabp Your resume layout is very good. But I would love to suggest you few things
- Put the education section on the top as you are an undergrad yet and are not working professional.
- Put links to a live working demo of your project. If one of your projects catches the eye of a recruiter then there is no way they can see the working project
- Be more elaborative on your projects. They should be highlighting the background of the project as well.
- Add technical skills to second number (After education section which would be 1st)

Overall it is good. Greate work!

**Comment by imabp** [comment]
Thats not good idea, if you dont have a good name college. 
I think, you still have to explore the interviews and company hirings off campus a bit :) 
Great, the issue is still open .. 

Regarding Links, yes I am editing that, on Latex

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by krishdevdb** [comment]
Hey, @imabp please don't close the issue, if you close it eddie will not be able to review it

**Comment by imabp** [comment]
Thank you, but I got few offers through this resume and had my interview
done. So I know now,  where it stands and improvements.

Unfortunately, I have changed my mind to not to go with resume review.
