### ISSUE TITLE
[REVIEW] UG-SEP

### ISSUE THREAD

**Issue by UG-SEP** [EddieHubCommunity/support#1474]
**Github Profile Link:**

[profile link](https://github.com/UG-SEP)
You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Can you mention me here in chat after implementing all the changes from the issues implemented which where created during eddies stream (https://www.youtube.com/watch?v=ugEJ8LBb1r0) think it makes more sense that we/I take al look at the profile after implementing those changes 🤖

**Comment by UG-SEP** [comment]
yah @schmelto 🤘

**Comment by UG-SEP** [comment]
hey @schmelto  i did the changes

**Comment by UG-SEP** [comment]
hey @schmelto  please recheck it

**Comment by schmelto** [comment]
> hey @schmelto  please recheck it 

I check again if time allows the issue is marked :)

**Comment by schmelto** [comment]
![Screenshot_20210620_081259.jpg](https://user-images.githubusercontent.com/30869493/122664068-59b56f00-d19f-11eb-851c-b6e85a286b0f.jpg)
Take a look here

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- remove double horizontal line
- too much bold
- try to do more issues and pull requests to get an even graph
- try moving list of details to the right next to your top projects - this will make better use of space
