### ISSUE TITLE
[REVIEW] Ankit0225

### ISSUE THREAD

**Issue by Ankit0225** [EddieHubCommunity/support#1477]
**Github Profile Link:**

(https://github.com/Ankit0225)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)
### Review my github profile what should I add more to look it more attractive

**Comment by schmelto** [comment]
Like it. May two suggestions.
* add a profile picture
* remove the view count due its inaccurate
otherwise i really like your profile 🚀

**Comment by starlightknown** [comment]
here are two bugs that I found
![b](https://user-images.githubusercontent.com/74637789/117089173-5c384280-ad72-11eb-91d9-54f059c8d794.png)
 
The markdown is not correct the `####` and a `-->` is still there. What is suggest is do the changes and once you do it, preview in preview tab, you'll know how it looks before commiting or making a PR for those changes. Another suggestion maybe you could put the github stats and stars side by side, it'll give you more space to add something cool

**Comment by Ankit0225** [comment]
Ok I would Work on it

**Comment by Sam-Varghese** [comment]
Hi @Ankit0225, nice profile. I have a suggestion that you should remove **Here are some ideas to get you started** as it was only meant to assist you on how to write and what to write in this readme. It is of no use to the visitor who intends to know more about you.
![image](https://user-images.githubusercontent.com/79152648/117487182-5d42bd00-af88-11eb-8137-2ce6111665f3.png)

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- highly suggest adding a GitHub profile picture
- add more to your bio
- language badges could go on 1 line to save vertical space
- suggest renaming `frameworks` to `tools` as most are not frameworks
- most languages widget takes up too much space, suggest removing
