### ISSUE TITLE
[REVIEW] https://github.com/abcdan/chainson

### ISSUE THREAD

**Issue by abcdan** [EddieHubCommunity/support#1478]
**Github Profile Link:**
[https://github.com/abcdan/chainson](https://github.com/abcdan/chainson)

**Comment by schmelto** [comment]
Really love the profile especially the joke at the end 🚀 

may two suggestions
* use conventional commits
* remove the package on the right side due its not needed :)

**Comment by abcdan** [comment]
Gotcha! Thanks!

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon. Great to see the community already giving you feedback 💥

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- using the old style default branch of `master` suggest using `main`
- delete branches that are not used
- use releases as well as tags
- suggest hiding packages if not using that feature
- missing code of conduct and contributing file
- use issues even if just you working on the project, so others can follow along - also thy find you from from `good first issue` label
- link in wiki to docs does not work
