### ISSUE TITLE
Create a livestream checklist to make sure Eddie's streams can go to the next level!

### ISSUE THREAD

**Issue by sreekaransrinath** [EddieHubCommunity/support#1480]
**Description**

Some wonderful streams face small hitches in performance because of some silly things we forget. Let's fix that by getting a checklist for Eddie!

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by sreekaransrinath** [comment]
@nhcarrigan you asked me to mention you :)

**Comment by nhcarrigan** [comment]
Checklist item #1 *must* be `Check the Green Bars`

**Comment by Rahma-AlWadhahi** [comment]
Another point that I would add is:
- Charge the lights or keep them plugged in to avoid ghosting shadows

**Comment by schmelto** [comment]
> * Charge the lights or keep them plugged in to avoid ghosting shadows

maybe consider to put the facecam to the right side of the stream that if the light goes out the shadows doesn't border (haha border 🤣 )

**Comment by Evavic44** [comment]
- Have his dinner early enough to enable him stay hours in the streams. ~Just kidding~😆

**Comment by starlightknown** [comment]
- make some tweaks so that you don't have to bring the whole discord screen to show who's talking and occupy screen space

**Comment by kaiwalyakoparkar** [comment]
> > * Put a timer on the screen for every reviewing every profile. (Although we love in between conversations but at the end the profile doesn't gets reviewed at its best)
> 
> This is a great idea 👍🏾

Guess what it is going to be implemented in the tonight's live stream :wink:

**Comment by eddiejaoude** [comment]
Thanks all for the great feedback 👍 

I think I have made most of these improvements. However, I just started using StreamYard and I do not think it is possible to have a timer and have me talking at the same time 😢
