### ISSUE TITLE
[REVIEW] GitHub Profile

### ISSUE THREAD

**Issue by Evavic44** [EddieHubCommunity/support#1484]
**Github Profile Link:**
[Profile Link](https://github.com/Evavic44)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

#### _Any ideas on how to improve my profile? especially on the `Progress Checklist` section. Thank you._ 👍🏾

**Comment by schmelto** [comment]
I really love the Progress Checklist! 🚀 And nice touch with the `A` in J🅰️vascript!

Maybe one suggestion. Remove the GitHub Follower count due it is redundant with what is already shown on the GitHub page.
![image](https://user-images.githubusercontent.com/30869493/117004076-f1412a00-ace5-11eb-89f2-cc958913e30f.png)

**Comment by Evavic44** [comment]
Lol. Can't believe I didn't notice that. 😄 🤦🏽‍♂️ Good sight.

**Comment by Priyanshu-official** [comment]
@Evavic44 Awesome Profile buddy also Nice idea of adding **Checklist**

**Comment by Evavic44** [comment]
> @Evavic44 Awesome Profile buddy also Nice idea of adding **Checklist**

Thank you so much, glad you liked it. 😎

**Comment by Sam-Varghese** [comment]
HI @Evavic44; liked your profile. In order to make your profile better, you can add more stats, contribution graphs etc. Ex: [My profile](https://github.com/Sam-Varghese)

**Comment by Sam-Varghese** [comment]
Welcome 🙂

**Comment by eddiejaoude** [comment]
@Evavic44 did you mean to close it? We can still review on a live stream, even though you already got community feedback

**Comment by Evavic44** [comment]
> @Evavic44 did you mean to close it? We can still review on a live stream, even though you already got community feedback

Oh, It has already been reviewed on the live stream. 😊 Thanks Eddie.
