### ISSUE TITLE
[REVIEW] Github Readme Streak Stats

### ISSUE THREAD

**Issue by DenverCoder1** [EddieHubCommunity/support#1526]
**Project Link:** https://github.com/DenverCoder1/github-readme-streak-stats

**Github Readme Streak Stats**
🔥 Stay motivated and show off your contribution streak!
🌟 Display your total contributions, current streak, and longest streak on your GitHub profile README

**Note:**
This repo was previously requested in #625, but there was not enough time to review the project and my profile page was reviewed instead. I have opened this new issue with Eddie's permission so the repo can be reviewed. :smile:

**Comment by schmelto** [comment]
Wow 🚀🚀🚀
You are behind readme streak stats nice 💪🏼

One small suggestions from my side.
- change the link to the demo website

**Comment by DenverCoder1** [comment]
> Wow 
> You are behind readme streak stats nice 💪🏼
> 
> One small suggestions from my side.
> 
> * change the link to the demo website
>   ![Screenshot_20210507_042100.jpg](https://user-images.githubusercontent.com/30869493/117389164-3c2c8e80-aeec-11eb-910b-e33e060539a4.jpg)

Thanks! :+1: 

I originally put that link before there was a demo site since it's a place you can see it in action, but the demo URL makes a lot more sense. I have updated it. :tada:

**Comment by Priyanshu-official** [comment]
@DenverCoder1 Nice GitHub Streak with Theme

**Comment by kaiwalyakoparkar** [comment]
Haha @DenverCoder1, what should I say. Your project is used by me on my profile as well. Loved it :smiley:

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- use releases/tags - this can be automated via GitHub Actions when merge to `main`
- GitHub Action to deploy after merge to `main`
- remove `wiki` as not being used 
- table of contents in the README is probably no longer needed as GitHub has this new feature now

**Comment by rohan-kulkarni-25** [comment]
## Nice Repository Especially the Read me It's really explained well 

You can add issue labels
