### ISSUE TITLE
[REVIEW] Keytotext

### ISSUE THREAD

**Issue by gagan3012** [EddieHubCommunity/support#1566]
**Project Link:** https://github.com/gagan3012/keytotext

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey @gagan3012, Thanks for submitting. The project is great but I would love to give some suggestion
- Delete unwanted branches (As I saw from the network. Many branches are not been in use for a long time)
- Add project board to your project (It depends person wise but having it really helps)
- Add GitHub actions
- Are the releases automated? (If not then making them automated will save you time.)

Loved the readme and the management of project. Your submission will get review by eddie on livestream soon as time permits

**Comment by schmelto** [comment]
Nice work!


Some. Suggestions from my side
![Screenshot_20210510_115026_com.github.android.jpg](https://user-images.githubusercontent.com/30869493/117640992-effc7b00-b185-11eb-8150-df911c15c224.jpg)
Update the banner you have more than 3 stars lol :)

The link in the description doesn't seems to work properly 
![Screenshot_20210510_115011_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/117641050-ff7bc400-b185-11eb-9e7a-8492643cb0d8.jpg)

**Comment by eddiejaoude** [comment]
Thank you for sharing, I will review on a live stream soon 👍

**Comment by Panquesito7** [comment]
Can someone remove the `no-issue-activity` label, please? Thanks. 🙂

**Comment by rohan-kulkarni-25** [comment]
## Great Readme thanks I got Idea when I need to add code snaps in readme you just took it to next level 
## Please use Github Actions to automate work 

As repository is big you can add repository structure in readme at bottom !! 

Project is quite impressive

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- releases look great
- can some branches be closed
- is the `.idea` folder required
- `UI` folder is in capitals everything else is lowercase
- live link does not work `This app has gone over its resource limits. Please try again in a few minutes.`
