### ISSUE TITLE
[REVIEW] COVID-Text-Extractor

### ISSUE THREAD

**Issue by gagangulyani** [EddieHubCommunity/support#1577]
**Project Link:**

(P.s. I raised issue and added them in project boards for the things I feel like are missing in this project, I'm new to open source.)

https://github.com/gagangulyani/COVID-Text-Extractor

**My Portfolio Site**

https://gagangulyani.github.io/

**Comment by schmelto** [comment]
Hey @gagangulyani,

nice project! 🚀 

some suggestions from my side:

- https://github.com/gagangulyani/COVID-Text-Extractor/community take a look here and add the missing points
- add a release to your repo


- I love that you are using a GIF to show the application

**Comment by gagangulyani** [comment]
Thank you for your time! I'll make sure to update this project.

**Comment by eddiejaoude** [comment]
Thank you for sharing, I will review on a live stream soon 👍

**Comment by rohan-kulkarni-25** [comment]
- Try to make Releases of bugs or features 
- You can try to add personalised issue labels 
- Try to automate working with action ( like syntax check or something like that ) 
- Can add links to requirement so user can hop in directly 
![Screenshot from 2021-09-03 21-53-55](https://user-images.githubusercontent.com/76584243/132038107-3d89e51a-47f1-41a4-93a8-c0f214d60dbd.png)

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- no releases, suggest using them or hiding
- hide packages if not using
- animated command line gif looks great
- maybe `good first issue` can get more people involved 
- add code of conduct
- add license
- hide `wiki` tab if not used
