### ISSUE TITLE
Remove unnecessary spaces generic.md

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#1582]
![Screenshot_20210510_175015.jpg](https://user-images.githubusercontent.com/30869493/117687590-3bc81800-b1b8-11eb-8b94-6b539aef0d42.jpg)

**Comment by krishdevdb** [comment]
Got it @starlightknown

**Comment by starlightknown** [comment]
Oops sorry 😬 I thought that was the same. @krishdevdb it's up for grab. Go ahead

**Comment by krishdevdb** [comment]
Working on it @starlightknown

**Comment by krishdevdb** [comment]
Did it @schmelto and @starlightknown

**Comment by starlightknown** [comment]
Requested some changes

**Comment by AyushRaj8271** [comment]
Hey @schmelto  I would like to work on this issue ! Is it still available?

**Comment by starlightknown** [comment]
Hey @AyushRaj8271 there's already a PR up for this issue
