### ISSUE TITLE
[REVIEW] ghulamyazdani

### ISSUE THREAD

**Issue by ghulamyazdani** [EddieHubCommunity/support#1587]
**Github Profile Link:**

  https://github.com/ghulamyazdani

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Really like your profile. Only one suggestion the connect with me links are nearly not visible in dark mode

**Comment by Ayush7614** [comment]
> **Github Profile Link:**
> 
> https://github.com/ghulamyazdani-bot
> 
> You can also join the discord community [here](http://discord.eddiehub.org)
> 
> Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

@ghulamyazdani-bot you can also add github stats in your profile so it looks more awesome

**Comment by rohan-kulkarni-25** [comment]
- Can make this one content center 
![Screenshot from 2021-09-03 21-58-36](https://user-images.githubusercontent.com/76584243/132038657-08e49a01-87e2-4c67-985a-c99f30c1efda.png)


- Can add description of your project ( Not to big ) 
- Can find a horizontal one for language card 
- In darkmode connect icon not visible 
- try to personalise content than common one given from github

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- `connect with me` icons are not very visible in dark mode
- maybe try to use the white space on the right a bit more to make the profile shorter in height
