### ISSUE TITLE
[REVIEW] My Github profile

### ISSUE THREAD

**Issue by janaSunrise** [EddieHubCommunity/support#1590]
**Github Profile Link:** [Profile](https://github.com/janaSunrise)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by janaSunrise** [comment]
Oh, Thanks a lot! 🤓 Also, Today I updated the Licenses for 90% of repo, Does it look fine, Updating everything? 😅

**Comment by Sam-Varghese** [comment]
Great profile, just one problem, clicking YouTube icon shows this:

![image](https://user-images.githubusercontent.com/79152648/122264585-526b3880-cef5-11eb-9ca3-40fedcb78ab0.png)

**Comment by janaSunrise** [comment]
Thank you! 😁 Got it fixed!

**Comment by krishdevdb** [comment]
Wasn't this fixed in https://github.com/EddieHubCommunity/support/pull/1873 @nhcarrigan? I think that the version of stalebot you made a fix for doesn't equal the version we are using?

**Comment by rohan-kulkarni-25** [comment]
- Can reduce intro a little bit 
![Screenshot from 2021-09-03 22-05-40](https://user-images.githubusercontent.com/76584243/132039472-25055bcd-71c5-44c0-acf2-353d5a6d8c6a.png)

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- `npx card` was very cool 😎 
- code block about you looks good, but I think is too long
- try shortening the profile as it hides your activities below
