### ISSUE TITLE
[REVIEW] Can you review my Github Profile? 

### ISSUE THREAD

**Issue by tansionline** [EddieHubCommunity/support#1591]
**Github Profile Link:**

https://github.com/tansionline

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- you are not part of the EddieHub GitHub Org
- The animated gif could go to the right and text on the left to make better use of space
- Try to make the skills stand out more
- Concise profile is really nice and clean
-

**Comment by tansionline** [comment]
Thank you for reviewing. Let me know if you come to Antalya. 💚
