### ISSUE TITLE
[REVIEW] Can you please review my Github Profile?

### ISSUE THREAD

**Issue by ayushtamra** [EddieHubCommunity/support#1592]
**Github Profile Link:**

https://github.com/ayushtamra
You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Like it only one think maybe consider using the same theme at the GitHub stats

**Comment by ayushtamra** [comment]
Sure, will be doing it,
Thanks @schmelto for your valuable review and suggestion.

**Comment by Ayush7614** [comment]
> **Github Profile Link:**
> 
> https://github.com/ayushtamra
> You can also join the discord community [here](http://discord.eddiehub.org)
> 
> Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

@ayushtamra i have one suggestion for you plss add the icons for languages and frameworks so it looks more good and uses themes in github readme stats so it looks good For example you can see my github profile

![image](https://user-images.githubusercontent.com/67006255/118594480-2c078f80-b7c7-11eb-965d-3a8fcb063dad.png)

**Comment by ayushtamra** [comment]
Thanks @Ayush7614, that's an impressive suggestion,
I will make the required changes today.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by rohan-kulkarni-25** [comment]
- Can make Allign My achivement to left that will look more better 
- 
![Screenshot from 2021-09-03 22-28-17](https://user-images.githubusercontent.com/76584243/132041791-0d125e46-bd3c-47ea-820e-d2b449bdc0e4.png)


Can align the image to center or can crop and fix allignment

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- In the section `My Devpost achievments` the badges are not centred
- Great use of space
