### ISSUE TITLE
Please invite me to EddieHub Community Org :)

### ISSUE THREAD

**Issue by ankushKun** [EddieHubCommunity/support#1593]
Name : Ankush Singh
Discord : weeblet~kun#0039

**Comment by schmelto** [comment]
Hey @ankushKun you can use the issue template here https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization this will automatically invite you to the github organization :)

**Comment by ankushKun** [comment]
@schmelto Oh, thank you for pointing that out :)

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/support/issues/1594 you can close this issue now :)

**Comment by ankushKun** [comment]
Thank you very much :)
