### ISSUE TITLE
[REVIEW] Open Source Project Review

### ISSUE THREAD

**Issue by adithyapaib** [EddieHubCommunity/support#1595]
**Project Link:**
Project: https://github.com/adithyapaib/antiabuseapi
Profile : https://github.com/adithyapaib
Portfollio: https://adithyapai.com/
Resume: https://resume.adithyapai.com/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by starlightknown** [comment]
Website looks good but maybe make it two modes as dark and light? Also I'm not sure if it's my device problem but your profile looks like this
![Screenshot_2021-05-11-01-18-36-993_com android chrome](https://user-images.githubusercontent.com/74637789/117716397-29210380-b1f7-11eb-9234-23c6cb64b10b.jpg)
![Screenshot_2021-05-11-01-17-49-921_com android chrome](https://user-images.githubusercontent.com/74637789/117716402-2aeac700-b1f7-11eb-886c-7f3fa848442e.jpg)
 The badges are not visible to me.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by rohan-kulkarni-25** [comment]
![image](https://user-images.githubusercontent.com/76584243/134707508-17496e44-926c-4bfe-8cfd-c58f0fcce82a.png)

- `Dont forget to star this repo and follow me!` this line in the last of readme don't look good please be little polite 
- Please Add more issue labels 
- Close projects if not used 
- No Code of Conduct and Contributing Guideliness Please Add it 
- Please remove packages if not used 

- Nice Commit analogy

**Comment by eddiejaoude** [comment]
Reviewed open source project on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg (please raise individual issues)

Looks good, some of our thoughts
- has not had a commit in a while
- hide packages if not being used
- hide wiki if not being used
- suggest using issues, this will help people discover and get involved in the project
