### ISSUE TITLE
[REVIEW] Resume Review

### ISSUE THREAD

**Issue by tansionline** [EddieHubCommunity/support#1597]
Resume link:
Can you review my [resume](https://drive.google.com/file/d/1yerX3NpYm3JrkTPdiTxhtHktpzJ7UCfS/view?usp=sharing)? thank you

**Comment by shubhendumadhukar** [comment]
Few grammatical changes and semantic changes which I think makes it sound more professional

I'm contributing **to** open-source on a daily basis.

During my internship, I worked on the dashboard ~side of the~ **for** Radiolize. I used Vue.js and Bootstrap in this project. ~On the other hand,~ I also ~was~ worked ~in~ upon the settings and setup of IoT devices.

_Also you should explain what Radiolize is_

**Comment by tansionline** [comment]
Thank you for your contribution. I changed it :smiley:

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 . Great to see you are already getting community feedback 💥

**Comment by rohan-kulkarni-25** [comment]
- Try to use the space in Left 
- Can avoid using I in `Who I am ` so many times !!
- You can try changing some font size so can be diffrentiated

**Comment by theriyazo** [comment]
As a UX designer, I think it looks better to add link color just to distinguish other text from the hyperlinks.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- Large `ST` looks great! Suggest maybe having a profile photo there
- Maybe group the sills together (databases, frontend ...)
- Really looks nice and clean

**Comment by tansionline** [comment]
Thank you guys reviewed my **old** resume ❤️ 
I am gonna update and share it again.
