### ISSUE TITLE
[REVIEW] hellosagar

### ISSUE THREAD

**Issue by hellosagar** [EddieHubCommunity/support#1599]
**Github Profile Link:**
https://github.com/hellosagar 

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Ayush7614** [comment]
> **Github Profile Link:**
> https://github.com/hellosagar
> 
> You can also join the discord community [here](http://discord.eddiehub.org)
> 
> Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

@hellosagar i have one suugestion that you can add theme in github stats that it looks more awesome

**Comment by hellosagar** [comment]
@ashwinexe how can I join idk ?

**Comment by hellosagar** [comment]
@schmelto Thanks I will

**Comment by hellosagar** [comment]
@Ayush7614 Like do you have any example? or may that would be great if you create any PR on the repo 
Thanks :)

**Comment by krishdevdb** [comment]
> @ashwinexe how can I join idk ?

Open an issue with the invite template, don't forget to publicize your membership: information in the template comments

**Comment by kaiwalyakoparkar** [comment]
> @ashwinexe how can I join idk ?

Don't worry have a look at this: https://dev.to/kaiwalyakoparkar/accelerate-your-learning-and-grow-your-network-with-eddiehub-1icn . You will understand everything. And if you get stuck somewhere let us know

**Comment by kaiwalyakoparkar** [comment]
@krishdevdb & @ashwinexe I would highly encourage you to share proper reference links with the solution so that they do not get confused and refer the specific document if they need further help.

**Comment by hellosagar** [comment]
> em

What do you mean by ` publicize your membership`

**Comment by hellosagar** [comment]
> > @ashwinexe how can I join idk ?
> 
> Don't worry have a look at this: https://dev.to/kaiwalyakoparkar/accelerate-your-learning-and-grow-your-network-with-eddiehub-1icn . You will understand everything. And if you get stuck somewhere let us know

Thanks. I've applied my application

**Comment by kaiwalyakoparkar** [comment]
@hellosagar Yay :tada: I can see it on your profile now! Welcome to EddieHub!

**Comment by hellosagar** [comment]
> @hellosagar Yay 🎉 I can see it on your profile now! Welcome to EddieHub!

Thanks, man, but after joining the eddihub what are the things that I can do?

**Comment by ashwinexe** [comment]
> > @hellosagar Yay 🎉 I can see it on your profile now! Welcome to EddieHub!
> 
> Thanks, man, but after joining the eddihub what are the things that I can do?

You can join and introduce yourself in the discord server https://discord.eddiehub.org/ 
:)

**Comment by kaiwalyakoparkar** [comment]
> > @hellosagar Yay tada I can see it on your profile now! Welcome to EddieHub!
> 
> Thanks, man, but after joining the eddihub what are the things that I can do?

Join the discord server, get into conversation, help someone solve their issue etc

**Comment by hellosagar** [comment]
> > > @hellosagar Yay tada I can see it on your profile now! Welcome to EddieHub!
> > 
> > 
> > Thanks, man, but after joining the eddihub what are the things that I can do?
> 
> Join the discord server, get into conversation, help someone solve their issue etc

oh, okay thanks
Thats cool

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by FayasNoushad** [comment]
Please merge [this](https://github.com/hellosagar/hellosagar/pull/2)

**Comment by Panquesito7** [comment]
I liked your profile a lot, @hellosagar! IMO, it looks very good as-is. 😄

**Comment by rohan-kulkarni-25** [comment]
- Can Add About Projects and Small Description
- Try to improve Contribution Graph Please also review PR and create Issues

**Comment by theriyazo** [comment]
Hey, Great portfolio.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- looks really clean and concise
- your contribution graph, is very commit heavy, suggest more issues, code reviews and pull requests
