### ISSUE TITLE
[REVIEW] wimpywarlord

### ISSUE THREAD

**Issue by wimpywarlord** [EddieHubCommunity/support#1601]
**Github Profile Link:**
https://github.com/wimpywarlord

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by FayasNoushad** [comment]
@wimpywarlord You are not the member of [Eddie Hub Community](https://github.com/EddieHubCommunity). Join the community.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- you are not part of EddieHub 😱 😢 you can join if you like 
- your profile is customised, but you could make more use of that area
- suggest doing more code reviews, your graph is very commit heavy
