### ISSUE TITLE
[REVIEW] Sharik - a cross-platform file sharing app

### ISSUE THREAD

**Issue by marchellodev** [EddieHubCommunity/support#1605]
https://github.com/marchellodev/sharik
Thanks! :>

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by Panquesito7** [comment]
Why are you closing this, @marchellodev? If you close this, it won't be reviewed in a live stream.

**Comment by marchellodev** [comment]
Oh, sorry, I thought it was already reviewed, and I missed it :)

Thanks!

**Comment by rohan-kulkarni-25** [comment]
- Nice ReadMe 
- Please add github profile Pic 
-  Try to switch from `master` to `main`
- Please Add `Code_of_Conduct` & `Contributing Guidelines`

## Nice !! Got to see some pinned issues

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- add a profile picture to your GitHub account
- suggest using labels for your issues, this helps contributions as well as discoverability 
- missing code of conduct, contributing file, issue templates
- screenshot of the app in the readme would be great

**Comment by marchellodev** [comment]
Thanks!!!!
