### ISSUE TITLE
[REVIEW] Open Source Http/Grpc mocking tool

### ISSUE THREAD

**Issue by shubhendumadhukar** [EddieHubCommunity/support#1606]
**Project Link:**
https://testinggospels.github.io/camouflage/
https://github.com/testinggospels/camouflage

**Comment by krishdevdb** [comment]
## Changes Requested 
- [ ] Add GitHub CI Builds
- [ ] Use https://gitmoji.dev For Commit Emojis
- [ ] Make more small commits than few large ones
- [ ] Add More To The Readme: https://github.com/EddieHubCommunity/support/discussions/1553
- [ ] Remove The Environments Section
- [ ] Add a better description
- [ ] Use Wiki, Projects, Issues and Pull Requests (You can create issues yourself and pull requests too)
- [ ] Move the complete site to `/docs` folder and src to `/src`.
- [ ] PR Templates
- [ ] Contributing.md
- [ ] Post It To Social Media (And Hacker Media)

## Feedback
- [x] Website looks good
- [x] Readme Hero Is Perfect
- [x] Nice Idea

**Comment by shubhendumadhukar** [comment]
- [ ] Add GitHub CI Builds
- [ ] Use https://gitmoji.dev For Commit Emojis
- [x] Make more small commits than few large ones - _I have recently started doing that_
- [ ] Add More To The Readme: #1553
- [x] Remove The Environments Section - _Done_
- [ ] Add a better description
- [ ] Use Wiki, Projects, Issues and Pull Requests (You can create issues yourself and pull requests too)
- [x] Move the complete site to /docs folder and src to /src. - _I have removed the docs from version control since it was making the npm package heavy. I would probably create a separate repo for that._
- [x] PR Templates
- [x] Contributing.md - _I think this is already there._
- [ ] Post It To Social Media (And Hacker Media)

**Comment by krishdevdb** [comment]
> I have removed the docs from version control since it was making the npm package heavy. I would probably create a separate repo for that.

Use .npmignore it works like .gitignore. You can ignore files not to be published :)

**Comment by krishdevdb** [comment]
> Contributing.md - I think this is already there.

![Screeshot](https://user-images.githubusercontent.com/76587897/118128343-62848980-b418-11eb-8a9a-9cc0492c284f.png)

**Comment by shubhendumadhukar** [comment]
Done(.npmignore) and Done(Contributing.md)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 . Great to see you are already getting community feedback 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- wow I have no suggestions, looks amazing 💥 
- if I am stretching some ideas, animated gif / video tutorial
