### ISSUE TITLE
[REVIEW] Please review my resume 🤓 

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#1607]
**Remove all personal data, otherwise the resume will be deleted.**

Resume link: [SS Resume.pdf](https://github.com/EddieHubCommunity/support/files/7227029/SS.Resume.2.pdf)

You can also join the discord community [here](http://discord.eddiehub.org)
Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Prince-Shaikh** [comment]
The resume looks great, everything is well organized and it's a one page resume. one thing I would suggest is to add some color to it, maybe change the color of skills or headings. it will make the resume a bit more attractive.

**Comment by SashoStoichkov** [comment]
> The resume looks great, everything is well organized and it's a one page resume. one thing I would suggest is to add some color to it, maybe change the color of skills or headings. it will make the resume a bit more attractive.

Thank you @Prince-Shaikh 👍🏻 I'll see what I can do

**Comment by schmelto** [comment]
> @schmelto Thank you for the review. Can you please clarify which line are you talking about? 🤔

sure

![image](https://user-images.githubusercontent.com/30869493/117928208-843c1e80-b2fb-11eb-9514-903ded48b1af.png)

Those lines under the headings. I personally prefer if there is a little bit space between end of document.

**Comment by SashoStoichkov** [comment]
Hey - I've updated the resume. I'll be more than happy to see what you think about the new version 🤩

**Comment by schmelto** [comment]
Like it!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks awesome, very clean and concise, I don't have many suggestions 
- could maybe use colours a bit for the skill badges and type (could they be grouped)
