### ISSUE TITLE
[REVIEW] Polyglot

### ISSUE THREAD

**Issue by pranavbaburaj** [EddieHubCommunity/support#1608]
**Project Link:**

https://github.com/pranavbaburaj/polyglot

**Comment by Prince-Shaikh** [comment]
Looks great, to me everything looks complete except the packages section, it's empty so you should turn it off in the settings 🙂

**Comment by pranavbaburaj** [comment]
Thank you :slight_smile:

**Comment by schmelto** [comment]
Some suggestions and on PR for you :)

* consider using conventional commits and using actions to automate the releases
* add a PR template

**Comment by pranavbaburaj** [comment]
> Some suggestions and on PR for you :)
> 
> * consider using conventional commits and using actions to automate the releases
> * add a PR template

Sure, Thank you 🙂

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by pranavbaburaj** [comment]
> Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

Thank you 🙂

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks good, some suggestions...
- suggest moving the wiki section to the docs section
- use issues to get the community involved and also to improve discoverability (with labels)

**Comment by pranavbaburaj** [comment]
Thank you for the suggestions :)
