### ISSUE TITLE
Suggestion: Inform People About Roles In Discord

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1656]
Add a #roles channel in the discord server and tell people about roles and how to get the roles. Because newcomers and people not knowing the feature might not have put on the roles. Maybe add a section to [`#readme`](https://github.com/EddieHubCommunity/support/blob/main/discord-readme.md) about it

**Comment by nhcarrigan** [comment]
Rather than adding a `roles` channel, I think we can use the existing `#bot-chat` channel for the commands. I've added a post in #readme about how to get roles.

**Comment by nhcarrigan** [comment]
🟩 for someone:

This markdown can be added to the bottom of the `discord-readme.md` file:

```md
**Roles**

Our server has a number of roles you can assign to yourself, such as roles for your specific tech stack or roles that we ping for certain events. 

To see the roles that are available, head over to #bot-chat and use the command `becca!role`. Becca will send a list of the roles you can assign to yourself.

To assign a role, use `becca!role <role name>` and Becca will give you that role. For example, if I wanted the `angular` role, I would send the command `becca!role angular`.
```

**Comment by krishdevdb** [comment]
Can I do this?

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by krishdevdb** [comment]
Submitted a PR @nhcarrigan #1659
