### ISSUE TITLE
[REVIEW] akshitadixit

### ISSUE THREAD

**Issue by akshitadixit** [EddieHubCommunity/support#1661]
**Github Profile Link:**

[akshitadixit](https://github.com/akshitadixit)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by animeshbhakat** [comment]
Hello, your profile looks good. Here are some suggestions from my side.

- Add some more info about yourself
- the visitor count doesn't always give the right info. consider removing that.

**Comment by akshitadixit** [comment]
@animeshbhakat thank you for the feedback, I assume by more info you mean the tech-stack I prefer or the technologies most familiar to me, right?

**Comment by animeshbhakat** [comment]
@akshitadixit Yes. You can also add a brief introduction about yourself, tech-stacks you prefer, your goals, current projects you are working on etc..

**Comment by akshitadixit** [comment]
@animeshbhakat thank you so much for the suggestion, will do ☺

**Comment by akshitadixit** [comment]
> > @akshitadixit Yes. You can also add a brief introduction about yourself, tech-stacks you prefer, your goals, current projects you are working on etc..
> 
> As this I really like that you show you're doing the 300 days of open source challange

@schmelto thanks, I see that you're doing 100 days of code as well 👍 like your profile 😇

**Comment by akshitadixit** [comment]
Hey I just made a few changes, if someone would check it out?

**Comment by starlightknown** [comment]
It looks neat and you got few points which you can add from the community members already. Try adding them and it'll be great!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on a video, coming out soon

Looks great, some feedback...
- A lot of white space wasted which makes the profile longer
- Use the bio more, give yourself a shoutout

**Comment by akshitadixit** [comment]
Wow, thank you so much!

**Comment by eddiejaoude** [comment]
You are welcome, thank you for submitting - the video will be out this Wednesday at the earliest or next Wednesday at the latest http://youtube.com/eddiejaoude
