### ISSUE TITLE
Outdated links in the organization invitation issue template

### ISSUE THREAD

**Issue by chaitanyasjoshi** [EddieHubCommunity/support#1667]
**Description**
Links to the GitHub organization list and hacktober fest practice repo in the EddieHub GitHub organization invitation issue template are outdated. 
The 1st link gives 404 while the 2nd redirects to the new URL automatically.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23653544/118286710-5ec43600-b4f0-11eb-86d4-cae14f41ae57.JPG)

**Comment by starlightknown** [comment]
Thank you for raising the issue, the org was renamed and this might be the result of that. We will fix it :)

**Comment by chaitanyasjoshi** [comment]
Thank you @starlightknown for addressing the issue quickly.
Closing as #1668 solves this issue.

**Comment by starlightknown** [comment]
Why did you close this? Please keep it open till the PR gets merged. When they'll merge it this will automatically get closed

**Comment by chaitanyasjoshi** [comment]
Oh! I'm sorry. I'm new here, I will reopen the issue.

**Comment by starlightknown** [comment]
It's alright. A line in PR like `Closes #issuenumber` does the work of closing the issue automatically when merged. This issue can be referenced when doing the same

**Comment by chaitanyasjoshi** [comment]
Ok. Thanks for helping me :)
