### ISSUE TITLE
[REVIEW] Shubhamdutta2000

### ISSUE THREAD

**Issue by Shubhamdutta2000** [EddieHubCommunity/support#1677]
**Github Profile Link:** : https://github.com/Shubhamdutta2000

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by animeshbhakat** [comment]
Hello, @Shubhamdutta2000. Your profile looks really good. Here are some suggestions from my side.

- The Medium icon under the "connect with me" section is not visible in the default dark mode.
- Consider putting the "My Works" section after Bio.
- The profile views don't always give the right info. Please consider removing that.
- The GitHub followers numbers are already on the profile. The GitHub follower count badge is looking a bit repetitive. Consider removing that also.

**Comment by schmelto** [comment]
Maybe also take a look at the icons some of them have transparent background some of them not looks little bit wired :) otherwise a good portfolio 🚀

**Comment by vinzvinci** [comment]
Maybe align these logos on the left?
![image](https://user-images.githubusercontent.com/73097560/118389290-d82c6780-b65b-11eb-8dee-a9fd4564d44b.png)

~~-~~
The tech stacks making the GitHub profile long, maybe let your project speaks for your tech stacks?

**Comment by animeshbhakat** [comment]
> Maybe align these logos on the left?
> ![image](https://user-images.githubusercontent.com/73097560/118389290-d82c6780-b65b-11eb-8dee-a9fd4564d44b.png)
> 
> ~-~
> The tech stacks making the GitHub profile long, maybe let your project speaks for your tech stacks?

Hello @vinzvinci .. isn't it a good a to put the GitHub stats in the same line to save some space and look the profile more compact.

**Comment by vinzvinci** [comment]
Yeah, for me, it's better to put it on the same line @animeshbhakat 👍

**Comment by Shubhamdutta2000** [comment]
Done can you suggest other changes

**Comment by Shubhamdutta2000** [comment]
https://github.com/Shubhamdutta2000

Can you review this README once more. I have done some changes

**Comment by schmelto** [comment]
Non transparent images are still open for me :)

![image](https://user-images.githubusercontent.com/30869493/120150075-e0071280-c1ea-11eb-9f2c-87e388ef34a0.png)

**Comment by krishdevdb** [comment]
> Non transparent images are still open for me :)
> 
> ![image](https://user-images.githubusercontent.com/30869493/120150075-e0071280-c1ea-11eb-9f2c-87e388ef34a0.png)

@schmelto I don't know if it is possible for doing that because some logos are text only and only black in color, I don't github will allow you to choose the image on the bases of theme the user is using?

But I have a suggestion @Shubhamdutta2000 you can instead only add the icons of the logo, this will make a difference

**Comment by schmelto** [comment]
VueJs is wotking for me :) ![image](https://vuejs.org/images/logo.svg)
Vue logo from https://vuejs.org/

**Comment by krishdevdb** [comment]
That's only an icon @schmelto that is what I told them to do

**Comment by Shubhamdutta2000** [comment]
Now check i have improved some icons

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on a video, coming out soon

Looks great, some feedback...
- Great use of white space and full width
- Add 1 more sentence to your bio
- Skills takes a lot of vertical space, suggest 2 or 3 columns
