### ISSUE TITLE
[REVIEW] Resume to aim for Fellowship

### ISSUE THREAD

**Issue by ashwinexe** [EddieHubCommunity/support#1688]
Hello people,

I would like to have my resume reviewed, I'm new to fellowships programs (MLH fellowship for example) and want to do one. So need to know where I can work upon to improve my resume/eligibility.

Resume link:  https://flowcv.io/resume/feedback/usIbo0xBtxxN

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Akshu-on-github** [comment]
Hey there! Thought that I'd add my two cents...

## Things I liked:
- Relavant experience (your term as a mentor) & current position under `Professional Experience`
- Provided a summary and a link to each project
- There's a clear timeline (reverse chronological order)

Kudos to you on those! However...

## Things I'd work on:
- Noticed that your resume goes over a page
- I'd advice against skill ratings (your 5/5 might not match up with what the interviewer has in mind + some ATS don't render images properly + takes up space that could be put to better use)
- Two of the external links don't work: the project related to stocks and the certificate related to algorithms

**Comment by ashwinexe** [comment]
Thanks @Akshu-on-github for the wonderful review, I've made the necessary changes, feel free to add any more suggestions you get at any point in future, I'll keep the thread open for suggestions.

**Comment by LamiWilliams** [comment]
Hi there. I like the use of colour. The information provided are also concise, which is great. Love your use of icons too.

Here's what I have to say:

1. "Experiences" is stretched out to the next section. It causes a bit of distraction. What you can do is to move it below "Professional" like "Canada" is below that date
![image](https://user-images.githubusercontent.com/54284167/119006146-04abf080-b988-11eb-96e8-f407cb705b41.png)

2. The two items; date-date and date/location are inconsistent. You could stick with one form
![image](https://user-images.githubusercontent.com/54284167/119006829-9d427080-b988-11eb-89ec-5757a125e464.png)

3. The indentations I marked red does not match the ones I marked green. The green one is more consistent in your design. So, you could go with that 
![image](https://user-images.githubusercontent.com/54284167/119007526-35405a00-b989-11eb-8f7b-b350952a0846.png)

4. Same problem with indentation
![image](https://user-images.githubusercontent.com/54284167/119008070-bbf53700-b989-11eb-9867-892c10bc6c63.png)

5. The left and right padding are not equal on both pages
![image](https://user-images.githubusercontent.com/54284167/119008512-25754580-b98a-11eb-8a60-f30458d22836.png)

6. Perhaps, you could try reducing it to one page?

Best of luck!

**Comment by kaiwalyakoparkar** [comment]
It is great and many folks have suggested some great things. I would love to add one more thing instead of "My Resume" you can put your name there.

**Comment by ashwinexe** [comment]
@LamiWilliams Thanks for the wonderful review with graphics, I'll make the changes you suggested soon :)

**Comment by ashwinexe** [comment]
Hey @kaiwalyakoparkar It was originally my name, I removed it because I read somewhere to remove any personal details (including full names), I might have misunderstood that part back then.

**Comment by kaiwalyakoparkar** [comment]
@ashwinexe Ahh, Actually the personal info things meant, phone number, email-id, address, etc. Name is not a concern here :)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥
