### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shonali2600** [EddieHubCommunity/support#1689]
Please invite me to the GitHub Community Organisation.

- #### Name: Sonali Kushwaha

- #### Discord Username(if exists): Sonali Kushwaha

- #### Additional Context:

I got to know about this community through LinkedIn and would like to be a part of this.
:nerd_face:

**Comment by eddiejaoude** [comment]
GitHub Actions were having a bad day when you created this issue. It looks like you were still added to the organisation. So I will close this for now. Any issues let us know 🤓
