### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by Skyhero-admin** [EddieHubCommunity/support#1699]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: https://skyhero-admin.github.io/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Prince-Shaikh** [comment]
NIce portfolio, looks good, some I have for you:
- the text above these icons is not clearly visible (HTML, CSS). It is almost the same as the background color.
![image](https://user-images.githubusercontent.com/47061218/118811175-2349b300-b8c6-11eb-80aa-2f0ed10d8684.png)

- The social media links on the left side will look better if they are left-aligned. 
![image](https://user-images.githubusercontent.com/47061218/118811281-41171800-b8c6-11eb-9d1f-725d9ea68aa7.png)

These are just my preferences tho...🙂

**Comment by schmelto** [comment]
Take a look at the text here

![Screenshot_20210519_153254_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/118821410-854eec00-b8b7-11eb-9997-54220f5ee523.jpg)

This is a duplicate I think

**Comment by Skyhero-admin** [comment]
Thanks for the suggestions @Prince-Shaikh  I am planning on fixing the dark text  😅 
Should I remove that text or change the color ?

**Comment by Skyhero-admin** [comment]
> Take a look at the text here
> 
> ![Screenshot_20210519_153254_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/118821410-854eec00-b8b7-11eb-9997-54220f5ee523.jpg)
> 
> This is a duplicate I think

Ohh
thanks for the suggestion
Are you talking about the last two sentences ?
Should I change the footer text to make it look a little different 🤔

**Comment by Prince-Shaikh** [comment]
> Thanks for the suggestions @Prince-Shaikh  I am planning on fixing the dark text  😅 
> Should I remove that text or change the color ?
> 

Changing the coulor to white should look good...🙂
Add some space above it too.. it'll give some breathing room to the text.

**Comment by Prince-Shaikh** [comment]
[Check this out aswell](https://www.freecodecamp.org/news/how-to-design-good-typography/)

**Comment by Skyhero-admin** [comment]
> [Check this out aswell](https://www.freecodecamp.org/news/how-to-design-good-typography/)

Sure I will check it out

**Comment by Skyhero-admin** [comment]
Can you suggest me about what type of fonts I should use @Prince-Shaikh

**Comment by Prince-Shaikh** [comment]
> Can you suggest me about what type of fonts I should use @Prince-Shaikh 

Helvetica and roboto are the fonts that I like to use. You'll have to see which one suits you better tho. 🙂

**Comment by Skyhero-admin** [comment]
ohk

**Comment by Skyhero-admin** [comment]
Can you explain the text issue again I didn't get it properly @schmelto 😅

**Comment by schmelto** [comment]
> Ohh
> thanks for the suggestion
> Are you talking about the last two sentences looking very similar?
> Should I change the footer text to make it look a little different 🤔

and

> Can you explain the text issue again I didn't get it properly @schmelto 😅

Yes thats what I would say :)

**Comment by Skyhero-admin** [comment]
ohk 👍

**Comment by schmelto** [comment]
@Skyhero-admin you meant to close this one? It would be still up for Livestream review if you reopen it :)

**Comment by Skyhero-admin** [comment]
ohk
thanks for informing @schmelto 😁

**Comment by Skyhero-admin** [comment]
I will probably open it again after some time
