### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Kritika-2000** [EddieHubCommunity/support#1700]
Please invite me to the GitHub Community Organisation.

- #### Name: Kritika Agrawal

- #### Discord Username(if exists):

- #### Additional Context:
 

:nerd_face: Met Eddie on Github </br> I am in love with open source contribution. These amazing communities helps us to share our skills and knowledge with each other. I want to join this community to contribute something useful to it and also to learn new things.

**Comment by eddiejaoude** [comment]
Hi @Kritika-2000 , it looks like you are already part of the organisation. 

```json
Validation Failed: 
{
   "resource":"OrganizationInvitation",
   "code":"unprocessable",
   "field":"data",
   "message":"Invitee is already a part of this org"
}
```
https://github.com/EddieHubCommunity/support/actions/runs/854146410

I will close this, but any issues let us know 🤓
