### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ambivert-sam** [EddieHubCommunity/support#1701]
Please invite me to the GitHub Community Organisation.

- #### Name: ambivert-sam

- #### Discord Username(if exists):

- #### Additional Context:
 Youtube , twitter

 I love open-source and love contributing to vivid projects

:nerd_face:

**Comment by eddiejaoude** [comment]
Hi @ambivert-sam ,  it looks like you are already part of the organisation. 

```json
Validation Failed: 
{
   "resource":"OrganizationInvitation",
   "code":"unprocessable",
   "field":"data",
   "message":"Invitee is already a part of this org"
}
```
https://github.com/EddieHubCommunity/support/actions/runs/854174693

I will close this, but any issues let us know 🤓
