### ISSUE TITLE
[REVIEW] portfolio 

### ISSUE THREAD

**Issue by vikkastiwari** [EddieHubCommunity/support#1715]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: https://iamvikkastiwari.web.app/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey @vikkastiwari, I guess you have opened two issues with two different links. It would be good if you add this link to the existing issue #1716. This will help us reduce the unnecessary clutter in the issue section

**Comment by eddiejaoude** [comment]
@kaiwalyakoparkar I think it is better if there is 1 link per issue

**Comment by krishdevdb** [comment]
> @kaiwalyakoparkar I think it is better if there is 1 link per issue

Yep 💯 True!!

**Comment by vikkastiwari** [comment]
> @kaiwalyakoparkar I think it is better if there is 1 link per issue

Yes, but I was then suggested to close one that's why I closed this one.
I created issue #1716 and #1715

**Comment by kaiwalyakoparkar** [comment]
Oh! @eddiejaoude we suggested this to some folks before so I thought! No worries my bad :)

**Comment by eddiejaoude** [comment]
> Oh! @eddiejaoude we suggested this to some folks before so I thought! No worries my bad :)

No worries, we are trying different things. I think the confusion is, we are suggesting a single issue / discussion  if sharing twitter / blog post links etc, you are right 👍 . But for live stream reviews it is probably better separate issues

**Comment by emmalearnscode** [comment]
@vikkastiwari this is a really great looking portfolio, it looks really professional. I just have a couple of small things

- I’m unsure of these bars under the titles. Are they supposed to represent your level of skill/confidence? I’m not sure they really get that across.
![B09AB99E-B081-4180-AB51-B99F5E75A4EB](https://user-images.githubusercontent.com/57045550/143929943-bed529b2-9ab8-4309-b301-6020321f6a10.jpeg)

- the open source section looks a bit cramped compared to everything else 
![9E2E6928-B637-4A49-A98B-F9690CAB8896](https://user-images.githubusercontent.com/57045550/143930035-0bcad773-7f03-421b-8464-6c6affc3c9b9.jpeg)

- try to sell your services a bit more in the contact section, don’t ask for suggestions as that makes you sound less confident. Instead have a call to action, you want people to hire you.

**Comment by krishguptadev** [comment]
- It will be nice if you add a consistent height

![image](https://user-images.githubusercontent.com/91655303/145826195-678a25a2-a01c-49b4-9ee3-2997ca2a104f.png)

- Weird cluttering over here

![image](https://user-images.githubusercontent.com/91655303/145826277-de9a3472-62b0-4793-ba56-480fe61c8a10.png)

- Work on lighthouse issues

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- typing animation looks great, but not accessible
- I would move skills and open source above resume

**Comment by Kira272921** [comment]
🤔 I think it isn't a great way to represent your skills level using the progress bar, coz the other person doesn't know what you have taken to the base and made those progress bar
