### ISSUE TITLE
[REVIEW] Personal Page - emanuel-dev

### ISSUE THREAD

**Issue by EmanuelGF** [EddieHubCommunity/support#1718]
**Personal Page**
[emanuel-dev](https://www.emanuel-dev.com)

Other things to review if time allows:

**Github Profile Link:**
[EmanuelGF](https://github.com/EmanuelGF)
**Github Project Link:**
[Template-react-ui](https://github.com/EmanuelGF/template-react-ui)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Only one thing I would move the how to contact me to the bottom of the readme otherwise I really like that you want to contribute to open source project related to global warming 🚀

**Comment by vinzvinci** [comment]
Just a quick suggestion:
- Have social media badges links like `Twitter`, `LinkedIn` and etc. coz maybe someone are interested to know you more~
- Put the GitHub Stats below
- You can look at other profiles for your GitHub profile inspiration.

**Comment by schmelto** [comment]
Hey @EmanuelGF due limited time during the livestream we only can review one of the three projects. Which one would you like to get reviewed

**Comment by EmanuelGF** [comment]
> Hey @EmanuelGF due limited time during the livestream we only can review one of the three projects. Which one would you like to get reviewed

Hi Tom 👋
I would be so glad if can review my new personal page. I've finished last week and would love to know opinions about it.  
I made it using React and Strapi headless cms.   
Thank you 😄

**Comment by schmelto** [comment]
> > Hey @EmanuelGF due limited time during the livestream we only can review one of the three projects. Which one would you like to get reviewed
> 
> Hi Tom 👋
> I would be so glad if can review my new personal page. I've finished last week and would love to know opinions about it.
> I made it using React and Strapi headless cms.
> Thank you 😄

I've updated your issue description :)

**Comment by schmelto** [comment]
WOW 

![image](https://user-images.githubusercontent.com/30869493/122356036-b5d78380-cf52-11eb-9df3-6fb2131eded6.png)

Scoring at its best
Personally I would make the navbar a little bit bigger

**Comment by EmanuelGF** [comment]
Thank you so much for your review 🙏

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by EmanuelGF** [comment]
> Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

Thanks Eddie! Looking forward for your review 😃🙏

**Comment by eddiejaoude** [comment]
Reviewed on a video, coming out soon

Looks great, some feedback...
- Great description
- Not part of EddieHub Org 😢 
- Cat gif is funny but a lot of wasted space on the right, suggest removing or putting the graph to the right of it
- Tech badges are very squashed, some have gaps and others do not, suggest grouping
- Try to do more code reviews even if you are not the maintainer on the project
