### ISSUE TITLE
[REVIEW] Prasundas99

### ISSUE THREAD

**Issue by Prasundas99** [EddieHubCommunity/support#1743]
**Github Profile Link:**
https://github.com/Prasundas99

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by krishdevdb** [comment]
## Requested Changes
- [ ] An hero image like [CyberBoyAyush](https://github.com/CyberBoyAyush) or [mine](https://github.com/krishdevdb) won't be bad?
- [ ] Profile Views Counter is an false indicator can be removed
- [ ] Make a table for your skills to make it short and not lengthy
- [ ] I guess the bullet before the frontend skills heading is by mistake

## Feedback
- [x] Overall: nailed it
- [x] Stats: 🤩 
- [x] Work Experience: 😍 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by schmelto** [comment]
One other point from my side. Take a look there are some images with non transparent background

![image](https://user-images.githubusercontent.com/30869493/119942295-ef3f5380-bf91-11eb-9bc2-ac8e90674529.png)

Dont border with the broken links / in my browser most of external images are blocked :)

**Comment by Prasundas99** [comment]
> ## Requested Changes
> * [ ]  An hero image like [CyberBoyAyush](https://github.com/CyberBoyAyush) or [mine](https://github.com/krishdevdb) won't be bad?
> * [ ]  Profile Views Counter is an false indicator can be removed
> * [ ]  Make a table for your skills to make it short and not lengthy
> * [ ]  I guess the bullet before the frontend skills heading is by mistake
> 
> ## Feedback
> * [x]  Overall: nailed it
> * [x]  Stats: 🤩
> * [x]  Work Experience: 😍
> 
> **Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

Thanks sir the for suggestions 
The bullet point before frontend was by mistake I didn't noticed it before .
Removed the profile view counter.
Will surely add a hero image I really loved those profile readme files those were amazing
For the skills I'll look after it, by checking others readme in this org

Thank you

**Comment by Prasundas99** [comment]
> One other point from my side. Take a look there are some images with non transparent background
> 
> ![image](https://user-images.githubusercontent.com/30869493/119942295-ef3f5380-bf91-11eb-9bc2-ac8e90674529.png)
> 
> Dont border with the broken images/ in my browser most of external images are blocked :)

Yeah I'll fix it I didn't checked how it look in dark mode
Thanks for the sugession

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by FayasNoushad** [comment]
GitHub icon of [Dev ops](https://github.com/Prasundas99#dev-ops) not visible in dark mode.

**Comment by Panquesito7** [comment]
Amazing profile, @Prasundas99! I loved it and liked it a lot! 🚀

I have made a [**pull request**](https://github.com/Prasundas99/Prasundas99/pull/5) in your repository for
some minor improvements in your `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 😄

**Comment by krishguptadev** [comment]
- Can make a table or left-right align to save space?
![image](https://user-images.githubusercontent.com/91655303/145828140-cc330a33-60b6-49c2-811c-f9ed7c3ed911.png)

- @krishdevdb's suggestions
![image](https://user-images.githubusercontent.com/91655303/145828213-6ed302b1-2772-404d-a4bf-90eddf296ae1.png)

- why do you have a age badge?
![image](https://user-images.githubusercontent.com/91655303/145828273-21f6ba7c-6657-4f95-a310-4cf197bde0e1.png)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- you haven't joined EddieHub GitHub Org yet 😱 
- not sure if `age` badge is a good think 🤔 
- 2 columns in the skills section to make more use of the white space
