### ISSUE TITLE
[REVIEW] Portfolio Website

### ISSUE THREAD

**Issue by Prasundas99** [EddieHubCommunity/support#1744]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: https://prasun-das.web.app/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by krishdevdb** [comment]
## Requested Changes
- [ ] Image on the home is a little unclear, blurry
- [ ] Change the pointer events on about/contact page title + some images won't hurt
- [ ] Use reveal.js for a effect
- [ ] Projects url can directly point to your repositories?
- [ ] Too many js/css files
- [ ] Add a favicon

## Feedback
- [x] Overall UI: nailed it
- [x] Page Transitions: 🤩 
- [x] Navigation: 😍 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by kaiwalyakoparkar** [comment]
> ## Requested Changes
> * [ ]  Image on the home is a little unclear, blurry
> * [ ]  Change the pointer events on about/contact page title + some images won't hurt
> * [ ]  Use reveal.js for a effect
> * [ ]  Projects url can directly point to your repositories?
> * [ ]  Too many js/css files
> * [ ]  Add a favicon
> 
> ## Feedback
> * [x]  Overall UI: nailed it
> * [x]  Page Transitions: star_struck
> * [x]  Navigation: heart_eyes
> 
> **Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated smiley**

Loved the way you give feedback :)

**Comment by schmelto** [comment]
It is a little bit a hard cut between your normal navigation though the page and the project section where you jump to your github profile I think it  would be better to add some example projects here with a link to github not only linking to github :)

**Comment by schmelto** [comment]
> Loved the way you give feedback :)

Yeah @kaiwalyakoparkar nailed it every time 🚀

**Comment by Prasundas99** [comment]
> ## Requested Changes
> * [ ]  Image on the home is a little unclear, blurry
> * [ ]  Change the pointer events on about/contact page title + some images won't hurt
> * [ ]  Use reveal.js for a effect
> * [ ]  Projects url can directly point to your repositories?
> * [ ]  Too many js/css files
> * [ ]  Add a favicon
> 
> ## Feedback
> * [x]  Overall UI: nailed it
> * [x]  Page Transitions: 🤩
> * [x]  Navigation: 😍
> 
> **Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

Loved the way you gave  this feedback.And thank you for the suggestions will surely look into it

**Comment by Prasundas99** [comment]
> It is a little bit a hard cut between your normal navigation though the page and the project section where you jump to your github profile I think it would be better to add some example projects here with a link to github not only linking to github :)

Thank you sir for the feedback didn't thought this earlier will surely do

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by shreyshreyansh** [comment]
Looks all good, but it would be better if about page would open in the another tab as it takes the user out of your website

**Comment by shreemaan-abhishek** [comment]
Fix spelling errors:
![image](https://user-images.githubusercontent.com/61597896/131613569-ae4a0aa3-4466-4b22-af4b-f7518d310b17.png)
languages*
![image](https://user-images.githubusercontent.com/61597896/131613598-1728ceab-ca9b-4930-82ce-0e67afb6d5bf.png)
Databases*

**Comment by krishguptadev** [comment]
- @krishdevdb's suggestion
- Weird alignment
![image](https://user-images.githubusercontent.com/91655303/145828608-794480ea-3d1b-4dab-aab9-48e1a70d9920.png)
- Why Gaps?
![image](https://user-images.githubusercontent.com/91655303/145828679-37207562-f8eb-4e3e-84b8-8d29d881572a.png)

**Comment by emmalearnscode** [comment]
Overall, I really like the design.

I wonder why you haven’t made a page for your projects, picking out your top ones that showcase your skills best? I think this would have a better effect than sending someone directly to your GitHub where they will be overwhelmed by 70-ish repos to choose from.

Also, just a couple of typos/grammar errors:
![28D27273-C2AA-4FC7-B527-840809C57761](https://user-images.githubusercontent.com/57045550/146437440-30d596da-b4de-4a92-9e49-aca15b22926f.jpeg)
![2E9B7F53-C5AD-4250-9D22-77845CB9BB41](https://user-images.githubusercontent.com/57045550/146437448-c2cc174b-d56a-4320-8c8e-20b20f50b77b.jpeg)

**Comment by eddiejaoude** [comment]
Reviewed on live stream, but looks like the community has covered everything. Thank you for sharing
