### ISSUE TITLE
[REVIEW] ashish-devv

### ISSUE THREAD

**Issue by ashish-devv** [EddieHubCommunity/support#1751]
Portfolio link: https://github.com/ashish-devv

**Comment by schmelto** [comment]
Some suggestion from my side:

* remove the profile count due its inaccurate
* check this image for me its broken
![image](https://user-images.githubusercontent.com/30869493/120024807-02810c00-bff0-11eb-8ba9-d45e4fa0a143.png)

otherwise its looking good

**Comment by vinzvinci** [comment]
This makes your profile long, make the 2 cards in one line

![image](https://user-images.githubusercontent.com/73097560/120052421-d8fbcb00-c057-11eb-927d-c33ddf8e8466.png)

**Comment by animeshbhakat** [comment]
- Some icons are not visible properly (especially the expressjs and flask) in the default dark mode.


![Screenshot (906)](https://user-images.githubusercontent.com/60314168/120056534-82dc5700-c05a-11eb-80b8-3abaf4385a12.png)

- Consider removing the profile visit counter because it does not always give the correct result.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by FayasNoushad** [comment]
- [Connect with me](https://github.com/ashish-devv#connect-with-me) icons not visible in dark mode

**Comment by FayasNoushad** [comment]
Please merge [this](https://github.com/ashish-devv/ashish-devv/pull/1)

**Comment by Panquesito7** [comment]
Great profile, @ashish-devv! I liked it a lot! 😄👍 

I have made a [**pull request**](https://github.com/ashish-devv/ashish-devv/pull/2) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your profile with us! 🚀

**Comment by krishguptadev** [comment]
- Incorrect Badge
![image](https://user-images.githubusercontent.com/91655303/145829072-a1a4054d-30bf-4e11-904b-6c89fb4f7a81.png)

- Not sure how does this look in dark mode
![image](https://user-images.githubusercontent.com/91655303/145829243-a56642a3-79e3-4b2e-a8fa-593eab1cef09.png)

- Weird Alignment
![image](https://user-images.githubusercontent.com/91655303/145829276-396cffd6-720e-4166-89a5-e57dfe264222.png)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- Not part of EddieHub GitHub Org 😢 
- Not a fan of the `profile views`
- 3 widgets at the bottom are not aligned and could make better use of the space on the left and right
