### ISSUE TITLE
[REVIEW] Resume

### ISSUE THREAD

**Issue by yusufdeepwork** [EddieHubCommunity/support#1760]
Resume link: https://flowcv.io/resume/feedback/Fvb6pxzRW4iW

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by vinzvinci** [comment]
I think it's better if the professional experience is on top, not the skills.

**Comment by yusufdeepwork** [comment]
> I think it's better if the professional experience is on top, not the skills.
I guess you are right, The MOST important is experience

**Comment by schmelto** [comment]
For a review in a live-stream could you remove any personal details like phone number? Or if you are good to go with your phone number etc. exposed in a live-stream I think its ok :)

**Comment by yusufdeepwork** [comment]
> For a review in a live-stream could you remove any personal details like phone number? Or if you are good to go with your phone number etc. exposed in a live-stream I think its ok :)

It is not problem for me, If you are bored you can call me however I care about you and  I've removed my phone number so thanks. By the way, How do you find my resume

**Comment by schmelto** [comment]
- I would group experience and education near to each other so the style is consistent.
- I like the call to action at the top.
- I would add the link to the website in plain text 
![image](https://user-images.githubusercontent.com/30869493/120155927-ac7bb680-c1f1-11eb-9312-2da50512fc22.png)
- maybe you can find a way to write out as many links as possible due if the resume is printed the reviewer knows where to look for your projects etc.

**Comment by yusufdeepwork** [comment]
> * I would group experience and education near to each other so the style is consistent.
> * I like the call to action at the top.
> * I would add the link to the website in plain text
>   ![image](https://user-images.githubusercontent.com/30869493/120155927-ac7bb680-c1f1-11eb-9312-2da50512fc22.png)
> * maybe you can find a way to write out as many links as possible due if the resume is printed the reviewer knows where to look for your projects etc.

Thanks for your suggestions and good thoughts. My projects have a link onclick event however you are right reviewer can not find my projects on paper. I will think about grouping experience and education.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on a video, coming out in the next few weeks

Looks great 👍 , some thoughts
- projects to have GitHub links (full link not icon)
- I wasn't keen on this sentence `I care about doing my work in time and fast`, I prefer quality, things like documentation and automation
- personal website to have full url (just incase someone prints the resume)

Bonus, join EddieHub Org 😉
