### ISSUE TITLE
[REVIEW] https://giomine.github.io/

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1761]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link:
- Current URL: https://giomine.github.io/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by giomine** [comment]
Thanks! URL is now https://giomine.github.io/

**Comment by kaiwalyakoparkar** [comment]
That's a great profile :star_struck: but I would like to give some suggestions: :point_down: 
- Improve the lighthouse score. Your current score is : 
- ![ghProfile](https://user-images.githubusercontent.com/53310847/120104660-2b7dda00-c173-11eb-81c3-4b51858f2d9e.png)
- You can shift your about section at the second number Main landing -> About -> Projects
- You can remove this section as it can potentially be replaced by the About section
![ghProfile](https://user-images.githubusercontent.com/53310847/120104733-97604280-c173-11eb-90e4-b9d290da085a.png)
- You can link your resume instead of your projects as the project section can be accessed from the navbar itself
![ghPages](https://user-images.githubusercontent.com/53310847/120104772-c37bc380-c173-11eb-86bb-74ee204172cb.png)
- This card looks a bit odd. You can remove some text or reduce line-height to maintain consistency in your project cards
![ghPages](https://user-images.githubusercontent.com/53310847/120104837-19e90200-c174-11eb-9aa8-9638349ab36f.png)

BTW great profile :)

**Comment by giomine** [comment]
Thanks for your feedback! How can I go about improving performance? Is that affected by the slow load-time of the two Heroku-hosted apps?

**Comment by kaiwalyakoparkar** [comment]
I don't think it's about Heroku-hosted apps. Actaually the performance is good for the Desktop but it gets affected when it switches to mobile view. This pdf contains all the ways you can improve your performance. (This pdf is generated from lighthouse extension itself)
[Lighthouse_Stats.pdf](https://github.com/EddieHubCommunity/support/files/6566252/Lighthouse_Stats.pdf)

**Comment by vinzvinci** [comment]
How about... add light/dark mode features? I highly suggested that and put it on top. Some folks don't really like light xD, just like me :(

**Comment by krishdevdb** [comment]
# Review
## Requested Changes 😉
- [ ] Light House Metrics (They Contain Links To web.dev articles) [Credits: @kaiwalyakoparkar]
- [ ] Anchor Tag links look meaningless, else use them in a section name way, that would be 💪🏻 
- [ ] This looks like a mistake: 
       ![image](https://user-images.githubusercontent.com/76587897/120106553-09885580-c17b-11eb-9b96-2f8d91419e63.png)
- [ ] Add a dark mode: Resource: https://github.com/GoogleChromeLabs/dark-mode-toggle (Enables Media + Custom Setting) [Credits: @vinzvinci]
- [ ] Use a consistent theme (Resource: https://maketintsandshades.com/)
- [ ] Focus On Using Correct Height For Elements That Don't Need It:
       ![image](https://user-images.githubusercontent.com/76587897/120106644-8d424200-c17b-11eb-8d08-d190805503e7.png)
- [ ] Contrast is something you really need to work on
- [ ] Add Favicons (Resource: http://realfavicongenerator.net/)
- [ ] Increase Size Of Content In Navbar, cause the navbar look empty
- [ ] Visual Hierarchy Is Not Correct
- [ ] Need to work on ux
- [ ] Use gsap/scrollreveal.js for animations:
       - GSAP: https://greensock.com/
       - ScrollReveal: https://scrollrevealjs.org/
- [ ] Add hover animations

## Feedback
- [x] Looks Cool 😎 
- [x] Elegant Theme 🤩
- [x] Overall 😍    

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by krishdevdb** [comment]
> Thanks! URL is now https://giomine.github.io/

Edited [My Message](https://github.com/EddieHubCommunity/support/issues/1761#issue-906737009)

How about creating another repo with the name of portfolio and adding a redirect to the new website?

**Comment by schmelto** [comment]
Consider using one light and one dark theme and make a toggle between them your website has a high contrast between several areas. This is just a personal preference from my side. Otherwise I like the overall design 💪🏼 great work!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by giomine** [comment]
Amazing thank you! I can't wait for the livestream :D
Thanks everyone for your amazing feedback!

**Comment by krishguptadev** [comment]
- @krishdevdb suggestion
- this is weird
![image](https://user-images.githubusercontent.com/91655303/145829554-dba34ac0-0f3c-48e5-b6b5-28ef17c0fa05.png)
- Can bold this or something?
![image](https://user-images.githubusercontent.com/91655303/145829729-790dd992-9102-4f04-9c79-7d262ab75e70.png)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- Maybe in the about section have a profile picture
- In the `contact me` section, how can they get in contact?
