### ISSUE TITLE
[REVIEW] Website

### ISSUE THREAD

**Issue by Sam-Varghese** [EddieHubCommunity/support#1806]
Hi; I have completed creating my first website for my father's coaching classes. Kindly review the website and suggest how could I have made it better.

Link: https://sam-varghese.github.io/PaulClassesWebsite/index.html

**Comment by Sam-Varghese** [comment]
I think community members are busy with other important works, hence I am closing this issue.

**Comment by starlightknown** [comment]
Hey @Sam-Varghese there are lots of issues and I would say they'll get to your issue soon, you can keep it open and Eddie will surely review it on livestream when he does

**Comment by schmelto** [comment]
Correct :)

great lighthouse score for the website lol :)

some suggestions from my side

- remove white-space at the bottom of the pages
- Its confusing that the navbar is changing on clicking on different links change of order etc.
- Personally I'm not a fan of that many colors on a web page
- I would take a look at the fonts think there are different fonts used on the page
- I would consider removing the "make text black on hover" effect
- also the zoom effects make the use of the website a little bit difficult and sometimes hiding or colliding with other contend

**Comment by Sam-Varghese** [comment]
> Hey @Sam-Varghese there are lots of issues and I would say they'll get to your issue soon, you can keep it open and Eddie will surely review it on livestream when he does. You can keep it open if you'd like to

Thanks a lot for your advice. I would surely like to reopen this issue.

**Comment by Sam-Varghese** [comment]
@schmelto  Thanks a lot for such useful feedback, I shall surely work upon these points.

Can you please describe some more about the white space that you are noticing at the bottom of the page because I am unable to see any such thing. This might possibly be due to the background image not taking full window size. Kindly mention your browser window size as well, so that I can see this on my laptop.

**Comment by schmelto** [comment]
![image](https://user-images.githubusercontent.com/30869493/121177046-39131e00-c85d-11eb-8d8a-93b0019a8187.png)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by shreyshreyansh** [comment]
Can work more on the styling part of the website

**Comment by Sam-Varghese** [comment]
@shreyshreyansh Thanks for your suggestion, but how can I improve the styling more? could you kindly elaborate

**Comment by shreyshreyansh** [comment]
> @shreyshreyansh Thanks for your suggestion, but how can I improve the styling more? could you kindly elaborate

You should work on the color scheme of the webiste.. as for some places has a high contrast and places it has a  low.
You could take help of this website to decide you color palletes for the website.
[Coolors](https://coolors.co/)

**Comment by Sam-Varghese** [comment]
Thanks for sharing this awesome website; would be very helpful for me

**Comment by Sam-Varghese** [comment]
Hey folks, thank you very much for your suggestions. I am closing this issue as I think I got enough reviews from you all. Thank you for your valuable suggestions ☺

**Comment by SaraJaoude** [comment]
Hi @Sam-Varghese if you still want this reviewed on a live stream, then please feel free to reopen or create a new issue.

**Comment by Sam-Varghese** [comment]
> Hi @Sam-Varghese if you still want this reviewed on a live stream, then please feel free to reopen or create a new issue.

I've got enough reviews from this awesome community, so I don't feel the need to reopen this issue, thanks a lot 😊
