### ISSUE TITLE
[REVIEW] Uklizdev

### ISSUE THREAD

**Issue by Uklizdev** [EddieHubCommunity/support#1830]
**Github Profile Link:**

https://github.com/Uklizdev

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Nice!

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] Remove the space between the first header and the images of the projects

## Feedback
- [x] Rest Everything is 😍 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by Uklizdev** [comment]
Thanks for the feedback, I've made a few changes!

**Comment by krishdevdb** [comment]
Why close the issue? If you close the issue, Eddie will not be able to review on livestream!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by krishguptadev** [comment]
Nice!

but the profile is big

can reduce a few projects and add the best as a table?

![image](https://user-images.githubusercontent.com/91655303/145830296-d93359c1-5142-4e0d-9274-95f2f406bc65.png)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- profile fields on the left under profile picture, suggest adding a url (website, twitter etc)
- maybe make more use of the extra space on the left/right of `latest projects` section (2 columns)
- profile is quite long, could it be shortened
