### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shashank-001** [EddieHubCommunity/support#1839]
Please invite me to the GitHub Community Organisation.

- #### Name: Shashank shekhar

- #### Discord Username(if exists): shashank_shekhar#4892

- #### Additional Context:

I saw @eddiejaoude in one of his youtube live stream

I think lots of supportive people in the community. they are doing great 🙌 
:nerd_face:

**Comment by eddiejaoude** [comment]
Thank you @shashank-001 ! the EddieHub community are amazing!

**Comment by schmelto** [comment]
> Thank you @shashank-001 ! the EddieHub community are amazing!

Eddie is up with speed commenting
Welcome to the community 🚀

**Comment by eddiejaoude** [comment]
lol it just popped up at the right time, I still have 4k+ notifications to go through 😱

**Comment by devsurajrai** [comment]
Please add me in this amazing community:

I just saw the live video on YouTube and keen to learn and contribute to open source by any means possible.

I have just started wish me Luck.

Thanks.

**Comment by starlightknown** [comment]
Hey @devsurajrai you have to open a new issue with invite me to the organisation so that you can get added

**Comment by shashank-001** [comment]
> 
> 
> Please add me to this amazing community:
> 
> I just saw the live video on YouTube and keen to learn and contribute to open source by any means possible.
> 
> I have just started with my Luck.
> 
> Thanks.

hey, @devsurajrai just create a new issue for joining. 
if you need any help you can join [discord](https://discord.gg/umMmatz7)
