### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by jviotti** [EddieHubCommunity/support#1840]
Please invite me to the GitHub Community Organisation.

Hey there! I've been doing open-source for a while, both on my own projects and on external ones. I initiated and led the Etcher project (https://github.com/balena-io/etcher) (>20k stars) for a long while. I'm currently a Technical Lead at @postmanlabs on the desktop app engineering side maintaining a fork of Electron.js (https://www.electronjs.org) and related utilities. During my career, I landed various contributions to projects such as Electron.js, FlatBuffers, Apache Thrift, Microsoft Bond, Smile, Electron Builder, AppImageKit, and more! On the side, I'm finishing my degree at University of Oxford. My dissertation is concluding with an innovative binary serialization format technology that will be open-sourced after I submit the papers! 

- #### Name: Juan Cruz Viotti

- #### Discord Username(if exists): `jviotti`

- #### Additional Context:

I accidentally came across some of the open-source project reviews, and the feedback is fantastic. I would love to help review some projects myself, and also put mines for honest feedback too!

:nerd_face:

**Comment by schmelto** [comment]
Bojaa welcome 🚀
