### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ps-19** [EddieHubCommunity/support#1853]
Please invite me to the GitHub Community Organisation.

- #### Name: Priyansh Singh

- #### Discord Username(if exists): None

- #### Additional Context: Solved over 2500+ coding question, have strong coding background. Part of an internship. Certified web developer. Contributed to kubernets and pytorch open source project.

Where did you meet Eddie?: I was just searching for new project to work on and i got this organisation.

What do you like about this community/ why do you want to join: Just want some good friends.
:nerd_face:

**Comment by schmelto** [comment]
Weocine @ps-19
