### ISSUE TITLE
Docs: new version of discord readme, private channels & welcome screen

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/support#1856]
**Welcome to the EddieHubCommunity Discord server!**

We believe Open Source is for everyone, yes you!
OPEN SOURCE is NOT about code, it is about people and collaboration
We are invested in getting you those green squares on GitHub! Contributing to Open Source Software (OSS) is a great way for you to learn, work with different people and also network. You'll find awesome people here who will guide you and if you're a beginner in open source, keep an eye on #first-timers and #good-first-issues , if you get stuck somewhere feel free to ask for help in the community, you'll find someone who can help you for sure and others will learn along too!

**Community Rules**
-> Follow the EddieHubCommunity Code of Conduct.
-> Spamming is not allowed.
-> Keep discussions relevant to channel topics and guidelines.
-> Using welcoming and inclusive language.
-> Being respectful of differing viewpoints and experiences.
-> Gracefully accepting constructive criticism.
-> Focusing on what is best for the community.
-> Showing empathy towards other community members.

**Links**
:link: **Code of Conduct:** https://github.com/EddieHubCommunity/support/blob/main/CODE_OF_CONDUCT.md
:link: **Website**: https://www.eddiehub.org/
:link: **GitHub Organization**: https://github.com/EddieHubCommunity

-> **Join our GitHub Organization.** Create an Issue with the type `Invitation to the GitHub Community Organization`
:link: https://github.com/EddieHubCommunity/support/issues/new/choose

**Enforcement**
Instances of abusive, harassing or otherwise, unacceptable behaviour may be reported by contacting the @moderators . All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.

EddieBotDev (or EddieBot), would be monitoring language used on the discord server, to ensure inclusive and welcoming language in the discord server. EddieBot suggests alternatives and it would be a good practice to edit your message, reflecting the suggestion

**Note**: EddieBot is still in development, and there might be a few words flagged by it which should not have been flagged. Open an issue on the repo and get a green square!

**Channels and Categories:**
Channels and Categories consist of the server's main text channels, that are for discourse regarding topics that aren't very tech-specific, and aren't off-topic:

-> GENERAL DISCUSSION 
-> DAILY 
-> COMMUNITY DISCUSSION
-> TECH
-> ALERTS

**How to ask for help**
Tips to help you ask questions which will give you a better chance to get the best answers from everyone.
1. **Read through your code first.** Your problem could be as simple as a typo or a missing closing tag.
2. **Ask Google.** Many code problems can be solved with a quick Google, so give this a try first. If that doesn't help, head back here to ask your question, and follow the tips below.
3. **Clearly describe the problem.** Explain what is happening and what you want to happen.
4. **Share your code.** It’s very unlikely that anyone will be able to solve your problem without seeing your code. Share a GitHub repository, a GitHub gist link or format the code by wrapping it in backticks, like the example below.
```
Code
```
5. **Send screenshots, if relevant.** It often helps people to see the browser output, so send over a screenshot of what you can see, in this case.
6. **Explain what you have already tried.** You don't want people to suggest things you have already done.
7. **Send updates so people know whether their answer has helped you.**
8. **Help other people out when you can.** If people see you helping others, they will be even more likely to help you when you need it.

<hr />
**MEE6 messages for roles**

**Roles**
> Our server has a number of roles you can assign to yourself, such as roles for your specific tech stack or roles that we ping for certain events. 

> To see the roles that are available, head over to #bot-chat and use the command becca!role. Becca will send a list of the roles you can assign to yourself.

> To assign a role, use becca!role <role name> and Becca will give you that role. For example, if I wanted the angular role, I would send the command becca!role angular.

> By reacting to the :ballot_box_with_check:, you agree to our community rules.

> React :ballot_box_with_check: to get @member role and see other private channels.

Example:
![image](https://user-images.githubusercontent.com/73097560/122202983-29847c80-ced0-11eb-8308-8aa33ff20729.png)

**Comment by vinzvinci** [comment]
I'm trying to make the new **discord readme**, so folks won't ignore it anymore. Please make suggestions before I make a pull request. If there's no suggestion, I will start making changes.

**Comment by vinzvinci** [comment]
We don't need to include a description about the specific channel on #readme but include it to channel description, for example 👇 

![image](https://user-images.githubusercontent.com/73097560/122204253-80d71c80-ced1-11eb-83c4-86a1e7f2b985.png)

**Comment by vinzvinci** [comment]
We can edit the messages on the welcome screen, for example 👇 
![image](https://user-images.githubusercontent.com/73097560/122205010-59348400-ced2-11eb-903f-20614040eb00.png)

**Comment by eddiejaoude** [comment]
Server welcome pages...

<img width="1035" alt="Screenshot 2021-06-17 at 14 29 48" src="https://user-images.githubusercontent.com/624760/122406293-a408d700-cf78-11eb-8ba6-2620e6260fb1.png">


<img width="825" alt="Screenshot 2021-06-17 at 14 30 08" src="https://user-images.githubusercontent.com/624760/122406313-a834f480-cf78-11eb-93fd-4e416353dba8.png">

<img width="773" alt="Screenshot 2021-06-17 at 14 30 14" src="https://user-images.githubusercontent.com/624760/122406327-ab2fe500-cf78-11eb-802f-7af64ac0cc31.png">

**Comment by vinzvinci** [comment]
Cool @eddiejaoude 💯 . It's all up to you now 😃 Close this issue if rebranding is done.

**Comment by Vyvy-vi** [comment]
Lgtm!

**Comment by schmelto** [comment]
I think we can close this now. If not feel free to reopen it.
