### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by okikijesutech** [EddieHubCommunity/support#1858]
Please invite me to the GitHub Community Organisation.

- #### Name: OkikiJesu 

- #### Discord Username(if exists):Kiki_J#0872

- #### Additional Context: 

I found him on youtube. The interview he had with Ruth Ikegah. It made me want to join this community.

what I like about this community is the encouragement you get from doing open source projects. The fact that you could do an open-source project no matter how long you've been in programming is really encouraging to me.
:nerd_face:

**Comment by schmelto** [comment]
Welcome @okikijesutech
