### ISSUE TITLE
[REVIEW] http://portfolio-iresharma.vercel.app

### ISSUE THREAD

**Issue by iresharma** [EddieHubCommunity/support#1862]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: [Iresharma](http://portfolio-iresharma.vercel.app)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Looking good

Some suggestions:

- `class = "chakra-image css-5ask6o"` make z-index higher
- take a look at the mobile view
- also take a look at the lighthouse check
![image](https://user-images.githubusercontent.com/30869493/122364281-ea9b0900-cf59-11eb-9951-3bb134d61c69.png)

**Comment by iresharma** [comment]
@schmelto yes responsiveness is really bad, that is something I have to work on

**Comment by vinzvinci** [comment]
I like your portfolio ❤️. Some thoughts, maybe add footer? include your social media links.

**Comment by schmelto** [comment]
I think there is also an issue with the joke api

![image](https://user-images.githubusercontent.com/30869493/122408269-85a7d900-cf82-11eb-8362-75e1c6567c99.png)

if one or two liner is checked there is no data

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by tash2020** [comment]
Hi, Iresharma.
Your website looks awesome.
It's neat and clean. 
Love the animation man. 

Here's what I've seen on my screen: 

1. The dev jokes section the category and type seems a bit misplaced. Also, there is a horizontal scroll.  
![Screenshot (115)](https://user-images.githubusercontent.com/66051012/124095558-ffac8780-da83-11eb-91f9-67a08889c179.png)

2. When I try using `tab key`, somehow it shows like this. It might be confusing for some people. Please consider to solve this issue.
![Screenshot (118)](https://user-images.githubusercontent.com/66051012/124097806-1fdd4600-da86-11eb-9f04-ea52924c61a5.png)

Hope that helps.

**Comment by krishguptadev** [comment]
- Favicon
![image](https://user-images.githubusercontent.com/91655303/145830639-1645a876-eb26-4151-b881-113ac033bc99.png)

- Too many whitespace
![image](https://user-images.githubusercontent.com/91655303/145830806-b0c5e130-f5af-44b4-9e0c-7cde4eb699ea.png)

- I don't think this needs to be prioritized to the top sections
![image](https://user-images.githubusercontent.com/91655303/145830977-0061c255-ef2a-4d86-8c0c-3bb2ce44f2b9.png)

- Ending CTA will be good!

**Comment by emmalearnscode** [comment]
Nice clean design, and great that you have both light and dark mode. A few suggestions:

![F3EDBD3D-C063-43BD-8E08-8A9566F0B319](https://user-images.githubusercontent.com/57045550/146438839-afea6498-3aa2-4252-a1aa-08b67eb47fb8.jpeg)
![014F351B-EEE8-4636-AB1D-65AA3876F891](https://user-images.githubusercontent.com/57045550/146438893-8cccbe53-c49f-4d00-8c9d-93665a470fdc.jpeg)
![979F780D-BDF6-4C6B-9754-0BB4936E8B30](https://user-images.githubusercontent.com/57045550/146438927-d7082e25-b5e0-445c-829f-6d9f10420616.jpeg)

Also, it would be really great if you could include some projects you’ve made and links to their repos.

**Comment by eddiejaoude** [comment]
Reviewed on live stream! Wow looks great, the community covered everything already
