### ISSUE TITLE
Review my virtual assistant project

### ISSUE THREAD

**Issue by SaptakBhoumik** [EddieHubCommunity/support#1864]
**Project Link:**
https://github.com/SaptakBhoumik/J.A.R.V.I.S

**Comment by schmelto** [comment]
Nice project

Take a look at this:

* https://github.com/Adapt-Development/J.A.R.V.I.S/community
* Use labels at issues
* Hide packages 
![image](https://user-images.githubusercontent.com/30869493/122517427-4a53eb80-d010-11eb-8146-3627ccd0df63.png)

**Comment by SaptakBhoumik** [comment]
Thanks for your feedback

**Comment by SaptakBhoumik** [comment]
I the future we are going to publish a pakage that's why it is there

**Comment by schmelto** [comment]
> I the future we are going to publish a pakage that's why it is there

Rgab I think you can leave it as it is 👌🏼

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by starlightknown** [comment]
great points by Tom already, I think adding a gif to the readme will make it POP.

**Comment by SaptakBhoumik** [comment]
@starlightknown thank you for your feedback😊

**Comment by Panquesito7** [comment]
@SaptakBhoumik, if you close this issue, it won't be reviewed in a live stream. If you want your project to be reviewed, feel free to re-open the issue. 🙂

**Comment by SaptakBhoumik** [comment]
@Panquesito7 I am no longer maintaining it so I closed it

**Comment by Panquesito7** [comment]
Well, you could keep this issue open for the project to be reviewed even if you're not maintaining it. It could be useful for many people. 🙂

**Comment by SaptakBhoumik** [comment]
ok then

**Comment by SaptakBhoumik** [comment]
also i transferred it to my friend

**Comment by krishguptadev** [comment]
- Screenshots will be noice.

![image](https://user-images.githubusercontent.com/91655303/145831547-067a5c44-1487-4b7d-b569-9d80b124ab55.png)

- Link to license here => 
![image](https://user-images.githubusercontent.com/91655303/145831904-68710db8-aa90-43e5-8fce-d7dc722d0adf.png)

**Comment by eddiejaoude** [comment]
Please create a new issue if it is another link to be reviewed
