### ISSUE TITLE
[REVIEW] saatviknagpal

### ISSUE THREAD

**Issue by saatviknagpal** [EddieHubCommunity/support#1866]
**Github Profile Link:** [Saatvik Nagpal](https://github.com/saatviknagpal)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Sam-Varghese** [comment]
Nice profile!

**Comment by schmelto** [comment]
Yeah looking good

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- not sure I like the Spotify widget as it changes on refresh
- on the diamond graph under the tiles, you have no code reviews or issues, suggest doing some of those to have a more balanced graph
