### ISSUE TITLE
[REVIEW] Github Profile

### ISSUE THREAD

**Issue by WebShivam** [EddieHubCommunity/support#1867]
**Github Profile Link:**

 https://github.com/WebShivam

Here's my GitHub profile Would love to hear feedbacks from you all!
Thank you!

**Comment by schmelto** [comment]
Looking good nice work!

**Comment by maciev** [comment]
Great profile and layout!

Some of the sentences come across as non-native English (and that is fine, and expected!)

Here are some small changes to help the sentences flow better:
- "Curious student who is keen on learning new things and building awesome stuff"
- "I'm getting involved in open source to give back to the community"

Everything else looks good!

**Comment by WebShivam** [comment]
Thank you so much @maciev for helping me out.
I did the changes as suggested by you  :)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Looks great! My thoughts...
- The same photo is used twice, I would suggest changing the profile picture
