### ISSUE TITLE
[REVIEW] Github Profile

### ISSUE THREAD

**Issue by niteshseram** [EddieHubCommunity/support#1868]
**Github Profile Link:**
https://github.com/niteshseram

This is my Github profile. Would love to hear your feedback about it

**Comment by Sam-Varghese** [comment]
Nice profile, few suggestions from my side:

- Clicking on your name ( which is  in the heading) takes me to this page:

![image](https://user-images.githubusercontent.com/79152648/122599899-aceacd00-d08c-11eb-923e-eb415163ef57.png)

- Icons below the heading are not visible for visitors with dark GitHub background

![image](https://user-images.githubusercontent.com/79152648/122600142-fdfac100-d08c-11eb-964b-e7ac3bf55a57.png)

**Comment by niteshseram** [comment]
@Sam-Varghese thanks a lot. Actually, I removed my github pages. Will update that link now.

**Comment by schmelto** [comment]
I would change the heading sizes to h3 or the hey at the beginning to h1 aka only one #

**Comment by niteshseram** [comment]
Thank you @schmelto for yoursfeedback. Surely, will update asap

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by niteshseram** [comment]
Thanks @eddiejaoude

**Comment by Panquesito7** [comment]
Amazing profile! I really loved it ❤️ great work!

I've made a [**pull request**](https://github.com/niteshseram/niteshseram/pull/3) to center the languages and tools section.
IMO, it makes it look cooler and more attractive for all users in GitHub. 😎

Thanks for sharing your awesome with us! 😄

**Comment by niteshseram** [comment]
Thanks for the feedback @Panquesito7. Just merged your PR.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Looks great! My thoughts...
- languages/tools - can it be limited to 1 line?
- contributing graph needs more code review and issue
