### ISSUE TITLE
[REVIEW] muthuannamalai12 

### ISSUE THREAD

**Issue by muthuannamalai12** [EddieHubCommunity/support#1884]
**Github Profile Link:**

https://github.com/muthuannamalai12

 Here is my Github profile link. Would love to hear feedbacks from everyone

**Comment by kaiwalyakoparkar** [comment]
That looks awesome! two cents from my side
- Shift contact link below the typewriter text
- Add more tools and tech maybe
- java image is small than HTML, CSS, and js. Even size images may look better
- The GitHub streak section is repeated. Maybe remove one
- Font size of the welcome text, about-text, can be increased to make it easier to read
- Add some projects to pinned (take advantage of max 6 limits)
Awesome profile btw!

**Comment by muthuannamalai12** [comment]
Thank you Kaiwalya for the feedback I have not created projects so I would pin my projects once I create them. I have removed the GitHub streak part and also moved my contact section below typewriter text

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by starlightknown** [comment]
Kaiwalya listed out great points, here's one from me:
Instead of dumping the whole text in about me, you can make it into bullet points, show what's important and yes a bit bold maybe? to make easily readable.

**Comment by FayasNoushad** [comment]
Nice

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Looks great! My thoughts...
- Suggest remove `aspiring...`
- Animate text does not work well in Safari, also not good for accessibility 
- Twitter badge looks different, can the badges be on 1 line
