### ISSUE TITLE
feat: discord verification program

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1893]
**Description**

Apply to the Discord Verification Program:

Let's Verify our server and let everyone know this is the official place for our community to gather.

Benefits: advanced server insights, server discovery, invite splash art and a custom invite link

**How will it help**
- advanced server insights will allow us to know how can we improve
- server discovery will allow people to just search for our server and join it, moreover, it will allow more folks to discover eddiehub and start their open source journey
- invite splash will make our community, more personalized
- custom invite link will make a permanent, custom invite link, allowing eddie to display small popups, with the link discord.gg/eddiehub

**Screenshots**

![discord com_verification](https://user-images.githubusercontent.com/76587897/123211963-c69f7080-d4e1-11eb-8b3b-287a703c0963.png)

**Additional Context**    

Link: [discord.com/verification](https://discord.com/verification)
Requirements (Already completed, last check 12:00 Noon IST 15/06/2021): [Qualifications for Discord Verification Program](https://support.discord.com/hc/articles/360001107231)

**Comment by eddiejaoude** [comment]
Done 

<img width="1243" alt="Screenshot 2021-06-24 at 07 32 17" src="https://user-images.githubusercontent.com/624760/123213816-61865380-d4be-11eb-9243-35faa0fdd8d4.png">

**Comment by krishdevdb** [comment]
> Done
> 
> <img alt="Screenshot 2021-06-24 at 07 32 17" width="1243" src="https://user-images.githubusercontent.com/624760/123213816-61865380-d4be-11eb-9243-35faa0fdd8d4.png">

Eddie is quick 🤩

**Comment by eddiejaoude** [comment]
Not usually, but if I didn't do it, I would forget 🤦‍♂️
