### ISSUE TITLE
feat: new rule

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1894]
**Description**

Discord Community Guidelines, being the most important guidelines on Discord are not included in our rules. If we want folks to completely follow the basic rules and etiquette, this is the best and official medium. I would like to see a new rule with linking to the community guidelines and also being clear in the terms and privacy

**Additional Context**    

All of this is taken in context to Discord moderator academy articles. This is already discussed on Discord with @eddiejaoude and @Vyvy-vi

**Comment by Panquesito7** [comment]
This sounds like a great idea! @eddiejaoude, you should probably look into adding this to the rules. It's an important rule we should add.

**Comment by krishdevdb** [comment]
@eddiejaoude maybe you can look into it before stale bot closes this?

**Comment by nhcarrigan** [comment]
Hey there,

I'm going to open this issue up for contribution. A pull request that resolves this issue will:

- Add a link to the Discord community guidelines (https://discord.com/guidelines) to the `docs/discord/discord-readme.md` file. This link should include a brief sentence about "in addition to our rules, members should follow Discord's community guidelines as well". This link can come after our code of conduct.

Once that PR is merged + approved, Eddie can update the text on Discord. 🙂

**Comment by krishguptadev** [comment]
Can I work on this? 🙂

**Comment by nhcarrigan** [comment]
Sure!
