### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by NikhilSharma03** [EddieHubCommunity/support#1896]
Please invite me to the GitHub Community Organisation.

- #### Name: Nikhil Sharma

- #### Discord Username(if exists): NikhilSharma#0316

- #### Additional Context:

Youtube

I want to contribute to various projects and gain as much knowledge as possible.

:nerd_face:

**Comment by krishdevdb** [comment]
Welcome @NikhilSharma03 🤓
