### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by XShyam** [EddieHubCommunity/support#1903]
Please invite me to the GitHub Community Organisation.

- #### Name: Shyam

- #### Discord Username(if exists): Nix#8096

- #### Additional Context:
 I found out when I was looking at the guilds present in MLH.

 I wanted to contribute to the open-source community but I was stuck as I didn't know where to start and I didn't know many languages too. When I saw the official website for the community, I felt this was the best way to start!

:nerd_face:

**Comment by krishdevdb** [comment]
Welcome to EddieHub 🤓

**Comment by XShyam** [comment]
Thank You!
