### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by NoorinSakhi** [EddieHubCommunity/support#1909]
Please invite me to the GitHub Community Organisation.

- #### Name: Noorin

- #### Discord Username(if exists):

- #### Additional Context:
 One of their repos were on my suggested repo list for me to look at next, so I went to see it!

 I love how it is a big community, and how I can contribute a lot here!

:nerd_face:

**Comment by krishdevdb** [comment]
Welcome to EddieHub 🤓
