### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by HareerSakhi** [EddieHubCommunity/support#1910]
Please invite me to the GitHub Community Organisation.

- #### Name: Hareer Sakhi

- #### Additional Context:

1. #### I first met Eddie when I was contributing to the hacktoberfest repo.

2. #### I like The EddieHubCommunity because they are an open-source organization and they aim to help GitHub users to contribute.

**Comment by krishdevdb** [comment]
Welcome to EddieHub 🤓
