### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by kamleshjoshi8102** [EddieHubCommunity/support#1911]
Please invite me to the GitHub Community Organisation.

- #### Name: Kamlesh Joshi

- #### Discord Username(if exists):spyd3r#0127

- #### Additional Context:

I Heard about this community through one of my senior and he said it's a supportive and helpful community

I would like to join because I am interested in opensource and want to collaborate with new people and Eddiehub is the right place for that
:nerd_face:

**Comment by krishdevdb** [comment]
Welcome to EddieHub 🤓

**Comment by kamleshjoshi8102** [comment]
> Welcome to EddieHub 🤓
Thank You @krishdevdb 😄
