### ISSUE TITLE
[REVIEW] Github Profile

### ISSUE THREAD

**Issue by shreyshreyansh** [EddieHubCommunity/support#1913]
Github Profile Link:

[My github link](https://github.com/shreyshreyansh)

Here's my GitHub profile Would love to hear feedbacks from you all!
Thank you!

**Comment by schmelto** [comment]
Looking great!

Some suggestions:

* remove the profile view count due its inaccurate
* remove the Github badge on the connect with me section due its not necessary

**Comment by Panquesito7** [comment]
Awesome profile! I liked it a lot! 🙂👍

I have made a [**pull request**](https://github.com/shreyshreyansh/shreyshreyansh/pull/1) in your repository
for some minor improvements in the `README.md` file.

Thank you for sharing your profile with us! 😄

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Looks great! My thoughts...
- too many tags
- not part of EddieHub Org 😢 
- contributing graph needs more code reivews, issues and pull request
