### ISSUE TITLE
[REVIEW] Open Source Project 

### ISSUE THREAD

**Issue by shreyshreyansh** [EddieHubCommunity/support#1914]
**Project Link:**
[PEER CODER](https://github.com/shreyshreyansh/Peer-Coder)

**Comment by schmelto** [comment]
Great Project! Some thougts:

* https://github.com/shreyshreyansh/Peer-Coder/community take a look at this page there are some points missing
* Add a release
* Consider using conventional commit messages and automatically create releases with those
* consider hiding the packages and wiki if not needed

**Comment by shreyshreyansh** [comment]
> Great Project! Some thougts:
> 
> * https://github.com/shreyshreyansh/Peer-Coder/community take a look at this page there are some points missing
> * Add a release
> * Consider using conventional commit messages and automatically create releases with those
> * consider hiding the packages and wiki if not needed

Thanks for reviewing, I will surely look on those points

**Comment by starlightknown** [comment]
Do add these to meet standards of a good open source project

- code of conduct
- contributing.md
- pull request template
- issue template

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

- suggest using releases (would be great with a GitHub Action)
- hide packages section as not being used
- hide wiki tab as not being used (better to use `docs/` folder anyway)
- add code of conduct, contributing file, issue template, pull request tempalte
- use issues and labels to have project discoverable and user friendly
- too much is in bold in the README
-
