### ISSUE TITLE
[REVIEW]  deepansharya1111

### ISSUE THREAD

**Issue by deepansharya1111** [EddieHubCommunity/support#1923]
### Discussed in https://github.com/EddieHubCommunity/support/discussions/1922

<div type='discussions-op-text'>

<sup>Originally posted by **deepansharya1111** July  3, 2021</sup>
Hi everyone 👋 I recently made some changes to my Profile's README file, please provide your views or suggestions on it.
If you like it or if I can improve something? 
The changes I've made are somewhat different from normal profiles so I'm curious to know your views. 
Please ignore the low green squares and contribution count: 😅 I have just started.
Here's my profile link: https://github.com/deepansharya1111</div>

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by schmelto** [comment]
Nice profile. Some thoughts from my side.

- only link to your portfolio website in the heading on your name not the whole h1 heading
- remove the hit count due it's inaccurate
- im not completely sure if all the links to external websites are necessary like the link on laptop etc.

**Comment by Sam-Varghese** [comment]
Nice profile! just want to inform you that clicking on the discord icon simply opens discord on my laptop and does not takes me to your channel.

**Comment by eddiejaoude** [comment]
@deepansharya1111 did you mean to close this? we did not review it yet on a live stream, although I know you got loads of great community feedback already

**Comment by deepansharya1111** [comment]
@eddiejaoude Yes actually I closed it as I am planning to make some major changes to my profile and I am figuring it out which will take me some time.

**Comment by Panquesito7** [comment]
Woah, awesome profile! I liked it a lot! 😄👍

I have made a [**pull request**](https://github.com/deepansharya1111/deepansharya1111/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 🚀

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Looks great! My thoughts...
- animated gif is used on many profiles
- have a profile of you (if possible)
- what is the token at the top? maybe it needs a few words
- I am not keen on the `hits` (profile views)
