### ISSUE TITLE
[REVIEW] GitHub Profile

### ISSUE THREAD

**Issue by suvrashaw** [EddieHubCommunity/support#1925]
**Github Profile Link: https://github.com/suvrashaw**

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing, I will review on a live stream soon 👍

**Comment by schmelto** [comment]
Nice one maybe reduce using bold a little bit but otherwise I really like that you also add your work experience on your profile.

**Comment by suvrashaw** [comment]
Thank you @schmelto

**Comment by schmelto** [comment]
When you close this issue it will not be covered in the livestream review. If you want to get a Livestream review feel free to reopen the issue

**Comment by Panquesito7** [comment]
Amazing! I liked your profile a lot! I do agree with @schmelto that you should reduce the bold a little. Overall, everything else looks perfect! 😄

> When you close this issue, it will not be covered in the live stream review. If you want to get a Livestream review, feel free to re-open the issue.

I agree with @schmelto here, too. You should re-open this issue if you want your profile to be reviewed in a live stream.
