### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Yayady1999** [EddieHubCommunity/support#1927]
Please invite me to the GitHub Community Organisation.

- #### Name:  Yayady S

- #### Discord Username(if exists):   Yayady1999
####email:    yayady1999@gmail.com

- #### Additional Context:
 Where did you meet Eddie?   I heard about Eddie community from a random search on Github. It sounded like a great community so I thought I could contribute my part to make Eddie great

What do you like about this community/ why do you want to join.
The part that everything is well maintained and guided, makes it a great community for anyone new.
:nerd_face:

**Comment by krishdevdb** [comment]
Welcome @Yayady1999 🤓
