### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by salitha10** [EddieHubCommunity/support#1934]
### Name

Salitha Tennakoon

### Discord Username(if exists)

saniro

### Additional Context

My friend told me about this.  I want to be a part of this awesome community and contribute to open source projects.

**Comment by schmelto** [comment]
Hey @salitha10 welcome to the community.

You are the first joining with the new issue form. Could you tell us a little bit how this process felt :)

**Comment by salitha10** [comment]
It was easy and straight forward. Happy to be a part of the community.

**Comment by krishdevdb** [comment]
Welcome @salitha10 🤓
