### ISSUE TITLE
[REVIEW] Github Profile

### ISSUE THREAD

**Issue by salitha10** [EddieHubCommunity/support#1935]
What you guys think about my GitHub profile?

**Github Profile Link:**
https://github.com/salitha10

**Comment by Sam-Varghese** [comment]
Nice profile! few suggestions from my side:

- PHP icon is not visible to visitors with dark GitHub background

![image](https://user-images.githubusercontent.com/79152648/124967323-eab29400-e041-11eb-9680-690366c4b26b.png)

- If you wish, then you may remove the profile view counter as it works incorrectly. It does not count the number of UNIQUE visitors to your page.
- You may also remove the GitHub followers counter as Github already shows this information on the same page.

**Comment by salitha10** [comment]
Thank you very much @Sam-Varghese

**Comment by schmelto** [comment]
Nice profile.

Consider making the top image a little bit smaller

**Comment by salitha10** [comment]
Thank you very much @schmelto

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

- add a profile picture
- wasted empty space near the widgets, try to do 2 columns
- contribute more to open source 🤓
