### ISSUE TITLE
[REVIEW] manusquall

### ISSUE THREAD

**Issue by ManuSquall** [EddieHubCommunity/support#1937]
**Github Profile Link:**
https://github.com/ManuSquall

Hello world, would you please make a review of my github profil.

**Comment by schmelto** [comment]
Like it!

**Comment by Sam-Varghese** [comment]
Nice profile! , few suggestions from my side:

- Clicking on the Linkedin icon takes me to the following web page:

![image](https://user-images.githubusercontent.com/79152648/124966648-2d27a100-e041-11eb-93b2-c181ef93ba90.png)

- Clicking on the discord icon takes me to the following web page:

![image](https://user-images.githubusercontent.com/79152648/124966778-4fb9ba00-e041-11eb-85e1-457d0e2127be.png)

**Comment by ManuSquall** [comment]
thanks @Sam-Varghese ! Accurate review :-) i fix the error, thanks again

**Comment by Sam-Varghese** [comment]
> thanks @Sam-Varghese ! Accurate review :-) i fix the error, thanks again

You're welcome

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

Looks good, some thoughts...
- widgets having wasted empty space, suggest 2 columns
- contributors graph has no code reviews, suggest reviewing PRs (can be on projects you don't maintain)

**Comment by ManuSquall** [comment]
> Reviewed on live stream https://youtu.be/i2t50B5lmIU
> 
> Looks good, some thoughts...
> 
> * widgets having wasted empty space, suggest 2 columns
> * contributors graph has no code reviews, suggest reviewing PRs (can be on projects you don't maintain)

Thanks you :-)
