### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ManuSquall** [EddieHubCommunity/support#1938]
### Name

ManuSquall

### Discord Username(if exists)

ManuSquall

### Additional Context

i discovered EddieHub throught chryz-hub, really excited to join this community!

**Comment by krishdevdb** [comment]
Welcome @ManuSquall 🤓

**Comment by ManuSquall** [comment]
thank you @krishdevdb ! :-) 💯
