### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rynrsts** [EddieHubCommunity/support#1940]
### Name

Ryan Aristosa

### Discord Username(if exists)

rynrsts#0442

### Additional Context

I met Eddie through the SurPath Hub, because this community is inspired by the EddieHub. I wanted to join because I want to explore, learn, and eventually, contribute to the open source community.

**Comment by krishdevdb** [comment]
Welcome @rynrsts 🤓
