### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hanshulll** [EddieHubCommunity/support#1948]
Please invite me to the GitHub Community Organisation.
        **•	Name:** Hanshul Chandel
        **•	Discord:** 
	**•	Additional Context:**

I got to know about Eddie through the MLH Local Hack Day build and saw the contributions Eddie is doing to advance open source and the community and also being at number 1.
I am so much influenced by Eddie's work and want to contribute to open source and want to learn more.
 🤓

**Comment by krishdevdb** [comment]
Welcome @hanshulll 🤓

**Comment by hanshulll** [comment]
Thank you so much @krishdevdb 🤓
