### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by skacem** [EddieHubCommunity/support#1950]
### Name

Skander Kacem

### Discord Username(if exists)

skander#5628

### Additional Context

Hi Everyone,

I came across your Github page by looking for a "good first issue" to start contributing to an open source project. That I stumbled upon you was a pleasant surprise. As I totally agree with the motto "collaboration first code second". 
Looking forward to a fruitful collaboration!

Greetings,
Skander

**Comment by krishdevdb** [comment]
Welcome @skacem 🤓

**Comment by skacem** [comment]
thanks @krishdevdb
