### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Ashmn07** [EddieHubCommunity/support#1957]
### Name

Ashwin Menon

### Discord Username(if exists)

Ashwin#9399

### Additional Context

I came to know about this community while I was scrolling through youtube. I am interested in web development and more specifically React, NextJs and also React Native. I would really like the opportunity to collaborate with similar minded people and build exciting stuff.

**Comment by krishdevdb** [comment]
Welcome @Ashmn07 🤓
