### ISSUE TITLE
[REVIEW] Portfolio

### ISSUE THREAD

**Issue by jigar-sable** [EddieHubCommunity/support#1958]
**Please ensure that you don't have any personal details in your Portfolio that you don't want to share publicly.**

Portfolio link: [Visit Here](https://lifecodess.cf)

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Take a look at your performace
![image](https://user-images.githubusercontent.com/30869493/125256665-f2519180-e2fc-11eb-8833-aaee55e14563.png)

Otherwise for me its a little bit to much "showing up" content ->condiser makeing them visible all the time once showed up

**Comment by jigar-sable** [comment]
@schmelto thanks for feedback I'll lookout at those.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by emmalearnscode** [comment]
Hi Jigar! Love your avatar on your site. However, I think there are too many moving things as soon as I open it up. With the background, the changing text and then the chat pop up bubbles appearing it’s very hard to focus and know where to look.
 - The chat pop up is also in the way of your content and also take two clicks to close which is annoying. 
- don’t capitalise every word in your about me section
- percentage bars don’t really mean anything, suggest removing and just listing your skills
- Great colour palette 
- Less animation on scroll
- Love the work experience timeline. Maybe add a line or two about what you did to each one.
- Great selection of projects
- resume button doesn’t work in safari
- Nicely responsive on mobile 👍 
- code button icon is slightly misaligned 
![E88E8A15-6C63-457D-8514-E04623675143](https://user-images.githubusercontent.com/57045550/146441318-4363aed5-4dca-482b-ae79-5c3fc0636ba7.jpeg)

**Comment by jigar-sable** [comment]
Thank you so much @emmalearnscode. Thanks for feedback. I'll surely look into it for the updates.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

Looks good, some thoughts...
- I really like the chat
- timeline for experience is really nice
- I think too much animations
- avatar badge has cursor showing i can click but nothing happens
- % on skills I think is confusing
- Project work could higher up the page
- Animations on projects does not work on safari

<img width="1680" alt="Screenshot 2022-01-07 at 22 45 33" src="https://user-images.githubusercontent.com/624760/148560488-153c32cd-c662-4c01-b86e-061d84160167.png">

**Comment by jigar-sable** [comment]
Thank you so much for your feedbacks. I'll look forward for the changes.
