### ISSUE TITLE
[REVIEW] GitHub Profile @snitin315

### ISSUE THREAD

**Issue by snitin315** [EddieHubCommunity/support#1959]
**GitHub Profile Link:**

https://github.com/snitin315

**Comment by Sam-Varghese** [comment]
Liked your profile!

**Comment by snitin315** [comment]
> Liked your profile!

Thanks!

**Comment by Panquesito7** [comment]
Great profile! I loved it. 😄

**Comment by snitin315** [comment]
> Great profile! I loved it. 😄
> 

Thank you.

**Comment by schmelto** [comment]
suggest aligning and writing the about me section in text not as image.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

Looks good, some thoughts...
- love the shoutout to past sponsors
- try to have the contribution graph a bit more balanced towards issues and PRs (partly due to new year of stats)
