### ISSUE TITLE
[REVIEW] My Resume

### ISSUE THREAD

**Issue by snitin315** [EddieHubCommunity/support#1960]
Resume link: https://drive.google.com/file/d/1L6yOzimU0dV9qLqKAh-2doFw1KQt-mq-/view?usp=sharing

**Comment by schmelto** [comment]
Contributor at Jest is not aligned correctly

![image](https://user-images.githubusercontent.com/30869493/125263673-8292d500-e303-11eb-83a4-277039151149.png)


otherwise I like the style of your portfolio!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed on video, coming out in the next few weeks

Looks great 👍 some feedback
- links to be full url, if someone prints it they won't be able to see the clickable link
- I like the 2 columns but this might be an issue for some resume platforms

**Comment by snitin315** [comment]
Thank you for the feedback @eddiejaoude
