### ISSUE TITLE
[REVIEW] GitHub Profile

### ISSUE THREAD

**Issue by verma-kunal** [EddieHubCommunity/support#1962]
**GitHub Profile Link:**
https://github.com/verma-kunal

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Sam-Varghese** [comment]
Nice profile, liked it!

**Comment by verma-kunal** [comment]
Thank you @Sam-Varghese !!

**Comment by Panquesito7** [comment]
Amazing profile! I only suggest centering those badges using HTML. IMO, it would look cooler. If you want, I can make a PR regarding my suggestion. 🙂

![image](https://user-images.githubusercontent.com/51391473/125145112-ca3c1580-e0e5-11eb-81a2-5caae6c6ab1a.png)

**Comment by verma-kunal** [comment]
Yeah! sure @Panquesito7 !! Go ahead with that 🙂

**Comment by verma-kunal** [comment]
I would be closing this issue as it was reviewed in the previous live-stream by @eddiejaoude !! Jotted down all the points and would improve my profile further !!

**Comment by Panquesito7** [comment]
> Yeah! sure @Panquesito7 !! Go ahead with that 🙂

Working on it, thanks. 🙂

**Comment by verma-kunal** [comment]
Hey @Panquesito7 , actually i did that today !! You can always raise issues on the repo if you have any more ideas & get a 🟩  square !! 🙂

**Comment by Panquesito7** [comment]
> Hey @Panquesito7, actually, I did that today! You can always raise issues on the repo if you have any more ideas & get a 🟩 square !! 🙂

Sure, thank you! I actually made a PR because it seemed it wasn't working well? Please check it out. Thanks! 😄
