### ISSUE TITLE
[REVIEW] suvrashaws resume

### ISSUE THREAD

**Issue by suvrashaw** [EddieHubCommunity/support#1964]
**Remove all personal data, otherwise, the resume will be deleted.**

Resume link: https://drive.google.com/file/d/1bkcbzMd91-p-5hwHVD8tmW6VIIC5SGWM/view?usp=sharing

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) These are my suggestions
- Really like the resume template
- Maybe left center it as it is difficult to read 
- Add more context to the projects

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍
