### ISSUE TITLE
[REVIEW] new-tailwind-app

### ISSUE THREAD

**Issue by msaaddev** [EddieHubCommunity/support#1965]
**Project Link:**

https://github.com/msaaddev/new-tailwind-app

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :)
- Maybe reduce the size of the image in the readme

**Comment by Cahllagerfeld** [comment]
Let me share my thoughts on this: 

- Its more a personal prefernce, but I'm not a fan of emojis in release-, and commit-messages
- I like the animated GIFs
- youre yousing tags quite good
- you removed packages when not using

all in all I like that project !!

**Comment by schmelto** [comment]
Nice you're using project board!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by msaaddev** [comment]
There is also a [profile review](https://github.com/EddieHubCommunity/support/issues/2104).

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks good, some suggestions...
- suggest removing `RELEASE` from the release name
- add issue templates
- suggestion to use animated gif instead of multiple images
-
