### ISSUE TITLE
[REVIEW] naveen8801s resume

### ISSUE THREAD

**Issue by naveen8801** [EddieHubCommunity/support#1966]
**Remove all personal data, otherwise, the resume will be deleted.**

PLease review 😄 
Resume link: https://drive.google.com/file/d/1vGpQhB7GoClum8SjmfN5bSm_ntMnLMIR/view?usp=sharing

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by naveen8801** [comment]
thanks ❤️  @kaiwalyakoparkar for suggestions :)

**Comment by schmelto** [comment]
take a look here personally I would suggest using less whitespace here
![image](https://user-images.githubusercontent.com/30869493/125264804-7b1ffb80-e304-11eb-8414-634d68770257.png)


there aremissing full stops
![image](https://user-images.githubusercontent.com/30869493/125264696-5f1c5a00-e304-11eb-83ab-9876f42a6618.png)

![image](https://user-images.githubusercontent.com/30869493/125264621-4ca22080-e304-11eb-852a-30982b0c1c23.png)

**Comment by naveen8801** [comment]
> take a look here personally I would suggest using less whitespace here
> ![image](https://user-images.githubusercontent.com/30869493/125264804-7b1ffb80-e304-11eb-8414-634d68770257.png)
> 
> there aremissing full stops
> ![image](https://user-images.githubusercontent.com/30869493/125264696-5f1c5a00-e304-11eb-83ab-9876f42a6618.png)
> 
> ![image](https://user-images.githubusercontent.com/30869493/125264621-4ca22080-e304-11eb-852a-30982b0c1c23.png)

Thanks, @schmelto ❤️, I really liked your suggestions.

**Comment by Panquesito7** [comment]
I would recommend changing the text to `For more personal projects, please check my GitHub profile`, obviously, with a link to your profile. Or maybe `For more projects, please check my GitHub profile`, with a link to your profile.

![image](https://user-images.githubusercontent.com/51391473/125842012-464a9ff2-1e86-49c7-92b3-774647f02634.png)

I also suggest changing the following text to `Consider checking my GitHub's PRs page for more information`.

![image](https://user-images.githubusercontent.com/51391473/125842774-d43a8810-f5be-4a05-9917-48799c405943.png)

Overall, everything else looks good; great work! 😄

**Comment by naveen8801** [comment]
> I would recommend changing the text to `For more personal projects, please check my GitHub profile`, obviously, with a link to your profile. Or maybe `For more projects, please check my GitHub profile`, with a link to your profile.
> 
> ![image](https://user-images.githubusercontent.com/51391473/125842012-464a9ff2-1e86-49c7-92b3-774647f02634.png)
> 
> I also suggest changing the following text to `Consider checking my GitHub's PRs page for more information`.
> 
> ![image](https://user-images.githubusercontent.com/51391473/125842774-d43a8810-f5be-4a05-9917-48799c405943.png)
> 
> Overall, everything else looks good; great work! 😄

Thanks @schmelto ❤️

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
I was going to review for my YouTube video, but I get the error, `file not available`, please create a new issue with the file for review
