### ISSUE TITLE
[REVIEW] nimit2801

### ISSUE THREAD

**Issue by nimit2801** [EddieHubCommunity/support#1967]
**GitHub Profile Link:**

https://github.com/nimit2801

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing @nimit2801 :) These are my suggestions
- You can add more context in your profile readme
- You are not a part of EddieHub. Maybe join us today :wink: 
- Increase the font of the text in your profile to make it more ligible

**Comment by Sam-Varghese** [comment]
Nice profile! I just observed that you mistakenly misspelled `little` on the second line.

**Comment by Cahllagerfeld** [comment]
Let me share my thoughts in addtion to the ones mentioned as well: 
- You should definitely join the Community!!
- I feel like theres too much blankspace at the right, maybe rearanging the content works

**Comment by Panquesito7** [comment]
I liked the profile! Looks cool. I suggest pinning non-forked repositories (especially if made for pull requests) unless they are a continuation of the forked project. That's my opinion, but if you want to keep it as-is, that's fine. 🙂

**Comment by schmelto** [comment]
Agree with all comments above. Maybe also add some more color to your profile.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Looks great! 

- photo was great!
- clean profile
- maybe make more use of the white space on right to reduce the page length 
- join EddieHub org github.eddiehub.org (create issue to join)
- recommend pinning only 2-4 repos
- 93% on commits, recommending trying issues, code reviews etc
