### ISSUE TITLE
[REVIEW] mayurchakalasiya1990

### ISSUE THREAD

**Issue by mayurchakalasiya1990** [EddieHubCommunity/support#1968]
**GitHub Profile Link:**
https://github.com/mayurchakalasiya1990/

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) These are my few suggestions
- Add a custom readme profile
- Join eddiehub maybe :wink: 
- More context to pinned Repos may help

**Comment by Panquesito7** [comment]
You could add some emojis to your bio. That will attract more users. 😉

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by mayurchakalasiya1990** [comment]
thanks
[image: photo]
*Regards,*
*Mayur Chakalasiya*
Software Developer
+91-7276200096 | Pune, Maharashtra.
<http://www.facebook.com/chakalasiya>
<http://in.linkedin.com/in/mayur-chakalasiya-777a7a30>

**Comment by schmelto** [comment]
Just a quick reminder. To get a profile review you need a custome github profile by adding a profile readme.

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/customizing-your-profile/about-your-profile

**Comment by eddiejaoude** [comment]
Looks good, some feedback...

- great profile picture
- profile is not customised
- no social links in profile
- popular repos to have descriptions
