### ISSUE TITLE
[REVIEW] Portfolio and project

### ISSUE THREAD

**Issue by rathod-sahaab** [EddieHubCommunity/support#1969]
Portfolio link: 
[https://rathod-sahaab.github.io](https://rathod-sahaab.github.io)

Project:

repo:
[https://github.com/elide-app](https://github.com/elide-app)
deploy
[https://console.elide.me](https://console.elide.me)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) I liked your profile personally maybe improve the contrast a bit and the language filter function is not working in the project section. Good job btw

**Comment by rathod-sahaab** [comment]
> Thanks for sharing :) I liked your profile personally maybe improve the contrast a bit and the language filter function is not working in the project section. Good job btw

Thanks for the feedback I made filtering functional ❤️

**Comment by schmelto** [comment]
Maybe consider using a rss feed or something like this to implement blog posts directly into your website
maybe add some padding at the bottom of the page in the skills and projects section

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by emmalearnscode** [comment]
Really nice design, just a few small things I noticed:

- under skills don’t be negative about JavaScript,
- Under skills there is are small typos in asynchronous, written, structure, separation 
- On the contact page the Twitter logo is blue but all others match your colour scheme

**Comment by eddiejaoude** [comment]
Link no longer works

**Comment by rathod-sahaab** [comment]
> Link no longer works
@eddiejaoude 
[https://abhay.rs](https://abhay.rs)
