### ISSUE TITLE
[REVIEW] Project Makes Math Easy

### ISSUE THREAD

**Issue by sairish2001** [EddieHubCommunity/support#1970]
**Project Link:**
https://github.com/makesmatheasy/makesmatheasy

Hosted Link:
https://makesmatheasy.github.io/makesmatheasy

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) The project is really cool few suggestions from my side
- You can remove release and packages if not used
- You can create a separate file for the feature list maybe coz the readme became a bit long
- Maybe nest files under single project to make 
- You can remove project board tab and wiki tab if not using

**Comment by sairish2001** [comment]
@kaiwalyakoparkar 
Thanks for suggestions, will surely look into it

**Comment by schmelto** [comment]
Take a look at the lighthouse scores of the deployed website
![image](https://user-images.githubusercontent.com/30869493/125405320-e545a880-e3b7-11eb-891f-8036a3e0608c.png)
think particlejs is draining a lot of performance

Nice use of labels in the project!
I suggest using conventional commit messages.

Otherwise I agree with @kaiwalyakoparkar s points.

**Comment by sairish2001** [comment]
> Take a look at the lighthouse scores of the deployed website
> ![image](https://user-images.githubusercontent.com/30869493/125405320-e545a880-e3b7-11eb-891f-8036a3e0608c.png)
> think particlejs is draining a lot of performance
> 
> Nice use of labels in the project!
> I suggest using conventional commit messages.
> 
> Otherwise I agree with @kaiwalyakoparkar s points.
> 
> 

Thanks for giving your valuable time to review this Project, Will surely look into it.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Looks good

- README is very long, maybe make some of them collapsable 
- Repo description to have 1 more sentence
- create releases
- hide wiki if not used
- hide packages if not used
