### ISSUE TITLE
[REVIEW] First Group project

### ISSUE THREAD

**Issue by ShivamTyagi12345** [EddieHubCommunity/support#1971]
**Project Link:**

I introduced my juniors to Github for the first time ,and together , we made 4 calculators using HTML CSS JS. I would be lovely if you give us a shout out and review this repo.

https://github.com/ShivamTyagi12345/first-project-of-WEB-team-Robotics-24
You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) These are my suggestion
- Add about for your project
- Remove packages and releases section if not using
- Add the following
-  Description
- Code of conduct
- Contributing
- License
- Choosing a license
- Issue templates
- Pull request template 
- Remove projects and wiki section if not using
- Add some context explaining your project in readme

**Comment by schmelto** [comment]
agree with all of @kaiwalyakoparkar s points

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, here are some thoughts...

- Hide releases, packages and wiki if not used
- Suggest having a project description in the repo and also the README
- Use issues for tasks even for the maintainers
- Each project to have a README with instructions on getting started
