### ISSUE TITLE
[REVIEW] GitHub profile

### ISSUE THREAD

**Issue by rofazayn** [EddieHubCommunity/support#1972]
**GitHub Profile Link:**
https://github.com/rofazayn

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Thanks for sharing :) These are suggestions from my side
- You can add more context to your custom profile maybe
- Add a description to the pinned projects might help

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

looks good 👍 
- maybe add a bit more to your GitHub bio on the left
- could you add the technologies you use to your customised profile

I hope that helps, it will grow with time also 🤓
