### ISSUE TITLE
REVIEW corona virus vaccine tracker

### ISSUE THREAD

**Issue by Anaslbkh** [EddieHubCommunity/support#1979]
**Project Link:**
https://github.com/Anaslbkh/vaccination-tracker

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
some thoughts from my side:

* add a release
* add a description
* add some tags
* remove the packages
* remove the wiki
* take a look here https://github.com/Anaslbkh/vaccination-tracker/community
* add the deployed link to the description
* use issues and prs

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
> add a release

If you still don't plan on adding a release, remove the release section from showing up in the repo.

**Comment by Akshu-on-github** [comment]
Hey, just a few thoughts:
![image](https://user-images.githubusercontent.com/61582763/157049935-07bcabe7-4d09-4c89-bd2d-66ba805f4aa8.png)
- Add labels/tags for the tech stack rather than just words
- Add a description before the setup
- Add the deployed version to the website/remove it from the readme if depreciated

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, here are some thoughts...

- Add project description to repo and README
- Hide packages and releases if not used
- GitHub Action to run linter and build commands from `package.json`
- Screenshot in the README would be great
- Use issues even if only 1 maintainer/contributor
