### ISSUE TITLE
[REVIEW] Anass Lebkhaiti  

### ISSUE THREAD

**Issue by Anaslbkh** [EddieHubCommunity/support#1980]
**GitHub Profile Link:**
https://github.com/Anaslbkh/

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Panquesito7** [comment]
Great profile! I just made a PR in your repository to add Twitter and website badges. Thank you for sharing your profile with us! :wink: Anaslbkh/Anaslbkh#1

**Comment by schmelto** [comment]
Cool profile. I agree with the badges for the connect section

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
@Anaslbkh The profile looks good, possibly add a banner/stats to your page.  Also maybe remove the / from the link in the connect with me section, I think it will look better this way.

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...

- Maybe get more active in open source
- Add more information about yourself in the customised profile
- Join EddieHub GitHub Org 😜
