### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by paramsiddharth** [EddieHubCommunity/support#1982]
### Name

Param Siddharth

### Discord Username(if exists)

ParamSiddharth#9722

### Additional Context

I found out about EddieHub a month ago, but I didn't pay much attention until now, when I came to know that the Awesome GitHub Profiles project belongs to EddieHub itself. That sparked my interest in being a part of the community.

**Comment by Sam-Varghese** [comment]
Welcome @paramsiddharth, happy to have you in the EddieHub community 🙂. Nice profile by the way!

**Comment by paramsiddharth** [comment]
> Welcome @paramsiddharth, happy to have you in the EddieHub community 🙂. Nice profile by the way!

Thank you very much, @Sam-Varghese ! 😊 I'd love to contribute my best.
