### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/support#1983]
### Name

David Leal

### Discord Username(if exists)

Panquesito7#3723

### Additional Context

I met Eddie thanks to EddieHub (he seems like a very nice guy!). I first contributed to EddieHub due to the `awesome-github-profiles` repository. I wasn't really interested in EddieHub until some days ago, but I'd like to join the GitHub organization to keep contributing. And most importantly, to help other people with their problems, pull request reviewing, and more.

**Comment by Sam-Varghese** [comment]
Welcome, @Panquesito7 to the EddieHub community🙂🥳 . We are happy to have you as our new community member, and, we really appreciate your willingness to contribute to open source, and help beginners in their journey.
