### ISSUE TITLE
[REVIEW] mrkc2303

### ISSUE THREAD

**Issue by mrkc2303** [EddieHubCommunity/support#1987]
**GitHub Profile Link:**

https://github.com/mrkc2303

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Github on the connect with me section seems a little bit of due we are already on your github profile. Also Co sonder removing gmthe view found due it's inaccurate.
Otherwise I really like the profile!

**Comment by mrkc2303** [comment]
Hi,
Thank You for your suggestions, I have removed the "connect me on Github". Unfortunately, I cannot understand what you are trying to say at last line in which you mentioned removing something which you found inaccurate.
Thank You!

**Comment by Sam-Varghese** [comment]
Profile view counter works incorrectly as it does not count the number of UNIQUE visitors to your profile. He is just suggesting you to remove that counter. I also agree with the points mentioned above by him.  Nice profile overall!

**Comment by mrkc2303** [comment]
I have made the changes suggested by both of you!
Thank you for reviewing my profile and your valuable suggestions!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by schmelto** [comment]
> Profile view counter works incorrectly as it does not count the number of UNIQUE visitors to your profile. He is just suggesting you to remove that counter. I also agree with the points mentioned above by him. Nice profile overall!

Thanks for clarification :D

**Comment by KendallDoesCoding** [comment]
> Show some ❤️ by looking at my some repositories

@mrkc2303 On the last line of the profile, the word "repositories" maybe hyperlink the repo page for that word?

Repo page: https://github.com/mrkc2303?tab=repositories

**Comment by mrkc2303** [comment]
Hey @KendallDoesCoding, 
Thanks for your valuable suggestions. I have done the required changes,
Thanks for taking out our time to review my profile :)

**Comment by KendallDoesCoding** [comment]
Thanks. Will re-review in a bit.

**Comment by KendallDoesCoding** [comment]
@mrkc2303 Thanks a lot for doing the requested changes. Other than that, your profile looks great to me :)

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...

- Typo `exites`
- The main titles have `<br>` might be better to use separate tags
- possibly reduce the pinned repos to 4
