### ISSUE TITLE
[REVIEW] jayesh-srivastava

### ISSUE THREAD

**Issue by jayesh-srivastava** [EddieHubCommunity/support#1988]
**GitHub Profile Link:**
https://github.com/jayesh-srivastava

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Sam-Varghese** [comment]
Nice profile! just one suggestion, that you may remove the visitor's count as it works incorrectly (it does not count the number of UNIQUE visitors to your page.).

**Comment by schmelto** [comment]
> Nice profile! just one suggestion, that you may remove the visitor's count as it works incorrectly (it does not count the number of UNIQUE visitors to your page.).

Agree with that

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by FayasNoushad** [comment]
Nice :heart:

**Comment by Panquesito7** [comment]
Woah, awesome profile! I loved it! Great work, @jayesh-srivastava! 🚀

I have made a [**pull request**](https://github.com/jayesh-srivastava/jayesh-srivastava/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your amazing profile with us! 😄

**Comment by jayesh-srivastava** [comment]
@Panquesito7 Thank you! Will review the changes!

**Comment by KendallDoesCoding** [comment]
Looks good @jayesh-srivastava . Really like the profile!

**Comment by eddiejaoude** [comment]
Looks great! Just 1 thought...

- Maybe reduce from 6 pinned to 4 pinned repos
