### ISSUE TITLE
[REVIEW] MuhammadUmairghufran

### ISSUE THREAD

**Issue by MuhammadUmairghufran** [EddieHubCommunity/support#1990]
**GitHub Profile Link:**
https://github.com/MuhammadUmairghufran

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
looking good

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Looks good! Really like the profile.

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...

- More open source activity would be great!
- Pinned repos are forked, might look better if you pin your repos (I suggest max of 4 pinnned repos)
