### ISSUE TITLE
[REVIEW] qwe123coder

### ISSUE THREAD

**Issue by qwel-exe** [EddieHubCommunity/support#1993]
**GitHub Profile Link:**

https://github.com/qwel-exe

**Comment by schmelto** [comment]
* remove the profile view count due its inaccurate
* maybe add a direct link to your discord

**Comment by Sam-Varghese** [comment]
Nice profile! I would suggest you to remove the profile view counter as it works incorrectly, as mentioned above. Great you mentioned Eddie on our profile page!👍

**Comment by qwe123coder** [comment]
thanks and how do you join the  EddieHub Organizations ?

**Comment by Sam-Varghese** [comment]
@qwe123coder You would need to create an issue over here: https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization and you would automatically get added into this organization.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by qwe123coder** [comment]
i made new updates in my readme.md

**Comment by KendallDoesCoding** [comment]
@qwel-exe I believe you changed your GitHub name... Please update the url in the description to https://github.com/qwel-exe

**Comment by KendallDoesCoding** [comment]
> @qwel-exe I believe you changed your GitHub name... Please update the url in the description to https://github.com/qwel-exe

Other then that, really like the README.md... Like the banner, everything looks good!

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...

- Very creative
- GitHub profile is very long (about 5 pages), suggest removing some widgets
- On the contributing graph, try to do commits, issues and pull requests
