### ISSUE TITLE
[REVIEW] bineetnaidu.github.io

### ISSUE THREAD

**Issue by bineetNaidu** [EddieHubCommunity/support#1994]
**Please ensure that you don't have any personal details in your Portfolio that you don't want to share publicly.**

Portfolio link: https://bineetnaidu.github.io

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Nice website. Definitely take a look on the mobile layout of your website.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by emmalearnscode** [comment]
Love the colour scheme you’ve chosen. It looks really nice, here’s just a few small things to consider:

![9B85B6AB-93BC-432F-B99E-21386D179A6C](https://user-images.githubusercontent.com/57045550/147369374-85eb03d2-2c28-4063-a94e-1745070f6c2c.jpeg)
Can there be a larger gap between the two columns?

![E2332FA4-4CF8-40E4-8B54-3053BB4EB818](https://user-images.githubusercontent.com/57045550/147369386-f06e2215-693b-409d-a2cb-b50d5f851f00.jpeg)
Some strange overlapping of projects is happening on iPad

**Comment by bineetNaidu** [comment]
> Love the colour scheme you’ve chosen. It looks really nice, here’s just a few small things to consider:
> 
> ![9B85B6AB-93BC-432F-B99E-21386D179A6C](https://user-images.githubusercontent.com/57045550/147369374-85eb03d2-2c28-4063-a94e-1745070f6c2c.jpeg) Can there be a larger gap between the two columns?
> 
> ![E2332FA4-4CF8-40E4-8B54-3053BB4EB818](https://user-images.githubusercontent.com/57045550/147369386-f06e2215-693b-409d-a2cb-b50d5f851f00.jpeg) Some strange overlapping of projects is happening on iPad

thanks for your feedback :v:

**Comment by KendallDoesCoding** [comment]
Right now, the experience tab and the contact go to the top of the page. 

I think that if the user clicks "Contact" it should be a mailto href tag, to automatically start a email to bineetnaiduapps@gmail.com. like the "Get in touch button" on the top does.

**Comment by eddiejaoude** [comment]
Looks great! Some thoughts

- Can't copy and paste text to search for your name on Twitter/LinkedIn
- Possible add a photo on the home or svg
- About section not to be in italic
- Tech stack to be made larger
- All sections are `01`
- Project section add description and links to the projects
- `Experience` nav link does not work
- `Contact` nav link does not work
