### ISSUE TITLE
[REVIEW] UtkarshMishra12

### ISSUE THREAD

**Issue by UtkarshMishra12** [EddieHubCommunity/support#2003]
**GitHub Profile Link:**
 @UtkarshMishra12

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Only one thing from my side consider removing the view count due it's inaccurate

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Maybe center align the logs in the Tech Stack section and add all of them in one line if possible, instead of 3?

**Comment by KendallDoesCoding** [comment]
> Maybe center align the logs in the Tech Stack section and add all of them in one line if possible, instead of 3?

Actually, it's fine if it's 3 lines, as the first line is coding languages, second is game engines, and third if IDE's. But, I think it will look better with a center align :)

**Comment by eddiejaoude** [comment]
Looks great! Some thoughts

- Make use of the GitHub profile description (left)
- I think visitor badge is not needed
- Keep badges the same size and style
- Maybe change the repository list link to your favourite / current repo
