### ISSUE TITLE
[REVIEW] Dmitry Burov

### ISSUE THREAD

**Issue by dmitryburov** [EddieHubCommunity/support#2007]
**GitHub Profile Link:**
https://github.com/dmitryburov

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Sam-Varghese** [comment]
Nice profile! liked it. Just want to share that the link for telegram is broken, as clicking on it takes me to the following page:

![image](https://user-images.githubusercontent.com/79152648/125451696-6f2597a4-0bdb-406a-b559-b0348c6b386f.png)

**Comment by dmitryburov** [comment]
Thanks, Sam!

We are you? Telegram don't blocked on your Country?
That is default telegram link :man_shrugging:

![image](https://user-images.githubusercontent.com/11191484/125452380-60c9c1a5-888f-423b-affa-92bcfe208265.png)

**Comment by dmitryburov** [comment]
> Nice profile! liked it. Just want to share that the link for telegram is broken, as clicking on it takes me to the following page:
> 
> ![image](https://user-images.githubusercontent.com/79152648/125451696-6f2597a4-0bdb-406a-b559-b0348c6b386f.png)

Thanks, Sam!

Where are you? Telegram don't blocked on your country?
That is default telegram link :man_shrugging:

![image](https://user-images.githubusercontent.com/11191484/125452380-60c9c1a5-888f-423b-affa-92bcfe208265.png)

**Comment by schmelto** [comment]
> Nice profile! liked it. Just want to share that the link for telegram is broken, as clicking on it takes me to the following page:
> 
> ![image](https://user-images.githubusercontent.com/79152648/125451696-6f2597a4-0bdb-406a-b559-b0348c6b386f.png)
> 

Working for me

**Comment by Sam-Varghese** [comment]
I am from India, and I found this on the internet

![image](https://user-images.githubusercontent.com/79152648/125454602-c397694c-f8cb-474b-af0a-c6df69a67efb.png)

I wasn't even aware of this, cause I still have the telegram app on my mobile, and people in India also use it.

**Comment by dmitryburov** [comment]
> I am from India, and I found this on the internet
> I wasn't even aware of this, cause I still have the telegram app on my mobile, and people in India also use it.

We went through that... in Russia) 
[https://en.wikipedia.org/wiki/Blocking_Telegram_in_Russia](https://en.wikipedia.org/wiki/Blocking_Telegram_in_Russia)

I was used proxy (MTProto) then

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Profile looks great!

**Comment by eddiejaoude** [comment]
Looks great!! I can't make any suggestions 😱
