### ISSUE TITLE
Fix: Hide Packages

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#2015]
**Description**

Hide Releases, cause we don't have any

**Stack**

Project stack or language (eg. Frontend): None (Only fixable by @EddieHubCommunity/support-repo)

![github com_EddieHubCommunity_support](https://user-images.githubusercontent.com/76587897/125590789-fc068e19-97ad-44bb-835e-de4ef8fcc49c.png)

**Comment by eddiejaoude** [comment]
Fixed in https://github.com/EddieHubCommunity/support/issues/2014

**Comment by Vyvy-vi** [comment]
I'd also like to point out that the team can not remove or add packages menu

**Comment by krishdevdb** [comment]
> I'd also like to point out that the team can not remove or add packages menu

But why ig you have permissions right?

**Comment by Vyvy-vi** [comment]
Nope
