### ISSUE TITLE
[REVIEW]  bartugenccan

### ISSUE THREAD

**Issue by bartugenccan** [EddieHubCommunity/support#2019]
### GitHub Profile Link

https://github.com/bartugenccan

**Comment by Panquesito7** [comment]
Nice profile, I liked it! I made a [**pull request**](https://github.com/bartugenccan/bartugenccan/pull/1) in that repository for minor improvements; please check it out. Thanks! 😄

**Comment by bartugenccan** [comment]
Thank you !  😄

**Comment by Sam-Varghese** [comment]
Nice profile, just one suggestion:

- Badge for Twitter appears twice on your profile, you may consider removing the top one.

**Comment by schmelto** [comment]
Consider removing this line `👨‍💻 All of my projects are available at github.com/bartugenccan` due we are already on your github profile

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Looks good

- maybe center align the stats?

**Comment by eddiejaoude** [comment]
Looks good, some thoughts

- Make more use of the GitHub profile on the left (url, description, location ...)
- Have Twitter and LinkedIn on the same line/section (under `connect with me`)
- Make use of the blank space on the right of the widgets
- Pin another repo (have an even number)

And join EddieHub GitHub Org
