### ISSUE TITLE
[REVIEW] BeratOz01

### ISSUE THREAD

**Issue by BeratOz01** [EddieHubCommunity/support#2020]
### GitHub Profile Link

https://github.com/BeratOz01

**Comment by Panquesito7** [comment]
Cool profile, I liked it! I made a [**pull request**](https://github.com/bartugenccan/bartugenccan/pull/1) in that repository for minor improvements; please check it out. Thanks! 😄

**Comment by Sam-Varghese** [comment]
Nice profile! here are my two cents:

- You may remove the profile view counter as it works incorrectly. ( I think this change is done by Panquesito7 in the PR mentioned above)
- The badge for Twitter appears twice on your profile. You may remove the top one from your profile.
- Express js badge is not visible for visitors with dark GitHub background. You may consider replacing it.

![image](https://user-images.githubusercontent.com/79152648/125874561-70242781-8ef6-4889-8303-a089370a66a2.png)

**Comment by schmelto** [comment]
With the suggestions mentioned above looking good for me maybe center some things like the github stats

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Looks good

- Twitter username is changed/deleted
- center align stats, inculding the stats (i dont know what its called) in the third line


![image](https://user-images.githubusercontent.com/84712013/154856979-452f7d04-a45b-4c4a-8d2d-9e3af8fe473d.png)
