### ISSUE TITLE
REVIEW my open source project

### ISSUE THREAD

**Issue by SaptakBhoumik** [EddieHubCommunity/support#2022]
**Project Link:** https://github.com/SaptakBhoumik/Palladium

You can also join the Discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey @SaptakBhoumik, Good project! Some suggestions from my side
- Add pull request template
- You can remove projects and wikis if not used
- I don't see any issues or PR's open. Even if you are working alone open issue -> solve it -> create PR -> Merge Pr -> Close issue
- Shift the logo of the project above the tags
<img src="https://i.imgur.com/WqsllMA.png">
- You can add screenshots or gifs of your project work. That would attract more people.
- You can add GitHub actions to ease your work.

**Comment by SaptakBhoumik** [comment]
@kaiwalyakoparkar Thank you for your feedback. I will do it😊

**Comment by schmelto** [comment]
Consider using other type of Release names like Version 1.0.0 etc.

**Comment by SaptakBhoumik** [comment]
@schmelto Thank you for your feedback

**Comment by Panquesito7** [comment]
@SaptakBhoumik, if you close this issue, it won't be reviewed in a live stream. If you want your project to be reviewed, feel free to re-open the issue. 🙂

**Comment by SaptakBhoumik** [comment]
@Panquesito7 I am no longer maintaining it so I closed it

**Comment by SaptakBhoumik** [comment]
I am working on a new project https://github.com/Swallow-lang/swallow

**Comment by Panquesito7** [comment]
> @Panquesito7 I am no longer maintaining it so I closed it

Well, you could keep this issue open for the project to be reviewed even if you're not maintaining it. It could be useful for many people. 🙂

**Comment by SaptakBhoumik** [comment]
ok then

**Comment by Akshu-on-github** [comment]
A few things that stuck out for me:
- Add the algorithm(s) used in the readme and tags for better visibility
- "Note- (...) It is not 100% accurate." -> I don't think there are any projects that have such high accuracy, I think it would be better to bring the actual accuracy here (93% to 97%) which is pretty good!

**Comment by SaptakBhoumik** [comment]
@Akshu-on-github Thanks:)

**Comment by eddiejaoude** [comment]
Looks good, some thoughts

- Use issues with labels to make the project more discoverable
- Use the GH Discussion instead of encouraging emails - this will help with community collaboration
