### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by juuz0** [EddieHubCommunity/support#2023]
### Name

Nikhil Tanwar

### Discord Username(if exists)

juuzou#6550

### Additional Context

 hoping to get added and get better at contribution :)

**Comment by Sam-Varghese** [comment]
Welcome to this community @juuz0 😊🎆🎆

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @juuz0! 😄👋
