### ISSUE TITLE
Attaching Screenshots in issues won't work

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#2027]
Attaching Screenshots in the issue forms seems net to work properly

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Changing relevant fields from type input to textarea

Due this is a relativ easy issue to fix I would suggest leaving it open for first timers / someone who just getting startet with open source contributions

**Comment by fireddd** [comment]
Hi, I have tried to address this issue in my PR
