### ISSUE TITLE
update the old links in the Readme

### ISSUE THREAD

**Issue by deephunt3r** [EddieHubCommunity/support#2031]
Hey, I just noticed Some of the links in the Readme are with old community name! I want to update them even though they are working fine! pls let me know Can I create a PR!

![image](https://user-images.githubusercontent.com/60481830/126039043-b562749c-5f91-4a04-9371-23b66cc27701.png)

**Comment by deephunt3r** [comment]
Hey folks, I just found this broken link in the README https://github.com/EddieJaoudeCommunity/EddieBot/tree/develop/tips
I need your help to find the original link

**Comment by kaiwalyakoparkar** [comment]
@deephunt3r Good spot. Did you make PR for the first one?

**Comment by deephunt3r** [comment]
I thought to update the broken link in same PR ! so I just updated the old links in local repo

**Comment by Panquesito7** [comment]
> Can I create a PR

Sure! Feel free to create a PR. It's always good to open issues first, then you can open a PR to fix that issue if other members agree with it. Thank you for your interest in our community! 😄
