### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by MRslimcoder** [EddieHubCommunity/support#2034]
### Name

Vivek aka Slim Coder

### Discord Username (if applicable)

slimcoder#1934

**Comment by Sam-Varghese** [comment]
Welcome to this community 🎉🎉✨ @MRslimcoder

**Comment by MRslimcoder** [comment]
@Sam-Varghese Thank you so much, I am very excited to work with team ❤️

**Comment by Panquesito7** [comment]
Welcome, @MRslimcoder! :smile:👋

**Comment by MRslimcoder** [comment]
@Panquesito7 thank you so much 🙏🙏
