### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AnirudhPanda** [EddieHubCommunity/support#2044]
### Name

Anirudh Panda

### Discord Username (if applicable)

Anirudh#9601

### Additional Context

I heard about Eddie on YouTube first and then saw a few of his videos. Then joined EddieHub guild on Local Hack Day by MLH and also in INIT 2021.
I love his thoughts about Open Source and I believe in 

> Open Source Is For Everyone

**Comment by Sam-Varghese** [comment]
Welcome to this community @AnirudhPanda ✨✨🎆🎉
