### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Amrutha1101** [EddieHubCommunity/support#2045]
### Name

Amrutha

### Additional Context

Hello! I'm a newbie in open source. All thanks to Eddie's YouTube channel. I joined EddieHub discord channel and found it's not only helping people professionally but also to develop personally. So I'm here and want to join the community organization.

**Comment by Sam-Varghese** [comment]
Welcome @Amrutha1101 to this community 🎉🎉✨🎇
