### ISSUE TITLE
[REVIEW] sidnegi2511

### ISSUE THREAD

**Issue by sidnegi2511** [EddieHubCommunity/support#2052]
### GitHub Profile Link

https://GitHub.com/sidnegi2511

**Comment by schmelto** [comment]
One thing from my side. Remove the view count due its inaccurate. Also consider to get more use of the space in the stats section.

**Comment by Sam-Varghese** [comment]
NIce profile, here are my two cents:

- You may the badges show below as they are not visible to visitors with dark GitHub background

![image](https://user-images.githubusercontent.com/79152648/126153702-27909339-47ea-4733-a10f-cd48137b279b.png)

![image](https://user-images.githubusercontent.com/79152648/126153752-570632f5-da0c-4877-aee5-92d076c0e918.png)

- You may fix the alignment of the badge shown below, as it doesn't appear to be aligned vertically

![image](https://user-images.githubusercontent.com/79152648/126153896-2bef4fc2-aebb-407f-a2ec-6bcc91fc07c0.png)

- As suggested, you may remove the visitor's count as it works incorrectly.

Loved the memes on your profile. ( I really refreshed your page 10-15 times in order to see more of these 😁)

**Comment by Panquesito7** [comment]
Great profile! I loved the memes in your profile; they are very nice. 😄
I have made a [**pull request**](https://github.com/sidnegi2511/sidnegi2511/pull/1) in your repository. 🙂

Thanks for sharing your profile with us! :wink:

**Comment by Panquesito7** [comment]
All looks perfect now! Your profile will look amazing for your visitors. 😄

**Comment by sidnegi2511** [comment]
> One thing from my side. Remove the view count due its inaccurate. Also consider to get more use of the space in the stats section.

Done. Any other suggestion??

**Comment by sidnegi2511** [comment]
> One thing from my side. Remove the view count due its inaccurate. Also consider to get more use of the space in the stats section.

Done. Thanks for the review.

**Comment by sidnegi2511** [comment]
> All looks perfect now! Your profile will look amazing for your visitors.

Thanks for providing the help.

**Comment by sidnegi2511** [comment]
> NIce profile, here are my two cents:
> 
> * You may change the badges show below as they are not visible to visitors with dark GitHub background
> 
> ![image](https://user-images.githubusercontent.com/79152648/126153702-27909339-47ea-4733-a10f-cd48137b279b.png)
> 
> ![image](https://user-images.githubusercontent.com/79152648/126153752-570632f5-da0c-4877-aee5-92d076c0e918.png)
> 
> * You may fix the alignment of the badge shown below, as it doesn't appear to be aligned vertically
> 
> ![image](https://user-images.githubusercontent.com/79152648/126153896-2bef4fc2-aebb-407f-a2ec-6bcc91fc07c0.png)
> 
> * As suggested, you may remove the visitor's count as it works incorrectly.
> 
> Loved the memes on your profile. ( I really refreshed your page 25-30 times in order to see more of these )

I don't know why but I am not able to align the photos properly, can you help me with that?

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
@sidnegi2511 did you mean to close this? we did not review it yet on a live stream, although I know you got loads of great community feedback already

**Comment by sidnegi2511** [comment]
> @sidnegi2511 did you mean to close this? we did not review it yet on a live stream, although I know you got loads of great community feedback already

Shall I reopen it again?

**Comment by eddiejaoude** [comment]
yep, thank you for reopening 👍

**Comment by eddiejaoude** [comment]
Looks good, some thoughts

- Add Twitter to the socials icons as well
- VScode icon is higher than the rest
- Put all 4 widgets into a 2x2 grid to make better use of space
- Possible remove the meme as does not look so professional

Join EddieHub Org 😂
