### ISSUE TITLE
[REVIEW] ishikkkkaaaa

### ISSUE THREAD

**Issue by ishikkkkaaaa** [EddieHubCommunity/support#2053]
### GitHub Profile Link

https://github.com/ishikkkkaaaa

**Comment by schmelto** [comment]
Hey only one suggestion from my side. Consider removing the profile view count due its inaccurate. Otherwise I really like the style of the social buttons 🚀

**Comment by Sam-Varghese** [comment]
Nice profile, just noticed one thing that clicking on the LinkedIn badge takes me to the following page

![image](https://user-images.githubusercontent.com/79152648/126155196-537ebcaf-fce3-455a-952f-9c008bda57e1.png)

**Comment by ishikkkkaaaa** [comment]
will fix it, thank you for letting me know @Sam-Varghese !

**Comment by Panquesito7** [comment]
> Consider removing the profile view count due to its inaccurate

I agree with @schmelto. 👍

**Comment by gautam-07** [comment]
@ishikkkkaaaa Your profile looks great but consider adding an About Me section in your profile so that anyone visiting your profile would know what are you learning these days and what skill level or project you are working on. 
Thank you

**Comment by ishikkkkaaaa** [comment]
Thankyou @gautam-07 !
Will keep a note and make the required changes ☺️☺️

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍
