### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ayush-devshark** [EddieHubCommunity/support#2060]
### Name

Ayush Agarwal

### Discord Username (if applicable)

àyush

### Additional Context

I have seen Eddie on youtube, and other social media platforms. I wasn't using git much before as i was new to coding and was learning fundamentals. Now, after learning for a while now, i want to contribute to open source. I want to join this community since there is no bias regarding acceptance of candidates, and it has helped many developers in soft skills. I want to be part of such helpful community both as contributer and learner.

**Comment by schmelto** [comment]
welcome to the community!

**Comment by Panquesito7** [comment]
Welcome to the community! 🙂
