### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by code-reaper08** [EddieHubCommunity/support#2069]
### Name

Vishwa.R

**Comment by Sam-Varghese** [comment]
Welcome to this community @code-reaper08 ✨✨🎉

**Comment by code-reaper08** [comment]
> Welcome to this community @code-reaper08 ✨✨🎉

Thank you for welcoming me @Sam-Varghese 
Happy to be a part of the community 😃
