### ISSUE TITLE
[REVIEW] gautam-07

### ISSUE THREAD

**Issue by gautamkhatter** [EddieHubCommunity/support#2070]
### GitHub Profile Link

https://github.com/gautam-07

**Comment by schmelto** [comment]
Consider removing the view count due its inaccurate

**Comment by gautam-07** [comment]
Ok, thanks for the suggestion.

**Comment by Sam-Varghese** [comment]
NIce profile! like it

**Comment by gautam-07** [comment]
Thank you

**Comment by Sam-Varghese** [comment]
@gautam-07 If you close this issue, then it won't be reviewed on Livestream

**Comment by gautam-07** [comment]
Ok, got it

**Comment by Panquesito7** [comment]
Amazing profile! I loved it, and it looks so cool! 😄👍
I have made a [**pull request**](https://github.com/gautam-07/gautam-07/pull/1) in your repository. Please check it out. 🙂

Thank you for sharing your profile with us! 😉

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by FayasNoushad** [comment]
Ohh! Looking good :heart:

**Comment by eddiejaoude** [comment]
Was going to review on live stream, but profile not found (`404`)

**Comment by eddiejaoude** [comment]
Found it thanks @schmelto 

Looks good, some thoughts

- Banner has the Nike slogan and could probably make it smaller 
- I don't think your name is needed here ` Hi, I am Gautam Khatter. 👋`
- Contributors graph, get involved in issues, code reviews and pull requests
