### ISSUE TITLE
[FEATURE REQUEST] Make the `Additional Context` part obligatory in the invitation template

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/support#2074]
### Description of feature request, idea

Make the `Additional Context` part obligatory in the invitation template.

### Add any other context about the feature request here

Many people just use the invitation template without explaining why do they want to join or simply without providing any input. I think we should make it obligatory. Let me know what do you think. Thanks. 🙂

**Comment by Sam-Varghese** [comment]
I think we should make `Additional Context` obligatory because this will make the community know the actual reason why people are getting into EddieHub and would encourage us to work more on that. It would also enable community members to know the newly joined folks better.

**Comment by Panquesito7** [comment]
@Sam-Varghese, that's what I just tried to say. :)

**Comment by schmelto** [comment]
I`m not a fan of making the "Additonal Context" obligatory.
I think when you want to join the community we sould make it as effortles as possible for new folks to join.

For myself it would be deterrent that I have to provide those informations. Further I new folks could simple fill out that field with `-` etc.
