### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by aakankshabhende** [EddieHubCommunity/support#2075]
### Name

Aakanksha Bhende

### Additional Context

Hey! I'm an open source enthusiast and want to join this community to develop my skills and grow professionally. I feel this community will be a great start for this and learn new things.

**Comment by Panquesito7** [comment]
Welcome to our community, @aakankshabhende! Here you will learn a lot of new things in collaboration and Open Source. We're glad you've joined us! 😉🎉
