### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Swastyy** [EddieHubCommunity/support#2076]
### Name

Swastika

### Discord Username (if applicable)

Swasty#1957

**Comment by Sam-Varghese** [comment]
Welcome to this community @Swastyy 🎉🎉🎊

**Comment by Swastyy** [comment]
> Welcome to this community @Swastyy 🎉🎉🎊

Thanks! 🎉

**Comment by Panquesito7** [comment]
Oh yay! Welcome to the great EddieHub community, @Swastyy, where we believe _Collaboration 1st, Code 2nd_! 😄👍🎉

**Comment by Swastyy** [comment]
Thank you so much @Panquesito7 🙂
