### ISSUE TITLE
Please add bloedboemmel

### ISSUE THREAD

**Issue by bloedboemmel** [EddieHubCommunity/support#2077]
### Name

bloedboemmel

### Discord Username (if applicable)

bloedboemmel#5373

### Additional Context

I like the opportunity to work together in a team. I've never met Eddie, but I want to!

**Comment by Sam-Varghese** [comment]
Welcome to EddieHub @bloedboemmel ✨✨🎉 Hope you have a good time at EddieHub engaging with this awesome community! 🙂
