### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by swarnakrishnan** [EddieHubCommunity/support#2078]
### Name

Swarna Krishnan Kuchibhotla

### Discord Username (if applicable)

Maleficient_1710#1120

**Comment by Sam-Varghese** [comment]
Welcome to this community @swarnakrishnan 🎉✨✨ Happy to have you here 🙂

**Comment by Panquesito7** [comment]
Welcome to the great EddieHub community, @swarnakrishnan, where we believe _Collaboration 1st, Code 2nd_. 😄🎉
