### ISSUE TITLE
[REVIEW] shivam-0510

### ISSUE THREAD

**Issue by shivam-0510-zz** [EddieHubCommunity/support#2087]
### GitHub Profile Link

https://github.com/shivam-0510

**Comment by schmelto** [comment]
One thing from my side consider centering also the Languages and Tools badges otherwise I really like your profile

**Comment by shivam-0510** [comment]
I have made the necessary changes. Now you can check them.

**Comment by gautam-07** [comment]
Your profile looks great but there is one thing that I would recommend. Consider adding an About Me section which tells everyone who you are and if you have, mention any projects that you have worked on.
Thanks

**Comment by shivam-0510** [comment]
Hi @gautam-07, I have added the About Me section. You can check it now on my profile.
Thanks

**Comment by gautam-07** [comment]
It looks good. You can also add your GitHub Readme stats and your subheading under your name, please consider making it a different font because it is not eye-catching.

**Comment by gautam-07** [comment]
And if you are looking for doing CP or DSA with someone, I am too. Please feel free to connect with me on any of my socials mentioned in my profile.
Thank you

**Comment by shivam-0510** [comment]
@gautam-07 I have added the Github Readme stats to my profile

**Comment by gautam-07** [comment]
@shivam-0510  It looks good. You didn't contact me for DSA. Do you wanna do it together?

**Comment by shivam-0510** [comment]
I started DSA recently so, whenever I need help I will definitely contact you.

**Comment by gautam-07** [comment]
@shivam-0510  I started it recently as well. That's why I thought it will be a good idea for us to do it together. just like pair programming.

**Comment by shivam-0510** [comment]
Sorry @gautam-07 but I am already doing pair programming with one of my college friend.

**Comment by gautam-07** [comment]
@shivam-0510  Ok, no problem but if you had any other friends who are looking for pair programming then, contact me

**Comment by shivam-0510** [comment]
Yeah, sure

**Comment by Panquesito7** [comment]
Amazing profile! I really, really loved it. It looks amazing! ❤️
However, there's one minor issue for users in dark mode.

![image](https://user-images.githubusercontent.com/51391473/127061531-fbfa8748-11a6-494a-ae77-4ae2d2dde247.png)

That text doesn't look so well in dark mode.
I have also made a [**pull request**](https://github.com/shivam-0510/shivam-0510/pull/1) in your repository.

Thank you for sharing your amazing profile! 😄

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- suggest having a profile photo of you
- profile does not look customised however some of the comments suggest it was previously
- add profile description
