### ISSUE TITLE
[REVIEW] Divakar

### ISSUE THREAD

**Issue by rexdivakar** [EddieHubCommunity/support#2094]
### GitHub Profile Link

https://github.com/rexdivakar

**Comment by gautam-07** [comment]
I really like your profile. But there is one thing that I wanna recommend. Consider spacing things out a little. They are clustered for now.
Thanks

**Comment by Panquesito7** [comment]
Amazing profile! I loved it! I have made a [**pull request**](https://github.com/rexdivakar/rexdivakar/pull/1) in your GitHub README repository for minor improvements. 🙂

Thank you for sharing your profile with us and for contributing to our community! 😄

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- animated gif takes away from your skills
- 100% commits, suggest doing more PRs, Issues, and reviews
- github badge with link is duplicated
