### ISSUE TITLE
[REVIEW] Notifly

### ISSUE THREAD

**Issue by rexdivakar** [EddieHubCommunity/support#2095]
### Project link

https://github.com/rexdivakar/Notifly

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by KendallDoesCoding** [comment]
Looks good

- Add bot.png (logo) above badges in README.md
- Center align badges in README.md
- hide discussions tab is not using
- add a security policy

**Comment by eddiejaoude** [comment]
Looks great, some feedback...

- table of contents not required as generated by github
- hide packages if not used
- add build badge for GitHub to README
