### ISSUE TITLE
[REVIEW] SahityaRoy

### ISSUE THREAD

**Issue by SahityaRoy** [EddieHubCommunity/support#2100]
### GitHub Profile Link

https://github.com/SahityaRoy

**Comment by schmelto** [comment]
conisder removing the duplicate badge with "buy me a coffee"

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by SahityaRoy** [comment]
Thanks

**Comment by Sam-Varghese** [comment]
Noce profile! I agree with the suggestion of removing the duplicate badge mentioned above. Here are my two cents:

- Twitter badge also appears twice on your profile. Consider removing anyone
- Horizontal alignment of the below stats are not the same. You may fix this for a better look

![image](https://user-images.githubusercontent.com/79152648/127208063-64a1dcde-9866-4fd2-bbd7-12e306818ad7.png)

**Comment by Panquesito7** [comment]
Amazing profile! I liked it so much! I have made a [**pull request**]() in your repository for some improvements and changes in your `README.md` file in your profile. 🙂

Thank you for sharing your profile with the community! 😉
