### ISSUE TITLE
[REVIEW] E-Learning-freesite

### ISSUE THREAD

**Issue by SahityaRoy** [EddieHubCommunity/support#2101]
### Project link

https://github.com/SahityaRoy/E-Learning-freesite

**Comment by schmelto** [comment]
* https://github.com/SahityaRoy/E-Learning-freesite/community take a look at those points
* add a release

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by SahityaRoy** [comment]
Thanks

**Comment by KendallDoesCoding** [comment]
Looks good

- add release/tag
- In the end of README.md remove "Plugin", "README"
- Make banner a little small in README.md
- Add badges above banner in README.md

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- suggest using releases/tags
- hide packages if not used
- hide wiki as it is only 1 page (also remove `guys`, use something like `people`, `folks`, `y'all`, `everyone`)
- `.vscode` should not be added to the repo (this should be in the gitignore
- suggest go through open issues and pull requests
