### ISSUE TITLE
[REVIEW] msaaddev

### ISSUE THREAD

**Issue by msaaddev** [EddieHubCommunity/support#2104]
### GitHub Profile Link

https://github.com/msaaddev

**Comment by schmelto** [comment]
👍🏼

**Comment by Panquesito7** [comment]
Amazing profile! I loved it! I have made a [**pull request**](https://github.com/msaaddev/msaaddev/pull/2) in your
repository for some improvements in your README profile. 🙂

Thank you for sharing your profile with the EddieHub community! 😄

**Comment by msaaddev** [comment]
Hey, @Panquesito7! Thanks for the PR. I will review it.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by Sam-Varghese** [comment]
Great profile! liked it, Your contribution graph is filled with green squares. I really appreciate your consistency towards contributing to open source development! 👍

**Comment by Panquesito7** [comment]
Amazing profile! I love it! 😄🎉

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- poster/banner looks amazing!
- love the bullet list about yourself
- suggest doing more code reviews / issues / pull requests
