### ISSUE TITLE
[REVIEW] Pridebot

### ISSUE THREAD

**Issue by qwe123coder** [EddieHubCommunity/support#2105]
### Project link

https://github.com/tyffical/Pridebot

**Comment by schmelto** [comment]
Some suggestions:

* add a release
* hide packages
* hide wiki if not used
* https://github.com/tyffical/Pridebot/community get those all green
* why are there no issues?

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍
