### ISSUE TITLE
[REVIEW] Rupesh-Darimisetti

### ISSUE THREAD

**Issue by Rupesh-Darimisetti** [EddieHubCommunity/support#2107]
### GitHub Profile Link

https://github.com/Rupesh-Darimisetti

**Comment by schmelto** [comment]
Only one thing from my side your name is double named here ![Screenshot_20210726_141920_com.github.android.jpg](https://user-images.githubusercontent.com/30869493/126987549-9b4e7a87-87f7-4dfe-957d-1c6a7d4d3a45.jpg)

**Comment by Rupesh-Darimisetti** [comment]
Thanks for your suggestions

**Comment by Panquesito7** [comment]
Great profile! I liked it. I have made a [**pull request**](https://github.com/Rupesh-Darimisetti/Rupesh-Darimisetti/pull/1) in
your README profile repository for some minor changes. 🙂

Thank you for sharing your profile with us! 😉

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by Sam-Varghese** [comment]
Nice profile! here are my two cents:

-  You may remove the GitHub badge under Connect With Me section as all visitors to your page are already on that page
- Badges under the Languages and tools section are very small.  If you wish, then you may make them bigger
- I think these stats would look better if they have consistent horizontal alignment

![image](https://user-images.githubusercontent.com/79152648/127205270-434d166e-2873-4141-a52f-b19b1dcdebe2.png)

**Comment by schmelto** [comment]
Consider also to remove the github bade in the connect with me section due we are already on your github profile :)
