### ISSUE TITLE
[REVIEW] rukundob451

### ISSUE THREAD

**Issue by rukundob451** [EddieHubCommunity/support#2112]
### GitHub Profile Link

https://github.com/rukundob451

**Comment by rukundob451** [comment]
Thank you for giving me this opportunity and I will indeed contribute more and more

**Comment by Panquesito7** [comment]
Great profile! I liked it! I have made a [**pull request**](https://github.com/rukundob451/rukundob451/pull/1) in your README 
profile for some improvements (they are shown in the Git diff). 🙂

Thank you for sharing your profile with the community! 😄👍

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by Sam-Varghese** [comment]
Liked your profile 😀👍Your contributing graph is looking amazing!

**Comment by rukundob451** [comment]
> Great profile! I liked it! I have made a [**pull request**](https://github.com/rukundob451/rukundob451/pull/1) in your README
> profile for some improvements (they are shown in the Git diff). 🙂
> 
> Thank you for sharing your profile with the community! 😄👍

Thank you indeed, I hope to learn more and more and be able to become a better contributor

**Comment by rukundob451** [comment]
> Thank you for sharing, we will review on a live stream soon 👍

Thank you so much Eddie, extremely happy for it to be reviewed in the live stream. Super pumped for it.

**Comment by rukundob451** [comment]
> Liked your profile 😀👍Your contributing graph is looking amazing!

Am glad you liked it, be sure to connect so that we can contribute more and more indeed.

**Comment by Panquesito7** [comment]
> > Great profile! I liked it! I have made a [**pull request**](https://github.com/rukundob451/rukundob451/pull/1) in your README
> > profile for some improvements (they are shown in the Git diff). 🙂
> > Thank you for sharing your profile with the community! 😄👍
> 
> Thank you indeed, I hope to learn more and more and be able to become a better contributor

You will have to merge my PR if you want to accept my changes. 🙂

**Comment by rukundob451** [comment]
> > > Great profile! I liked it! I have made a [**pull request**](https://github.com/rukundob451/rukundob451/pull/1) in your README
> > > profile for some improvements (they are shown in the Git diff). 🙂
> > > Thank you for sharing your profile with the community! 😄👍
> > 
> > 
> > Thank you indeed, I hope to learn more and more and be able to become a better contributor
> 
> You will have to merge my PR if you want to accept my changes. 🙂

I have finished merging your PR, thank you for the improvements made to my readMe.

**Comment by schmelto** [comment]
At the point "How to reach me: rukundob32@gmail.com and benja_rukundo" maybe add a link to your twitter handle or say in text that this is your twitter handle.

**Comment by Panquesito7** [comment]
I agree with @schmelto. Apart from what they said, all seems to be looking nice! Good job. 😄👍

**Comment by rukundob451** [comment]
> I agree with @schmelto. Apart from what they said, all seems to be looking nice! Good job. 😄👍

Thank you so much, I want to learn about more feature on here and working with projects very well and being member of the Eddie Jaoude community indeed.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- great clear and professional profile picture
- great bio, love the `open source enthusiast`, I suggest removing `upcoming`
- probably has too many widgets, suggest reducing them

**Comment by rukundob451** [comment]
Thanks for the profile review @eddiejaoude.
