### ISSUE TITLE
[REVIEW] my-wallet-app-ui

### ISSUE THREAD

**Issue by rukundob451** [EddieHubCommunity/support#2113]
### Project link

https://github.com/rukundob451/my-wallet-app-ui

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍

**Comment by schmelto** [comment]
* https://github.com/rukundob451/my-wallet-app-ui/community
* add a release
* hide packages
* hide wiki
* add more to the readme seems to be the initial flutter readme
* use issues and Prs

**Comment by KendallDoesCoding** [comment]
> * https://github.com/rukundob451/my-wallet-app-ui/community
> * add a release
> * hide packages
> * hide wiki
> * add more to the readme seems to be the initial flutter readme
> * use issues and Prs

Agree with Tom.. If your not gonna use issues, please hide the tab.

**Comment by rukundob451** [comment]
Sure going to do this immediately

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- only has 1 commit, suggest committing in stages
- releases are great to use, but while not using them, suggest hiding them for now (same with packages)
- suggest having a screenshot in the README
- hide wiki if not used

**Comment by rukundob451** [comment]
Thanks for this surely, let me do this straight up.
Really appreciate your reviews. Possibly you could recommend me to some projects as a contributor @eddiejaoude. What do you think?
