### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by abhishekjha812** [EddieHubCommunity/support#2114]
### Name

Abhishek Jha

### Discord Username (if applicable)

Abhishek jha#9372

### Additional Context

I didn't met Eddie personally but i have heard of him from many people like Kunal Kushwaha in the community that how good he is with the community and how well he interacts with everyone .

This community is very engaging with people with great ambition and enthusiasm .

I would love to join this community as we all are very much similar about are goals.
"Community for all , all for community " :)

**Comment by Panquesito7** [comment]
Welcome to the community, @abhishekjha812! We're glad you've found us and that you want to collaborate and contribute with us! 😄👍🎉
