### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by emmalearnscode** [EddieHubCommunity/support#2115]
### Name

Emma Dawson

### Discord Username (if applicable)

emmalearnscode

### Additional Context

I followed Eddie on Twitter and then found his youtube channel which I really enjoy watching and would like to be part of the community.

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @emmalearnscode! We're glad you've joined us! 😄👋
