### ISSUE TITLE
[REVIEW] friskycodeur

### ISSUE THREAD

**Issue by friskycodeur** [EddieHubCommunity/support#2118]
### GitHub Profile Link

https://github.com/friskycodeur

**Comment by Sam-Varghese** [comment]
Nice profile! 🙂here are my two cents:

- Link to your Twitter account appears twice on your profile. You may remove anyone.
- If you wish, then you may remove the GitHub badge from your profile as visitors are already on this page.
- You may change the link to your Instagram profile as it takes me to this page:

![image](https://user-images.githubusercontent.com/79152648/127202623-11d8fb7a-30bc-423a-99c4-4bb001712287.png)

**Comment by Panquesito7** [comment]
Great profile! I liked it! I have made a [**pull request**](https://github.com/friskycodeur/friskycodeur/pull/1) in
your repository for minor improvements in your README profile.

Thank you for sharing your profile with us! 😉

**Comment by friskycodeur** [comment]
Thank you @Panquesito7 and @Sam-Varghese for taking out your time and helping out with the changes, will change as per your points. 😄

**Comment by schmelto** [comment]
Great profile consider removing Jupiter Notebook form the most used languages due I think also images etc. count in the file size / line count which would be increase the percantege here :)

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- great profile picture
- suggest pinning even number of repos (currently 5, suggest only 5)
