### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by danjohnson77** [EddieHubCommunity/support#2121]
### Name

Daniel Johnson

### Discord Username (if applicable)

Daniel Johnson#7184

### Additional Context

I first found Eddie on a livestream with RealToughCandy, he really helped demystify Open Source and make it feel like a welcoming community! I'm really hoping to improve my coding skills through collaboration, as well as meeting new coders of course.

**Comment by Panquesito7** [comment]
Welcome to the amazing EddieHub community, @danjohnson77, where we believe *Collaboration 1st, Code 2nd*! 😄🎉👋
