### ISSUE TITLE
[REVIEW] Ritwik880

### ISSUE THREAD

**Issue by Ritwik880** [EddieHubCommunity/support#2124]
### GitHub Profile Link

https://github.com/Ritwik880

**Comment by schmelto** [comment]
Nice profile.

Consider removing the profile view count due it's inaccurate

Also consider remove the GitHub follow count due this information is already provided by github

**Comment by Ritwik880** [comment]
Hey @schmelto thanks for reviewing my profile, any more suggestion from your side?

**Comment by Panquesito7** [comment]
Hey, @Ritwik880! Great profile! I loved it. I have made a [**pull request**](https://github.com/Ritwik880/Ritwik880/pull/3) for some minor improvements. *Some* of those improvements are:

- Remove the profile views count as it's inaccurate like @schmelto said.
- Change the black icons to badges as they are not visible for users in dark mode.

Thank you for sharing your profile with the EddieHub community! 😄

**Comment by shubhimainalli** [comment]
Great profile!!

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- you have 3 pinned repos, suggest having 2 or 4 (even number)
- very commit heavy, suggest creating issues and pull requests, also reviewing pull requests
- maybe add more description to the customised profile
