### ISSUE TITLE
[REVIEW] kalashsharma.me

### ISSUE THREAD

**Issue by k99sharma** [EddieHubCommunity/support#2125]
### Portfolio link

https://www.kalashsharma.me/

**Comment by mikeysan** [comment]
I'll let the designers comment on aesthetics. Here's something I spotted, though.

When you mouse-over (1 and 2) your recent projects the background resizes. 
![image](https://user-images.githubusercontent.com/13338176/127755206-3bc55f71-072c-48e2-8872-afd5ace0d801.png)

Look at the size difference
![image](https://user-images.githubusercontent.com/13338176/127755237-e7ad5440-608a-4f66-bf72-cd0f7b71bfff.png)

**Comment by k99sharma** [comment]
Yes, actually I was going to fix this issue. But this portfolio is temporary, and I will make a new single-page portfolio with a blog feature. Until then I will open this as an issue and maybe someone can fix this for me. Thanks for your comment!

**Comment by emmalearnscode** [comment]
I really liked your about me section, I got a good impression of you as a person from it. A few ideas:

- there are some colour contrast and hierarchy issues with your main content on the first page. The blue on black is too dark and although it’s bigger the white text stands out more so the eye is drawn there more than anywhere else.
- Add more projects so we can see your skills

**Comment by eddiejaoude** [comment]
Please share the github repo link

**Comment by mikeysan** [comment]
I was just about to ask if this should be closed when I noticed your last comment, @eddiejaoude was two days ago 😄 I suppose a link to the repo would be good as a final step before closing.

**Comment by schmelto** [comment]
https://www.kalashsharma.me/ is not available

**Comment by k99sharma** [comment]
Hey @eddiejaoude I just saw your email. I think I missed the previous email somehow and was not able to reply back soon.

Portfolio link: https://www.kalashsharma.com

**Comment by k99sharma** [comment]
@schmelto you are right. I re-designed the portfolio in react and got a new domain name. Actually I got the last one using GitHub student pack and it got expired after 1 year.

**Comment by eddiejaoude** [comment]
No GitHub link, going to close - please submit a new issue if you have a GitHub repo link
