### ISSUE TITLE
[REVIEW] Ritwik880

### ISSUE THREAD

**Issue by Ritwik880** [EddieHubCommunity/support#2126]
### Resume link

https://drive.google.com/file/d/1v16ZV__l9Mq-FQhCJI1O0A2yibeTUv71/view?usp=sharing

**Comment by Panquesito7** [comment]
You have a lot of experience! I also liked the resume. 😄

- I would recommend changing this to a Markdown-like link. Something like: My [LinkedIn](https://www.linkedin.com/in/ritwik-sinha-8854a2146/) and my [GitHub](https://www.linkedin.com/in/ritwik-sinha-8854a2146/) profiles.

![image](https://user-images.githubusercontent.com/51391473/127382573-d25ac476-89ef-4c41-94ca-58a896181a43.png)

- Here it should be `Hacktoberfest`.

![image](https://user-images.githubusercontent.com/51391473/127383005-92b9c682-5369-4a59-883b-64605b42993f.png)

- Some colons are not separated from both texts. IMO, they should be (same in other parts of the resume).

![image](https://user-images.githubusercontent.com/51391473/127383326-e390181e-e21c-4abe-bc1f-7185cca421b3.png)

Overall, it looks great! I loved it! Great job, @Ritwik880! 😄👍🎉

**Comment by Ritwik880** [comment]
@Panquesito7 thanks for reviewing.

**Comment by mikeysan** [comment]
Are any of the projects you worked on online? And are you able (allowed) to share a link to any of them?

I don't know if it is still a thing, but I would have liked to see one of two of them. 

Someone correct me if that's not needed these days :smile:

**Comment by Ritwik880** [comment]
Hey @mikeysan you can check my projects by going to my repository.

**Comment by eddiejaoude** [comment]
Reviewed on video, video coming out in a few weeks

Looks good 👍  some thoughts
- titles not all the same, `skill` is different, better to be consistent
- have some more spacing around the section for clearer divide 
- projects to have GitHub repo links
