### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by aqsakazi** [EddieHubCommunity/support#2127]
### Name

Aqsa Kazi

### Discord Username (if applicable)

ayekyuaise#2057

**Comment by Sam-Varghese** [comment]
Welcome, @aqsakazi to EddieHub 😄🎉We would be waiting for you in discord 🙂

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @aqsakazi! 😄🎉
