### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Subathra19** [EddieHubCommunity/support#2129]
### Name

Sri Subathra Devi B

### Discord Username (if applicable)

Subathra#9802

**Comment by Sam-Varghese** [comment]
Welcome to this community @Subathra19 😀Happy to have you here at EddieHub 🎉🎉

**Comment by Panquesito7** [comment]
Welcome to the amazing EddieHub community, @Subathra19! We're glad you've joined us! 😄👍🎉
