### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by warrenferns** [EddieHubCommunity/support#2133]
### Name

Warren Fernandes

### Discord Username (if applicable)

wARZ#1199

### Additional Context

- [x]  I want to make the world a better place, even if it’s only by making sure our community has its turn at making OSS contribution better.
- [x] To learn workplace & tech skills from being an active contributor
- [x] To collaborate through threaded discussions, conversations, and interactions.
- [x] Learn from other members of the community
- [x] Reuse solutions through asking and answering questions

**Comment by Sam-Varghese** [comment]
Welcome @warrenferns to EddieHub  🎉😊We are glad to have you in our community 🥳 Waiting to welcome you in the discord too 😊
