### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by foo290** [EddieHubCommunity/support#2134]
### Name

Nitin

### Discord Username (if applicable)

foo()#5609

### Additional Context

Hi, I am new to open-source and found this amazing organization with a very active community. I wanna be a part of your organization and find a place to use my skills to contribute to open-source.

**Comment by Sam-Varghese** [comment]
Welcome to EddieHub 🎉🥳 @foo290 We're glad to have you in our community 😊Waiting to welcome you in discord too 😀
