### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AbhayRaghuram** [EddieHubCommunity/support#2135]
### Name

Abhay Raghuram

### Discord Username (if applicable)

Abiggz24

### Additional Context

I spoke with Eddie on radioEddie, about being a beginner and wanting to better myself as a self taught developer. I was asked to join this community and get started immediately on open source contributions and expanding my network.
I like the inclusitivity and helpfulness of this community and feel that I will be able to improve my coding skills as well as make meaningful connections. I want to join to improve my skills and get to a position where I can land a role as a developer. I also want to be able to help others like me who are new to the industry and get started and contribute to open source projects.

**Comment by Panquesito7** [comment]
It's nice to have you in our community, @Abhay0809! Welcome! 😄👋🎉

**Comment by Abhay0809** [comment]
> It's nice to have you in our community, @Abhay0809! Welcome! 😄👋🎉
> 

Wrong Ping xD

**Comment by Panquesito7** [comment]
> Wrong Ping xD

Haha, sorry. 😅

**Comment by AbhayRaghuram** [comment]
Thank you @Panquesito7 I look forward to it!😁
