### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Krishnapro** [EddieHubCommunity/support#2136]
### Name

Krishna Kumar

### Discord Username (if applicable)

Krishn(P)#3230

### Additional Context

First time I saw Eddie on YouTube with Kunal. Recently I watched a video on open source in that video Eddie said "collaboration 1st and code 2nd" I like that mindset. Because I want learn about open source.

**Comment by Panquesito7** [comment]
Welcome to the amazing EddieHub community, @Krishnapro! We hope you learn more about Open Source with us! 😄👋🎉
