### ISSUE TITLE
[REVIEW] Currently a University Student

### ISSUE THREAD

**Issue by jamesmarcooo** [EddieHubCommunity/support#2139]
### Resume link

https://bit.ly/ReyesMarco_Resume2021

**Comment by Panquesito7** [comment]
Nice resume! I liked it a lot! You should probably add your social media links such as your GitHub or Twitter profiles. 🙂

**Comment by jamesmarcooo** [comment]
I got some clickable links for LInkedIn and Github under my name. Thank you so much, Panquesito7!!! I really appreciate this :)

**Comment by shreemaan-abhishek** [comment]
I loved the clarity of your resume James, would you mind sharing an editable version of your file?

**Comment by Panquesito7** [comment]
Amazing! It'll be great when this is reviewed in a live stream. 😄🥳🎉

**Comment by eddiejaoude** [comment]
Reviewed on video, video coming out in a few weeks

Looks good 👍 , my thoughts
- linkedin/github links to be full urls 
- education section to be towards the end
- projects to be towards the top
- projects to have GitHub repo links
- skills and interests seem to not have interests (hobbies), suggest removing the word and having a separate section if you want to include hobbies
