### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by yash9263** [EddieHubCommunity/support#2143]
### Name

Yashwant

### Discord Username (if applicable)

SONU#3691

### Additional Context

Hi, I am a full-stack developer. I wanted to start contributing to open-source projects. I got to know about this community from the freecodecamp video that Eddie had done about open source. I would love to be a part of this open-source community and learn from you all.

**Comment by Sam-Varghese** [comment]
Welcome to the community @yash9263 🥳🥳Glad to have you here 🎉💥
