### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by euhidaman** [EddieHubCommunity/support#2145]
### Name

Euhid Aman

### Discord Username (if applicable)

Frazermitt#6110

### Additional Context

I got to know about Eddie from another Open Source enthusiast 'Kunal Kushwaha'.
And, after that I started seeing his videos on YouTube and his playlists were just awesome, they helped me a lot to start contributing to the Open Source community.

I want to join this community because, as a fellow Open Source enthusiast , I believe it's my duty to also learn and share my knowledge to other beginners, just like Eddie shared his knowledge with us. And, I don't want people to struggle the way I did, when I first started with Open Source.

**Comment by Sam-Varghese** [comment]
Welcome to EddieHub @euhidaman 🥳Glad to have you in this community 🎉
