### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rukundob451** [EddieHubCommunity/support#2148]
### Name

Benjamin Rukundo

### Discord Username (if applicable)

Dev Ben#2742

### Additional Context

I have been following Eddie for sometime and he is the reason I was able to get started with opensource. I like that the community is collaborative and teaches new things to people such as improvement in communication. I would like to join this community to be able to connect like minded and be able to network opensource enthusiasts too.

**Comment by Sam-Varghese** [comment]
Welcome, @rukundob451 to EddieHub 😀🎉Glad to know your feedback on the community😇 . Best wishes for all your future endeavors 👍

**Comment by rukundob451** [comment]
> Welcome, @rukundob451 to EddieHub 😀🎉Glad to know your feedback on the community😇 . Best wishes for all your future endeavors 👍

Thank  you @Sam-Varghese, glad to find really welcoming people like you in the community. Super pumped to collaborate with you all.

**Comment by Sam-Varghese** [comment]
I guess you have not joined [dicord](https://discord.com/invite/jZQs6Wu) yet. Our community is very active on discord, and we share important information about hackathons, open src, etc. We also have regular meetups, so you are welcomed to join our discord server too

**Comment by rukundob451** [comment]
> I guess you have not joined [dicord](https://discord.com/invite/jZQs6Wu) yet. Our community is very active on discord, and we share important information about hackathons, open src, etc. We also have regular meetups, so you are welcomed to join our discord server too

Sure @Sam-Varghese, let me join in real quick. Don't want to miss out any conversations on there, thank you.
