### ISSUE TITLE
[REVIEW] ChatBud - Instant Chat Web Application

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/support#2156]
### Project link

https://github.com/guptasajal411/instant-chat-app

### Deployed on Heroku

https://try-chatbud.herokuapp.com/

**Comment by schmelto** [comment]
* Take a look [here](https://github.com/guptasajal411/instant-chat-app/community)
* add a release
* hide packages
* hide wiki if not used

Nice Lighthouse checks on your deployed website
![image](https://user-images.githubusercontent.com/30869493/128477129-696a05c3-f056-4f63-b1fd-f455d5c60565.png)

**Comment by guptasajal411** [comment]
Thanks a lot, Tom! Loved your suggestions 😄

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- use releases (ideally automated from GitHub Actions)
- use issues even if you are the only person - using issues with labels will help your project get discovered and more contributions 
- maybe use animated give in README to reduce the images
