### ISSUE TITLE
[REVIEW] Search Github User

### ISSUE THREAD

**Issue by mukul98s** [EddieHubCommunity/support#2160]
### Project link

https://github.com/mukul98s/search-github-user

**Comment by schmelto** [comment]
* take a look here https://github.com/mukul98s/search-github-user/community
* hide wiki if not used
* add a release
* hide packages
* add some screenshots or demo video in the reamde
* why do I have to login to enter the website?
* use issues and labels

**Comment by Panquesito7** [comment]
I think you should re-open this issue, @mukul98s, if you want it to be reviewed in a live stream.

**Comment by KendallDoesCoding** [comment]
Looks good

- Add badges to README.md
- consider making a banner for the project
- Add [security policy](https://github.com/mukul98s/search-github-user/security)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- last active contribution was in August
- I think releases/tags should be used
- suggest using issues and labels
