### ISSUE TITLE
[REVIEW] Project Zone

### ISSUE THREAD

**Issue by rockingrohit9639** [EddieHubCommunity/support#2161]
### Project link

https://github.com/rockingrohit9639/project-zone

**Comment by schmelto** [comment]
some thoughts:

* consider removing the wiki if not used
* maybe change the screenshot so a gif or demo video

**Comment by rockingrohit9639** [comment]
> some thoughts:
> 
> * consider removing the wiki if not used
> * maybe change the screenshot so a gif or demo video

Thanks for your review, I will definitely look into it.

**Comment by KendallDoesCoding** [comment]
Looks good

- make banner a little small in README.md
- Add a [security policy](https://github.com/rockingrohit9639/project-zone/security)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

Looks great some thoughts...
- great to see releases being used
- great README
- is the `.github/.workflows` needed?
