### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rockingrohit9639** [EddieHubCommunity/support#2162]
### Name

Rohit Saini

### Discord Username (if applicable)

Rohit Saini#1017

### Additional Context

Hi there, I am Rohit and I am following Eddie from a long time. I want to thank him for guiding everyone to contribute and encourage open source contributors I am also one of them. He is such an inspiration. I am an open-source enthusiast and I think this community would be perfect for me to grow more in the field of open source as there are already experienced members in the community.
It would be my great pleasure if I can join this community.

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @rockingrohit9639! We hope you learn more about open source and grow your skills. Only remember the most important thing: community first, code second! 😄👋🎉
