### ISSUE TITLE
[REVIEW] Owiin : Free & Open Source Enterprise Asset Management (EAM)

### ISSUE THREAD

**Issue by riadmennour** [EddieHubCommunity/support#2163]
### Project link

https://github.com/owiin/owiin

**Comment by schmelto** [comment]
Great work. Some thoughts:

* Hide wiki if not used
* provide some issue tempates
* Hide packages if not usef
* consider moving org.adempiere.base-*** files in a seperate folder (for example src dont know if this works)
* you also could remove the table of contents due github povides this feature now :)

Otherwise I really like it 
Greate Demo Gif 🚀

**Comment by starlightknown** [comment]
looks good but maybe you can add a quick start guide in the readme itself and maybe add some issue templates for users to raise issues ? otherwise looks good!

**Comment by Panquesito7** [comment]
Amazing! I liked how you've structured the code and how it's made. However, I do agree with what @schmelto and @starlightknown said. I also recommend removing the `Supporters` section in the readme and change it to `Contributors`. We can already see the stargazers and forkers directly on GitHub.

You can use something like this in your readme. I've used it and it looks cool.

<a href="https://github.com/EddieHubCommunity/support/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=EddieHubCommunity/support" />
</a>

**Comment by KendallDoesCoding** [comment]
Looks good

- There is a two line space between the logo and the next section in README.md, consider making it one or none for that matter, as I think its leaving a little extra space.
- You've made a tag, but not a release, so consider making a release as well.
- Hide wiki if not using
- Hide issues tab is not using
- Hide packages tab is not using
- Check out https://github.com/owiin/owiin/community

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- using releases 🎉 
- suggest hiding packages if not used
- suggest hiding wiki if not used
- GitHub now creates a table of contents, so can manually remove the existing one in the README
