### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by dipeshbabu** [EddieHubCommunity/support#2164]
### Name

Dipesh Babu

### Discord Username (if applicable)

dipesh.babu#3698

### Additional Context

I had heard about this community through the Eddie Jaoude's youtube channel and have been following it since a month. I hope joining into this community will make me more familiar with open sourcing. I will be pleased being part of this community.

**Comment by Panquesito7** [comment]
Welcome to the EddieHub community, @dipeshbabu! Happy you've joined us! 😄👋🎉
