### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/support#2168]
### Name

Sajal Gupta

### Additional Context

I came to know about EddieHub community from MLH hackathons. I heard they are doing some amazing stuff around open-source. Since I joined the community, everyone has been so helpful! Looking forward to join the EddiHub org on GitHub

**Comment by Panquesito7** [comment]
Welcome, @guptasajal411! We're glad you have learned new stuff with us and continue to keep getting involved! 😄👋🎉
