### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Simran-Gupta234** [EddieHubCommunity/support#2170]
### Name

Simran Gupta

### Discord Username (if applicable)

Simran#0909

### Additional Context

The first time, I saw Eddie on a youtube CodeForCause with Kunal Kushwaha. I got so much influence from him. 
I like this community and want to be part of this community because this is a very inclusive community and help beginners to learn.
Lastly, I love both slogans by Eddie. The first one is "Collaborate first and code second" and the second one is "Open Source is for everyone".

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @Simran-Gupta234! We hope you learn and grow your skills with us! 😄👋🎉
