### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by mrbuddhu** [EddieHubCommunity/support#2176]
### Name

Aryabhatta

### Discord Username (if applicable)

mrbuddhu#3967

### Additional Context

I found Eddie on Twitter. I want to be a part of this awesome community :)

**Comment by Panquesito7** [comment]
Welcome, @mrbuddhu, to EddieHub! We hope you learn more about open source and coding with us! 😄👋🎉
