### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by jpzs444** [EddieHubCommunity/support#2178]
### Name

Jose Paolo Indiongco

### Discord Username (if applicable)

jpzs444#5038

### Additional Context

I knew about the community from several posts on Twitter and a local organization that I'm a part of. I've heard good things about it in terms of open source, diversity, and collaborative work. Definitely looking forward to participating in productive activities on EddieHub!

**Comment by Panquesito7** [comment]
Welcome to EddieHub, @jpzs444! We hope you learn more and grow your skills with us! 😄👋🎉
