### ISSUE TITLE
Please add me to the organization.

### ISSUE THREAD

**Issue by maskmanlucifer** [EddieHubCommunity/support#2179]
### What would you like to share?

I want to join EddieHubCommunity

**Comment by Panquesito7** [comment]
Hey, @maskmanlucifer. We have an issue template for that. The bot will automatically invite you to the GitHub organization. Click [here](https://github.com/EddieHubCommunity/support/issues/new/choose) and choose the option below.

![image](https://user-images.githubusercontent.com/51391473/126003703-eeb1dcb7-d329-4da3-989a-50158048d016.png)

**Comment by Panquesito7** [comment]
@schmelto, can you close this issue, please? Thanks. 🙂
