### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by maskmanlucifer** [EddieHubCommunity/support#2180]
### Name

Aman Kumar Singh

### Additional Context

I found Eddie on one of my friends github profile.
I am a newbie in open source and i saw the profile review discussions in issues so i being a part of this organization  will really help me to improve myself.

**Comment by Panquesito7** [comment]
Welcome to the EddieHub community, @maskmanlucifer! We hope you learn more about open source and programming and grow your skills with us! 😄👋🎉
