### ISSUE TITLE
[REVIEW] OpenSource for Everyone

### ISSUE THREAD

**Issue by PulkitSinghDev** [EddieHubCommunity/support#2189]
### Project link

https://github.com/PulkitSinghDev/OpenSource-for-Everyone

**Comment by Panquesito7** [comment]
I quickly reviewed the repository, and overall it looks good, except for those weird skeletons 😅 IMO, they should be removed.

**Comment by PulkitSinghDev** [comment]
Hey @Panquesito7 , thanks!
I have added those skeletons just for making folks more friendly with the repository

**Comment by schmelto** [comment]
Consider removing the package and hiding the package

**Comment by KendallDoesCoding** [comment]
Looks good

- Hide wiki if not using
- Add security policy: https://github.com/PulkitSinghDev/OpenSource-for-Everyone/security
- Add contributing guidelines (Check out: https://github.com/PulkitSinghDev/OpenSource-for-Everyone/community)
- Add PR template (Check out: https://github.com/PulkitSinghDev/OpenSource-for-Everyone/community)

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- suggest hiding packages if not used
- missing contributing file
- hide wiki if not being used
