### ISSUE TITLE
[Review] VasudevJaiswal 

### ISSUE THREAD

**Issue by VasudevJaiswal** [EddieHubCommunity/support#2192]
### GitHub Profile Link

https://github.com/VasudevJaiswal

**Comment by Panquesito7** [comment]
Nice profile! I liked it a lot. I have made a [**pull request**](https://github.com/VasudevJaiswal/VasudevJaiswal/pull/1) in your README profile repository for some minor improvements. 🙂

Thank you for sharing your awesome profile with the community! 😄

**Comment by schmelto** [comment]
Duplicate Information on your profile:

![image](https://user-images.githubusercontent.com/30869493/129317768-9affcfa1-3f06-4745-b6b0-fd0ad10fd750.png)
![image](https://user-images.githubusercontent.com/30869493/129317790-c29aabcb-cc7b-4466-8d60-259b256f902c.png)
(last links on your profile)

**Comment by VasudevJaiswal** [comment]
YouTube review

**Comment by schmelto** [comment]
> YouTube review link

What do you mean by this?

**Comment by starlightknown** [comment]
> YouTube review link

I think they meant where will it be reviewed on youtube @schmelto 
https://www.youtube.com/user/eddiejaoude it'll be reviewed on this channel when Eddie does the live stream for reviews, press the bell icon and subscribe to get notified @VasudevJaiswal

**Comment by VasudevJaiswal** [comment]
@schmelto  Yes you understand what i want to say 😊

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] What's the GitHub icon above the about me section?
- [ ] Too many `<br>`/whitespace
- [ ] ` if you like what i do, maybe consider buying me a coffee/tea 🥺👉👈` can be plain text (to save space)

## Feedback
- [x] I personally like the sophisticated, minimal, and informative design ❤️ 
- [x] It is pretty informative and cool 😍 
- [x] You are a part of the EddieHub Org 🤩  

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by deepansharya1111** [comment]
Nice profile! It's great to see that you've put your coding profile URLs as well, along with the social ones. Let's connect on Twitter.

**Comment by eddiejaoude** [comment]
User blocked from Org
