### ISSUE TITLE
[REVIEW] FayasNoushad

### ISSUE THREAD

**Issue by FayasNoushad** [EddieHubCommunity/support#2204]
### GitHub Profile Link

https://github.com/FayasNoushad

**Comment by schmelto** [comment]
Hey @FayasNoushad nice profile.

I've made a PR https://github.com/FayasNoushad/FayasNoushad/pull/2
Otherwise I would recommend to remove the GitHub Badge in the "My Accounts" section due we are allready on your Github Profile.

**Comment by FayasNoushad** [comment]
> Hey @FayasNoushad nice profile.
> 
> I've made a PR [FayasNoushad/FayasNoushad#2](https://github.com/FayasNoushad/FayasNoushad/pull/2)
> Otherwise I would recommend to remove the GitHub Badge in the "My Accounts" section due we are allready on your Github Profile.

Done ✅, and thanks for your pull request.

**Comment by Panquesito7** [comment]
Wow, @FayasNoushad, amazing profile; I loved it! 🥳🎉
I've made a [**pull request**](https://github.com/FayasNoushad/FayasNoushad/pull/3) for some minor improvements. 🙂

Thanks for sharing your profile with the community! 😄

**Comment by SahityaRoy** [comment]
@FayasNoushad Hey dude you have a amazing profile i really like it plz go ahead

**Comment by FayasNoushad** [comment]
> Wow, @FayasNoushad, amazing profile; I loved it! 
> I've made a [**pull request**](https://github.com/FayasNoushad/FayasNoushad/pull/3) for some minor improvements. 
> 
> Thanks for sharing your profile with the community!

Done

**Comment by VasudevJaiswal** [comment]
Things added/changed:
I've made [Pull request ](https://github.com/FayasNoushad/FayasNoushad/pull/4) for Minor improvements in the README.md file.
All the changes are shown in the Git diff. If you have any questions/comments, let me know. 🙂

**Comment by FayasNoushad** [comment]
> @FayasNoushad
> Things added/changed:
> I've made [Pull request ](https://github.com/FayasNoushad/FayasNoushad/pull/4) for Minor improvements in the README.md file.
> All the changes are shown in the Git diff. If you have any questions/comments, let me know.

Merged 👍

**Comment by Panquesito7** [comment]
Your profile looks amazing! I love it! Surely a lot of people like it. 😄🥳🎉

**Comment by FayasNoushad** [comment]
> Your profile looks amazing! I love it! Surely a lot of people like it.

Thanks 😊

**Comment by VasudevJaiswal** [comment]
@FayasNoushad 
Awesome work! I liked the profile a lot! It'll be great when it's reviewed in a live stream. Great work! 😄🥳🎉

**Comment by FayasNoushad** [comment]
> @FayasNoushad
> Awesome work! I liked the profile a lot! It'll be great when it's reviewed in a live stream. Great work!

Hmm

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] I don't think having bullet points on the right and text on the center is good for readability (IMO it looks weird)
- [ ] Link the links like google maps, using `<a target="_blank">` to make it open on a new tab

## Feedback
- [x] Pretty cool that you link almost everything ❤️ 
- [x] I personally love it for being sophisticated, minimal, and informative
- [x] You are using all GitHub settings wisely 🤩 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by shreemaan-abhishek** [comment]
I really love how you have centered things at the beginning of the Readme.md.

Instead of saying `my accounts` you could replace it with `Connect with me`

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Really concise GitHub profile
- Very commit heavy, suggest doing code reviews as well
- Maybe a photo/banner would be a bit more creative


Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
