### ISSUE TITLE
[REVIEW] sahilcode17

### ISSUE THREAD

**Issue by sahilcode17** [EddieHubCommunity/support#2213]
### GitHub Profile Link

https://github.com/sahilcode17

**Comment by schmelto** [comment]
One thing from my side consider removing the profile views due those are inaccurate

**Comment by sahilcode17** [comment]
> One thing from my side consider removing the profile views due those are inaccurate
Ya, I was also thinking to remove it as it increases on my visit too, is there any other badge or something to measure profile engagement.

**Comment by Panquesito7** [comment]
Awesome profile! I liked it a lot. I have made a [**pull request**](https://github.com/sahilcode17/sahilcode17/pull/2) in your
repository for some minor improvements in the `README.md` file. 🙂

Thank you for sharing your profile with us! 😄

**Comment by Panquesito7** [comment]
> is there any other badge or something to measure profile engagement.

I think there are, but they are inaccurate too. GitHub should provide profile views with accurate numbers.

**Comment by sahilcode17** [comment]
@Panquesito7 I am glad you liked it. I have accepted your changes.

**Comment by Panquesito7** [comment]
Awesome work! I liked the profile a lot! It'll be great when it's reviewed in a live stream. Great work! 😄🥳🎉

**Comment by VasudevJaiswal** [comment]
@sahilcode17 
Things added/changed:
1. I've made  [Pull request ](https://github.com/sahilcode17/sahilcode17/pull/4) for Minor improvements in the README.md file.
2. All the changes are shown in the Git diff. If you have any questions/comments, let me know. 🙂
***
3. Thanks for sharing your profile with the community! 😄

**Comment by VasudevJaiswal** [comment]
Your profile looks amazing! I love it! Surely a lot of people like it. 😄🥳🎉

**Comment by sahilcode17** [comment]
Thanks, @VasudevJaiswal  for your contribution now my profile look more attractive.

**Comment by shreemaan-abhishek** [comment]
LGTM

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] I'll rather not be having three stats, most used languages can be removed
- [ ] The wave takes up some space and doesn't fit the theme, can be removed
- [ ] I'll use GitHub features, like bio, website, and Twitter (For the Bio make it informational)

## Feedback
- [x] Your profile sure gives a coding vibe ❤️ 
- [x] Love the night coder gif 😍 
- [x] Overall it is pretty cool 🤩 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by sahilcode17** [comment]
@krishdevdb thanks for the suggestion

**Comment by krishdevdb** [comment]
@sahilcode17 If you close the issue, it will not be able to be reviewed on a live stream, maybe you wanna reopen this?

**Comment by sahilcode17** [comment]
@krishdevdb oh thanks i was not aware about that and when this live stream happens?

**Comment by krishdevdb** [comment]
> @krishdevdb oh thanks i was not aware about that and when this live stream happens?

There is a weekly live stream, but not sure if it is going to be for the reviews. Many more topics are also there for live streams, so maybe we can ask Eddie about that :-)

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Recommend having a more professional profile picture
- Maybe look at contributing more to open source


Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
