### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Omkar0114** [EddieHubCommunity/support#2236]
### Name

Omkar Kulkarni

### Discord Username (if applicable)

rockzz#4715

### Additional Context

Hey, I Omkar Kulkarni currently a junior pursuing my bachelor's in AI and Data Science. I heard about your organization from a blog and it's a very cool and inspiring organization. I want to explore more about open source contributions and related things. And want to learn new things in daily life. Very excited to join the organization as soon as possible.

**Comment by krishdevdb** [comment]
Welcome @Omkar0114 🎉
