### ISSUE TITLE
[REVIEW] UmairJibran

### ISSUE THREAD

**Issue by UmairJibran** [EddieHubCommunity/support#2243]
### Portfolio link

https://umairjibran.com

#### Changes in Progress
https://polite-river-0640ed603-30.westeurope.azurestaticapps.net/

**NOTE**
If you can only review one (please do the one with changes in progress)

**Comment by ErrolFernandes** [comment]
Everything seems okay!but it would be good if you change the font of Ur name as it is not readable friendly.

**Comment by UmairJibran** [comment]
Thanks @ErrolFernandes I would do that ASAP!!

**Comment by Panquesito7** [comment]
Awesome portfolio! I really loved it ❤️ great work!

I just recommend making this part

![image](https://user-images.githubusercontent.com/51391473/131262482-f742bcd8-adac-4c73-aa6f-87fd020ca593.png)

look like

![image](https://user-images.githubusercontent.com/51391473/131262499-aaad1fb2-18e3-45c1-aafb-b27bbc2ac13b.png)

Thanks for sharing your awesome portfolio with the amazing community! 😄

**Comment by UmairJibran** [comment]
hey @Panquesito7 thanks for the suggestion, however, I would like to take another input from you as well.
my initial thoughts were having professional social/links and general socialising links separately.

do you think it was a good idea? I mean given that you noticed it, I suppose I should stick them up together.

**Comment by Panquesito7** [comment]
That sounds like a good idea! But I would like to make it look both like in the screenshot I showed. 🙂

**Comment by UmairJibran** [comment]
Thanks a lot @Panquesito7 I have added this in the TODO I will do them ASAP, hopefully by the end of the week, fingerscrossed

**Comment by emmalearnscode** [comment]
Nice design and a lot of it works really well. I tested with keyboard navigation and it's easy to move around your site. However, there are a few accessibility issues which you can pick up if you run a lighthouse test.

On the projects page I would suggest making all the cards the same size so it looks more uniform. Also, I'm unsure why you've hidden things away behind dropdowns on the education page. I'd suggest having them visible all the time as it avoids too many clicks which many people are adverse to.

**Comment by UmairJibran** [comment]
Thank you @emmalearnscode that is a very great idea, I will make them always expand on the education page, I am looking for some ideas because even though the current cards deliver the required info, I want to make them more pleasing.

**Comment by eddiejaoude** [comment]
Please share the github repo link

**Comment by eddiejaoude** [comment]
No GitHub link, going to close - please submit a new issue if you have a GitHub repo link
