### ISSUE TITLE
[REVIEW] vishalda

### ISSUE THREAD

**Issue by vishalda** [EddieHubCommunity/support#2286]
### GitHub Profile Link

https://github.com/vishalda

**Comment by Panquesito7** [comment]
Awesome profile! I liked it a lot. 😄👍 

I have made a [**pull request**](https://github.com/vishalda/vishalda/pull/1) in your repository for
some minor improvements in the `README.md` file.

Thanks for sharing your amazing profile with us! 😉

**Comment by schmelto** [comment]
with the changes of @Panquesito7 its looking really good for me 🚀

**Comment by KukretiShubham** [comment]
@schmelto agree

**Comment by vishalda** [comment]
> Awesome profile! I liked it a lot. smile+1
> 
> I have made a [**pull request**](https://github.com/vishalda/vishalda/pull/1) in your repository for
> some minor improvements in the `README.md` file.
> 
> Thanks for sharing your amazing profile with us! wink

Thank you for the pull request! 😄

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Animated heading does not work well in lightmode
- 100% commits, suggestion doing issues, pull requests and reviews

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
