### ISSUE TITLE
[REVIEW] Opentek

### ISSUE THREAD

**Issue by AnirudhPanda** [EddieHubCommunity/support#2290]
### Project link

https://github.com/Opentek-Org/opentek

**Comment by Panquesito7** [comment]
Woah, amazing project! I liked it so much! Congratulations. 😄👍
I recommend doing the following things:

- Disable the GitHub Wiki if it's not being used.
- [Verify the organization's domain](https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization).
- Add some issue templates (at least basic templates such as the bug and feature request) in the form version.
- Add a brief description of the organization in the organization's profile settings.
- Watch the repository to be informed of new commits, pull requests, issues, and more [here](https://github.com/Opentek-Org/opentek/watchers).
- Add more tags for people to find your repository easier.
- The project is missing a license. I would recommend using the [MIT](https://mit-license.org) license.

Overall, everything else is looking great! I've just
made some pull requests for minor improvements. 🙂

Thank you for sharing your awesome project with us! 😄

**Comment by AnirudhPanda** [comment]
Thanks for the amazing suggestions @Panquesito7

**Comment by KendallDoesCoding** [comment]
Amazing project, Love the UI

- make banner a little small in README.md
- add tags/releases (The releases tab is currently hidden, but I highly recommend you un-hide it and make some releases)

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Create a release/tag
- Missing image in README
- Demo title with no content looks a bit strange
- Make commit messages more descriptive 
- 

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
