### ISSUE TITLE
[REVIEW] xerexcoded

### ISSUE THREAD

**Issue by xerexcoded** [EddieHubCommunity/support#2292]
### GitHub Profile Link

https://github.com/xerexcoded

**Comment by Panquesito7** [comment]
Hey, @xerexcoded! Thanks for sharing your profile with us! 😄

I have made a [**pull request**](https://github.com/xerexcoded/xerexcoded/pull/1) for some minor
improvements in the `README.md` file. 🙂

**Comment by helper-uttam** [comment]
> ### GitHub Profile Link
> https://github.com/xerexcoded

hey @xerexcoded ! Thanks for sharing your GitHub profile with us, I liked it :)
but you can also make use of <anchor tag> while raising issues or PR to make your link looks more attractive and understandable.

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Suggest having a profile picture of you
- Too many titles with no content

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
