### ISSUE TITLE
[REVIEW] Uttam

### ISSUE THREAD

**Issue by helper-uttam** [EddieHubCommunity/support#2294]
### Portfolio link

- <a href="http://pubgofficial.me/myportfolio/"> here </a>

**Comment by helper-uttam** [comment]
Thanks bot, for the warn welcome! 💯 

What should I do now for getting into Github Organiztion 🤷‍♀️.  The mentioned link take me to collection of repo's and then I confused what should I do next 😢

**Comment by helper-uttam** [comment]
> Nice portfolio! I liked it a lot. 😄👍
> Just two things to consider in adding:
> 
> * Consider adding SSL to the website (use HTTPS instead of HTTP).
> * Add a favicon to the website to make it look better. 😎
> 
> Overall, everything else looks great! Thanks for sharing your portfolio with the community! 😄

I will do it for sure, thankyou so much for the suggestion.

**Comment by Panquesito7** [comment]
> What should I do now for getting into Github Organization

Click [here](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) to get an invite to the awesome [EddieHub](https://www.eddiehub.org)
organization. Let me know if you need any further help. 🙂

**Comment by helper-uttam** [comment]
@Panquesito7  You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️

**Comment by helper-uttam** [comment]
@Panquesito7 I tried enforcing the site from `http` to `https` but I can't tick the check box do it because on my GitHub pages it shows:-
 
 - [ ] Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS

Any idea how to configure my domain?

**Comment by VasudevJaiswal** [comment]
@helper-uttam 
1. Bro don't make this portfolio because it's look copy source code 
2. Not attractve  many user copy this source code of this website design

**Comment by KukretiShubham** [comment]
@helper-uttam hey, I liked it. Would suggest one thing. Don't use percentage to signify your level of knowledge. Afaik once Eddie suggested too that, other person don't know what % level is. Instead you can simply write your skills with logo's or badges.

**Comment by Panquesito7** [comment]
> @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️

That'd be great, thanks! 😄

**Comment by Panquesito7** [comment]
@helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄

**Comment by helper-uttam** [comment]
> @helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄


> > @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️
> 
> That'd be great, thanks! 😄

🙄🙄 can you share your twitter or anything else where we can connect 😅 as eddie Said open source is also about collaboration🤣

**Comment by Panquesito7** [comment]
> > @helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄
> 
> > > @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️
> > 
> > 
> > That'd be great, thanks! 😄
> 
> 🙄🙄 can you share your twitter or anything else where we can connect 😅 as eddie Said open source is also about collaboration🤣

My Twitter is in my GitHub profile. If you can't find it, it is `David_Leal_7`. 🙂

**Comment by helper-uttam** [comment]
> > > @helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄
> > 
> > 
> > > > @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️
> > > 
> > > 
> > > That'd be great, thanks! 😄
> > 
> > 
> > 🙄🙄 can you share your twitter or anything else where we can connect 😅 as eddie Said open source is also about collaboration🤣
> 
> My Twitter is in my GitHub profile. If you can't find it, it is `David_Leal_7`. 🙂

Done 😅 came to know you know devops 😅 can you please lemme know where should I start learning devops 😶 I don't even know, what is devops😪

**Comment by Panquesito7** [comment]
> > > > @helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄
> > > 
> > > 
> > > > > @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️
> > > > 
> > > > 
> > > > That'd be great, thanks! 😄
> > > 
> > > 
> > > 🙄🙄 can you share your twitter or anything else where we can connect 😅 as eddie Said open source is also about collaboration🤣
> > 
> > 
> > My Twitter is in my GitHub profile. If you can't find it, it is `David_Leal_7`. 🙂
> 
> Done 😅 came to know you know devops 😅 can you please lemme know where should I start learning devops 😶 I don't even know, what is devops😪

Let's move this conversation to another place. If you have Discord, you should join the EddieHub [Discord server](http://discord.eddiehub.org) and ask for help there. 🙂

**Comment by helper-uttam** [comment]
> @helper-uttam hey, I liked it. Would suggest one thing. Don't use percentage to signify your level of knowledge. Afaik once Eddie suggested too that, other person may not know what % level is. Instead you can simply write your skills with logo's or badges.

Hi shubham, I'll update that for sure🤥 thankyou so much for sharing that

**Comment by helper-uttam** [comment]
> > > > > @helper-uttam, I really liked your portfolio. I would recommend re-opening this issue; so it gets reviewed in a live stream! 😄
> > > > 
> > > > 
> > > > > > @Panquesito7 You are just insane , thankyou for you quick assistance :) I'll be glad if we can connect on LinkedIn or twitter , if you don't mind.🤷‍♀️
> > > > > 
> > > > > 
> > > > > That'd be great, thanks! 😄
> > > > 
> > > > 
> > > > 🙄🙄 can you share your twitter or anything else where we can connect 😅 as eddie Said open source is also about collaboration🤣
> > > 
> > > 
> > > My Twitter is in my GitHub profile. If you can't find it, it is `David_Leal_7`. 🙂
> > 
> > 
> > Done 😅 came to know you know devops 😅 can you please lemme know where should I start learning devops 😶 I don't even know, what is devops😪
> 
> Let's move this conversation to another place. If you have Discord, you should join the EddieHub [Discord server](http://discord.eddiehub.org) and ask for help there. 🙂

I m thinking the same 🤣 I am already there on eddiehub but its late night here 🥴 and I had not installed discord on my phone, can i msg you in twitter? Else I will reach you tomorrw (timezone IST) 🤣

**Comment by schmelto** [comment]
Take a look here
![image](https://user-images.githubusercontent.com/30869493/131911316-79a604fe-f110-42ac-befd-ba6547c8e7fa.png)

the email field is missing on scroll down

**Comment by helper-uttam** [comment]
> Take a look here
> ![image](https://user-images.githubusercontent.com/30869493/131911316-79a604fe-f110-42ac-befd-ba6547c8e7fa.png)
> 
> the email field is missing on scroll down

Hey, @schmelto ,
Thankyou for pointing out that.
🤷‍♂️🤷‍♂️🤷‍♂️ try reloading the web page, I'll look after this in some time and fix this.

**Comment by VasudevJaiswal** [comment]
Dear members 
क्या नशा किए हो ये copy paste lagti hai portfolio

**Comment by helper-uttam** [comment]
> Dear members
> क्या नशा किए हो ये copy paste lagti hai portfolio

yes bro but I made little changes and connected to database and don't worry I'm gonna edit this more

**Comment by VasudevJaiswal** [comment]
@helper-uttam 
भाई अब तुमने कही सही बात मतलब सब तारीफ pr tarif किए जा रहे हैं ये तो देखो कमी क्या है ।
और First Page change kro pehle

**Comment by KukretiShubham** [comment]
@VasudevJaiswal I don't think this is the correct way of communication. Giving your opinion is okay and kindly use inclusive language it helps others to get involved 🙂 
Thanks you

**Comment by VasudevJaiswal** [comment]
@KukretiShubham 
Sorry bro for that

**Comment by KukretiShubham** [comment]
Hey @VasudevJaiswal , do you want to practice open source & inclusive culture? Join EddieHub [discord server](https://discord.gg/FvuDGC9Hh2) Also, every Saturday, we do public speaking sessions on discord & we practice our speaking skills. You can join us 🙂

**Comment by FayasNoushad** [comment]
Like @Saadpasta's portfolio

**Comment by FayasNoushad** [comment]
Why closed this issue?

**Comment by helper-uttam** [comment]
> Why closed this issue?

Should I keep open this forever? I mean issue can't be forever🤷‍♀️🤷‍♀️ I am thinking to put my GitHub under review. What do you think?

**Comment by FayasNoushad** [comment]
Re Open. No problem. Wait for some days for live stream.

**Comment by helper-uttam** [comment]
> Re Open. No problem. Wait for some days for live stream.

Opened! Please review my GitHub too I had updated the issue.

**Comment by Panquesito7** [comment]
> > Re Open. No problem. Wait for some days for live stream.
> 
> Opened! Please review my GitHub too I had updated the issue.

Please make a separate issue for reviewing your GitHub profile. 🙂

**Comment by helper-uttam** [comment]
> > > Re Open. No problem. Wait for some days for live stream.
> > 
> > 
> > Opened! Please review my GitHub too I had updated the issue.
> 
> Please make a separate issue for reviewing your GitHub profile. 🙂

done!

**Comment by helper-uttam** [comment]
please refer to  #2443 . I had raised a new review issue there :)
