### ISSUE TITLE
[REVIEW] sumitmukharjeeeeee

### ISSUE THREAD

**Issue by sumitmukharjeeeeee** [EddieHubCommunity/support#2297]
### GitHub Profile Link

https://github.com/sumitmukharjeeeeee

**Comment by VasudevJaiswal** [comment]
@sumitmukharjeeeeee 
Things added/changed:
1. I've made  [Pull request ](https://github.com/sumitmukharjeeeeee/sumitmukharjeeeeee/pull/2) for Minor improvements in the README.md file.
2. All the changes are shown in the Git diff. If you have any questions/comments, let me know. 🙂
***
3. Thanks for sharing your profile with the community! 😄

**Comment by Panquesito7** [comment]
@sumitmukharjeeeeee, if you close this issue, your profile won't be reviewed in a live stream. I recommend to re-open it. 🙂
