### ISSUE TITLE
[REVIEW] Dopefolio - Portfolio Template for Developers

### ISSUE THREAD

**Issue by rammcodes** [EddieHubCommunity/support#2303]
### Project link

https://github.com/rammcodes/Dopefolio

**Comment by Panquesito7** [comment]
Awesome project! I loved it! 😄👍
I recommend doing the following things:

- Disable the GitHub Wiki if it's not being used.
- Add some issue templates (at least basic templates such as the bug and feature request) in the form version.
- Add a bit more tags for people to find your repository easier.
- Try to share your project more with the people you know and on Twitter. That will make it more popular.

Overall, everything else is looking great! I've just
made some pull requests for minor improvements. 🙂

Thank you for sharing Dopefolio with us! I really liked it. 😃

**Comment by schmelto** [comment]
Agree with @Panquesito7 points :)

**Comment by rammcodes** [comment]
Hey @Panquesito7 , Thank you so much for taking your time to review my project and pointing out those important issues. I will make sure to fix those issues as soon as possible. Thank you once again for helping me 😇❤️

**Comment by KendallDoesCoding** [comment]
Agree with @Panquesito7 's points.

Further,

- add security policy https://github.com/rammcodes/Dopefolio/security
- Have a look https://github.com/rammcodes/Dopefolio/community

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Create a release/tag
- Hide packages if not being used
- Lots of great documentation, but makes the README very long, suggest moving the details to the docs folder
- Highly recommend having a Code of Conduct

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
