### ISSUE TITLE
[BUG] remove introduction in discord reamde

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#2306]
### Description of the bug

Remove Line 42 in the discord-readme.md due this channel is no longer available,

https://github.com/EddieHubCommunity/support/blame/main/discord-readme.md#L42

**Comment by Guannan-Shen** [comment]
I am happy to take this, and it would be my first contribution to a opensource project.

**Comment by schmelto** [comment]
@Guannan-Shen I've assigned you to the issue please let us know if you need any help

**Comment by Guannan-Shen** [comment]
Thank you so much, I really appreciate it.

**Comment by suryablaster** [comment]
i want to do it

**Comment by schmelto** [comment]
Closed in #2311
