### ISSUE TITLE
[REVIEW] Sin-Sumit

### ISSUE THREAD

**Issue by Sin-Sumit** [EddieHubCommunity/support#2312]
### GitHub Profile Link

https://github.com/Sin-Sumit

**Comment by Panquesito7** [comment]
Awesome profile, @Sin-Sumit! I liked it a lot! 😄👍

I have made a [**pull request**](https://github.com/Sin-Sumit/Sin-Sumit/pull/1) in your repository for
some minor improvements in the `README.md` file.

Thanks for sharing your amazing profile with the community! 😉

**Comment by VasudevJaiswal** [comment]
@Sin-Sumit   
Things added/changed:
1. I've made  [Pull request ](https://github.com/Sin-Sumit/Sin-Sumit/pull/2) for Minor improvements in the README.md file.
2. All the changes are shown in the Git diff. If you have any questions/comments, let me know. 🙂
***
3. Thanks for sharing your profile with the community! 😄

**Comment by FayasNoushad** [comment]
Ohh! Looking good.

**Comment by FayasNoushad** [comment]
Please merge my [pull request](https://github.com/Sin-Sumit/Sin-Sumit/pull/3) for some improvements.

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Animated gif is used a lot already
- All sections have emojis suggest adding one to `My Experiences`
- Need some more green squares 😉 

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
