### ISSUE TITLE
[Review] Zeel codder

### ISSUE THREAD

**Issue by zeel-codder** [EddieHubCommunity/support#2315]
### Portfolio link

https://zeelcodder.tech/me/zeel
Code : https://github.com/zeel-codder/MyWebSitNextjs

**Comment by schmelto** [comment]
![Screenshot_20210905_211822_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/132138845-8a38dab4-994d-46d5-8a74-af294dbad7b0.jpg)

Take a look at the alignment here

**Comment by zeel-codder** [comment]
oh, Thanks. I will Fix It.
Thank You 😇

**Comment by emmalearnscode** [comment]
Nice clean design which works well on both mobile and desktop.

A few suggestions:
- run a lighthouse check and fix the errors it flags
- your links in the navigation are not reachable with the keyboard ie I can't tab to them
- some of the animations are a little overwhelming, is it possible to reduce how much everything moves?

**Comment by KendallDoesCoding** [comment]
Repo Wise:

- hide wiki if not using
- add security policy, refer https://github.com/zeel-codder/MyWebSite/security
- take a look at https://github.com/zeel-codder/MyWebSite/community

Website Wise:
- It is currently "zeel" it should be "Zeel".

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- hide packages if not being used
- README is missing quickstart ...
- Hide wiki tab if not using
- Add Code of Conduct and License
- `.vscode` should probably not be added to repo
- commit messages could be improved

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
