### ISSUE TITLE
[REVIEW] BADSHAH-AMAN 

### ISSUE THREAD

**Issue by BADSHAH-AMAN** [EddieHubCommunity/support#2316]
### GitHub Profile Link

https://github.com/BADSHAH-AMAN

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- Great profile picture, professional but still relaxed
- visitor count I don't think adds value
- Profile is a bit long, can you shorten, so they can get to the code section
- Maybe reduce the animations
