### ISSUE TITLE
[REVIEW]Salonee-Jain

### ISSUE THREAD

**Issue by Salonee-Jain** [EddieHubCommunity/support#2318]
### Portfolio link

https://github.com/Salonee-Jain/Salonee-Jain

**Comment by Panquesito7** [comment]
Great profile! I liked how you made it simple, concise, and short. It looks great! 😄👍
I just made a [**pull request**](https://github.com/Salonee-Jain/Salonee-Jain/pull/2) to add a missing comma where you introduced yourself. 🙂

Thank you for sharing your profile with us! 😃

**Comment by schmelto** [comment]
Made also a little pr for you https://github.com/Salonee-Jain/Salonee-Jain/pull/3

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- Great you have a profile picture, maybe use the one from Twitter as it is clearer
- Suggest moving animated green square gif into hidden `details` section and move out of hidden section the `What I am currently learning / improving on` and `Get in touch`
