### ISSUE TITLE
[REVIEW] Blogit!

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/support#2319]
### Project link

https://github.com/guptasajal411/blogit

Check out the deploy on Heroku as well! https://try-blogit.herokuapp.com/

**Comment by rohan-kulkarni-25** [comment]
- Can increase Issue lables 
- Can convert the how it works to  point wise as this will help in getting it more easily

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- maybe reduce the repo description size
- readme is great! animated gif and video with you in it look great 🔥 
- suggest adding a linter, then also adding to GitHub Action
