### ISSUE TITLE
[REVIEW] iatharva (What should I use to implement blogs in this?)

### ISSUE THREAD

**Issue by iatharva** [EddieHubCommunity/support#2320]
### Portfolio link

https://iatharva.github.io/

**Comment by rohan-kulkarni-25** [comment]
- the view more button in project is not working 
- Can increase the font size of heading as this will help in highlighting 
- Can increase the social logo size little bit 
- Can add logo of languages ( totally upto you ) 

Check padding you can always keep extra padding so you don't get anything hidden 
![Screenshot from 2021-09-03 22-48-23](https://user-images.githubusercontent.com/76584243/132043897-608e419b-bbd8-47a4-8ea7-6e34d85c245f.png)

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- Personal projects: links do not work, link could be on the title
- Langauges/tools/frameworks, seem like links but do not work
- Great colours and style, maybe make a bit bigger
-
