### ISSUE TITLE
[REVIEW] iatharva

### ISSUE THREAD

**Issue by iatharva** [EddieHubCommunity/support#2321]
### GitHub Profile Link

https://github.com/iatharva

**Comment by Panquesito7** [comment]
Great profile! I liked it a lot! 😄👍 

I have made a [**pull request**](https://github.com/iatharva/iatharva/pull/1) in your repository
for minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 😄

**Comment by schmelto** [comment]
Awsome GIF 🚀

**Comment by iatharva** [comment]
Thanks :)

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- Maybe use the profile picture from your website for your GitHub profile image
- I am not keen on profile views, suggest removing
- Suggest removing the animate green square snake image and also 1 widget, so there is only 1 line of widgets as this takes longer for people to see the rest of your profile

**Comment by iatharva** [comment]
Thanks a lot, really appreciate the feedback!
