### ISSUE TITLE
[REVIEW] shreyaansjain

### ISSUE THREAD

**Issue by shreyaansjain06** [EddieHubCommunity/support#2322]
### GitHub Profile Link

https://github.com/shreyaansjain06

**Comment by Panquesito7** [comment]
Great profile! I liked how you keep it simple, short, and concise. 😄👍

I have made a [**pull request**](https://github.com/shreyaansjain/shreyaansjain/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thanks for sharing your awesome profile with us! 😉

**Comment by FayasNoushad** [comment]
Add a space before `|`.

**Comment by FayasNoushad** [comment]
> Add a space before `|`.

In description

**Comment by shreyaansjain** [comment]
I have updated my profile please review it now

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- animated gif appears broken on Safari
- big contribution graph, highlights more the bad stuff, suggest removing
