### ISSUE TITLE
[REVIEW] Dev Jain (889-dj)

### ISSUE THREAD

**Issue by 889-dj** [EddieHubCommunity/support#2323]
### GitHub Profile Link

https://github.com/889-dj

**Comment by helper-uttam** [comment]
hey dev! your github profile was really awesome and I liked it a lot

**Comment by Panquesito7** [comment]
Nice profile, @889-dj! I liked it a lot! 😄👍

I have made a [**pull request**](https://github.com/889-dj/889-dj/pull/1) in your repository
for minor improvements in the `README.md` file. 🙂

Thanks for sharing your profile with us! 😉

**Comment by FayasNoushad** [comment]
Email icon not visible in dark mode. Change icon colour or add border.

**Comment by 889-dj** [comment]
> hey dev! your github profile was really awesome and I liked it a lot

thanks a lot @helper-uttam 😃

**Comment by FayasNoushad** [comment]
Please merge [this](https://github.com/889-dj/889-dj/pull/2)

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- I think profile view counter is not useful
- widgets are on 2 lines, suggest removing 1 widget and having it on 1 line
- Suggest being consistent on naming ` I am currently learning Node Js, expressjs and DOCKER`
