### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by zeeshanmahar007** [EddieHubCommunity/support#2324]
### Portfolio link

https://maharzeeshan.me

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- not much feedback, looks great!
- maybe reduce social badges at the top, and have the most important ones there and the rest lower down

**Comment by zeeshanmahar007** [comment]
Thank you so much for your feedback 🙂
