### ISSUE TITLE
[REVIEW] zeeshanmahar007

### ISSUE THREAD

**Issue by zeeshanmahar007** [EddieHubCommunity/support#2326]
### GitHub Profile Link

https://github.com/zeeshanmahar007

**Comment by Panquesito7** [comment]
Awesome profile! I liked it a lot. 😄👍

I have made a [**pull request**](https://github.com/zeeshanmahar007/zeeshanmahar007/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your profile with us! 😉

**Comment by zeeshanmahar007** [comment]
Yes I just merge it. Thank you again for your feedback.

**Comment by helper-uttam** [comment]
awesome! Keep it up :)

**Comment by zeeshanmahar007** [comment]
> awesome! Keep it up :)

Thank you :)

**Comment by FayasNoushad** [comment]
Please squash merge [this](https://github.com/zeeshanmahar007/zeeshanmahar007/pull/2)

**Comment by FayasNoushad** [comment]
[Connect with me](https://github.com/zeeshanmahar007#connect-with-me) icons not visible in dark mode. Please change the colour or add border.
