### ISSUE TITLE
[REVIEW] KukretiShubham

### ISSUE THREAD

**Issue by KukretiShubham** [EddieHubCommunity/support#2330]
### GitHub Profile Link

https://github.com/KukretiShubham

**Comment by rohan-kulkarni-25** [comment]
- Try to add somethings more about you 
- You can add about your projects and explain them a bit
- Can arrange the card side by side with help of table 
![Screenshot from 2021-09-03 23-02-17](https://user-images.githubusercontent.com/76584243/132045153-590e8c11-ab5e-4f10-ba21-69e7a73192ea.png)

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- type writer effect (svg) not shown in safari
-  try to make more use of the space, widgets could be side by side
- 91% commits, try to get some code reviews and pull request
