### ISSUE TITLE
[REVIEW] Raju Ghorai

### ISSUE THREAD

**Issue by coderj001** [EddieHubCommunity/support#2332]
### Github Profile link

https://github.com/coderj001

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- try to do some code reviews and pull requests
- I think visitors counter badge is not great
- separate in categories for langauges and tools
- try to make more use of the white space on the right hand side
-

**Comment by coderj001** [comment]
thank you for reviewing my profile
