### ISSUE TITLE
[REVIEW] Vijay Jaisankar

### ISSUE THREAD

**Issue by vijay-jaisankar** [EddieHubCommunity/support#2334]
### Portfolio link

https://vijay-jaisankar.github.io/

**Comment by vijay-jaisankar** [comment]
It isn't responsive - but I'll love feedback on this :)

**Comment by eddiejaoude** [comment]
Reviewed with the awesome EddieHub on live stream https://www.youtube.com/watch?v=e5EDm9S3m-4

Looks good, here are some thoughts:
- project section, colours and font are difficult to read
- the name/logo animate is very cool
