### ISSUE TITLE
[REVIEW] mohitmishra786

### ISSUE THREAD

**Issue by mohitmishra786** [EddieHubCommunity/support#2340]
### GitHub Profile Link

https://github.com/mohitmishra786

**Comment by FayasNoushad** [comment]
Nice 👍

**Comment by mohitmishra786** [comment]
If i can work on something to improve my profile do let me know, i am always ready to learn new stuffs.

**Comment by FayasNoushad** [comment]
Please merge [this](https://github.com/mohitmishra786/mohitmishra786/pull/1) pull request.

**Comment by FayasNoushad** [comment]
**Use this:**

<p align="center">
    <img width="49%" src="https://github-readme-stats.vercel.app/api?username=mohitmishra786&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight&custom_title=GitHub+Stats"/>
    <img width="49%" src="https://github-readme-streak-stats.herokuapp.com?user=mohitmishra786&theme=tokyonight"/>
</p>

**Comment by schmelto** [comment]
Maybe take a look at the failing github action otherwise I like your profile

**Comment by Panquesito7** [comment]
Apart from what @FayasNoushad and @schmelto said, everything is looking great! 😄👍

**Comment by mohitmishra786** [comment]
> Maybe take a look at the failing GitHub action otherwise I like your profile

actually, I am not able to understand why they are falling , can you help me out with that

**Comment by Panquesito7** [comment]
> > Maybe take a look at the failing GitHub action otherwise I like your profile
> 
> actually, I am not able to understand why they are falling, can you help me out with that

I think you should remove that action; it is not needed. 🙂

**Comment by mohitmishra786** [comment]
> > > Maybe take a look at the failing GitHub action otherwise I like your profile
> > 
> > 
> > actually, I am not able to understand why they are falling, can you help me out with that
> 
> I think you should remove that action; it is not needed. 🙂

i also don't knew how to remove them

**Comment by Panquesito7** [comment]
> i also don't knew how to remove them

Made a [**pull request**](https://github.com/mohitmishra786/mohitmishra786/pull/2) to fix that. 🙂

**Comment by mohitmishra786** [comment]
> > i also don't knew how to remove them
> 
> Made a [**pull request**](https://github.com/mohitmishra786/mohitmishra786/pull/2) to fix that. 🙂

Thanks, I do have merged it but can you tell me that what does it mean , I mean after merging if I will make any changes will it not go inside workflow run

**Comment by Panquesito7** [comment]
> > > i also don't knew how to remove them
> > 
> > 
> > Made a [**pull request**](https://github.com/mohitmishra786/mohitmishra786/pull/2) to fix that. 🙂
> 
> Thanks, I do have merged it but can you tell me that what does it mean , I mean after merging if I will make any changes will it not go inside workflow run

After merging, the workflow should be gone and my changes would be implemented now. 🙂

**Comment by ShehanMaduwantha** [comment]
It looks cool
