### ISSUE TITLE
[REVIEW] SarveshLimaye

### ISSUE THREAD

**Issue by SarveshLimaye** [EddieHubCommunity/support#2342]
### GitHub Profile Link

https://github.com/SarveshLimaye

**Comment by FayasNoushad** [comment]
Nice. My suggestion :- Add `---` before and after a paragraph.

**Comment by SarveshLimaye** [comment]
@FayasNoushad Thank you for the suggestion. I will surely implement it.

**Comment by Panquesito7** [comment]
Hey, @SarveshLimaye! I liked your profile a lot; good work! 😄👍

I have made a [**pull request**](https://github.com/SarveshLimaye/SarveshLimaye/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile! 😄

**Comment by SarveshLimaye** [comment]
@Panquesito7 Thank you for the pr. 🙂 
I  am really glad that you liked my profile.

**Comment by schmelto** [comment]
I would suggest centering the connect with me badges

**Comment by SarveshLimaye** [comment]
@schmelto Done. Thanks for the suggestion. 🙂

**Comment by eddiejaoude** [comment]
Looks greats 👍  Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- remove/hide some of the graphs
- try to do some more code reviews
