### ISSUE TITLE
[REVIEW] dth99

### ISSUE THREAD

**Issue by dth99** [EddieHubCommunity/support#2343]
### Portfolio link

https://github.com/dth99

**Comment by FayasNoushad** [comment]
- Add GitHub profile photo
- Add GitHub profile README.md
- Join [Eddie Hub Community](https://github.com/EddieHubCommunity)

**Comment by dth99** [comment]
>     * Add GitHub profile photo
> 
>     * Add GitHub profile README.md
> 
>     * Join [Eddie Hub Community](https://github.com/EddieHubCommunity)

Done

**Comment by dth99** [comment]
> # It's great having you contribute to this project
> Welcome to the community nerd_face
> 
> If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](http://discord.eddiehub.org) and our [GitHub Organisation](http://github.eddiehub.org) - we help and encourage each other to contribute to open source little and often nerd_face . Any questions let us know.

done

**Comment by FayasNoushad** [comment]
- Add bio, twitter username, link, organization etc.

**Comment by helper-uttam** [comment]
> * Add bio, twitter username, link, organization etc.

Hey deepak, nice github profile! I had made a PR to your's readme. :) hope you liked it

**Comment by dth99** [comment]
> > * Add bio, twitter username, link, organization etc.
> 
> Hey deepak, nice github profile! I had made a PR to your's readme. :) hope you liked it

Yes, I really liked it. Thank you so much

**Comment by dth99** [comment]
>     * Add bio, twitter username, link, organization etc.

I will do it sooner.

**Comment by schmelto** [comment]
One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page

**Comment by FayasNoushad** [comment]
> One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page

Yeah it's a good suggestion. So many github users added in their github profile README.md.

**Comment by dth99** [comment]
> > One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page
> 
> Yeah it's a good suggestion. So many github users added in their github profile README.md.



> One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page

But it's look good to me.

**Comment by FayasNoushad** [comment]
> > > One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page
> > 
> > 
> > Yeah it's a good suggestion. So many github users added in their github profile README.md.
> 
> > One thing from my side consider removing the profile views count due it's inaccurate due it's coining every reload of the page
> 
> But it's look good to me.

No problem, its your personal.

**Comment by Panquesito7** [comment]
Awesome! You're already getting a lot of great feedback! I also liked your profile a lot. 😄👍

I have made a [**pull request**](https://github.com/dth99/dth99/pull/2) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 😉

**Comment by dth99** [comment]
Thank you for your work.

**Comment by schmelto** [comment]
Nice profile!

**Comment by dth99** [comment]
> Nice profile!

thank you bro
