### ISSUE TITLE
[REVIEW] helper-uttam

### ISSUE THREAD

**Issue by helper-uttam** [EddieHubCommunity/support#2347]
### GitHub Profile Link

https://github.com/helper-uttam

**Comment by Panquesito7** [comment]
Great profile, @helper-uttam! I liked it a lot. 😄👍

I have made a [**pull request**](https://github.com/helper-uttam/helper-uttam/pull/2) in your repository for
some minor improvements in the `README.md` file. 🙂

Thanks for sharing your profile with the community! 😉

**Comment by helper-uttam** [comment]
> Great profile, @helper-uttam! I liked it a lot. 😄👍
> 
> I have made a [**pull request**](https://github.com/helper-uttam/helper-uttam/pull/2) in your repository for
> some minor improvements in the `README.md` file. 🙂
> 
> Thanks for sharing your profile with the community! 😉

Thankyou for reviewing :)

**Comment by eddiejaoude** [comment]
Looks greats 👍  Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- pinned repos to have descriptions
- suggest only pinning 4 repos
- I think the 1st banner doesn't work in safari
