### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by suman-somu** [EddieHubCommunity/support#2352]
### What would you like to share?

invite me to the GitHub Community Org

**Comment by FayasNoushad** [comment]
Click here :- https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

**Comment by Panquesito7** [comment]
Hey, @suman-somu. We have an issue template for that. The bot will automatically invite you to the GitHub organization. Click [here](https://github.com/EddieHubCommunity/support/issues/new/choose) and choose the option below.

![image](https://user-images.githubusercontent.com/51391473/126003703-eeb1dcb7-d329-4da3-989a-50158048d016.png)
