### ISSUE TITLE
[REVIEW] AbhijithGanesh

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/support#2362]
### GitHub Profile Link

https://github.com/AbhijithGanesh

**Comment by FayasNoushad** [comment]
- Change `Chennai` to `Chennai, Tamil Nadu, India`.
- `Languages & Frameworks`, `Tools`, and `How to reach me` photo buttons not centered.

**Comment by FayasNoushad** [comment]
`Github Stats` not centered

**Comment by schmelto** [comment]
Agree with @FayasNoushad

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- Duplicate logo, suggest having a banner and profile pic of you
- "how to reach me" badges could be in 1 line to save vertical space
- Suggest having less commits and more of the other contributions

**Comment by AbhijithGanesh** [comment]
Thanks Eddie
