### ISSUE TITLE
[REVIEW] Mark-up-Portfolio

### ISSUE THREAD

**Issue by Aditya664** [EddieHubCommunity/support#2371]
### Portfolio link
Check out my portfolio website is created with just markdown language.

http://aditya-deshmukh.me/Mark-up-Portfolio/

**Comment by helper-uttam** [comment]
> ### Portfolio link
> Check out my portfolio website is created with just markdown language.
> 
> http://aditya-deshmukh.me/Mark-up-Portfolio/

Hey there! awesome portfolio. Thanks for sharing <3

**Comment by Aditya664** [comment]
@helper-uttam thanks man

**Comment by emmalearnscode** [comment]
Love the design, it's great! the only thing that really stood out that you could improve was the skills page where all of the icons are very close together so it's hard to focus on anything among the sea of icons.

**Comment by eddiejaoude** [comment]
No GitHub link, going to close - please submit a new issue if you have a GitHub repo link
