### ISSUE TITLE
[REVIEW] 0x30c4

### ISSUE THREAD

**Issue by 0x30c4** [EddieHubCommunity/support#2377]
### Portfolio link

https://0x30c4.github.io/

**Comment by schmelto** [comment]
![Screenshot_20210910_002052.jpg](https://user-images.githubusercontent.com/30869493/132770199-ec326a37-59f3-41f0-80ab-62cb9a066716.jpg) take a closer look here on mobile view

**Comment by mohitmishra786** [comment]
Looks fine

**Comment by FayasNoushad** [comment]
> ![Screenshot_20210910_002052.jpg](https://user-images.githubusercontent.com/30869493/132770199-ec326a37-59f3-41f0-80ab-62cb9a066716.jpg) take a closer look here on mobile view

Not better in mobile.

**Comment by emmalearnscode** [comment]
Maybe take a look at the skills section on mobile, it's not all fitting on the screen as it should.

**Comment by emmalearnscode** [comment]
Also, you're getting some console errors because the google font api needs to be https instead of http so the fonts aren't loading correctly.

**Comment by 0x30c4** [comment]
Thank you for your review.
@emmalearnscode Currently I am working on my portfolio, I am rebuilding it and trying to do something new.

**Comment by KendallDoesCoding** [comment]
Looks good but on my end it's a little buggy and laggy, it may just be me though!

**Comment by 0x30c4** [comment]
@KendallDoesCoding no it's not only you basically everyone is having the same problem.
So, I'm now rebuilding my portfolio from scratch

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding no it's not only you basically everyone is having the same problem. So, I'm now rebuilding my portfolio from scratch

Ok cool!

**Comment by KendallDoesCoding** [comment]
btw please share the repo link of the portfolio in the description as eddie likes vieweing the code more than the portfolio usually.

**Comment by 0x30c4** [comment]
https://github.com/0x30c4/0x30c4.github.io

**Comment by KendallDoesCoding** [comment]
> Looks good but on my end it's a little buggy and laggy, it may just be me though!

This issue doesn't occur on my laptop though.

**Comment by 0x30c4** [comment]
can you share a ss?

**Comment by KendallDoesCodingAlt1** [comment]
> Reference in new i

of what?

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=yK-NLKZ8cHU

Looks great, some suggestions...
Portfolio
- have the YouTube link displayed as the full YouTube url (same with Twitter link)
- progress bars are not a great display of skills/experience
- suggest including GitHub pull requests / repos anything display your real world experience
- about me to have more information

Repo
- add screenshot to the README
- add link to the repo settings under description
- quickstart guide

**Comment by 0x30c4** [comment]
Thanks for your kind review.
