### ISSUE TITLE
[REVIEW] Jassi10000

### ISSUE THREAD

**Issue by Jassi10000** [EddieHubCommunity/support#2415]
### GitHub Profile Link

https://github.com/Jassi10000

**Comment by schmelto** [comment]
https://github.com/Jassi10000/jas/blob/master/background.PNG

Not found

**Comment by Jassi10000** [comment]
Thanks for telling 
Now Check !!

**Comment by FayasNoushad** [comment]
> ### GitHub Profile Link
> https://github.com/Jassi10000

Singh is King

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- The page is quite long, suggest reducing the length
- Suggest removing visitor counter
-
