### ISSUE TITLE
[REVIEW] Krishnapro

### ISSUE THREAD

**Issue by Krishnapro** [EddieHubCommunity/support#2418]
### GitHub Profile Link

https://github.com/Krishnapro

**Comment by Panquesito7** [comment]
Great profile, @Krishnapro! I liked it a lot! 😄👍

I have made a [**pull request**](https://github.com/Krishnapro/Krishnapro/pull/24) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 🚀

**Comment by schmelto** [comment]
Suggest removing the profile view count and duplicate information as the linkedin badges

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- suggest removing the visitor counter as it doesn't add value
- pinning even number of repos (2 or 4) is best to make use of the space
- banner doesn't work well in Safari
