### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Krishnapro** [EddieHubCommunity/support#2420]
### Name

Krishna Kumar

### Discord Username (if applicable)

Krishn#3230

### Additional Context

I like that "collaboration 1st code 2nd ". Because collation is very important part for newbie in tech field.

**Comment by Panquesito7** [comment]
> Hi Eddie..
> Kindly add me to the organization

Hey, @amreekminocha. We have an issue template for that. The bot will automatically invite you to the GitHub organization. Click [here](https://github.com/EddieHubCommunity/support/issues/new/choose) and choose the option below.

![image](https://user-images.githubusercontent.com/51391473/126003703-eeb1dcb7-d329-4da3-989a-50158048d016.png)

**Comment by FayasNoushad** [comment]
Click here -> https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

**Comment by schmelto** [comment]
Don't know why it's not working normally with the label it should work..

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/support/actions/runs/1243314912

**Comment by Panquesito7** [comment]
They're already part of the organization. @Krishnapro is, but @amreekminocha is not.

**Comment by schmelto** [comment]
> They're already part of the organization. @Krishnapro is, but @amreekminocha is not.
> 

Ab now I see it :)

**Comment by schmelto** [comment]
@amreekminocha please open a new issue with the right issue type. I'm going to close this one due @Krishnapro is already part of the organization

**Comment by schmelto** [comment]
Thanks @Panquesito7 and @FayasNoushad for the help!
