### ISSUE TITLE
[FEATURE REQUEST] Add GitHub Organization README profile

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/support#2428]
### Description of feature request, idea

Just found out this new GitHub feature on GitHub org.

### Add any other context about the feature request here

- I just posted it :) https://twitter.com/vinzvinci/status/1438033675313025024
+
- blog: https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/

> to work with this, you need to create a new repository and name it `.github` then tada 🎉 you found the new feature 🥳

**Comment by eddiejaoude** [comment]
This feature looks great and we have early access too 🎉

**Comment by schmelto** [comment]
> This feature looks great and we have early access too 🎉

Could you ping us here when you created the `.github` repository?

**Comment by krishdevdb** [comment]
Ping me too, please?

**Comment by qwe123coder** [comment]
mee too pls i have some cool ideas for it

**Comment by Panquesito7** [comment]
Same here. 🙂

**Comment by voidz7** [comment]
I would like to work on this too !

**Comment by Panquesito7** [comment]
We could add a brief description of what is EddieHub, and add our socials and website to get to know more about us! We could also add a banner. 🙂

**Comment by Akshu-on-github** [comment]
Lemme know when this repo's set up - feel free to ping me

**Comment by eddiejaoude** [comment]
Great suggestions everyone 💥 

It has been started, contributions welcome ...
<img width="1643" alt="Screenshot 2021-09-19 at 11 25 59" src="https://user-images.githubusercontent.com/624760/133924056-d78c2736-17d7-4714-8480-c478d6189d1c.png">
