### ISSUE TITLE
[REVIEW] AbhijithGanesh.tech

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/support#2430]
### Portfolio link

https://AbhijithGanesh.tech

**Comment by aditya-shrivastava** [comment]
Hi there, thanks for sharing your portfolio. Looks really amazing 👍 

Few things I would suggest:
- The animation can be a little distracting, maybe reduce the opacity of the animated objects.
- Embedding a contact form.

**Comment by FayasNoushad** [comment]
> ### Portfolio link
> https://AbhijithGanesh.tech

Its opensource?

**Comment by AbhijithGanesh** [comment]
> 
> 
> Hi there, thanks for sharing your portfolio. Looks really amazing 👍
> 
> Few things I would suggest:
> 
>     * The animation can be a little distracting, maybe reduce the opacity of the animated objects.
> 
>     * Embedding a contact form.
> 
>     * Add a favicon to the website.

I'll keep these points in my mind.

**Comment by AbhijithGanesh** [comment]
> 
> 
> > ### Portfolio link
> > https://AbhijithGanesh.tech
> 
> Its opensource?

Would you like to clone this repository and redesign?

**Comment by schmelto** [comment]
Take a look at the width of the project cards in mobile view those are a little bit small

**Comment by emmalearnscode** [comment]
Nice design. Some of the project cards are not big enough and the text is overflowing the bottom so it's worth checking the page on different screen sizes. Also, I suggest doing a lighthouse check and fixing the errors it shows as the site could be improved for both accessibility and SEO

**Comment by eddiejaoude** [comment]
Going to close as no GitHub link, we can re-open when a GitHub link is added or feel free to create a new issue
