### ISSUE TITLE
README For EddieHub Org

### ISSUE THREAD

**Issue by Sam-Varghese** [EddieHubCommunity/support#2440]
### Description of feature request, idea

Just came across a way to make README for an organization like [this one](https://github.com/IndianOpenSourceFoundation)         
 in [this article](https://dev.to/siddhantkcode/how-to-create-an-github-special-repository-for-organisation-3g86). What are your opinions folks about making a README for the EddieHub organization.

### Add (multiple) screenshot links (if applicable)

![image](https://user-images.githubusercontent.com/79152648/133623400-407eb690-7e08-4818-aff8-6b1e76cb0963.png)

**Comment by krishdevdb** [comment]
Thanks for the suggestions. Unfortunately It's a duplicate of #2428. Could you close this?

**Comment by Sam-Varghese** [comment]
> Thanks for the suggestions. Unfortunately It's a duplicate of #2428. Could you close this?

Oh didn't see that, thanks for informing 🙂 👍
