### ISSUE TITLE
[REVIEW] Bookshelfly

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/support#2441]
### Project link

https://github.com/guptasajal411/bookshelfly

**Comment by Panquesito7** [comment]
- Add a readme of what your project is for or how does it work.
- Disable the Wiki if it's not being used.
- Missing a pull request template.
- I would recommend naming the website `bookshelfly` and not `try-bookshelfly`.

Overall, everything else is looking great! Awesome work! 😄
I've also made a [**pull request**](https://github.com/guptasajal411/bookshelfly/pull/19) for some minor improvements. 🚀

**Comment by KendallDoesCoding** [comment]
Looks good

- Add badges to README
> - Disable the Wiki if it's not being used.

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- suggest using GitHub Actions (for example creating releases)
- hide wiki as not being used
- suggest using pull request templates
- "demo" section in the README is blank, suggest removing
- all titles in README are `h1` (`#`)
- suggest having a screenshot at the top
