### ISSUE TITLE
[REVIEW] helper-uttam's resume 

### ISSUE THREAD

**Issue by helper-uttam** [EddieHubCommunity/support#2443]
### Resume link
<a href="https://drive.google.com/file/d/1zFCEvSKrJ_PMb8kepaVEs4blYOK9MZz4/view?usp=sharing">My resume</a>

**Comment by helper-uttam** [comment]
> ### Resume link
> http://pubgofficial.me/portfolio/

Please suggest me some changes in my **resume**.  Why it's not being shortlisted :(

**Comment by schmelto** [comment]
Duplicate with #2294

**Comment by schmelto** [comment]
Oh just saw that those are two different portfolios.
Could you please only open one issue :9 If you want to get a review on this one please close the other issue :)

**Comment by helper-uttam** [comment]
> Oh just saw that those are two different portfolios.
> Could you please only open one issue :9 If you want to get a review on this one please close the other issue :)

Please pardon me! I had closed the previous issue   :)

**Comment by Panquesito7** [comment]
Woah, **awesome portfolio**! I liked it a lot! Great work, @helper-uttam! 🚀
I just made a [**pull request**](https://github.com/helper-uttam/portfolio/pull/1) to improve the portfolio a bit to make it look better. 🙂

Thank you for sharing your awesome portfolio with the community! 😄👍

**Comment by helper-uttam** [comment]
> Woah, **awesome portfolio**! I liked it a lot! Great work, @helper-uttam! 🚀
> I just made a [**pull request**](https://github.com/helper-uttam/portfolio/pull/1) to improve the portfolio a bit to make it look better. 🙂
> 
> Thank you for sharing your awesome portfolio with the community! 😄👍

Thankyou! :)
Please review my resume :) tell me if you have any suggestion to improve it

**Comment by Panquesito7** [comment]
> > Woah, **awesome portfolio**! I liked it a lot! Great work, @helper-uttam! 🚀
> > I just made a [**pull request**](https://github.com/helper-uttam/portfolio/pull/1) to improve the portfolio a bit to make it look better. 🙂
> > Thank you for sharing your awesome portfolio with the community! 😄👍
> 
> Thankyou! :)
> Please review my resume :) tell me if you have any suggestion to improve it

For resume review, you can create a separate issue for that with the appropriate template. 🙂

**Comment by helper-uttam** [comment]
I had raised this issue with `resume [RIVIEW]` label. So, I had updated the issue with
```diff
- portflio
+ Resume
```
 please review it 

> ### Resume link
> [My resume](https://drive.google.com/file/d/1zFCEvSKrJ_PMb8kepaVEs4blYOK9MZz4/view?usp=sharing)

**Comment by schmelto** [comment]
> I had raised this issue with `resume [RIVIEW]` label. So, I had updated the issue with
> ```diff
> - portflio
> + Resume
> ```
>  please review it 
> 
> > ### Resume link
> > [My resume](https://drive.google.com/file/d/1zFCEvSKrJ_PMb8kepaVEs4blYOK9MZz4/view?usp=sharing)
> 
> 

I don't have access to the resume

**Comment by Panquesito7** [comment]
I think you should make a multiple issue for the resume review. People will get confused with the messages sent above regarding your portfolio. 🙂

**Comment by helper-uttam** [comment]
> > I had raised this issue with `resume [RIVIEW]` label. So, I had updated the issue with
> > ```diff
> > - portflio
> > + Resume
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > please review it
> > > ### Resume link
> > > [My resume](https://drive.google.com/file/d/1zFCEvSKrJ_PMb8kepaVEs4blYOK9MZz4/view?usp=sharing)
> 
> I don't have access to the resume

Updated the permission, now please check it

**Comment by eddiejaoude** [comment]
I was going to review on a video, but the file is not available, I get this error `Sorry, the file you have requested does not exist.`

I will close this, you can create a new issue with a working link if you would like it reviewed on a live stream / video

**Comment by helper-uttam** [comment]
Ahh! Really sorry.
That's because resume needs to be updated time to time. Please go through my updated one #2909
