### ISSUE TITLE
[REVIEW] prince02765

### ISSUE THREAD

**Issue by prince02765** [EddieHubCommunity/support#2448]
### GitHub Profile Link

https://github.com/prince02765

**Comment by schmelto** [comment]
One thing from my side consider removing the profile views count due it's inaccurate

**Comment by Panquesito7** [comment]
Hey there! Cool profile; I liked it! 😄👍
I would only recommend doing

- What @schmelto said.
- Add a bit more information about yourself, your experience, etc.

**Comment by helper-uttam** [comment]
> ### GitHub Profile Link
> https://github.com/prince02765

Hi prince thanks for sharing your profile with us 😁
It was really good, I had raised a PR with some little changes please consider that :)

**Comment by prince02765** [comment]
Thanks for the suggestion @schmelto @Panquesito7 

Yeah, @helper-uttam I would be happy to change. 😊

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=yK-NLKZ8cHU

Looks great, some suggestions...
- I think adding a profile picture would make it personal
- suggest doing more pull requests, code reviews and issues
