### ISSUE TITLE
[REVIEW] MukulKolpe

### ISSUE THREAD

**Issue by MukulKolpe** [EddieHubCommunity/support#2455]
### GitHub Profile Link

https://github.com/MukulKolpe

**Comment by Panquesito7** [comment]
Awesome profile, @MukulKolpe! I liked it a lot! 😄👍

I have made a [**pull request**](https://github.com/MukulKolpe/MukulKolpe/pull/4) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 🚀

**Comment by helper-uttam** [comment]
> ### GitHub Profile Link
> https://github.com/MukulKolpe

@MukulKolpe  great profile :)
I made a PR for adding typewriter effect 👍 Check it out

**Comment by MukulKolpe** [comment]
Thanks a lot for the amazing reviews @Panquesito7 @helper-uttam !!

**Comment by schmelto** [comment]
Consider adding some more plattforms in the connect with me section

**Comment by MukulKolpe** [comment]
I am not sure what else can be added😅 Can you give me some examples?

**Comment by helper-uttam** [comment]
> I am not sure what else can be added😅 Can you give me some examples?

take a look on other's profile 🥇

**Comment by schmelto** [comment]
> I am not sure what else can be added😅 Can you give me some examples?

LinkedIn, StackOverflow, Dev, etc.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks good, some suggestions...
- contribute with more issues, pull requests, and code reviews
- maybe make better use of the white space down the right side for "connect with me"
-

**Comment by MukulKolpe** [comment]
Thanks a lot the review @eddiejaoude 😄
