### ISSUE TITLE
[FEATURE REQUEST] Create an Organisation README.md

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/support#2459]
### Description of feature request, idea

GitHub launched `README.md`s for organizations a few days ago - since then, there have been several awesome Organization `README.md`s popping up! I'd love to jump onto that bandwagon

### Add (multiple) screenshot links (if applicable)

Not sure if screenshots are applicable here, but here are a few links:
- [GitHub Changelog](https://www.linkedin.com/company/github/videos/native/urn:li:ugcPost:6844601667451809792/)
- [GitHub's README.md](https://github.com/github)

### Add any other context about the feature request here

I think this will evolve into a way to find organizations - let's not miss out on this!

**Comment by krishdevdb** [comment]
Thanks for the suggestions. Unfortunately It's a duplicate of #2428. Could you close this?

**Comment by Akshu-on-github** [comment]
Sure thing, @krishdevdb - looking forward to working on it! 😃
