### ISSUE TITLE
[OTHER] GitHub error, not sure how to fix.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/support#2465]
### What would you like to share?

Everytime I press on a commit someone has pushed on GitHub, it takes me to a 404 page. I am not sure why. I am not able to review anything, as it just takes me to a 404 unknown page.

### Additional information

 I tried to ask for help on the actual GitHub repo, but I am not sure if that was the right place to ask. And I am not sure if this is the right place to ask to. I will send a screenshot showing what happens.
Thank you.

**Comment by CodingSpecies** [comment]
https://user-images.githubusercontent.com/70807500/133926610-25fd3ac6-70bd-4fa6-9684-11831f12339f.mp4

It doesn't work when I sign in, or in any browser.

**Comment by Panquesito7** [comment]
Look at the link closely: it looks like GitHub has an error here. It has happened to me too, and the thing you need to do is go to the commits tab and click on the commit you want. I hope that helps. Let me know if you need any more help! 😄

**Comment by CodingSpecies** [comment]
@Panquesito7 thank you so much.
