### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by R11manish** [EddieHubCommunity/support#2499]
### Name

Manish Rawat

### Discord Username (if applicable)

Manish#2183

### Additional Context

i met eddie first time on youtube. when i was learning ablout git and github. so from that time being i follow eddie everywhere.
the members of the community are just awesome. they all are so much welcoming and encouraging..  that is the one of the reason why i wanna join eddiehub community

**Comment by R11manish** [comment]
i didn't receive any invitation

**Comment by R11manish** [comment]
help me guys. how to join ?

**Comment by eddiejaoude** [comment]
check your spam folder, but you can also accept the invite from our GitHub Org page https://github.com/EddieHubCommunity

**Comment by R11manish** [comment]
thank you eddie. finally found it.
