### ISSUE TITLE
[REVIEW] MathKnight

### ISSUE THREAD

**Issue by syedmazharaliraza** [EddieHubCommunity/support#2500]
### Project link

https://github.com/syedmazharaliraza/MathKnight

**Comment by schmelto** [comment]
To make the repo fully open source consider adding a license, contribution.md etc.

**Comment by syedmazharaliraza** [comment]
> To make the repo fully open source consider adding a license, contribution.md etc.

@schmelto Added contributing.md and code_of_conduct.md. Will look up for the license

**Comment by nhcarrigan** [comment]
Hey there @syedmazharaliraza,

Was this closed intentionally? It hasn't been reviewed on a live stream yet. 🙂

**Comment by syedmazharaliraza** [comment]
> Hey there @syedmazharaliraza,
> 
> Was this closed intentionally? It hasn't been reviewed on a live stream yet. 🙂

@nhcarrigan Hello. Yes I closed it on purpose I believe I need to make certain changes in the project

**Comment by nhcarrigan** [comment]
We have quite a bit of backlog on reviews, so leaving this open should be fine (that way you don't lose your place in the queue 🙂 )
