### ISSUE TITLE
[REVIEW] Debbie's porfolio 

### ISSUE THREAD

**Issue by hellodeborahuk** [EddieHubCommunity/support#2501]
### Portfolio link

https://dann.digital

**Comment by schmelto** [comment]
On the contact side you mention your email twice think only one time is needed. Otherwise I really like the portfolio.

**Comment by hellodeborahuk** [comment]
> On the contact side you mention your email twice think only one time is needed. Otherwise I really like the portfolio.

Thank you Tom. I've removed the duplicate email.
