### ISSUE TITLE
[REVIEW] thepranaygupta

### ISSUE THREAD

**Issue by thepranaygupta** [EddieHubCommunity/support#2503]
### GitHub Profile Link

https://github.com/thepranaygupta

**Comment by schmelto** [comment]
Like it!

**Comment by Panquesito7** [comment]
Awesome profile, @thepranaygupta! I liked it a lot! 😄 

I have made a [**pull request**](https://github.com/thepranaygupta/thepranaygupta/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your amazing profile with us! 🚀

**Comment by thepranaygupta** [comment]
Thank you @schmelto and @Panquesito7 for the appreciation and improvement. 😍 

Good day! 😄
