### ISSUE TITLE
[REVIEW] DGKSK8LIFE

### ISSUE THREAD

**Issue by DGKSK8LIFE** [EddieHubCommunity/support#2504]
### GitHub Profile Link

https://github.com/DGKSK8LIFE

**Comment by Panquesito7** [comment]
Nice profile! I would only recommend adding something about yourself. 🙂

**Comment by DGKSK8LIFE** [comment]
Thanks.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=YVJyz7DZMQo

Looks great as minimalistic and clean profile
- Suggest customising your GitHub profile
- Use bio and link
- Try to have more code reviews, issues and pull requests
