### ISSUE TITLE
[REVIEW] adityathakurxd

### ISSUE THREAD

**Issue by adityathakurxd** [EddieHubCommunity/support#2506]
### GitHub Profile Link

https://github.com/adityathakurxd

**Comment by schmelto** [comment]
Nice one! only one thing consider removing the profile view count due its inaccurate

**Comment by adityathakurxd** [comment]
Thank you for the feedback! @Panquesito7's Pull Request helped remove the profile count.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=yK-NLKZ8cHU

Looks great, some suggestions...
- large line graph at the end takes a lot of space and I think hurts your profile
- suggest doing more pull request, issues and code reviews
- are the pinned repos and also the repo widgets in the README both required?
