### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by pratham-10** [EddieHubCommunity/support#2514]
### Resume link

https://drive.google.com/file/d/1ka2fW7cYkNVz1ind7uUI-NTn6ZXG7uad/view?usp=sharing

**Comment by eddiejaoude** [comment]
Reviewed on video, video to come out in a few weeks

Looks good 👍  some thoughts
- needs more spacing between sections
- skills section `SQL` and `SQl` needs to be consistent
- VSCode and Jupter should be separate bullet points like the others, it is the only one with a `,`
- projects to have GitHub links
