### ISSUE TITLE
[REVIEW] http://prathmeshbhansali.me/ 

### ISSUE THREAD

**Issue by prathambhansali** [EddieHubCommunity/support#2515]
### Portfolio link

http://prathmeshbhansali.me/

**Comment by schmelto** [comment]
One thing from my side. Consider adding a certificate that you can use https

**Comment by pratham-10** [comment]
> One thing from my side. Consider adding a certificate that you can use https

Sure  I will add that. Thank you.

**Comment by emmalearnscode** [comment]
Wow, looks great on both mobile and desktop! Just some small things - there are a few apostrophes where they are not needed and doing a lighthouse check shows a few small errors that could be improved but they're only minor things. You did a great job!

**Comment by krshkun** [comment]
The URL doesn't open, also can you please add GitHub Url of repo

![image](https://user-images.githubusercontent.com/91655303/194842087-1bc551f1-1364-4bb3-833f-baf2552aa0b5.png)

**Comment by eddiejaoude** [comment]
Closing as no GitHub url
