### ISSUE TITLE
[REVIEW] Spotifynd

### ISSUE THREAD

**Issue by vijay-jaisankar** [EddieHubCommunity/support#2517]
### Project link

https://github.com/absotone

**Comment by vijay-jaisankar** [comment]
The main project is `Spotifynd`
The documentation is at `spotifynd-docs`

**Comment by schmelto** [comment]
Consider adding Screenshots in the main repo

**Comment by vijay-jaisankar** [comment]
Will do, thanks for the advice :) 
@schmelto

**Comment by vijay-jaisankar** [comment]
Edit: Done! 
Sorry for the delay, I was busy with a uni assigment.

Please check it out :)

**Comment by eddiejaoude** [comment]
Reviewed on live stream

- Org could have more info like description and link
- Suggest adding more members
- Customise GitHub Org with more information (similar to GitHub profile)
