### ISSUE TITLE
[REVIEW] Harry Potter Game

### ISSUE THREAD

**Issue by SayantaniDeb** [EddieHubCommunity/support#2518]
### Project link

https://github.com/SayantaniDeb/Harry-Potter

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks good, some suggestions...
- create releases (ideally on GitHub Actions)
- hide packages if not using it
- add link to demo under repo description (on the top right)
- use issues, great way to get contributors and also help discoverability 
- hide wiki if not using 
- add code of conduct, license, contributing file
