### ISSUE TITLE
[REVIEW] RoshanMhatre 

### ISSUE THREAD

**Issue by RoshanMhatre** [EddieHubCommunity/support#2525]
### GitHub Profile Link

https://github.com/RoshanMhatre

**Comment by Panquesito7** [comment]
Awesome profile! I liked it a lot! 🚀

I have made a [**pull request**](https://github.com/RoshanMhatre/RoshanMhatre/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thanks for sharing your amazing profile with the community! 😄

**Comment by RoshanMhatre** [comment]
Thank you, David! Your profile looks amazing 😍

**Comment by Panquesito7** [comment]
> Thank you, David! Your profile looks amazing 😍

Thank you! 😄

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream, some suggestions...

- maybe too many badges and titles
- maybe try to get some more green squares by getting involved in open source
