### ISSUE TITLE
[REVIEW] ZISHAN JAWEDs Resume

### ISSUE THREAD

**Issue by zishanjawed** [EddieHubCommunity/support#2527]
### Resume link

https://drive.google.com/file/d/1-O-9Lr-2ey3MlO_xLln4Cb5UJQX1R1U3/view?usp=sharing

**Comment by eddiejaoude** [comment]
Reviewed on video, video coming out in a few weeks

Looks good 👍 , some thoughts
- `New Delhi` is this a footer or part of another section - looks out of place
- projects to have GitHub repo links, with full urls
