### ISSUE TITLE
[REVIEW] leplerjacob 

### ISSUE THREAD

**Issue by leplerjacob** [EddieHubCommunity/support#2528]
### Portfolio link

https://github.com/leplerjacob

**Comment by leplerjacob** [comment]
I have just started contributing to open source projects. Thanks for the advice so far :)

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- too many widgets
- suggest creating more issues, so the contributor graph is more balanced
- try to break up the block of text with markdown
- not sure the profile view counter is a good idea
