### ISSUE TITLE
[REVIEW] 4C website

### ISSUE THREAD

**Issue by FrancescoXX** [EddieHubCommunity/support#2530]
### GitHub Profile Link

https://github.com/FrancescoXX/4c-site

**Comment by eddiejaoude** [comment]
Thank you for sharing, reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg

Looks great, some thoughts...
- suggest creating releases (start with manual, then can use GitHub Action)
- hide packages and wiki if not using
- like the use of the spacing with the project image, suggest making it smaller, so there is no scroll on "running the project"
- using labels will help contributors and discoverability 
- add a code of conduct, contributing file and issue templates (forms)
- commits to use conventional commit messages, so you can automate the releases
