### ISSUE TITLE
[REVIEW] suchitragiri

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [EddieHubCommunity/support#2531]
### GitHub Profile Link

https://github.com/suchitragiri

**Comment by helper-uttam** [comment]
Hey @SUCHITRAGIRI , awesome profile.
I had made a pull request to your GitHub `readme.md` please consider that.

**Comment by Panquesito7** [comment]
Wow 👀 amazing profile! I liked it very much! 😲

I have made a [**pull request**](https://github.com/SUCHITRAGIRI/SUCHITRAGIRI/pull/2) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your amazing profile with the community! 🚀

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- animated svg doesn't work well on safari
- recent blog posts could be automated with a GitHub action
- maybe do some more contributions to open source
