### ISSUE TITLE
[REVIEW] hilalsidhic

### ISSUE THREAD

**Issue by hilalsidhic** [EddieHubCommunity/support#2578]
### GitHub Profile Link

https://github.com/hilalsidhic

**Comment by helper-uttam** [comment]
Hey @hilalsidhic !
Thankyou for sharing your profile with us, I liked it a lot but it needs some improvements I had opened a pull request with some minor changes, please consider that

**Comment by krshkun** [comment]
Hi there 👋 I have a few suggestions and improvements for your profile

## 📝 Suggestions

- [ ] This svg has know issues on safari, I would suggest removing it
![image](https://user-images.githubusercontent.com/91655303/194848271-d80b34b1-f59e-471a-9d6b-0ddb691a3cf1.png)
- [ ] The left section of your profile is empty, you can add much more there
- [ ] Unsure why 2 horizontal rules 
![image](https://user-images.githubusercontent.com/91655303/194848408-c7cb18b0-d976-4457-a864-c938142bc801.png)
- [ ] You can make these widgets come side by side: 
![image](https://user-images.githubusercontent.com/91655303/194848451-42b50ace-bd0c-42f0-abd0-559c32b665bf.png)

## 🚀 Appreciation

- [x] The banner looks good and the profile is concise!

**Comment by eddiejaoude** [comment]
Reviewed on live stream...

Looks good, some thoughts:
- ideally use a profile picture of yourself
- maybe the widgets could be side by side to make better use of the space
- contributing graph is very commit heavy, I suggest trying to also do issues, pull requests and reviews
