### ISSUE TITLE
[REVIEW] https://iamsunil25.github.io/portfolio/ 

### ISSUE THREAD

**Issue by iamsunil25** [EddieHubCommunity/support#2587]
hey please review my portfolio website which is made by me using html, css and js.

### Portfolio link

https://iamsunil25.github.io/portfolio/

**Comment by schmelto** [comment]
https://github.com/iamsunil25/portfolio/pull/3

**Comment by iamsunil25** [comment]
@schmelto i accepted your pull request 👍

**Comment by emmalearnscode** [comment]
Hi Sunil! My main advice would be to focus on the responsive design of your site, since you are selling yourself on responsive design skills. I notice there are several elements which currently overlap/don't work well on mobile screen sizes so you might want to check those out.

**Comment by eddiejaoude** [comment]
Closing as no GitHub url
