### ISSUE TITLE
[REVIEW] murtuzaalisurti

### ISSUE THREAD

**Issue by murtuzaalisurti** [EddieHubCommunity/support#2596]
### Portfolio

Portfolio website:- https://murtuzaalisurti.github.io

**Comment by krishguptadev** [comment]
Please separate the portfolio and profile into two separate issues else Eddie won't be able to review both of them

**Comment by murtuzaalisurti** [comment]
> Please separate the portfolio and profile into two separate issues else Eddie won't be able to review both of them

Done

**Comment by schmelto** [comment]
puhh nice one!! Great work!

**Comment by murtuzaalisurti** [comment]
> puhh nice one!! Great work!

Thanks

**Comment by Panquesito7** [comment]
Wow 👀 awesome work on making that portfolio! Looks very good. 🚀

**Comment by murtuzaalisurti** [comment]
> Wow 👀 awesome work on making that portfolio! Looks very good. 🚀

Thanks

**Comment by emmalearnscode** [comment]
It looks great on both mobile and desktop! Also, it's easy to navigate with a keyboard and super impressed that you also included a skip link 👍 The only thing I found a little jarring was the different speeds of the text animations in the header.

**Comment by eddiejaoude** [comment]
Closing as no GitHub url
