### ISSUE TITLE
[FEATURE REQUEST] CREATION OF A EDDIEHUB DOCS website/repo

### ISSUE THREAD

**Issue by AbhijithGanesh** [EddieHubCommunity/support#2644]
### Description of feature request, idea

We can create an entire website/repository containing the compiled resources for all repos listed under EddieHub Community.  It will make the contribution process much simpler because multiple resources would be combined and it will be a good hub(central node) for docs.

We can make this a part of Hacktober fest as it improvises the community experience too.
Another advantage is that it'll have space for developers to contribute too.

**Comment by eddiejaoude** [comment]
This was started here in [tips](https://github.com/EddieHubCommunity/support/tree/main/tips), we could go full docs though and deploy the files to a website

**Comment by AbhijithGanesh** [comment]
Can we broaden the docs and compile it into a website?

**Comment by Vyvy-vi** [comment]
> We can create an entire website/repository containing the compiled resources for all repos listed under EddieHub Community. It will make the contribution process much simpler because multiple resources would be combined and it will be a good hub(central node) for docs.

In my opinion a central website in a separate repo wouldn't make much sense.
It would be neat if docs are included in the repo in which the project exists.. That way it's easier for people to edit docs and collaborate and contribute changes.

However, one thing we could do is make a `docs` folder in each repo that contains markdown files, and have a github action use `docsify` or `asciidoctor` or any other markdown parser, and deploy this on github-pages...
The way github-pages handles files enables us to have all the docs available on the same domain

**Comment by AbhijithGanesh** [comment]
Why is that so @Vyvy-vi ? Can you elaborate why it is not practical and ideal?

**Comment by Vyvy-vi** [comment]
I think we got mixed up here...
I misinterpreted this, and thought that we were talking about creating all of our documentation in one repo

**Comment by AbhijithGanesh** [comment]
Oh wait! I am sorry for your confusion! I shall rephrase things here to make it clear for future readers.

**Comment by Vyvy-vi** [comment]
I think we could certainly make a `docs.eddiehub.org/` website, and have a layout like this-
```
/ - Leads to a landing page that contains some information, and an index of contents (this is hosted in a separate central repo). sub-pages inside that repo are guides.
tips/ - A page listing out all the tips and their topics
tips/<id>(or <slug>?) - This is the place where people from the community can add tips.. (the ones on the main page at / are the eddiehub-documentation, and the tips path is where people can share their tips. These exist in the central repo, in a tips folder)
resources/ - A list of resources and links
resources/<slug> - Specific resources that need more detail go in the resources folder and have more textual data
projects/<repo-name> - leads to the documentation page for certain projects. (these are hosted on the domain by the repo mentioned in the repo-name) 
```

Imo, maybe to keep things simple it might make sense to use a markdown renderer, since that way people can easily write guides, without any issues. asccidoc, docsify, jekyll whatever we prefer.

**Comment by stemount** [comment]
I'm with @Vyvy-vi on this, docs should definitely be local to the repository.

If you really want, a GitHub action could simply be a Docker action where it takes the docs of project `xxx`, takes it's name and puts it in a repository, then you create the github pages from this and then you can then get a guaranteed URL of the latest things e.g.

`https://docs.eddiehub.com/` <- some helper stuff, maybe an index, whatever
`https://docs.eddiehub.com/projects` <- index page of the projects
`https://docs.eddiehub.com/projects/same-git-repo-name` <- always the slug

**Comment by stemount** [comment]
> A site like that would be awesome! I think we could certainly make a `docs.eddiehub.org/` website, and have a layout like this-
> 
> ```
> / - Leads to a landing page that contains some information, and an index of contents (this is hosted in a separate central repo). sub-pages inside that repo are guides.
> tips/ - A page listing out all the tips and their topics
> tips/<id>(or <slug>?) - This is the place where people from the community can add tips.. (the ones on the main page at / are the eddiehub-documentation, and the tips path is where people can share their tips. These exist in the central repo, in a tips folder)
> resources/ - A list of resources and links
> resources/<slug> - Specific resources that need more detail go in the resources folder and have more textual data
> project/ - Lists out our projects
> projects/<repo-name> - leads to the documentation page for certain projects. (these are hosted on the domain by the repo mentioned in the repo-name) 
> ```
> 
> Imo, maybe to keep things simple it might make sense to use a markdown renderer, since that way people can easily write guides, without any issues. asccidoc, docsify, jekyll whatever we prefer.

wow, just totally realised you already suggested the whole routes thing and I did the same thing. GREAT MINDS THINK ALIKE, but for some reason my mind just duplicated what you said lol

The benefit of the above repo thing is that the docs would be built to static HTML using any solution as you suggest @Vyvy-vi local to that repository, then GitHub pages or the eddiehub k8s cluster can simply just host that repository using nginx with least effort possible.

**Comment by AbhijithGanesh** [comment]
I completely agree, using NGINX to load static files and docs would make life much easier and we should implement this.

**Comment by stemount** [comment]
@AbhijithGanesh @Vyvy-vi I've just had a quick browse through all the repositories, is there any specific list of projects that have `asciidoc` or similar already building in the project?

1. Just wondering what the next steps are if the repos need the documentation adding to them.
2. If they do have documentation, does the README.md also count? It'd be good to build the README.md as the index of something like the suggested URL of 'docs.eddiehub.org/repo-name/` then build a link to it.

**Comment by AbhijithGanesh** [comment]
Read me can be a top level view but some projects really need more documentation related to project specifics

**Comment by Vyvy-vi** [comment]
> I'm with @Vyvy-vi on this, docs should definitely be local to the repository.
> 
> If you really want, a GitHub action could simply be a Docker action where it takes the docs of project `xxx`, takes it's name and puts it in a repository, then you create the github pages from this and then you can then get a guaranteed URL of the latest things e.g.
> 
> `https://docs.eddiehub.com/` <- some helper stuff, maybe an index, whatever
> `https://docs.eddiehub.com/projects` <- index page of the projects
> `https://docs.eddiehub.com/projects/same-git-repo-name` <- always the slug


GitHub pages handles that magic ;D

**Comment by Vyvy-vi** [comment]
I think at the moment we don't really have detailed docs for most projects, since we're still planning out the projects.

I think we were using asciidoc for the stargate project

**Comment by AbhijithGanesh** [comment]
Well , if we're gonna use asciidoc, can I work along with y'all and establish/create it ?

**Comment by Vyvy-vi** [comment]
Sure!
I think we can make the main resource site in the support repo itself.

Thoughts @eddiejaoude ?

**Comment by AbhijithGanesh** [comment]
I wanna be an active contributor and learn with this so if @Vyvy-vi can mentor me once Eddie approves it'll be of massive help

**Comment by schmelto** [comment]
we could do something with jekyll docs :)

**Comment by AbhijithGanesh** [comment]
Jekyll or Asciiidocs?  Which would be best-suited folks?

**Comment by krishguptadev** [comment]
I'd like to see docsify since it is being used in this repo

**Comment by Panquesito7** [comment]
I think this is already fixed. Might want to close this. 🙂

**Comment by krishguptadev** [comment]
> I think this is already fixed. Might want to close this. 🙂

Only support community docs are created 🙂 We need to have for LinkFree, API and more...
