### ISSUE TITLE
[REVIEW] Have a look on my random joke presenting chrome extension

### ISSUE THREAD

**Issue by subhamengine** [EddieHubCommunity/support#2676]
### Project link

https://github.com/subhamengine/Op-Jokes-chromeExtension

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=YVJyz7DZMQo

- suggest hiding `releases` and `packages` if not used
- suggest not committing the `rar` file and using GitHub Actions
