### ISSUE TITLE
[BUG] remove statistics wokflow

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#2682]
### Description of the bug

https://github.com/EddieHubCommunity/support/actions/runs/1307836916

**ToDo:**

remove following code in [community.yml](https://github.com/EddieHubCommunity/support/blob/main/.github/workflows/community.yml)
```diff
-  statistics:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v1
-      - uses: EddieHubCommunity/gh-action-community/src/statistics@main
-        if: ${{ github.repository_owner == 'EddieHubCommunity' }}
-        with:
-          firebase-key: ${{ secrets.FIREBASE_KEY }}
```

### Project stack or language (e.g. front-end)

GitHub Action

**Comment by krishguptadev** [comment]
Can I work on this?
