### ISSUE TITLE
[BUG] SSL protocol error on some builds of Chrome

### ISSUE THREAD

**Issue by vielmetti** [EddieHubCommunity/support#2691]
### Description of the bug

On some versions of Google Chrome, the eddiehub.org site fails to 
load with an SSL protocol error. 

Not working: Version 94.0.4606.61 (Official Build) (x86_64)
Working: Version 94.0.4606.71 (Official Build) (x86_64)

### Project stack or language (e.g. front-end)

Chrome

### Working Environment (e.g. operating system, browser, device)

Google Chrome on MacOS Big Sur 11.6

### Please add screenshots (if applicable)

![Screen Shot 2021-10-06 at 7 39 17 AM](https://user-images.githubusercontent.com/35047/136197726-ec240f75-d356-49d7-88c6-9bb6fdb0ce6a.png)

### Add any other context about the problem here

Problem resolved by upgrading Chrome.

**Comment by vielmetti** [comment]
These are the release notes for the 94.0.4606.71 release of Chrome: 

https://chromereleases.googleblog.com/2021/09/stable-channel-update-for-desktop_30.html

**Comment by KendallDoesCoding** [comment]
That's weird.

**Comment by eddiejaoude** [comment]
Thanks @vielmetti for raising. I am going to close this for now if no one else can verify the same issue.

Feel free to comment if it is still an issue and we can re-open it

**Comment by vielmetti** [comment]
Thanks @eddiejaoude - confirmed to all be working as of

Version 102.0.5005.61 (Official Build) (arm64)

**Comment by eddiejaoude** [comment]
thanks for confirming 👍
