### ISSUE TITLE
[REVIEW] diganta413

### ISSUE THREAD

**Issue by diganta413** [EddieHubCommunity/support#2701]
### GitHub Profile Link

https://github.com/diganta413

**Comment by dth99** [comment]
> ### GitHub Profile Link
> 
> https://github.com/diganta413
Hi diganta, I made few changes in your profile. Can you check my pull request.

**Comment by eddiejaoude** [comment]
Reviewed on live stream...

Looks good, some thoughts:
- try to be more consistent with open source contributions
- also try to do more code reviews and issues
