### ISSUE TITLE
[REVIEW] krishguptadev

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/support#2716]
### GitHub Profile Link

https://github.com/krishguptadev

**Comment by Panquesito7** [comment]
Cool profile! I liked it a lot. 🚀

I have made a [**pull request**](https://github.com/krishguptadev/krishguptadev/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thanks for sharing your awesome profile with the community! 😉

**Comment by krishguptadev** [comment]
> > ### GitHub Profile Link
> > https://github.com/krishguptadev
> 
> Hi kid, I made few changes in your profile. Can you check my PR?

Requested Changes.

**Comment by krishguptadev** [comment]
I have completely revamped my profile, lemme know what you think 🙂

**Comment by dth99** [comment]
> I have completely revamped my profile, lemme know what you think slightly_smiling_face

I made few changes in your profile. Can you check my PR?

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- banner is quite large, also had the same profile photo, suggest removing the photo from the banner and making it half the height 
- not a fan of the trophies (personal opinion)
