### ISSUE TITLE
[REVIEW]  fliscopt : Flight Scheduling Optimization in Python

### ISSUE THREAD

**Issue by Agrover112** [EddieHubCommunity/support#2742]
### Project link
A flight scheduling optimization algorithms in Python.

https://github.com/Agrover112/fliscopt

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- quite a lot of branches, these should probably be reduced
- suggest using semver in your Releases
- remove wiki and use docs folder
- `.vscode` and `.DS_Store` files should not be committed
