### ISSUE TITLE
[REVIEW] tabsMonster

### ISSUE THREAD

**Issue by aUnicornDev** [EddieHubCommunity/support#2755]
### Project link

https://github.com/aUnicornDev/tabsMonster

**Comment by schmelto** [comment]
* Add a release
* add link in the description (https://aunicorndev.github.io/tabsMonster/)

**Comment by eddiejaoude** [comment]
Thank you for submitting, review on live stream https://www.youtube.com/watch?v=9IRIVYCuYOw

Looks great, some thoughts
- hide releases and packages if not used
- use releases
- hide wiki as not used
