### ISSUE TITLE
[REVIEW] lyqht

### ISSUE THREAD

**Issue by lyqht** [EddieHubCommunity/support#2808]
### GitHub Profile Link

https://github.com/lyqht

**Comment by weeyin83** [comment]
What a friendly and welcoming profile!  Great work!

**Comment by lyqht** [comment]
thanks @weeyin83  :)

**Comment by schmelto** [comment]
Great job!

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- love the banner!
- maybe use your photo as the profile picture so it is more personal
- suggest removing 1 pinned repo from 5 to 4 to make better use of the space
