### ISSUE TITLE
[REVIEW] japerezd

### ISSUE THREAD

**Issue by japerezd** [EddieHubCommunity/support#2826]
### GitHub Profile Link

https://github.com/japerezd

**Comment by japerezd** [comment]
> Hi Jorge, I like your profile, especially the list of skills. My suggestions would be to make all i's capital please when they should be. I don't think you need to be linking to github on the contact section as they're already there. So maybe if you have fewer contact links, move them up above the skills with your portfolio.
> 
> On your portfolio, I've heard that ranking skill out of 100 isn't good practice. I'd also change the alignment of the "download my resume" button. I hope this helps.

You can check my website again, is rebuilt from scratch! Let me know what do you think 😁

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- suggest removing the widget it always says `A+`
- also suggest contribution to open source more
