### ISSUE TITLE
[REVIEW] Asmit2952

### ISSUE THREAD

**Issue by asmitbm** [EddieHubCommunity/support#2830]
### Portfolio link

https://asmit2952.github.io/

**Comment by emmalearnscode** [comment]
Nice clean design but I agree with Debbie, some of the animation makes it hard to focus on the actual content. I think some animation is fine but make it subtle. I couldn't read the paragraph where all the language names were hopping around next to it for example. Check your site works with only a keyboard, when I just tried it on chrome I can navigate as far as the portfolio section but then tabbing tries to jump to things hidden in the carousel and everything breaks. Also, make sure to use semantic html tags like header, nav and main.

**Comment by eddiejaoude** [comment]
Closing as no GitHub url
