### ISSUE TITLE
[REVIEW] kumaryash18

### ISSUE THREAD

**Issue by kumaryash18** [EddieHubCommunity/support#2843]
### GitHub Profile Link

https://github.com/kumaryash18

**Comment by weeyin83** [comment]
Great profile, I particular like the snake animation.

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- the widget that says `A+` always says A+ suggest removing
- I am not a fan of the trophy widgets 
- animation of the snake does not work on all browsers
