### ISSUE TITLE
[REVIEW] Skylar "The Help-Mate"

### ISSUE THREAD

**Issue by jaskiratmokha** [EddieHubCommunity/support#2853]
### Project link

https://github.com/Jas-Script/Skylar_TheHelpMate

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- Great you have a code of conduct but the file name is incorrect as doesn't appear on the community insights page
- Repo doesn't have a description
- Hide packages and releases if not used
- Add issue and pull request templates
