### ISSUE TITLE
[REVIEW] logesh-kumar

### ISSUE THREAD

**Issue by logesh-kumar** [EddieHubCommunity/support#2860]
### GitHub Profile Link

https://github.com/logesh-kumar

**Comment by helper-uttam** [comment]
Hey @logesh-kumar ,
Nice profile but but consider adding more content to your profile.

I've made some changes to your profile. 
Look at the <a href="https://github.com/logesh-kumar/logesh-kumar/pull/2">PR</a>

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- Bio description more about you, what are you looking for, why should people collaborate
- Widget don't add much value
- Animated svg doesn't work on Safari
- Suggest pinning 2 repos to use the space on the right
