### ISSUE TITLE
[REVIEW] DurveshKumarPal

### ISSUE THREAD

**Issue by DurveshKumarPal** [EddieHubCommunity/support#2867]
### GitHub Profile Link

https://github.com/DurveshKumarPal

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- Suggest removing the "graph of my contributions"
- Suggest doing more code reviews and pull requests
- Share more about the technologies you use (maybe use badges)
