### ISSUE TITLE
[REVIEW] dhananjayandayalan

### ISSUE THREAD

**Issue by dhananjayandayalan** [EddieHubCommunity/support#2896]
### GitHub Profile Link

https://github.com/dhananjayandayalan

**Comment by schmelto** [comment]
To get a github profile review please add a custom profile readme to your profile.
Here is a course of eddie on how to do that.

https://www.eddiejaoude.io/course-github-profile-landing

**Comment by helper-uttam** [comment]
> ### GitHub Profile Link
> https://github.com/dhananjayandayalan

Consider adding `readme.md` named as same as your username and then try to make it look more attractive :)

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- Add more to your bio's description
- Suggest pinning your favourite 2 or 4 repos
- Try to do more more code reviews and pull request
