### ISSUE TITLE
[REVIEW] siddhantprateek

### ISSUE THREAD

**Issue by siddhantprateek** [EddieHubCommunity/support#2897]
### GitHub Profile Link

https://github.com/siddhantprateek

**Comment by helper-uttam** [comment]
I loved it :) awesome profile @siddhantprateek

**Comment by schmelto** [comment]
Nice banner!

**Comment by hellodeborahuk** [comment]
I really love your profile, especially the banner. My only takeaway would be to vary your activity so it's not all commits in the activity overview.

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream...

Some suggestions 
- the image could be smaller giving more space for the text
- contribution graph doesn't seem to work
- I think reduce pinned repos to 4
- try to do some code reviews

**Comment by CBID2** [comment]
- Fix the contribution graph
- Fix the alignment of the “How to Reach Me” section
