### ISSUE TITLE
[BUG] Becca Bot should allow links from Prime React documentation

### ISSUE THREAD

**Issue by mohan-murali** [EddieHubCommunity/support#2900]
### Description of the bug

Currently, If we try to paste a link from prime react documentation, Becca Bot gets mad and deletes the link. She should allow the link to Prime React official docs.

### Project stack or language (e.g. front-end)

EddieBot

### Working Environment (e.g. operating system, browser, device)

Discord Bot

**Comment by Panquesito7** [comment]
I think you should open this issue in the [Becca Lyria](https://github.com/BeccaLyria/discord-bot) repository.
The owner will see this issue easier there. Thank you. 😄

**Comment by krishguptadev** [comment]
This issue should be in [Becca Lyria repo](https://github.com/BeccaLyria/discord-bot) as mentioned, please close this issue and open a new one in the repo as mentioned 🙂

**Comment by nhcarrigan** [comment]
Hi there,

I've gone ahead and added the primereact docs to the permitted links for the server. Thanks for letting us know!

@Panquesito7 @krishguptadev so you are both in the loop: specific links to allow are set on a per-server basis through the `/automod` command, and should not be opened as issues on Becca's repository. 🙂
