### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [EddieHubCommunity/support#2903]
### Name

Jyoti prakash Rout

### Discord Username (if applicable)

Jyoti#0398

### Additional Context

I'm an Web Dev Enthusiasts & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Android Devlopment, IOS Devlpoment, Machine Learning & Devops & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why and what relating to Technologies around me.

I would like to grow my programming skills by doing lot's of  Open Source Contribution. Looking forward to learn, collabrate and grow as a community.

**Comment by eddiejaoude** [comment]
Oh not sure why the bot didn't work. Please could you close the issue and try again

**Comment by eddiejaoude** [comment]
oh it worked, I guess there was a queue/delay

**Comment by Jyoti-prakash-rout** [comment]
Thank you!! ;) @eddiejaoude
