### ISSUE TITLE
[REVIEW] Astrodevil

### ISSUE THREAD

**Issue by Astrodevil** [EddieHubCommunity/support#2914]
### GitHub Profile Link

https://github.com/Astrodevil

**Comment by starlightknown** [comment]
profile looks good. few tips the profile views badge sometimes gives wrong numbers ( just what I heard from others)
the leetcode badge is not visible in dark mode

**Comment by krishguptadev** [comment]
Made PR to remove profile views badge and border on stat images: https://github.com/Astrodevil/Astrodevil/pull/4

Might consider using a consistent theme for all stat imgs

**Comment by Astrodevil** [comment]
@starlightknown @krishguptadev Thanks For The Suggestions🙏🏼. I will make changes.

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream...

Some suggestions 
- broken image under "open source gallery"
- suggest removing stats and recent activity, so that blog posts are higher
- pinned even number of repos like 2 or 3

**Comment by Astrodevil** [comment]
Thanks for reviewing my GitHub. Made some changes as you suggested.
