### ISSUE TITLE
[REVIEW] viveknathani

### ISSUE THREAD

**Issue by viveknathani** [EddieHubCommunity/support#2915]
### GitHub Profile Link

https://github.com/viveknathani/

**Comment by Ramanbaral** [comment]
Great profile! 
Love your projects.

**Comment by viveknathani** [comment]
Thanks a lot! @Ramanbaral

**Comment by krishguptadev** [comment]
All good but, You haven't set up a custom github profile though 😅 Just create a repo with the name of your username (for you it will be: `viveknathani/viveknathani`) and everything in the readme of that repo will appear on to your profile, you can take my profile as a example!

**Comment by viveknathani** [comment]
@krishguptadev yeah I am in the process of making one. Will push soon. Thanks for your review!

**Comment by krishguptadev** [comment]
> @krishguptadev yeah I am in the process of making one. Will push soon. Thanks for your review!

Awesome! Looking forward to seeing it soon! 😊

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream...

Some suggestions 
- try to pin even number of repos
- try to do more code reviews
- maybe add a bit more to your description, what are you learning and creating
- join EddieHub 😉
