### ISSUE TITLE
[REVIEW] luna: A DSL that translates to regex

### ISSUE THREAD

**Issue by AbhinavOmprakash** [EddieHubCommunity/support#2922]
### Project link

https://github.com/AbhinavOmprakash/luna

**Comment by schmelto** [comment]
Consider adding a code of conduct

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream...

Some suggestions 
- fix failing GitHub action on the latest commit
- hide packages and other GitHub features not being used
- suggest using issues with labels to get more contributors
- possibly a screenshot or animated gif in the readme
