### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Ramanbaral** [EddieHubCommunity/support#2949]
### What would you like to share?

I am new to open source and I would really like to contribute in the community. I really like the approach of the this community "Collaboration 1st, Code 2nd".

can someone please guide me?

**Comment by schmelto** [comment]
Sure you can contribute to some of our beginner friendly projects like "awsome gh profiles" or "linkfree".
Otherwise feel free to comment, review, open prs / issues in one of our repositorries.

Hope that helps.

Further you can join our discord. http://discord.eddiehub.org/
