### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Shivansh-yadav13** [EddieHubCommunity/support#2961]
### Name

Shivansh Yadav

### Discord Username (if applicable)

Shivansh Yadav#6952

### Additional Context

I got to know about this amazing ⭐ organization from the commclassroom discord server, I am new to Open Source 🤓 and **EddieHubCommunity** is where I made my first few pull requests.
#### What do I like about the community ?
- **The EddieHubCommunity** is so welcoming 🙋‍‍♂️.
-  Super friendly with everyone 🙂.
- Made it easier for me to start my open source journey 👨‍💻.
- Super helpful people 👬‍.

I started my open source journey with **EddieHubCommunity**, I would like to continue contributing and stay with this community.

**Comment by krishguptadev** [comment]
Welcome to the community!
