### ISSUE TITLE
[REVIEW] elenajp

### ISSUE THREAD

**Issue by elenajp** [EddieHubCommunity/support#2965]
### GitHub Profile Link

https://github.com/elenajp

**Comment by krishguptadev** [comment]
Looks good to me! 😄 I made a PR to your repository (https://github.com/elenajp/elenajp/pull/8) for a few minor improvements, aside from them I would suggest to:

- Add dynamic blogs using GH Actions, if you have a blog
- Add at least 2 Stat images in total
- Link to your site in the header image.

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream...

Some suggestions 
- maybe remove the widget
- you could pin 2 or 4 of your favourite repos
