### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Tejas-Teju** [EddieHubCommunity/support#2967]
### Name

Tejas S

### Discord Username (if applicable)

Tejasteju#1276

### Additional Context

Google, I like the fact that this is the best place to start with open source hence I would like to join and start my open source journey.

**Comment by krishguptadev** [comment]
Welcome to the community! Check your mail for an invite 😄

**Comment by Tejas-Teju** [comment]
Thanks @krishguptadev , Looking forward to contribute to projects. Let me know if you find any good-first-issues or beginner friendly issues.

**Comment by krishguptadev** [comment]
> Thanks @krishguptadev , Looking forward to contribute to projects. Let me know if you find any good-first-issues or beginner friendly issues.

Sure! Would recommend keeping an eye on the good-first-issues channel in EddieHub 🙂
