### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by thuongtruong1009** [EddieHubCommunity/support#2969]
### Name

Tran Nguyen Thuong Truong - @thuongtruong1009

### Discord Username (if applicable)

thuongtruong1009

### Additional Context

Hi guys!
Because this organization is a great community for me.
I want to join this organization for learning good Developer Skills and contribute to Open Source.
Nice to meet you!
Thank you very much!

**Comment by krishguptadev** [comment]
Welcome to the community! Check your email for an invite.

**Comment by thuongtruong1009** [comment]
> Welcome to the community! Check your email for an invite.

Thank you very much!
