### ISSUE TITLE
[REVIEW] eebbann

### ISSUE THREAD

**Issue by eebbann** [EddieHubCommunity/support#2973]
### GitHub Profile Link

https://github.com/eebbann

**Comment by krishguptadev** [comment]
Consider adding an Avatar/Profile Picture for yourself

A website or portfolio would be nice too 😄

Made PR https://github.com/eebbann/eebbann/pull/2 to improve your profile by adding stats. More PRs will come soon 🚀

**Comment by weeyin83** [comment]
Great start to your profile, looking forward to seeing where you take it.

**Comment by eebbann** [comment]
Thanks guys i really appreciate @krishguptadev and @weeyin83

**Comment by eddiejaoude** [comment]
Great profile, reviewed on live stream https://www.youtube.com/watch?v=JQ1wZRjint8 ... some suggestions...

- I prefer a real picture of the person, I think it is more personal
- the widgets take up too much space, I suggest removing them or have them in 1 row (side by side)
