### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Rajaniraiyn** [EddieHubCommunity/support#2978]
### Name

Rajaniraiyn

### Additional Context

I am an open-source freak. Currently I am working on a very large Project [Raj Lang](https://github.com/rajlang/), for that I need a lot of friends. I have a goal to achieve tech self-sustainability. I come to know that this organization has done a great job on promoting opensource around the world. I have a desire to contribute to the world.

**Comment by krishguptadev** [comment]
Welcome to the community 😄 Check your default GitHub Email for an invite
