### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ShubhamYadav7063** [EddieHubCommunity/support#2979]
### Name

ShubhamYadav7063

### Additional Context

I've seen Kunal Kushwaha's podcast with Eddie. Thing I like about this community is their dedication towards the community and open source. I want to join this community because I'm new to open source and to get some knowledge and contribute to Open Source.

**Comment by krishguptadev** [comment]
Welcome to the community 😄 Check your default GitHub Email for an invite
