### ISSUE TITLE
[REVIEW] fabiocaccamo

### ISSUE THREAD

**Issue by fabiocaccamo** [EddieHubCommunity/support#2986]
### GitHub Profile Link

https://github.com/fabiocaccamo

**Comment by krishguptadev** [comment]
All good but, You haven't set up a custom github profile though 😅 Just create a repo with the name of your username (for you it will be: `fabiocaccamo/fabiocaccamo`) and everything in the readme of that repo will appear on to your profile, you can take my profile as an example!
