### ISSUE TITLE
Please Review my Resume

### ISSUE THREAD

**Issue by dhananjayandayalan** [EddieHubCommunity/support#2991]

**Comment by emmalearnscode** [comment]
Hi @dhananjayandayalan can you add a link to your resume?

**Comment by krishguptadev** [comment]
Hi @dhananjayandayalan please use [this template](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=resume+review%2Clive+stream+review&template=resume-review.yml&title=%5BREVIEW%5D) for a resume review 😃 Also please close this issue 🙂
