### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by sohamp19** [EddieHubCommunity/support#2992]
### Name

Soham Parate

### Discord Username (if applicable)

st1nG#5186

### Additional Context

I heard about EddieHub on youtube, I am a beginner and have already joined the discord server. 

I like the fact that there will always be someone to help me with any beginner issue that I encounter over here. I am currently learning basics of web development, and people on the discord server have already answered few of my beginner questions.

EddieHub, in my opinion, would a great place to start my open source journey.

**Comment by krishguptadev** [comment]
Welcome to the community!
