### ISSUE TITLE
[REVIEW] dhananjayandayalans resume

### ISSUE THREAD

**Issue by dhananjayandayalan** [EddieHubCommunity/support#2993]
### Resume link

https://drive.google.com/file/d/1eVBK196J9CPb-qBd_I0yi8_9OTNLLjt8/view?usp=sharing

**Comment by krishguptadev** [comment]
Nice resume! I'd like to suggest the following:

- A Pic of yours would be nice
- Maybe give some more whitespace

**Comment by ditsuke** [comment]
> * A Pic of yours would be nice

Uhh... I don't like pictures in resumes.

**Comment by krishguptadev** [comment]
> > * A Pic of yours would be nice
> 
> Uhh... I don't like pictures in resumes.

The recruiter wants to work with you so they might wanna see your pic

**Comment by ditsuke** [comment]
> > > * A Pic of yours would be nice
> > 
> > 
> > Uhh... I don't like pictures in resumes.
> 
> The recruiter wants to work with you so they might wanna see your pic

In practice, adding a picture can end up hurting your chances of getting an interview.

Generally speaking, resumes should only have information relevant to your application — the way you look does not have a bearing on how you work, your experiences and your accomplishments. 
Adding a picture can introduce conscious or subconscious bias based on the way you look, your race, your gender or other factors which can give the reviewer a chance to discriminate. For much of the same reasons, it's not a good idea to mention your marital status, religious beliefs, sexual orientation or political views on your resume — they should not have a place in your professional life.

Ultimately, resumes are tools for securing interviews. Your face comes out anyways, but it has _lesser_ chances of hurting you once you've already made it through the short resume screen. 😃

**Comment by dhananjayandayalan** [comment]
Thanks🙂

**Comment by dhananjayandayalan** [comment]
Sure @emmalearnscode , I'll correct it. Thanks for the feedback😊

**Comment by eddiejaoude** [comment]
I was going to review on a video, but the file cannot be found. I will close.
