### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by nerdjfpb** [EddieHubCommunity/support#2996]
### Name

Muhammad Ali

### Discord Username (if applicable)

nerdjfpb#9854

### Additional Context

I saw Eddie in twitter first. I know open source for last few years but never really contribute anything. I'm a software engineer for around 5 years now so I'm just planning to do some help to open source because I use a lots of stuff from open source. 

Hope this will be a great journey with this community!

**Comment by krishguptadev** [comment]
Welcome to the community!
