### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Saurabh-Suchak** [EddieHubCommunity/support#2997]
### Name

Saurabh

### Discord Username (if applicable)

Saurabh#6910

### Additional Context

I came to know about Eddie largely due to his Youtube channel.
I like the fact that this community guides beginners into the open source domain and helps them.There is so much value and new things to learn from  so I am also interested to be a part of this awesome community and contribute to the best of my abilities.

**Comment by krishguptadev** [comment]
Welcome to the community!
