### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by avneesh0612** [EddieHubCommunity/support#2998]
### Name

Avneesh Agarwal

### Discord Username (if applicable)

Avneesh#5806 

### Additional Context

Hey there, I got to know about Eddie from Francesco. I am loving that this community is helping so many people to improve their profiles, OSS projects and their portfolios! I would love to help others too :D

**Comment by krishguptadev** [comment]
Welcome to the community!

**Comment by avneesh0612** [comment]
Thank you!
