### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by tymsai** [EddieHubCommunity/support#2999]
### Name

T.Y.M.SAI

### Additional Context

I saw Eddie in twitter first. I know open source for last few years but never really contribute anything. I'm a C/C++ Developer for around 2 years now so I'm just planning to do some help to open source because I use a lots of stuff from open source.

Hope this will be a great journey with this community!

**Comment by krishguptadev** [comment]
Welcome to the community! ❤️
