### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shrutiiaroraaa** [EddieHubCommunity/support#3006]
### Name

Shruti Arora

### Discord Username (if applicable)

shrutii#1672

### Additional Context

I met Eddie on Twitter and was flattered by his skills and community work and how amazing a mentor he is . Eddie's reputation is certainly a factor. I would love to be a part of this growth and want to enter in the Open Source World .

**Comment by krishguptadev** [comment]
Welcome to the community!
