### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ewainy** [EddieHubCommunity/support#3008]
### Name

Emma Wain

### Discord Username (if applicable)

ewainy#0401

### Additional Context

I met Eddie on Twitter, started following and talking to him because he was so positive and supportive and doing amazing things in the community! I want to join Eddie's community because it is inclusive and so that I can help in any way possible and give back to the community and help others along their way on their journey 😊

**Comment by krishguptadev** [comment]
Welcome to the community ❤️
