### ISSUE TITLE
[OTHER] Regarding Invitation to join the Org!

### ISSUE THREAD

**Issue by kr-anurag** [EddieHubCommunity/support#3009]
### Name

Anurag

### Discord Username (if applicable)

anurag#2281

### Additional Context

Hey there
I got to know about Eddie Hub during Hacktoberfest #2021, and I'm forever grateful for it. So I wanna join Eddie Hub Org on GitHub!

**Comment by krishguptadev** [comment]
Welcome to the community! ❤️
