### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by salmantec** [EddieHubCommunity/support#3010]
### Name

Mohamed Salman

### Discord Username (if applicable)

salman#4319

### Additional Context

I have recently started following Eddie, I like the way he puts his efforts on the open-source to help others. I would like to help each other in this open source world.

**Comment by krishguptadev** [comment]
Welcome to the community! ❤️

**Comment by salmantec** [comment]
Hi, I'm glad to be a part of this group. Thank you for the warm welcome.
