### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Aditya-Gupta1** [EddieHubCommunity/support#3012]
### Name

Aditya Gupta

### Discord Username (if applicable)

Aditya008

### Additional Context

I got to know about Eddie and this community from Twitter.
I want to start my open-source journey by being a part of this community. 
I haven't done any significant open source contributions yet and with this, I'm planning to step up my open-source game.

**Comment by krishguptadev** [comment]
Welcome to the comm!

**Comment by Aditya-Gupta1** [comment]
Thanks, @krishguptadev ! Let me know if you have any project suggestions for me!
I'm experienced in Python and Scala language and a little bit of JavaScript.

**Comment by krishguptadev** [comment]
> Thanks, @krishguptadev ! Let me know if you have any project suggestions for me! I'm experienced in Python and Scala language and a little bit of JavaScript.

Projects to contribute?

**Comment by Aditya-Gupta1** [comment]
Yes

**Comment by krishguptadev** [comment]
> Yes, in this organisation.

Linkfree and event calendar are in js (React)
