### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by fabioalmeida100** [EddieHubCommunity/support#3014]
### Name

Fábio Almeida

### Additional Context

Hello! My Name if Fábio (aka FabIn).

I meet Eddie though other GitHub friend! I would like to join for contribute with others devs and I hope help improve the OpenSource projects here. I like the approach about of the Eddie in relation the collaboration.

**Comment by krishguptadev** [comment]
Welcome :D
