### ISSUE TITLE
[REVIEW] pooreffects

### ISSUE THREAD

**Issue by Pooreffects** [EddieHubCommunity/support#3016]
### Resume link

https://drive.google.com/file/d/1IH-GKCMXhSORj5ezTzevmKPyXoFCsAPx/view?usp=sharing

**Comment by krishguptadev** [comment]
A little white space would be nice 🤔

**Comment by schmelto** [comment]
Missing space 
![image](https://user-images.githubusercontent.com/30869493/143851710-be28a58e-e90c-4d7c-873c-6df0d5381daa.png)

**Comment by Pooreffects** [comment]
Thank you ever much for your feedback. 
I will refactor the typos and consider spacing a bit more @schmelto @krishguptadev 🙌

**Comment by emmalearnscode** [comment]
I really love the colours you’ve chosen. Just a couple of things I think could be improved:

- write the about section in first person like the rest of your resume, it sounds strange to read it in different perspectives. 
- align your columns to be the same, currently about section is not aligned with the section underneath and it is slightly jarring on the eye. Also align all your purple titles to the left so it makes them easier to see that they belong to the paragraph and easier for the eye to follow down the page.

**Comment by Pooreffects** [comment]
@emmalearnscode Alright! Although, do you think it was a turn-off having a 2-page resume?
& do you think it might have been better if the open-source/side projects were listed on the first page instead of work experience or the priority's better as it is?

**Comment by emmalearnscode** [comment]
@Pooreffects for me it wasn’t a turn off that it’s on two pages, I think 1-2 pages is fine. Personally, I would leave the order as it is, experience will weigh heaviest so it’s good that it comes first and will be seen first.

**Comment by eddiejaoude** [comment]
Looks good, some suggestions reviewed in video coming out soon on my youtube channel http://youtube.com/eddiejaoude

- have open source section on the 1st page if possible, this is what I always look for
- other sections seem to have the badge heading but open source doesn't
- I really like the design and profile picture - if people print it the links will be fine, but the dark background might not print so well
