### ISSUE TITLE
[REVIEW] still in progress Portfolio

### ISSUE THREAD

**Issue by Pooreffects** [EddieHubCommunity/support#3017]
### Portfolio link

https://www.pooreffects.com/

**Comment by krishguptadev** [comment]
Good portfolio but overlapping... 
![image](https://user-images.githubusercontent.com/91655303/143850859-73b89a70-26e0-40c7-922f-65a04ea4ec70.png)

This could be a button: 
![image](https://user-images.githubusercontent.com/91655303/143850918-6c5a42b7-fc46-4890-bea7-1f79207e8bcd.png)

Nice effects, but is it accessible?

**Comment by schmelto** [comment]
Take a look at the performance of your page. Also SEO should be a little bit improved.
![image](https://user-images.githubusercontent.com/30869493/143851436-eba769fd-04f8-43b8-bd94-776add1aeb41.png)

**Comment by Pooreffects** [comment]
Than

> Good portfolio but overlapping... ![image](https://user-images.githubusercontent.com/91655303/143850859-73b89a70-26e0-40c7-922f-65a04ea4ec70.png)
> 
> This could be a button: ![image](https://user-images.githubusercontent.com/91655303/143850918-6c5a42b7-fc46-4890-bea7-1f79207e8bcd.png)
> 
> Nice effects, but is it accessible?

Thanks a million for your time and consideration.
Can you please elaborate more on what screen size you have reviewed the website on, and provide thoughts on what can be improved?

**Comment by Pooreffects** [comment]
> Take a look at the performance of your page. Also, SEO should be a little bit improved. ![image](https://user-images.githubusercontent.com/30869493/143851436-eba769fd-04f8-43b8-bd94-776add1aeb41.png)

Sure will do. Any thoughts/recommendations on what I might do to improve SEO and performance in a Nuxt application. 
PS: Should I open-source the project?

**Comment by Pooreffects** [comment]
Roger that. I will work on improving the responsiveness and the overall design and UX.

**Comment by emmalearnscode** [comment]
It’s a really nice design, here are just a few things that could be improved:

- inconsistent use of full stops in the first paragraph 
![9A676570-DA51-4463-B4CF-F563F2E26815](https://user-images.githubusercontent.com/57045550/143916795-669ef122-df8c-4a0b-901d-8a842935e42f.jpeg)

- failing colour contrast on headings 
![3F8ABDB2-A341-44EE-B1A4-86D5771AC3C9](https://user-images.githubusercontent.com/57045550/143916877-c338436c-a8a0-4fab-8c70-f94567327cc4.jpeg)

- some overlapping issues in projects (iPad Pro horizontal) Also, I want to be able to swipe them but they only move by clicking (no idea if that’s possible)
![8D1F7D1F-0947-4232-B6C6-C8C098C092D5](https://user-images.githubusercontent.com/57045550/143916976-0578dc4e-b087-450a-b005-d0afcf7df4a0.jpeg)

- where it says ‘book’ in the menu, I interpreted it that you’d written a book, not that I could book a time to chat with you so maybe make that clearer.

**Comment by Pooreffects** [comment]
@emmalearnscode Thanks a million for your fruitful feedback.
I will definitely add those to the enhancements bucket 😊

**Comment by eddiejaoude** [comment]
Closing as no GitHub url
