### ISSUE TITLE
[BUG] the README.md in the support section has a link to "finding-open-source-projects.md" which is showing "Page not found" error

### ISSUE THREAD

**Issue by pranv-sonawane** [EddieHubCommunity/support#3020]
### Description of the bug

*link: https://github.com/EddieHubCommunity/support/blob/main/tips/finding-open-source-projects.md 
is it supposed to be updated? If yes, then how can I update it?*

### Working Environment (e.g. operating system, browser, device)

browser

### Please add screenshots (if applicable)

![buggg](https://user-images.githubusercontent.com/55915944/143912417-528422e2-7e74-4362-8fc9-e2860bfe772b.jpg)

![bugg](https://user-images.githubusercontent.com/55915944/143911069-51c620a2-b7bf-4894-a7e9-cacee362e96a.jpg)

__This is my first time raising an issue. Thanks for all the support @EddieHubCommunity__

**Comment by Panquesito7** [comment]
Looks like this was introduced due to the latest changes implementing Docsify.
Anyone who wants a green square, this is the correct link: https://github.com/EddieHubCommunity/support/blob/main/docs/tips/finding-open-source-projects.md

There might be other broken links as well. 🙂

**Comment by pranv-sonawane** [comment]
i want my first green square!!!
