### ISSUE TITLE
[BUG] Broken link in support for Open source tips from EddieBot 

### ISSUE THREAD

**Issue by pranv-sonawane** [EddieHubCommunity/support#3022]
### Description of the bug

The link in the support readme for Open source tips from EddieBot was broken

### Project stack or language (e.g. front-end)

readme file

### Working Environment (e.g. operating system, browser, device)

browser

### Please add screenshots (if applicable)

![pr2](https://user-images.githubusercontent.com/55915944/143921336-8d44a515-28cc-478c-b96d-98ae34ad7a7f.jpg)

**Comment by nhcarrigan** [comment]
Closed in #3021
