### ISSUE TITLE
[REVIEW] Kira272921

### ISSUE THREAD

**Issue by Kira272921** [EddieHubCommunity/support#3036]
### GitHub Profile Link

https://github.com/Kira272921

**Comment by schmelto** [comment]
Consider removing the profile views count due it's inaccurate otherwise I like your profile

**Comment by Kira272921** [comment]
> Consider removing the profile views count due it's inaccurate otherwise I like your profile

Thanks 😄

I have removed the `profile view count`

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- duplicate profile photo is not a great use of space
- GitHub widget stats could be left/right to make better use of space
- I am not a fan of the trophies, this is just a personal preference
