### ISSUE TITLE
[REVIEW] Polokghosh53

### ISSUE THREAD

**Issue by Polokghosh53** [EddieHubCommunity/support#3043]
### GitHub Profile Link

https://github.com/Polokghosh53

**Comment by hellodeborahuk** [comment]
Hi Polok, I like the experiences section of your profile, it's nice to see something different. I use dark mode and I can't see clearly the icons along the top. The "my pronouns are" doesn't have great contrast either but can be seen. 
![image](https://user-images.githubusercontent.com/29425781/144595014-d1f96566-b9fc-4fc3-b629-503eaeb86f32.png)

**Comment by Polokghosh53** [comment]
> 

Well you are right about the differences in the dark mode, even I had seen them. Have to find something color neutral I guess.
Thank you for the review. :)

**Comment by eddiejaoude** [comment]
Reviewed on live stream...

Looks good, some suggestions
- maybe too much text, makes it like a resume
- do the social icons display in dark mode?
- A+ widget always shows A+ suggestion removing
- Trophy widgets wrap on multiple lines (suggest removing)
- suggest pinning max 4 repos
