### ISSUE TITLE
[REVIEW] thelabuzov

### ISSUE THREAD

**Issue by thelabuzov** [EddieHubCommunity/support#3048]
### GitHub Profile Link

https://github.com/thelabuzov

**Comment by shubhimainalli** [comment]
Hey @thelabuzov amazing portfolio.

**Comment by eddiejaoude** [comment]
Great profile, reviewed on live stream https://www.youtube.com/watch?v=JQ1wZRjint8 ... some suggestions...

- great photo!
- separate the examples from the widget with headings
- I think there are too many widgets
- move tech stack to the top
- try to do more code reviews and issues
