### ISSUE TITLE
[REVIEW] SAEb-ai

### ISSUE THREAD

**Issue by SAEb-ai** [EddieHubCommunity/support#3099]
### GitHub Profile Link

https://github.com/SAEb-ai

**Comment by shubhimainalli** [comment]
Hi @SAEb-ai great profile, small suggestion developer is written twice 
![image](https://user-images.githubusercontent.com/70970530/168869209-93d74027-b097-42f3-a281-7ce8a75f3ad6.png)
and you add some points to your bio

**Comment by eddiejaoude** [comment]
Great profile, reviewed on live stream https://www.youtube.com/watch?v=JQ1wZRjint8 ... some suggestions...

- profile picture looks great
- join EddieHub Org
- I don't think profile views adds value
- suggest doing more issues
