### ISSUE TITLE
[REVIEW] Amr Monier

### ISSUE THREAD

**Issue by AmrMonier** [EddieHubCommunity/support#3100]
### Resume link

https://drive.google.com/file/d/1IQQ0NfGJNLOILNkbxI9M2FfMBon_ota_/view?usp=sharing

**Comment by emmalearnscode** [comment]
Apologies for all the notes and using red (I just wanted it to stand out and it was easiest to mark small grammar errors with a pen). I hope some of my notes are useful to you. 
![B144798C-E9CE-43EE-9D1E-E09E8A5E5101](https://user-images.githubusercontent.com/57045550/146436076-ba90b0bd-4646-417a-b7e9-98454ebdb453.jpeg)

**Comment by AmrMonier** [comment]
@emmalearnscode thank you very much for your review. it helped me a lot to improve my resume as a result i created a new one and here is the link in case you would like to look at it and i would appreciate getting your opinion about it 
https://drive.google.com/file/d/1D5QgOH-AXpAJSSNnJh-W1VnjV4zR5ImZ/view?usp=sharing

**Comment by emmalearnscode** [comment]
> @emmalearnscode thank you very much for your review. it helped me a lot to improve my resume as a result i created a new one and here is the link in case you would like to look at it and i would appreciate getting your opinion about it
> https://drive.google.com/file/d/1D5QgOH-AXpAJSSNnJh-W1VnjV4zR5ImZ/view?usp=sharing

Great job, Amr! Here’s some more notes :)

![69CD9CF9-97AF-4A98-A197-67D44706A685](https://user-images.githubusercontent.com/57045550/148587925-e0ba9755-0d0b-4c38-a915-a722a5a7e313.jpeg)

**Comment by AmrMonier** [comment]
> > @emmalearnscode thank you very much for your review. it helped me a lot to improve my resume as a result i created a new one and here is the link in case you would like to look at it and i would appreciate getting your opinion about it
> > https://drive.google.com/file/d/1D5QgOH-AXpAJSSNnJh-W1VnjV4zR5ImZ/view?usp=sharing
> 
> Great job, Amr! Here’s some more notes :)
> 
> ![69CD9CF9-97AF-4A98-A197-67D44706A685](https://user-images.githubusercontent.com/57045550/148587925-e0ba9755-0d0b-4c38-a915-a722a5a7e313.jpeg)

thank you @emmalearnscode  for the great helpful notes as usual

**Comment by eddiejaoude** [comment]
Looks good, some suggestions reviewed in video coming out soon on my youtube channel http://youtube.com/eddiejaoude

- I recommend changing the `Projects` title to have `Open Source Projects`, make it clear they are open source
- Have links to each open source project, full link displayed and clickable, make it easier for them to have a look
- Include technologies in the project section for each item
- Freelance on Upwork, can you add a link to your profile, also include how many clients you have (approximately, for example 5+)
- I also suggest moving the open source project section higher up
