### ISSUE TITLE
[REVIEW] Amr Monier

### ISSUE THREAD

**Issue by AmrMonier** [EddieHubCommunity/support#3101]
### GitHub Profile Link

https://www.github.com/AmrMonier

**Comment by shubhimainalli** [comment]
Hey @AmrMonier your profile is great, here are my suggestions:
1. Amr Monier's GitHub activity graph --> image is missing
2. you can align the images one below other, might look good
![image](https://user-images.githubusercontent.com/70970530/168443867-39d8b1dc-6e4e-4a17-b8c9-e43e05d2a6f7.png)

**Comment by AmrMonier** [comment]
@shubhimainalli 
For some reason this activity graph works only when you refresh the page, weird but haven't been able to fix it.
Second, I really appreciate your review 🙏😁, and thank you for your time and the good advice

**Comment by shubhimainalli** [comment]
It looks good and the graph is working. Good job you fixed the issue!!

**Comment by eddiejaoude** [comment]
Great profile, reviewed on live stream https://www.youtube.com/watch?v=JQ1wZRjint8 ... some suggestions...

- photo looks good but very dark, suggest having something brighter
- banner is too large (high), takes too much space
- animated text doesn't work in all browsers
- too many widgets
