### ISSUE TITLE
[REVIEW] koushikpuppala

### ISSUE THREAD

**Issue by koushikpuppala** [EddieHubCommunity/support#3107]
### GitHub Profile Link

https://github.com/koushikpuppala

**Comment by shubhimainalli** [comment]
Awesome profile @koushikpuppala

**Comment by eddiejaoude** [comment]
Reviewed on live stream, looks great, some suggestions

- remove all widgets
- very commit heavy, suggest doing Pull Requests, Issues and code reviews
