### ISSUE TITLE
[REVIEW] AnishDe12020

### ISSUE THREAD

**Issue by AnishDe12020** [EddieHubCommunity/support#3113]
### GitHub Profile Link

https://github.com/AnishDe12020

**Comment by shubhimainalli** [comment]
Amazing profile @AnishDe12020

**Comment by AnishDe12020** [comment]
> Amazing profile @AnishDe12020

Glad you liked it!

**Comment by eddiejaoude** [comment]
Looks good, some suggestions (reviewed on live stream)

- Banner is quite large, suggest halving the height
- Too many widgets
- Images to have alt text
- Pin max of 4 repos
- Contributors graph to be more balanced, try to do more code reviews, pull requests and issues
