### ISSUE TITLE
[REVIEW] abrahamalen

### ISSUE THREAD

**Issue by abrahamalen** [EddieHubCommunity/support#3115]
### GitHub Profile Link

https://github.com/abrahamalen

**Comment by AmrMonier** [comment]
very nice profile i would just suggest minor changes just center the first header with your name and the activity stats and i have made a PR with those incase you might want to add them

**Comment by abrahamalen** [comment]
> very nice profile i would just suggest minor changes just center the first header with your name and the activity stats and i have made a PR with those incase you might want to add them

@AmrMonier Hey thanks for the changes
