### ISSUE TITLE
[REVIEW] boyka-framework

### ISSUE THREAD

**Issue by WasiqB** [EddieHubCommunity/support#3116]
### Project link

https://github.com/WasiqBhamla/boyka-framework

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- Table of contents is not required, this is created by GitHub
- Code screenshots are not great, suggest using code block
- Gitpod badge is not in a great place
