### ISSUE TITLE
[REVIEW] WasiqB

### ISSUE THREAD

**Issue by WasiqB** [EddieHubCommunity/support#3117]
### GitHub Profile Link

https://github.com/WasiqB

**Comment by Kira272921** [comment]
I like your simple and minimalistic profile 🎉

**Comment by WasiqB** [comment]
@Kira272921 , thanks. It's good to know that you liked it. Would appreciate if you can share feedback on improving it further.

**Comment by Kira272921** [comment]
@WasiqB Maybe trying mentioning on which open source projects you are currently working, and trying adding their repository links as well 

🤔 It would be good, if there is a techstack section. You can look at my profile for the idea and [here](https://github.com/Ileriayo/markdown-badges) is a great repository which contains lot of README badges

**Comment by WasiqB** [comment]
Thanks for sharing the feedback, will look into the links you've shared and update the profile accordingly.

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream, some suggestions are:

- suggest removing widgets
- also the duplicate repo widgets are not required
- pin max 4 repos
