### ISSUE TITLE
[REVIEW] AdventOfCode repo

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#3118]
### Project link

https://github.com/SashoStoichkov/AdventOfCode2021

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- hide wiki if not using (docs are better in the `docs` folder anyway)
- hide releases and packages if not using
- example in the README (maybe first challenge)
-
