### ISSUE TITLE
[REVIEW] subinsk

### ISSUE THREAD

**Issue by subinsk** [EddieHubCommunity/support#3119]
### GitHub Profile Link

https://github.com/subinsk

**Comment by Kira272921** [comment]
Hey 👋, Here are few changes needed to be dono to your profile 
- Consider removing the profile views count due it's inaccurate
- Trying aligning the social media badges side by side 
- Maybe adding all the widgets under one section

**Comment by eddiejaoude** [comment]
Looks good, some suggestions
- great profile picture
- make more use of the bio
- suggest moving "buy me a coffee to the end of the profile"
- make better use of the blank space on the right
- remove 1 or 3 of the pinned repos to make 4 or 2
