### ISSUE TITLE
[REVIEW] geegatomar

### ISSUE THREAD

**Issue by geegatomar** [EddieHubCommunity/support#3142]
### GitHub Profile Link

https://github.com/geegatomar

**Comment by schmelto** [comment]
Maybe consider enhancing the profile with a little more sections about yourself

**Comment by AmrMonier** [comment]
it would be much better if you added more information about who you are? what are capable of ? what programming languages and frameworks do you use. you can take a look on this repo provided by eddie community it contain a lot of awesome profiles https://github.com/EddieHubCommunity/awesome-github-profiles

**Comment by eddiejaoude** [comment]
Looks good, some suggestions
- use the profile fields for example bio, link, location etc
- add more information in the customised profile
