### ISSUE TITLE
[REVIEW] krishguptadev

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/support#3151]
### GitHub Profile Link

https://github.com/krishguptadev

**I've applied the changes requested from https://github.com/EddieHubCommunity/support/issues/2716**

**Comment by schmelto** [comment]
🚀

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=wQvlaYc5nl8

Wow looks great 👍
