### ISSUE TITLE
[REVIEW] inb

### ISSUE THREAD

**Issue by joshiayush** [EddieHubCommunity/support#3159]
### Project link

https://github.com/joshiayush/inb

**Comment by schmelto** [comment]
Nice repo! Some thoughts from my side. 

There is lots of duplicate information in the readme maybe considering removing the badges showing the open issues etc and I think also the tech stack could be found at the right side provided by GitHub itself.  

Further consider adding issue templates (maybe also issue forms due those are way cooler) to the repo. 

Also take a look at the failing action.

**Comment by eddiejaoude** [comment]
Looks good, some suggestions
- wiki looks empty, suggest removing tab
- hide releases and packages as not being used
- hide project board tab as not used
