### ISSUE TITLE
[REVIEW] Susmita-Dey

### ISSUE THREAD

**Issue by Susmita-Dey** [EddieHubCommunity/support#3163]
### GitHub Profile Link

https://github.com/Susmita-Dey

**Comment by AmrMonier** [comment]
you currently using the basic profile template from github you can improve it by adding headers and divide it into sections add brief introduction about yourself and what you do what programming languages and framework you use. you may also use some of the project that provide charts and graphs for your activity on github
you can take alook on my profile and other profiles in this repo https://github.com/EddieHubCommunity/awesome-github-profiles

**Comment by eddiejaoude** [comment]
Looks great!

- I am not keen on `visitors` badge
- profile is a bit long, try to remove lower priority items
