### ISSUE TITLE
[REVIEW] Daily.Dev

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/support#3171]
### Project link

https://github.com/dailydotdev/daily

**Comment by krishguptadev** [comment]
## Feature Request

- Use releases.
- Hide Packages

![image](https://user-images.githubusercontent.com/91655303/147256387-06c0dfad-6193-4a94-9cda-57cfc098d79d.png)

- Move the wiki to a docs folder

![image](https://user-images.githubusercontent.com/91655303/147256413-26fc99fe-96a1-4297-b1e4-4e01093fe819.png)

- Pull Request Template

- GitHub Actions CI

- Make the branch  `main`

### Description

Watch live stream recording here => https://www.youtube.com/watch?v=wQvlaYc5nl8

**Comment by eddiejaoude** [comment]
Some thoughts...

- using conventional commits which is awesome! So could create releases a GitHub Action with a change log https://github.com/EddieHubCommunity/LinkFree/releases
- Wiki to have a link to docs repo
- Maybe use `quickstart` in the getting started section
