### ISSUE TITLE
[REVIEW] NikhilSharmaWe

### ISSUE THREAD

**Issue by NikhilSharmaWe** [EddieHubCommunity/support#3177]
### GitHub Profile Link

https://github.com/NikhilSharmaWe

**Comment by AmrMonier** [comment]
your profile looks great and i have just suggested some minor changes hopefully it would be helpful.
https://github.com/NikhilSharmaWe/NikhilSharmaWe/pull/2

**Comment by NikhilSharmaWe** [comment]
@AmrMonier thanks for the suggestions

**Comment by weeyin83** [comment]
Nice work! I think the only change I would make is use icons for your social media links, they are getting a bit lost at the moment. 👍
