### ISSUE TITLE
[REVIEW] bharadwajduggaraju

### ISSUE THREAD

**Issue by bharadx07** [EddieHubCommunity/support#3188]
### GitHub Profile Link

https://github.com/bharadwajduggaraju

**Comment by schmelto** [comment]
I would use 'I' as pronunciation but this is only my personal preference otherwise I really like the text and the profile.

**Comment by bharadwajduggaraju** [comment]
Thanks a lot, I think that is a useful change that I will probably implement. If you like my work, a follow would be hugely appreciated!

**Comment by bharadwajduggaraju** [comment]
@schmelto do you think that adding the way to pronounce my name (brod-waj) right next to my name would also be a viable solution?

**Comment by bharadwajduggaraju** [comment]
And some other useful feedback would be what other sections should I add to the readme/what badges to add.

**Comment by schmelto** [comment]
> @schmelto do you think that adding the way to pronounce my name (brod-waj) right next to my name would also be a viable solution?

I think this could be a good idea

**Comment by eddiejaoude** [comment]
Profile not found, so I will close
