### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by linuxdotexe** [EddieHubCommunity/support#3208]
### Name

sai nivas mangu

### Discord Username (if applicable)

linux.exe

### Additional Context

Hey! I was looking to network with fellow developers around the world and I was searching for welcoming communities and following new people on Twitter. That's when I found Eddie's Twitter profile. I went to the website in the profile and EddieHub from there (or the other way around) and liked what I saw. I immediately joined the Discord server and spent some time looking around. I was on the organization page of EddieHub, looking at the projects and seeing if I can contribute anything and I saw that I can join the organization. Truth be told, I love being part of communities and working with people. I think being part of an active community and participating in their activities can make me a better developer and a person. That is why I want to be a part of this community :)

A little bit about myself:
I am a CS major from India. I like making small CLI apps in python and I plan on making some of them into Flask projects for the web. I am currently learning SQLite to use with python. I'm interested in the front-end aspect of web development and I am currently working on my own LinkTree clone [EinLink](https://github.com/linuxdotexe/einlink) and a website for my [nordic wallpapers](https://github.com/nordic-wallpapers) repository (find the project at [nordic-wallpapers-website](https://github.com/nordic-wallpapers-website)). Both the projects I have are works in progress. Here are some of the python scripts I wrote for Hacktoberfest 2021:

- [Pomodoro CLI app](https://github.com/gdsc-gvp/Pyscripts/tree/main/pomodoro)
- [A CLI password generator](https://github.com/gdsc-gvp/Pyscripts/tree/main/passwordGenerator)
- [A simple rock-paper-scissors script](https://github.com/gdsc-gvp/Pyscripts/tree/main/rock-paper-scissors)

**Comment by eddiejaoude** [comment]
Welcome, don't forget to share your introduction in our [Discord](http://discord.eddiehub.org)
