### ISSUE TITLE
[REVIEW] VaibhavUpreti

### ISSUE THREAD

**Issue by VaibhavUpreti** [EddieHubCommunity/support#3216]
### GitHub Profile Link

https://github.com/VaibhavUpreti

**Comment by shubhimainalli** [comment]
Hey @VaibhavUpreti great profile, here are some suggestion:
1.You can add some relatable cover 
![image](https://user-images.githubusercontent.com/70970530/168867127-b7e2dfe7-e4bd-472e-94eb-6891e51dc795.png)
2.There are so many icons going on here can you make it look little neat or horizontal aligned.
![image](https://user-images.githubusercontent.com/70970530/168867448-573f2da5-7661-4b52-a836-22ba74f1c416.png)
