### ISSUE TITLE
[REVIEW] Linkedin Redesigned Frontend

### ISSUE THREAD

**Issue by symaticvisuals** [EddieHubCommunity/support#3236]
### Project link

https://github.com/symaticvisuals/linkedin-redesigned-clone

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

Looks good, some thoughts
- use releases
- hide packages
- hide wiki
- deployment link does not work
- git ignore `.idea. folder
- great to see you using gitpod, but suggest adding badge to README
- recommend using issues + labels
