### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by qadirpervez** [EddieHubCommunity/support#3238]
### Resume link

https://docs.google.com/document/d/1981TiiTfjg1rky8ZFhwlu6aDqrq2hSwdg_TSVmapnBo/edit?usp=sharing

**Comment by emmalearnscode** [comment]
Really nice, clean layout which is easy to read. Great that you include your most recent work experience at the top. 

My suggestions:
- much of your work experience sentences start with the word ‘developed’. Try to mix it up a little with created, coded, collaborated on, pair programmed… etc. Also try to include something about the impact this had eg. Mentored 12 students who all went on to achieve x grade’, or ‘created xx program which is now used by xxxx number of people across xxxx number of schools’ or ‘developed x which increased revenue by xxx amount.
- Include links to project code or hosted sites where possible. If I were interested in interviewing you I’d want to be able to see your projects.

**Comment by eddiejaoude** [comment]
Looks good, some suggestions reviewed in video coming out soon on my youtube channel http://youtube.com/eddiejaoude

- adding open source projects to your resume, or if your projects are open source share GitHub links to them
- maybe spreading out over 2 pages, looks a big squished
