### ISSUE TITLE
[REVIEW] Portfolio review

### ISSUE THREAD

**Issue by SamiKamal** [EddieHubCommunity/support#3254]
### Portfolio link

https://www.samii.dev

### Repo Link
https://github.com/SamiKamal/portfolio

**Comment by shubhimainalli** [comment]
I have few suggestions to your github profile:
1.You can add profile picture
2.You can add bio aswell

**Comment by SamiKamal** [comment]
hey @shubhimainalli thanks for the suggestions, I appreciate that 😄

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- add repo description
- customise readme
- add code of conduct and license
- add topics
