### ISSUE TITLE
[REVIEW] lavakush07

### ISSUE THREAD

**Issue by lavakush07** [EddieHubCommunity/support#3334]
### GitHub Profile Link

https://github.com/lavakush07

**Comment by shubhimainalli** [comment]
Hey great portfolio @lavakush07. Small suggestion i see more of visuals you can add little bit about yourself, only if you wish too.
Overall good one!!

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- the animated snake doesn't work, so looks bad
- pin 4 repos
- contribute more to open source
