### ISSUE TITLE
[REVIEW] prabhkaur301

### ISSUE THREAD

**Issue by prabhkaur301** [EddieHubCommunity/support#3357]
### GitHub Profile Link

https://github.com/prabhkaur301

**Comment by shubhimainalli** [comment]
Wow great portfolio loved it @prabhkaur301!!

**Comment by prabhkaur301** [comment]
Thank you so much for feedback.

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- animated SVGs don't work well on safari, suggest changing/removing
- too many widgets, recommend removing some
- pin 4 repos (not 5)
- keep contributing to open source, also look at doing reviews and issues
