### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Rajp2294** [EddieHubCommunity/support#3389]
### Name

Raj Parekh

### Discord Username (if applicable)

shroud

### Additional Context

I came across eddie on youtube when I was searching about open-source, then I asked him about my doubts via commenting on his tweet to which he replied back here... https://twitter.com/eddiejaoude/status/1485544173868810240,
I want to learn and grow myself while giving back to the awesome and supportive tech community for which open source is the best way and since Eddie is the torchbearer in the open-source world, what better way than to work under his guidance!!

**Comment by Rajp2294** [comment]
How and where do I start? What should I do? I only know Java and DSA problem solving... I haven't built any major projects.

**Comment by eddiejaoude** [comment]
Join the EddieHub Discord and you can chat in there with the community

Here is a video I created that might help https://www.youtube.com/watch?v=8B_JWf7pG20
