### ISSUE TITLE
[REVIEW] KendallDoesCoding

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/support#3483]
### GitHub Profile Link

https://github.com/KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Created this as a duplicate, forgot I requested for the profile review already, this has a convo though, so will close the original issue https://github.com/EddieHubCommunity/support/issues/3483.

Discussed in #3505

**Comment by KendallDoesCoding** [comment]
Actually, re-opening this as eddie, reviews the issues depending on the time posted.

**Comment by KendallDoesCoding** [comment]
> First of all nice profile. Some suggestions form my side:

- consider making the banner a little bit smaller. (lots of unused space)
- consider removing the profile view count due its mostly inaccurate.

Suggestions by @schmelto

**Comment by eddiejaoude** [comment]
Closing as the user is banned due to abusive language
