### ISSUE TITLE
[REVIEW] KendallDoesCoding

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/support#3505]
### Project link

https://github.com/KendallDoesCoding

**Comment by schmelto** [comment]
First of all nice profile. Some suggestions form my side:

* consider making the banner a little bit smaller. (lots of unused space)
* consider removing the profile view count due its mostly inaccurate.

**Comment by KendallDoesCoding** [comment]
> First of all nice profile. Some suggestions form my side:
> 
> * consider making the banner a little bit smaller. (lots of unused space)
> * consider removing the profile view count due its mostly inaccurate.

thanks, will work on this shortly

**Comment by KendallDoesCoding** [comment]
Created this as a duplicate, forgot I requested for the profile review already, this has a convo though, so will close the original issue #3483.

**Comment by KendallDoesCoding** [comment]
> > First of all nice profile. Some suggestions form my side:
> > 
> > * consider making the banner a little bit smaller. (lots of unused space)
> > * consider removing the profile view count due its mostly inaccurate.
> 
> thanks, will work on this shortly

Removed the profile views, will have to make the size small using Canva for the banner though, will do that later.
