### ISSUE TITLE
[REVIEW] Ibrahim Raimi

### ISSUE THREAD

**Issue by ibrahimraimi** [EddieHubCommunity/support#3560]
### GitHub Profile Link

https://github.com/ibrahimraimi

**Comment by schmelto** [comment]
Like the banner 🚀

**Comment by ibrahimraimi** [comment]
Thanks @schmelto i made it with canva, i can share you the design if you want.

**Comment by KendallDoesCoding** [comment]
Looks good

- maybe make the banner a little bigger
- move the "Hey 👋" above the banner and center align it
- move the twitter underneath the banner
