### ISSUE TITLE
[REVIEW] Harshil-Jani

### ISSUE THREAD

**Issue by Harshil-Jani** [EddieHubCommunity/support#3573]
### GitHub Profile Link

https://github.com/Harshil-Jani

**Comment by schmelto** [comment]
Hey @Harshil-Jani it seems that you don't have a custom GitHub profile we can review. 
You could add one. Here is a course on how to do it https://www.eddiejaoude.io/course-github-profile-landing

**Comment by Harshil-Jani** [comment]
> Hey @Harshil-Jani it seems that you don't have a custom GitHub profile we can review. You could add one. Here is a course on how to do it https://www.eddiejaoude.io/course-github-profile-landing

Yo! Now, I do have one :)

**Comment by KendallDoesCoding** [comment]
Looks good

- make the banner a little small (so we can see a little of the text as well instead of scrolling, also coz the banner is a little too big 😆 )

**Comment by KendallDoesCoding** [comment]
The gmail icon redirects to: https://github.com/Harshil-Jani/Harshil-Jani/blob/main for some reason, instead of the mailto:
