### ISSUE TITLE
[REVIEW] yellowberard

### ISSUE THREAD

**Issue by yellowberard** [EddieHubCommunity/support#3577]
### GitHub Profile Link

https://github.com/yellowberard

**Comment by hellodeborahuk** [comment]
I like how you've got important contact links at the top. There's a lot of white space on the right, you could put all the languages, frameworks and tools all in one section. I'd definitely try and use all matching icons.

**Comment by yellowberard** [comment]
Thanks for the suggestion I will definitely work on it.

**Comment by KendallDoesCoding** [comment]
This is more-or-less the same as #1987 my only suggestion is

- On the last line of the profile, the word "repositories" maybe hyperlink the repo page for that word?

Repo page: https://github.com/yellowberard?tab=repositories

**Comment by yellowberard** [comment]
I will make the changes.

**Comment by KendallDoesCoding** [comment]
> I will make the changes.

Thanks!

**Comment by eddiejaoude** [comment]
Looks great, some thoughts...

- join EddieHub 😜 
- double title at the top looks a bit strange
- too many widgets, pick 1 or 2 (if 2, 1 single line)
- try to do more issues and code reviews
