### ISSUE TITLE
[REVIEW] krshdev

### ISSUE THREAD

**Issue by krshdev** [EddieHubCommunity/support#3584]
### GitHub Profile Link

https://github.com/krshdev

**Comment by krshdev** [comment]
(Already reviewed by eddie, for the guest reviewers today :D https://www.youtube.com/watch?v=HCsQWr5r6_s)

**Comment by hellodeborahuk** [comment]
I love the banner. I think having everything collapsable is amazing as it means people can expand if they want to or go straight to your pinned repos without it being a long scroll.

**Comment by schmelto** [comment]
Yessss link behind the banner 🚀

**Comment by krshdev** [comment]
Reviewed on live stream :)

**Comment by KendallDoesCoding** [comment]
Center align links.
