### ISSUE TITLE
[REVIEW] React and Next.js Snippets

### ISSUE THREAD

**Issue by avneesh0612** [EddieHubCommunity/support#3585]
### Project link

https://github.com/avneesh0612/react-nextjs-snippets

**Comment by KendallDoesCoding** [comment]
Looks good

Repo Wise:
Really like the look of the repo, but here are a suggestions

- add badges to README.md


Website:
The website looks great just one edit. 

- In the installation section, update it from "Atom text editor" to "Atom Text Editor"

**Comment by avneesh0612** [comment]
What kind of badges?

**Comment by KendallDoesCoding** [comment]
> What kind of badges?

project size, open/closed pr and issues.

**Comment by avneesh0612** [comment]
Oh I see
