### ISSUE TITLE
[REVIEW] Ullas Kunder

### ISSUE THREAD

**Issue by ullaskunder3** [EddieHubCommunity/support#3588]
### GitHub Profile Link

https://github.com/ullaskunder3

**Comment by schmelto** [comment]
Consider removing the duplicate and incorrect information here:

![image](https://user-images.githubusercontent.com/30869493/154807600-0c7d97de-d0a5-4c3e-a4c8-9eabdec287ff.png)

Otherwise great rofile

**Comment by hellodeborahuk** [comment]
Hi Ullas, I love your banner! I agree with Tom about the follower badges. I'd move Gmail up to your other connect badges, and make it the same style.

**Comment by ullaskunder3** [comment]
So 
- need to remove those follower badge
- need to move gmail badge up with other badges

**Comment by ullaskunder3** [comment]
DONE... Thanks @hellodeborahuk & @schmelto

**Comment by KendallDoesCoding** [comment]
Looks good. Here are a few suggestions

- Put the "Hi there 👋" text above the banner (screenshot below)
- I don't really see the point of this [GIF](https://user-images.githubusercontent.com/66258652/133882911-1c2e5b1f-01b3-438f-83cb-7256e912f655.gif) as it isn't pointing to anywhere lol.
- Center align stats

**Comment by ullaskunder3** [comment]
Thanks @KendallDoesCoding I did as you suggested... thank you

**Comment by KendallDoesCoding** [comment]
> Thanks @KendallDoesCoding I did as you suggested... thank you

Thanks, on my profile a line comes below the heading, I dont even know how I did that, please try to get that on your profile too. Also, please do my second and third point in the suggestion. Thanks again.

**Comment by ullaskunder3** [comment]
@KendallDoesCoding thanks again, 2nd suggestion the gif is temporary I'm making another one, 3rd I tried earlier but center align looks awful 😄

**Comment by KendallDoesCoding** [comment]
Welcome. Ok cool. The 3rd suggestion doesnt really make a different so its
ok if you dont do that.
