### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by nayanm9** [EddieHubCommunity/support#3607]
### Name

Nayan

### Discord Username (if applicable)

nayanm9

### Additional Context

I recently completed the free course.

**Comment by KendallDoesCoding** [comment]
Is your other GitHub account @VFXGamer?

**Comment by VFXGamer** [comment]
Yes 😅, I don't use that account anymore.

**Comment by nayanm9** [comment]
😅 due to multiple devices I often make this mistake. Sorry if it caused any sort of trouble.

**Comment by nayanm9** [comment]
Pleased to be here 😁
