### ISSUE TITLE
[OTHER] Center align chat badge in README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/support#3610]
### What would you like to share?

In the "Community Support" section, center align the chat badge.

### Additional information

I think it will look better if it's center aligned.

I can work on this.

**Comment by Adarsh-jaiss** [comment]
-- hey, are you working on this issue?

**Comment by KendallDoesCoding** [comment]
> -- hey, are you working on this issue?

I was planning to start work in a while, but you can go ahead if you want to work on this!

**Comment by Ash-KODES** [comment]
I think it look better the way it is, so no need to change:)

**Comment by Adarsh-jaiss** [comment]
Okay sure 🙂 let's do this
