### ISSUE TITLE
[BUG] Image's not loading on website

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/support#3611]
### Description of the bug

In the "Community Discussion" and "Alerts" section under "Rules" the images aren't rendering. 

### Project stack or language (e.g. front-end)

uh idk

### Working Environment (e.g. operating system, browser, device)

OS: Windows 10
Browser: Chrome
Device: PC

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/84712013/154990974-d222060e-9aab-4cb4-877a-ca7e86482b69.png)
![image](https://user-images.githubusercontent.com/84712013/154991195-b50220f8-c4ce-4b1c-b690-939a2c8b97bc.png)

**Comment by schmelto** [comment]
Those are all links no images here.
