### ISSUE TITLE
[BUG] Live Stream Review Template (404 NOT FOUND)

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/support#3612]
### Description of the bug

The "Live Stream Review Template" page is not found, even though it's mentioned in the side as a catergory.

### Project stack or language (e.g. front-end)

front-end, maybe?

### Working Environment (e.g. operating system, browser, device)

OS: Windows 10
Browser: Chrome
Device: PC

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/84712013/154991582-54879f52-675e-456c-8a3a-2ca2eca4b6a2.png)

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/support/blob/main/docs/_layout/sidebar.md

I think we can delete the entry there

**Comment by KendallDoesCoding** [comment]
> https://github.com/EddieHubCommunity/support/blob/main/docs/_layout/sidebar.md
> 
> I think we can delete the entry there

Good idea. If it's not being used in the website.. I can see if I can work on this.
