### ISSUE TITLE
[REVIEW] Linkgen

### ISSUE THREAD

**Issue by nathgoutam93** [EddieHubCommunity/support#3617]
### Project link

https://github.com/nathgoutam93/linkgen-react

**Comment by KendallDoesCoding** [comment]
Looks good

- hide wiki if not using
- create release/tags
- I see you've hid the release tab, but I suggest you create releases.
- look at https://github.com/nathgoutam93/linkgen-react/community
- create a security policy, look at https://github.com/nathgoutam93/linkgen-react/security
- add badges to README

**Comment by schmelto** [comment]
Further you could add a contributing.md

**Comment by KendallDoesCoding** [comment]
> * look at https://github.com/nathgoutam93/linkgen-react/community

> look at https://github.com/nathgoutam93/linkgen-react/community

@schmelto That is within the community tab link which I shared.

**Comment by KendallDoesCoding** [comment]
> Thanks for the review folks

Your welcome!

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...

- Demo link not working
- Missing Code of Conduct
- Suggest using issues with labels so the project can be discovered and followed more easily
- App does not work in Safari but works in Chrome
