### ISSUE TITLE
[Video Idea] How to use dotfiles for a "portable developer workflow" including using online IDEs.

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/support#362]
As there are so many package packagers etc this one will be quite a tough one but opening the discussion...

- What package managers would suit? (pip, composer, npm, brew?)
- What operating systems should we cover?
-- What online IDE solutions are the community using?
- Share good examples of things like `Brewfile`(s) and Chocolatey config etc

**Comment by stemount** [comment]
@eddiejaoude volunteered ​http://dotfiles.github.io as a good reference...

👍🏻

**Comment by eddiejaoude** [comment]
Thank you @stemount 👍

**Comment by mikeysan** [comment]
Someone please tell stale bot to calm down. I think this is still worth pursuing.

**Comment by eddiejaoude** [comment]
I agree this is a good video to make, using dotfiles, has made my life so much easier!

**Comment by prince1y** [comment]
@eddiejaoude How does one go about solving this issue? I'm just beginning my open source journey.

**Comment by Vyvy-vi** [comment]
@prince1y  I think this issue is a Video Request
We use this support repository for things like- "video requests", "community questions", "community ideas", "questions for eddie" etc.

**Comment by eddiejaoude** [comment]
@prince1y thank you for commenting. @Vyvy-vi is correct, this is an issue for me to create a video, I have removed `good first issue` label because that is confusing. 

@prince1y join our [Discord](discord.eddiehub.org) and lets continue the conversation there, we also use the `Discussion` tab at the top to chat too 🤓

**Comment by prince1y** [comment]
Thank you very much for the replies @Vyvy-vi @eddiejaoude. I am already on the discord page. I've just been very busy and unable to follow the discussion in there. I'm going to be deliberate about it now.

**Comment by eddiejaoude** [comment]
I created this video last week 🎉 , I will be sharing it this week on Wednesday 🤓 sorry for the delay
