### ISSUE TITLE
Help to understand how this repo works.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/support#3649]
### What would you like to share?

I have been looking at the issues in this repo, and I see that users have been putting their GitHub profiles, repos, resumes etc. I have seen reviewers try to give suggestions to improve their work. But before I contribute here, I wish to know what happens to the issues, and the work. Say I make an issue, and wish for my portfolio or GitHub profile to be reviewed, does the reviewers suggest improvements for my work? Also, does Eddie Jaoude's YouTube channel review others issues in their livestreams? I wish to know the purpose of this repo, is it like a support channel, where you can help others and improve?
Thank you, I hope you can answer my questions!

**Comment by KendallDoesCoding** [comment]
Hey,

Yup your absolutely correct, People from the community give suggestions to
improve your profile, repo project, project etc, and Eddie reviews with a
couple of coders, his friends, etc on live-streams and gives his feedback
too. It is kinda like a support channel here you can help others and  share
tips for the whole community to improve.

**Comment by CodingSpecies** [comment]
Thank you @KendallDoesCoding. That really helped!

**Comment by KendallDoesCoding** [comment]
Glad to hear that :)
