### ISSUE TITLE
[OTHER] Banned from EddieHubCommunity for some reason?!

### ISSUE THREAD

**Issue by KendallDoesCodingAlt1** [EddieHubCommunity/support#3657]
### What would you like to share?

May I know why I was banned from EddieHub on both @KendallDoesCoding and @kendalldoescodingalt? @eddiejaoude

**Comment by eddiejaoude** [comment]
Hi @KendallDoesCodingAlt1 ,

We appreciate your enthusiam for contributing to the EddieHub community. It has come to my attention that you are under age for GitHub's T&Cs (and Discord). Please see their T&Cs below. Please understand that we need to follow the rules.

> You must be age 13 or older. While we are thrilled to see brilliant young coders get excited by learning to program, we must comply with United States law. GitHub does not target our Service to children under 13, and we do not permit any Users under 13 on our Service. If we learn of any User under the age of 13, we will [terminate that User’s Account immediately](https://docs.github.com/en/github/site-policy/github-terms-of-service#l-cancellation-and-termination)

https://docs.github.com/en/github/site-policy/github-terms-of-service

As to your comment (quoted below), we have to stand by our maintainers and allow them to do their job unhindered

> unless yall are biased against the mantainers

I recommend you stop creating multiple GitHub accounts as that also breaks GitHub's T&Cs (again see below)

> You may maintain no more than one free machine account in addition to your free User Account.

Unfortunately I will need to block your 3rd account as well.

We wish you all the best and look forward to collaborating with you when you reach the required minimum age.

All the best,
Eddie
