### ISSUE TITLE
[REVIEW] victoriacheng15

### ISSUE THREAD

**Issue by victoriacheng15** [EddieHubCommunity/support#3671]
### GitHub Profile Link

https://github.com/victoriacheng15

**Comment by Akshu-on-github** [comment]
Heya @victoriacheng15! Here are a few things that caught my eye:

**Things I liked:**
- The labels under what I'm learning and plan to learn are a nice touch - mind if I steal that?
- The blog posts are a nice touch! It's really nice that they're automated, GH Actions ftw! ✨ 

**Things to improve on:**
- The font size of the social handle logos are on the smaller side, thus a bit difficult to read:
![image](https://user-images.githubusercontent.com/61582763/156969249-af987350-ac0e-43be-af93-e1ccffb6e74a.png)
- This might be a pet peeve of mine, but I feel that the banner height could be a lot smaller? It feels like there's unnecessary empty space

On the whole, it's a pretty cool profile - hope my review helped!

**Comment by victoriacheng15** [comment]
Hi @Akshu-on-github !
> * The labels under what I'm learning and plan to learn are a nice touch - mind if I steal that?

Sure, please feel free to do so! 

> * The blog posts are a nice touch! It's really nice that they're automated, GH Actions ftw! ✨

GitHub action is so cool. I am planning to look into it more once I have time!

> * The font size of the social handle logos are on the smaller side, thus a bit difficult to read:
>   ![image](https://user-images.githubusercontent.com/61582763/156969249-af987350-ac0e-43be-af93-e1ccffb6e74a.png)

My original plan is to have links look different from skill badges, but you have a point there, it looks small. I will look into badge styles.

> * This might be a pet peeve of mine, but I feel that the banner height could be a lot smaller? It feels like there's unnecessary empty space

Good thinking! I am in process of changing my banner. I will take it into consideration!

> On the whole, it's a pretty cool profile - hope my review helped!

Thank you so much for your time and feedback. I am appreciated them!

**Comment by hellodeborahuk** [comment]
I love your profile! My only idea would be to turn on the activity overview.

![image](https://user-images.githubusercontent.com/29425781/157634159-915fd8c4-1aa6-48a0-aa72-147a67ae6b2a.png)

And just because I'm being really picky, I'd use full stops on your about me section as you have exclamation marks, just to keep it consistent.

**Comment by victoriacheng15** [comment]
> I love your profile! My only idea would be to turn on the activity overview.

Thank you, @hellodeborahuk! I used to have activity overview on, but I don't find it attractive/useful since it is pretty much my commits. So I am curious, what is your thoughts on it?
 
> And just because I'm being really picky, I'd use full stops on your about me section as you have exclamation marks, just to keep it consistent.

I just re-read the about me section and realized that they are not consistent. Thank you for bringing it up. I will make changes.

**Comment by schmelto** [comment]
Coding environment dark mode I like it 🔥
