### ISSUE TITLE
[OTHER][DOCS] Update links at bottom of README

### ISSUE THREAD

**Issue by TheRemyD** [EddieHubCommunity/support#3686]
### What would you like to share?

# Proposed change
-On line 80 and 81 at the bottom of the README

## Discord Link Change
-Join our [Discord](http://discord.eddiehub.org) community. 

**or**

-Join our [Discord community](http://discord.eddiehub.org).

## Youtube Link Change
-Subscribe to our [YouTube](https://www.youtube.com/user/eddiejaoude) channel.

**or**

-Subscribe to our [YouTube channel](https://www.youtube.com/user/eddiejaoude).

### This is in order to make the links a little more concise and help the flow of the document.
-Please post your thoughts to this update below

**Comment by schmelto** [comment]
@Nithin108 go on for it :)

**Comment by Nithin108** [comment]
yes

**Comment by Nithin108** [comment]
any one review my pull request

**Comment by 20481A05F2** [comment]
@schmelto review my pull request and merge it

**Comment by karnatisrinivas** [comment]
Hello @Nithin108 , Are you still working on this??

**Comment by karthikmurali60** [comment]
@TheRemyD @schmelto If this issue is not closed, can I work on it?

**Comment by karthikmurali60** [comment]
@schmelto @krshkodes here the PR for review - https://github.com/EddieHubCommunity/support/pull/3940
