### ISSUE TITLE
[REVIEW] Refurbished my GitHub profile

### ISSUE THREAD

**Issue by Preethi-Dev** [EddieHubCommunity/support#3692]
### Portfolio link

https://github.com/Preethi-Dev

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:

- remove the profile view counter due its inaccurate.

---

- Languages: all
- Labels: Style guide

**Comment by Preethi-Dev** [comment]
Thanks for your suggestion @schmelto. 

I can't get what you mean about 
- Languages: all
- Labels: Style guide

**Comment by schmelto** [comment]
> Thanks for your suggestion @schmelto. 
> 
> 
> 
> I can't get what you mean about 
> 
> - Languages: all
> 
> - Labels: Style guide

You can ignore that those are internal tags for myself
