### ISSUE TITLE
[REVIEW] devaaquib

### ISSUE THREAD

**Issue by imaaquibali** [EddieHubCommunity/support#3715]
### GitHub Profile Link

https://github.com/devaaquib/

**Comment by devaaquib** [comment]
@eddiejaoude  Please Review it in your live stream.

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:

- Why is there a <br> tag?

![image](https://user-images.githubusercontent.com/30869493/160780543-c226aa1c-6dac-4bd1-8e22-c9e8c194d175.png)

- I really like Olaf 😄 
- I would make the first line as a headline not as a code line

---

- Languages: all
- Labels: Style guide

**Comment by eddiejaoude** [comment]
Yes I will review on live stream soon 👍 

Great to see you are getting feedback from Tom already 🔥

**Comment by imaaquibali** [comment]
@schmelto Thanks for your reviews I'll keep in mind :)
