### ISSUE TITLE
[REVIEW] LeetDroid

### ISSUE THREAD

**Issue by cdhiraj40** [EddieHubCommunity/support#3716]
### Project link

https://github.com/cdhiraj40/LeetDroid

**Comment by eddiejaoude** [comment]
Looks good, some thoughts

- wiki is not used, suggest hiding
- use issues and labels so people can discover and get involved in your project
- at the end of the README there are `~~` is that meant to have a closing one to be strikethrough

**Comment by cdhiraj40** [comment]
Thanks for the feedback @eddiejaoude !!

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍
