### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Neklaustares-tPtwP** [EddieHubCommunity/support#3720]
### Name

Anant

### Additional Context

I want to contribute

**Comment by schmelto** [comment]
Hey @Neklaustares-tPtwP you are already part of EddieHub ✨ 
![image](https://user-images.githubusercontent.com/30869493/158345797-ecca3d1d-f245-44b7-98d9-9cb6a497dc67.png)
