### ISSUE TITLE
[REVIEW] DDRSS

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/support#3814]
### Project link

https://github.com/Pradumnasaraf/DDRSS

**Comment by schmelto** [comment]
Nice one 🔥
Consider removing the bit.ly link and using the original one. For me bitly links have some kind of negativ touch but this is only my personal opinion on that.

**Comment by Pradumnasaraf** [comment]
> Nice one fire Consider removing the bit.ly link and using the original one. For me bitly links have some kind of negativ touch but this is only my personal opinion on that.

Agree Tom, removed it :rocket:

**Comment by Pradumnasaraf** [comment]
> Nice one fire Consider removing the bit.ly link and using the original one. For me bitly links have some kind of negativ touch but this is only my personal opinion on that.


Agree Tom, removed it :rocket: , Thank you

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Recommend using issues with labels
- Animated gif might make it come to life a bit more

Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
