### ISSUE TITLE
[FEATURE REQUEST] EddieHub Community design system

### ISSUE THREAD

**Issue by MatteuSan** [EddieHubCommunity/support#3845]
### Description of feature request, idea

Make a design system for the EddieHub Community.

### Add any other context about the feature request here

I've been thinking about this concept for a while. I saw the EddieHub website and (no offense) I thought it looked a tad bit inconsistent in some places (buttons have different styles, theming is a bit all over the place, etc.), and that's where the spark began. 

## Goals
The goals of this design system are:
- To represent the EddieHub community as a whole. Create an identity, a motif if you will, throughout every EddieHub project (current, and future).
- To minimize time doing the project. Make a set of design principles and patterns that govern the EddieHub community. This way developers of the project don't have to waste time reinventing principles and patterns for each project.

## Conceptualization
I began thinking of how the EddieHub Community works, because if we were to build a design system, we have to know how things work internally, how the people will use the code. This was an immediate roadblock for the conceptualization phase. EddieHub projects are created with the community in mind, and I felt that putting a design system in the middle of every project making process makes it sort of limited in a way. I felt the idea makes less room for the individuality of each project, to which is one of the beauties of the community.

## Implementation: First steps
Like every developer, we're all excited to get our hands dirty into the nitty-gritties of this project. However, I would like to point out that we're making this with the EddieHub community in mind.

So, my proposal for the first steps are to have a 2-3 month period of just surveys and rough planning. This way we get input from the community and they will in turn help shape the design guidelines, the public API of the design system, and the other needs of the design system.

## Conclusion
Despite the roadblocks, I think it's going to be a fun challenge. To create a design system despite the constraints given.

Thoughts? Any feedback (may it be positive or negative, as long as it's beneficial to the proposal and constructive) is **greatly greatly greatly** appreciated. :>

PS: Sorry if my explanation is really vague, my thoughts are a little over the place while writing this lol.

**Comment by eddiejaoude** [comment]
Great explanation! I like the idea, but the website is made with low code and therefore and limited changes we can make to it.

I look forward to reading the discussion from other EddieHub members

**Comment by vinzvinci** [comment]
Great idea👏 Eddie needs time if this will implement :D but I'm sure @MatteuSan and hubbers can be able to collaborate to implement this. Design system is great to have 👍

**Comment by abh139** [comment]
Yes I also like the idea I think we should work on it Can we make a separate website for EddieHub that would be awesome

**Comment by MatteuSan** [comment]
bumping this up. is everyone cool with this?

**Comment by MatteuSan** [comment]
Made a discussion thread here: https://github.com/EddieHubCommunity/support/discussions/3879

**Comment by schmelto** [comment]
Closed due moved to GitHub Discussions https://github.com/EddieHubCommunity/support/discussions/3879
