### ISSUE TITLE
[REVIEW] CoderSalman 

### ISSUE THREAD

**Issue by codersalman** [EddieHubCommunity/support#3853]
### GitHub Profile Link

https://GitHub.com/CoderSalman

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:

- remove the profile view counter due its inaccurate.
- remove the GitHub Follower count due its duplicate information

**Comment by codersalman** [comment]
> ## Profile Review
> ### TLDR;
> 
> Your profile looks awesome! See the full details with my suggestions below.
> 
> ---
> 
> ### Full details
> 
> Your profile looks awesome! Here some suggestions from my side:
> 
> - remove the profile view counter due its inaccurate.
> - remove the GitHub Follower count due its duplicate information
> 

Thank you 💚
