### ISSUE TITLE
[𝗥𝗘𝗩𝗜𝗘𝗪] <shaurya-blip> 

### ISSUE THREAD

**Issue by shaurya-blip** [EddieHubCommunity/support#3870]
### GitHub Profile Link

https://github.com/shaurya-blip/

**Comment by shaurya-blip** [comment]
My open-source project is [PyServed](https://github.com/SblipDev/PyServed).

**Comment by eddiejaoude** [comment]
Looks good, some thoughts...
- remove profile review
- do more code reviews and pull requests
- and join EddieHub GitHub Org 😉 

Please raise a new issue for the project
