### ISSUE TITLE
[REVIEW] Open source with Pradumna

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/support#3959]
### Project link

https://github.com/Pradumnasaraf/open-source-with-pradumna

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=T14I0ECfPlU

looks great
- as some sections are work in progress, could you highlight this with a progress bar or percentage
- also maybe add a link to the official github docs
