### ISSUE TITLE
[REVIEW] Terminal Portfolio

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#3968]
### Portfolio link

https://schmelto.github.io/Portfolio/terminal/terminal.html

Source: https://github.com/schmelto/Portfolio

**Comment by eddiejaoude** [comment]
Reviewed on https://www.youtube.com/watch?v=T14I0ECfPlU

Some thoughts...
- wow
- have a animated gif demo in README
- suggest hiding project tab until you use it
- more cypress tests needed, for example running the commands
