### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by VardaanAggarwal** [EddieHubCommunity/support#4060]
### Name

Vardaan Aggarwal

### Discord Username (if applicable)

RYUK#3044

### Additional Context

I first got to know about Eddie's great work and contributions through his podcast with Kunal Kushwaha on his Youtube channel .
I got very much impressed by his great contribution towards the whole community, so I also want to be a part of such great communities and make my contributions in them.

**Comment by Noxx-7** [comment]
Name
Rahul Sharma

Discord Username (if applicable)
Rahul sharma77#8390

Additional Context
My name is Rahul Sharma, I'm a 5th semester computer science student at CGU Bhubaneswar.

I'm
● MERN-Stack Developer 
● Android Developer
● Freelancer (Video Editor) 
● Part-Time YouTuber 

At the moment, I am learning DevOps. Looking for a position in which I can utilize my technical skills to solve real-life problems in a flexible and dynamic environment that encourages me to grow.

**Comment by schmelto** [comment]
@VardaanAggarwal you are already part of the community @Noxx-7 please open a new issue for joining the community
