### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by thecodexhub** [EddieHubCommunity/support#4102]
### Name

Sandip Pramanik

### Discord Username (if applicable)

Inferno#1159

### Additional Context

I found this organization from a [tweet](https://twitter.com/pradumna_saraf/status/1535189553195241475) by @Pradumnasaraf yesterday while sharing GitHub profiles.

Also, a few days back, I was listening to a [Twitter space](https://twitter.com/BhosalePratim/status/1531985660713717761) titled **"How to start Content Creation in Tech"** where I get to know Eddie Jaoude @eddiejaoude and get interested in his work and contribution to the open-source community.

I am willing to learn about the open-source community and how it works. I want to get connected with a lot of other experienced developers, learn their way of thinking and collaborate in the creation of new open-source software. I'm also prepared to assist others to grow and contribute to the open-source community.

**Comment by Pradumnasaraf** [comment]
> ### Name
> 
> Sandip Pramanik
> 
> ### Discord Username (if applicable)
> 
> Inferno#1159
> 
> ### Additional Context
> 
> I found this organization from a [tweet](https://twitter.com/pradumna_saraf/status/1535189553195241475) by @Pradumnasaraf yesterday while sharing GitHub profiles.
> 
> Also, a few days back, I was listening to a [Twitter space](https://twitter.com/BhosalePratim/status/1531985660713717761) titled **"How to start Content Creation in Tech"** where I get to know Eddie Jaoude @eddiejaoude and get interested in his work and contribution to the open-source community.
> 
> I am willing to learn about the open-source community and how it works. I want to get connected with a lot of other experienced developers, learn their way of thinking and collaborate in the creation of new open-source software. I'm also prepared to assist others to grow and contribute to the open-source community.

Awesome, thank you joining 🎉

**Comment by eddiejaoude** [comment]
Welcome 🎉
