### ISSUE TITLE
[REVIEW] MrKrishnaAgarwal

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [EddieHubCommunity/support#4274]
### GitHub Profile Link

https://github.com/MrKrishnaAgarwal

**Comment by vincekashaka** [comment]
- great profile
- I suggest trying to reduce it to 2 pages

**Comment by MrKrishnaAgarwal** [comment]
Thanks @vincekashaka for the suggestion.
I'll definitely look upon it!
