### ISSUE TITLE
[REVIEW] trafficinterventions

### ISSUE THREAD

**Issue by vijay-jaisankar** [EddieHubCommunity/support#4280]
### Project link

https://github.com/WSL-IIITB/Traffic-Interventions

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream https://www.youtube.com/watch?v=afo0E5RrJYA

- use semver number versioning for releases
- hide packages if not used
- hide wiki if not used
- add code of conduct
- highly recommend add issues with labels to be discovered
