### ISSUE TITLE
[REVIEW] Harshal0902

### ISSUE THREAD

**Issue by Harshal0902** [EddieHubCommunity/support#4296]
### GitHub Profile Link

http://github.com/Harshal0902

**Comment by vincekashaka** [comment]
- great profile
-  I am impressed by those green squares

**Comment by Harshal0902** [comment]
Thank you @vincekashaka

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- animated hands could be removed
- maybe some more attention to code reviews/issues/pull requests from the contributors graph
