### ISSUE TITLE
QAWolf - VS Code/Chromium browser test generator

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/support#459]
### QAWolf (not my project!) for generating simple Jest test cases from browser recording

**Items we can review on a live stream:**

https://github.com/qawolf/qawolf

![shiny](https://camo.githubusercontent.com/8d7ff967d0dbc50a616db6aa508b0a26ace6fdb5592173a683c73f5541765627/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f646f63732e7161776f6c662e636f6d2f776562736974652f6372656174652e676966)

---

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by mikeysan** [comment]
Thanks for sharing 👍

**Comment by eddiejaoude** [comment]
Thanks @stemount 👍  - I will review it in one of my next videos / live streams 🤓

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/oM8rBNyiwPY

Btw great...
- README
- Really like the table for `Is QA Wolf a good fit for you?`
- Animated gif is epic

Here are some of my suggestions
- Animated gif to have a progress bar so we can the loop position
- Maybe reduce the topics
- Maybe add a bit more the repo's description 
- Add a `Contributing` https://github.com/qawolf/qawolf/community
