### ISSUE TITLE
[Video/Livestream Guest] - Debbie O'Brien

### ISSUE THREAD

**Issue by AllanRegush** [EddieHubCommunity/support#463]
Bring Debbie back on for more nuxt.js

**Comment by eddiejaoude** [comment]
Spoke to Debbie and she will be coming back 👍

**Comment by debs-obrien** [comment]
Hey. Ahhh how nice to request me back. Lets do it after Christmas. I might have some new Nuxt stuff to tease Eddie with. 😜. But if there is something you want me to cover @AllanRegush just let me know 😊

**Comment by eddiejaoude** [comment]
Tease Eddie!? ... not again 😱

**Comment by eddiejaoude** [comment]
We got Debbie back 🎉 , so I will close this. I know people are still asking for @debs-obrien to join me again on a live stream
