### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by priya-172** [EddieHubCommunity/support#4644]
### Name

Priya Pramanick

### Additional Context

I saw @eddiejaoude on a podcast with Kunal Kushwaha where they discussed a lot about open source and git hub .Remote work  made me curious and since then i have been enlightening upon a lot of new things . I really  wanted to join @eddiejaoude's community .

**Comment by eddiejaoude** [comment]
Welcome to the EddieHub GitHub Org! Don't forget to join us in Discord where we collaborate daily with the amazing community members!
