### ISSUE TITLE
[FEATURE REQUEST] EddieHub Kubernetes cluster

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/support#4655]
### Description of feature request, idea

- Build cluster by code not clicks in DO's Pulumi
- Load balancer using Pulumi
- Teleport for mods/maintainers access to logs and monitoring
- SSL
- Pulumi secrets to Kubernetes

- Centralised logging
- Centralised monitoring
- Persistent storage for databases (MongoDB, MySQL)

**Comment by loftwah** [comment]
Centralised logging and monitoring can probably be a single issue.
