### ISSUE TITLE
[REVIEW] <octonawish-akcodes>

### ISSUE THREAD

**Issue by octonawish-akcodes** [EddieHubCommunity/support#4815]
### GitHub Profile Link

https://github.com/octonawish-akcodes

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- suggest trying to organise the badges differently - try columns
- maybe try the banner at the top

**Comment by octonawish-akcodes** [comment]
Thanks @eddiejaoude I will work on that.
