### ISSUE TITLE
[REVIEW] SQLite-UI

### ISSUE THREAD

**Issue by Shivansh-yadav13** [EddieHubCommunity/support#4816]
### Project link

https://github.com/Shivansh-yadav13/SQLite-UI

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- add screenshot to README
- possible add a link to a deployed demo
- hide wiki not being used 
- needs a contributing file and issue templates could be useful too
-
