### ISSUE TITLE
[REVIEW] <Memphis broker>

### ISSUE THREAD

**Issue by Saarryan** [EddieHubCommunity/support#4818]
### Project link

https://github.com/memphisdev/memphis-broker

**Comment by eddiejaoude** [comment]
Looks great! Some suggestions from the live stream https://www.youtube.com/watch?v=UYiuVStI85M

- hide packages if not used
- `.vscode` should probably be removed
- screenshots are great, maybe move them higher up
- hide features not being used like `wiki`
