### ISSUE TITLE
[DOCS] Spelling email

### ISSUE THREAD

**Issue by janet-dev** [EddieHubCommunity/support#4887]
### Description of the bug

Two different spellings - 'email' and 'e-mail' for the CODE_OF_CONDUCT.md. 

https://github.com/EddieHubCommunity/support/blob/main/CODE_OF_CONDUCT.md

Just wondering if there is a site wide convention?

### Project stack or language (e.g. front-end)

front-end

### Working Environment (e.g. operating system, browser, device)

MacOS Catalina v10.15.5, Chrome, MacBook Pro

### Please add screenshots (if applicable)

<img width="1083" alt="CODE_OF_CONDUCT" src="https://user-images.githubusercontent.com/67335440/183244406-315ac55b-2933-4cd3-a875-3cdd6cca7b00.png">

### Add any other context about the problem here

Here is an interesting article "Is it e-mail, email, E-mail or Email?"

https://www.future-perfect.co.uk/grammar-tips/evolving-words/is-it-e-mail-email-e-mail-or-email

**Comment by Madankh** [comment]
hey can i solve this

**Comment by Saiteja-Basam** [comment]
#8073 
Hi @janet-dev 
After going through the article that you have attached
I have changed e-mail to email in doc and raised a PR #8073 
I hope you can review and merge

**Comment by kiranrega** [comment]
please assign this to me I will work on it

**Comment by janet-dev** [comment]
> 

Thank you @Saiteja-Basam for doing that.

**Comment by janet-dev** [comment]
@Saiteja-Basam I am not an assigned reviewer. @kiranrega, if you are an official reviewer - can you review and merge for us?

**Comment by mathanraj0601** [comment]
Is the issue still there can I contribute?

**Comment by vishesh-hue** [comment]
PPLLLLZZZ GIBBBB MEEEE THISSS ONEEEEE

**Comment by janet-dev** [comment]
Thank you for your offers, but the change has been done. We are waiting for an authorised reviewer to approve and merge the PR. See the above comments 🤩

**Comment by Anjalisharma3463** [comment]
#8228 
hello @janet-dev ,
I've read that documentation that you have mentioned and i changed accordingly and also i mentioned the reason in PR why we want to change e-mail --> email.

I hope it will be merged.
Thank u!

**Comment by eddiejaoude** [comment]
Thank you for raising @janet-dev 👍 

Thanks for raising @Anjalisharma3463 on the BioDrop repo - I will review now.

Please note that this file is from a template, so I suggest someone proposing an update to the official repo

**Comment by realdezzy** [comment]
Maintainers should close this issue.

**Comment by jovyllebermudez** [comment]
I nominate this to be closed.

**Comment by drvcodenta** [comment]
Is this issue still open?

**Comment by I-MirzaBaig** [comment]
Is it still opened or resovled?

**Comment by adityaraute** [comment]
If the PR is merged, why didn't the Issue get closed automatically?

**Comment by oahmadgit** [comment]
I guess the linked PR still needs 1 more approval from the repo owners to get merged.

**Comment by Axxi3** [comment]
is it still open?

**Comment by Amitkumarkoli** [comment]
Is this issue still open?

**Comment by eddiejaoude** [comment]
Thank you everyone, this was completed in this PR https://github.com/EddieHubCommunity/support/pull/8228/files and the issue should now be closed
