### ISSUE TITLE
Suggestion: Add a link to Eddie's video on asking for help. 

### ISSUE THREAD

**Issue by AllanRegush** [EddieHubCommunity/support#49]
Asking for help on a problem can be hard - let's make it easier.

Create a link for Eddie's video on how to ask for help

https://www.youtube.com/watch?v=GjK60wF3Aic

**Comment by eddiejaoude** [comment]
Thanks @AllanRegush . The video is old, I wonder if we could do an updated version with suggestions from people?

People could send me bullet points of suggestions of how to ask for help and I could collate it and make a video, just an idea 🤓

**Comment by eddiejaoude** [comment]
In the meantime, adding the link to the `question` template could be a good idea 👍

**Comment by eddiejaoude** [comment]
> adding the link to the question template could be a good idea 👍

@Ruth-ikegah worked on the issue templates, I would be interested to know her thoughts

**Comment by Ruth-ikegah** [comment]
> > adding the link to the question template could be a good idea 👍
> 
> @Ruth-ikegah worked on the issue templates, I would be interested to know her thoughts

Nice idea @eddiejaoude , but a better place to add this link will be to the readme file. Adding it to the section of *if you wanna ask a question, create an issue*

**Comment by BOLT04** [comment]
i still think this is relevant stale bot 😃

**Comment by Vyvy-vi** [comment]
Also, maybe, we can compile a list of resources like dontasktoask.com ?

**Comment by kcoder63** [comment]
[5 ways to ask for help](https://hbr.org/2014/12/5-ways-to-get-better-at-asking-for-help) 
[How to ask](http://www.catb.org/~esr/faqs/smart-questions.html) 
[The art of asking](https://www.sarahkpeck.com/2013/09/the-art-of-asking/) 

These articles are similar to don't ask to ask , will these be helpful?

**Comment by varghesejose2020** [comment]
Great one @kcoder63  

> 'open source culture is not only  related to  code it is a part of life

**Comment by eddiejaoude** [comment]
I also think I need to remake this video, my videos back then are even more embarrassing 😂
