### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by MahendraBishnoi29** [EddieHubCommunity/support#4934]
### Name

Mahendra Bishnoi

### Discord Username (if applicable)

browny

### Additional Context

I met Eddie on Twitter, people are mentioning him a lot in terms of open source and community. I went through his Blogs, YT channel and saw that he's doing some insane amount of work for community so i decided to join this beautiful community 💖, Also a HUGE thanks to @eddiejaoude 🙌🏻🔥

**Comment by eddiejaoude** [comment]
Thank you @MahendraBishnoi29 for the great feedback! See you in EddieHub
