### ISSUE TITLE
Update Discord Readme

### ISSUE THREAD

**Issue by GoluffyxD** [EddieHubCommunity/support#499]
**Description**
The #readme channel in discord needs to be updated to include one of the missing channels(#videos) in the ALERTS section.
![image](https://user-images.githubusercontent.com/46129076/101202142-de6eee80-368e-11eb-819d-d2f90c708b2b.png)
Discord Channels:
![image](https://user-images.githubusercontent.com/46129076/101202220-fd6d8080-368e-11eb-8d3b-55c0c01facf2.png)
The #videos channel seems to be missing in the documentation and can be added.

**Comment by eddiejaoude** [comment]
Good spot 👍 . Thank you 🤓

**Comment by eddiejaoude** [comment]
I think this is now done
