### ISSUE TITLE
[REVIEW] itsalb3rt

### ISSUE THREAD

**Issue by itsalb3rt** [EddieHubCommunity/support#4998]
### GitHub Profile Link

https://github.com/itsalb3rt

**Comment by itsalb3rt** [comment]
Thanks @schmelto 🙌

**Comment by eddiejaoude** [comment]
Looks greats 👍 Reviewed on live stream https://www.youtube.com/watch?v=KnR5OoVLpc4

Some suggestions
- very commit heavy, suggest doing code reviews/issues/pull requests
- suggest removing profile views
-
