### ISSUE TITLE
Please review my project and my profile

### ISSUE THREAD

**Issue by tusharnankani** [EddieHubCommunity/support#504]
Items we can review on a live stream:

- GitHub profile: https://github.com/tusharnankani
- Open-source project: https://github.com/tusharnankani/ToDoList

PS: The project is not really advanced, but I received contributions lately, and I try to maintain all my projects the right way.

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a video / live stream soon 🤓

**Comment by dumbcoder7** [comment]
I reviewed your profile. It's good. Some minor suggestions:

1. This is your bottom section
![image](https://user-images.githubusercontent.com/43912470/104834996-7cc6b480-58c9-11eb-8c13-d8630a4d5452.png)
Remove the table, have the linked images in a div next to each other, and center that div. I think it will look better.

1. I always recommend getting rid of the `profile views` tab. Those stats keep incrementing at every Refresh and can thus be manipulated. Hence not trustworthy.

1. 
![image](https://user-images.githubusercontent.com/43912470/104835056-f3fc4880-58c9-11eb-8c17-922d6bfe8746.png) 
The `alt text` for this logo is Github readme stats, but there are no stats, neither does the image lead the user anywhere. Having it in the center is confusing as the visitor tends to click on it, hoping for more info. Consider removing it or placing it in a corner for less importance. Don't make it the center of attention.

**Comment by dumbcoder7** [comment]
Also reviewed your project. Looks awesome. Some suggestions:

1. Make the to-do cards more attractive. Simple rounded rectangles don't do it for me.
2. When I delete a card, the screen momentarily shrinks with the scroll bar appearing, and then it's back to now. Try solving this issue.
3. Add a link to the bottom corner to your repo or profile.

**Comment by eddiejaoude** [comment]
Reviewing with the community on a live stream https://youtu.be/oM8rBNyiwPY

The app looks great, here are some suggestions
- `CSS` and `JS` should probably be lowercase
- Screenshot from the app high up in the README (consider having an animated gif)
- Add a quickstart guide

**Comment by Akshu-on-github** [comment]
Maybe add in a PR template too!
