### ISSUE TITLE
[FEAT]: Discord server custom link

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/support#506]
## **Description**

A brief description of the feature request:

In videos on youtube or on github, the discord server link often shared is the default invite link, that looks something like 
`github.com/invite/ChAracT3s`
![Screenshot 2020-12-05 at 6 22 46 PM](https://user-images.githubusercontent.com/62864373/101243590-5ab51080-3727-11eb-8354-e9df35570fc9.png)
However, wouldn't it be better if we have a more definite invite-link? 

## What can we do:
Something like `discord.io/EddieJaoudeCommunity` or `invite.gg/EddieHub` or linking from some domain?

Now, discord also offers `discord.com/CommunityName` after partnering, but that has a few requirements:
1- more than 500 members(at least now) [more info](https://support.discord.com/hc/en-us/articles/360035969312-Community-Server-Guidelines)
2- Community Server Activation(I think we discussed this on discord in `#ideas`) [conversation on discord](https://discord.com/channels/699608417039286293/703901317457903687/782010134598778900)

So, for now could we just use https://discord.io/ or something else to set up a redirect from discord.io/EddieJaoudeCommunity to the discord server invite. Or perhaps we could do what @nhcarrigan does(he uses chat.(his domain).com to link to discord server)

## But, **WHY** ?:
It would always be easier to have consistent naming conventions all-over socials(some golden advice from eddie) and would ensure better reference for the server and the community. Using a custom discord server link would enable the community to be easily linkable, without needing to memorise/copy-paste random strings.

---
## On a side-note(related to this...)

Also, we could also add a server widget on github/website (you can find how to do this in server settings), which ae provided by discord.

The custom server widgets look something like this: (more designs are available)
![Screenshot 2020-12-05 at 6 32 16 PM](https://user-images.githubusercontent.com/62864373/101243747-49203880-3728-11eb-90b5-0b8c89c037fb.png)
The above is an image, but the actual widget can be seen on my repo: [TearDrops](https://github.com/TearDrops).
These look nice and link directly to the server when clicked.

[How to setup custom server widget for discord](https://blog.discord.com/add-the-discord-widget-to-your-site-d45ffcd718c6)

---
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)
Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by nhcarrigan** [comment]
> Or perhaps we could do what @nhcarrigan does(he uses chat.(his domain).com to link to discord server)

This was incredibly painless to implement as well. And the nice thing is it's in my DNS, so if I ever lose/replace/regenerate the invite it's one record to update and all of my links will still work. 🙂

**Comment by eddiejaoude** [comment]
@Vyvy-vi great ideas 👍 

- widget on the website can be done now
- but the url, let's do this over the holiday season, so we can get everything aligned especially the name etc

**Comment by nhcarrigan** [comment]
@eddiejaoude this can be closed now, I believe, with the custom domain being set up.

**Comment by AllanRegush** [comment]
closing. @eddiejaoude added custom domains. Our discord custom domain is `discord.eddiehub.org`

**Comment by nhcarrigan** [comment]
Thanks Allan!

**Comment by eddiejaoude** [comment]
Thanks all 👍
