### ISSUE TITLE
[OTHER] The emojis on the support website are not visible 

### ISSUE THREAD

**Issue by 2802AdityA** [EddieHubCommunity/support#5074]
### Some emojis on the support website (https://eddiehubcommunity.github.io/support/#/discord/discord-readme) are not visible.

![emoji-echanges](https://user-images.githubusercontent.com/84802479/185789676-764fa968-6088-4736-86e2-db17051b11e2.jpg)

It's a small thing but I think it'll be good for me to get started.
I can make a PR about this issue.

**Comment by schmelto** [comment]
Maybe this script helps
'
<script src="//unpkg.com/docsify/lib/plugins/emoji.min.js"></script>'

**Comment by 2802AdityA** [comment]
> Maybe this script helps '
> 
> <script src="//unpkg.com/docsify/lib/plugins/emoji.min.js"></script>'

Thanks! I will take a look into it.
