### ISSUE TITLE
First timers guide to opensource

### ISSUE THREAD

**Issue by AllanRegush** [EddieHubCommunity/support#508]
We should create a first timers guide to opensource. This could be a checklist, a collection of @eddiejaoude's videos, etc.

**Comment by BOLT04** [comment]
Really cool idea @AllanRegush 👍, maybe this resource would help on that: https://www.firsttimersonly.com/

**Comment by eddiejaoude** [comment]
I like it 👍 . We could write something in the `support` repo in the `tips` section? which eventually could be generated into a website with embedded videos? I can create more as they are needed too

**Comment by Nishant123412** [comment]
can this issue be solved cause it would be really useful for me. I have no idea about how to go on with open source.

**Comment by chryzcodez** [comment]
I would really love to contribute on this..It would really have impact to those interested in open source.

Looking forward to seeing this idea as a reality!

**Comment by eddiejaoude** [comment]
This was initially started here https://github.com/EddieHubCommunity/support/blob/main/Finding-Open-Source-Projects.md

**Comment by chryzcodez** [comment]
> This was initially started here https://github.com/EddieHubCommunity/support/blob/main/Finding-Open-Source-Projects.md

so what is the way forward Eddie, should pull request on that start now?

**Comment by eddiejaoude** [comment]
Sure, let us know your ideas and plans

**Comment by BOLT04** [comment]
> 
> 
> I would really love to contribute on this..It would really have impact to those interested in open source.
> 
> Looking forward to seeing this idea as a reality!

Hi @chryzcodez 😃, I'm glad you want to contribute 👍. You can create a PR that adds this guide in the `tips` folder, and if you feel it's not ready [mark it as a draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Here are some ideas that could help:
- The file could be named `first-timers-guide-to-opensource`
- We can have a `Resources` section at the end that references other blog posts, files in the repo, videos, etc. For example this list of resources:
  - [GitHub labs by Eddie](https://www.youtube.com/playlist?list=PL4lTrYcDuAfzgLkdH-iLCW9HBiLVEBHjB)
  - [A First Timers Guide to an Open Source Project by Luke Oliff](https://auth0.com/blog/a-first-timers-guide-to-an-open-source-project/)
  - [Complete Guide to Open Source - How to Contribute by Eddie](https://www.youtube.com/watch?v=yzeVMecydCE)

By the way @chryzcodez, there is similar work being done on EddieBot on this PR: https://github.com/EddieHubCommunity/EddieBot/pull/392. I think we have talked about merging all the tips on the `support` repo, but we would need to refactor the code on the bot to fetch the files in a new location.

I still encourage you to create a PR for this issue👍. 

_Sidenote: Eddie is [preparing a crash course](https://github.com/EddieHubCommunity/support/discussions/434) on GitHub. This could be a useful resource to add to this list later on 😃_

**Comment by chryzcodez** [comment]
> > I would really love to contribute on this..It would really have impact to those interested in open source.
> > Looking forward to seeing this idea as a reality!
> 
> Hi @chryzcodez 😃, I'm glad you want to contribute 👍. You can create a PR that adds this guide in the `tips` folder, and if you feel it's not ready [mark it as a draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/).
> 
> Here are some ideas that could help:
> 
> * The file could be named `first-timers-guide-to-opensource`
> * We can have a `Resources` section at the end that references other blog posts, files in the repo, videos, etc. For example this list of resources:
>   
>   * [GitHub labs by Eddie](https://www.youtube.com/playlist?list=PL4lTrYcDuAfzgLkdH-iLCW9HBiLVEBHjB)
>   * [A First Timers Guide to an Open Source Project by Luke Oliff](https://auth0.com/blog/a-first-timers-guide-to-an-open-source-project/)
>   * [Complete Guide to Open Source - How to Contribute by Eddie](https://www.youtube.com/watch?v=yzeVMecydCE)
> 
> By the way @chryzcodez, there is similar work being done on EddieBot on this PR: [EddieHubCommunity/EddieBot#392](https://github.com/EddieHubCommunity/EddieBot/pull/392). I think we have talked about merging all the tips on the `support` repo, but we would need to refactor the code on the bot to fetch the files in a new location.
> 
> I still encourage you to create a PR for this issue👍.
> 
> _Sidenote: Eddie is [preparing a crash course](https://github.com/EddieHubCommunity/support/discussions/434) on GitHub. This could be a useful resource to add to this list later on 😃_

What of if we sectionalize it, like videos, websites, docs and so on than putting everything together.

**Comment by BOLT04** [comment]
@chryzcodez yes we can have a section for each instead of putting everything together 👍
