### ISSUE TITLE
[REVIEW] Shubhcs01

### ISSUE THREAD

**Issue by Shubhcs01** [EddieHubCommunity/support#5089]
### GitHub Profile Link

https://github.com/Shubhcs01

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:


- remove the profile view counter due its inaccurate.
- consider adding some more words about yourself
- consider adding a profile picture

**Comment by Shubhcs01** [comment]
Thanks for your suggestions.
