### ISSUE TITLE
[REVIEW] schmelto

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#5116]
### GitHub Sponsor profile link

https://github.com/sponsors/schmelto

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=He9lBSlTvhQ

looks great Tom, some thoughts...
- Suggest having more monthly tiers: $5, $10, $25, $100 (companies might want to pay more)
- I think having a more detailed description would encourage more people to sponsor you
