### ISSUE TITLE
Blue screen on youtube live 

### ISSUE THREAD

**Issue by iason9** [EddieHubCommunity/support#512]
**Description**

sometimes there is a flash of a blue screen when you are doing live youtube video. its like less than a second, it doesn't bother but maybe you should look into it

**Stack**

Youtube Live since last Sunday when you did the live stream.

**Working Environment**

macOS Mojave

**Browser **

Firefox

**Comment by BOLT04** [comment]
I have seen this blue flash as well. Here is an example: https://youtu.be/WHbGLJpGrco?t=3280 (hopefully is visible)

**Comment by thejason1** [comment]
yes this is it i wanted to add a screenshot now we have it! good work capturing it @BOLT04 .

**Comment by eddiejaoude** [comment]
Oh 😱 . Thank you for the example that really helps! 👍 

It looks like, I do not flash but the screen behind me? The screen is coming from my iMac to the streaming PC, and the camera of me goes directly to the streaming PC - so I think it is the output from my iMac, my iMac has been having issues recently, I needs a re-install I think.

**Comment by thejason1** [comment]
Maybe you should upgrade to Mac Big Sur instead of reinstall. It might fix some bugs but do keep a backup of your system you never know what may happen.

**Comment by eddiejaoude** [comment]
I find upgrades can create some issues too, a clean reinstall to Big Sur I think would be best 👍 - I will do it over the holidays

**Comment by eddiejaoude** [comment]
I did not re-install yet, but it is on the list of things to do in the next 2 weeks

**Comment by eddiejaoude** [comment]
oh 2 weeks is up, and I have delayed again by another week again 🤦‍♂️ - not sure if still happening or not? but I think it will be fixed by reinstalling my Mac because I need to reboot each time now to make it work
