### ISSUE TITLE
[REVIEW] <CharlesCreaticeContent>

### ISSUE THREAD

**Issue by CharlesCreativeContent** [EddieHubCommunity/support#5120]
### GitHub Sponsor profile link

https://github.com/sponsors/CharlesCreativeContent

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=He9lBSlTvhQ

Looks awesome
- for higher amounts quantify what people get
- would be great to see the banners with you in it, I feel it is more personal
