### ISSUE TITLE
Please review my profile

### ISSUE THREAD

**Issue by mohitrakhade20** [EddieHubCommunity/support#516]
Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
Do you have links to the things you would like to be reviewed?

**Comment by eddiejaoude** [comment]
Thank you for creating an issue. I can review your GitHub profile. I will review on a video / live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/oM8rBNyiwPY

Your profile looks good 👍 , some suggestions:
- Website link does not work in the README

**Comment by mohitrakhade20** [comment]
Thank you for reviewing my profile, looks like domain got expiered : / I will relaunch website
