### ISSUE TITLE
Review my Github Profile

### ISSUE THREAD

**Issue by ksdkamesh99** [EddieHubCommunity/support#517]
Items we can review on a live stream:

- GitHub profile

https://github.com/ksdkamesh99

@eddiejaoude please review my github profile and can give me some tips to improve my profile for participating in GSOC 21. Lastly I am big fan of you and love things you do in motivating people towards open source.Thanks in advance 

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
@ksdkamesh99 What is GSOC 21?

**Comment by ksdkamesh99** [comment]
@AllanRegush GSOC means Google summer of code

**Comment by eddiejaoude** [comment]
Thank you for sharing your link. I will review on a video / live stream soon 👍

**Comment by ShyamPraveenSingh** [comment]
Hi @eddiejaoude,
Please review my GitHub profile and share your valuable feedback.

GitHub Profile: https://github.com/ShyamPraveenSingh

Thanks in advance.

**Comment by Vyvy-vi** [comment]
@ShyamPraveenSingh I think your profile could be reviewed faster if you open an issue on the [support](https://github.com/EddieJaoudeCommunity/support) repository. Generally, comments on issues might get lost and due to the large amount of notifications, Eddie might not notice the above comment.

You could open an issue to get your profile reviewed here:
https://github.com/EddieJaoudeCommunity/support/issues/new/choose

**Comment by ShyamPraveenSingh** [comment]
> @ShyamPraveenSingh I think your profile could be reviewed faster if you open an issue on the [support](https://github.com/EddieJaoudeCommunity/support) repository. Generally, comments on issues might get lost and due to the large amount of notifications, Eddie might not notice the above comment.
> 
>  It would be great if you could open an issue to get your profile reviewed here:
> https://github.com/EddieJaoudeCommunity/support/issues/new/choose
> 
> Also, thanks for sharing :)

Hi, @Vyvy-vi thanks mate!

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/oM8rBNyiwPY

Looks great, some suggestions 
- Animation looks good but not accessible and also kind of looks like it is broken?
- GitHub badge in custom profile not needed, as already on your GitHub profile page
