### ISSUE TITLE
[REVIEW] <bishal7679>

### ISSUE THREAD

**Issue by bishal7679** [EddieHubCommunity/support#5249]
### GitHub Sponsor profile link

https://github.com/sponsors/bishal7679?o=sd&sc=t

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=He9lBSlTvhQ

Looks good, some suggestions...
- add more info and use markdown to break it up / more digestible 
- suggest having a few more tiers to make it easier for people
- add 1-2 featured repos
