### ISSUE TITLE
[REVIEW] Panquesito7's sponsor page

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/support#5257]
### GitHub Sponsor profile link

https://github.com/sponsors/Panquesito7

P.S.: I will make an update to my profile soon and the tiers as well (it's currently very long).

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=He9lBSlTvhQ

Looks good, some thoughts...
- try to shorten the text
