### ISSUE TITLE
[REVIEW] WasiqB

### ISSUE THREAD

**Issue by WasiqB** [EddieHubCommunity/support#5260]
### GitHub Sponsor profile link

https://github.com/sponsors/WasiqB

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=He9lBSlTvhQ

Looks good, some suggestions...
- pinning/featuring 2-4 repos
- starting from $1
- if the next tier includes the previous tier better to state it than to list them all each time
- goal is very high, suggest making it achievable from the person viewing it - so they can see they can have an impact
