### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ad3rinto** [EddieHubCommunity/support#5268]
### Name

Micheal Aderinto

### Discord Username (if applicable)

ad3rinto#6785

### Additional Context

I first came across Eddie on twitter about 2 years ago when he posted a guide to make your GitHub page more attractive.
I have followed his work since then

**Comment by ad3rinto** [comment]
Done.
Joined discord and the community server.

**Comment by schmelto** [comment]
You are already part of the GitHub org. 🔥
