### ISSUE TITLE
[REVIEW] LinuxGamer

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/support#5344]
### GitHub Profile Link

https://github.com/LinuxGamer/

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=YVJyz7DZMQo

-

**Comment by LinuxGamer** [comment]
Thanks folks, I've updated it a bit now, all you're feedback was very much welcome. (just quick about the pfp, i'll work on that soon.

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- love the collapsables 
- suggest removing the GitHub activity and use another GitHub Action
- try to do more code reviews
