### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by riya1511** [EddieHubCommunity/support#5408]
### Name

Riya Rai

### Discord Username (if applicable)

Riya Rai#8364

### Additional Context

Hey Eddie,
This feels excellent writing to you, the first time I came across the Eddie Hub was on Twitter, I consistently follow your content there and am very motivated to start open source, hence I came here to post my first issue and begin my journey.

**Comment by Ropcol** [comment]
Hi Eddie am new here and would like to be part of your team.am willing to learn
