### ISSUE TITLE
Please review my current open source project

### ISSUE THREAD

**Issue by RasPiPkr** [EddieHubCommunity/support#542]
Please review my latest project:

- Open source project 
https://github.com/RasPiPkr/myHome
It's my Home Heating and Security Control via Raspberry Pi and touchscreen coded in Python.

Many thanks
Martin Parker

**Comment by BOLT04** [comment]
Hi @RasPiPkr 😃, I took a look at your project and the project looks great 👍. I do think there are some areas where it can improve and incentivize contributions from new contributors. Here is my feedback:

- The `README` can make use of more markdown features to emphasize important parts. This helps the reader get straight to the info they need and are looking for, for example:

... command line enter:
`pip3 install pychromecast` <-- Used for voice announcement on Google Home.
`pip3 install beautifulsoup4` <-- Used for web scraping for sunrise and sunset times.

- Use labels to categorize your issues. 
_Note: It's great you're organizing your work with GitHub issues in the 1st place 👍_

Hope that helps 😃

**Comment by RasPiPkr** [comment]
Great idea, I'm new to documenting my repositories.

Cheers 👍😁

**Comment by eddiejaoude** [comment]
Looks great @RasPiPkr ! And great feedback @BOLT04 👍 

@RasPiPkr I will review in a future video / live stream too 🤓

**Comment by RasPiPkr** [comment]
That would be great thanks :thumbsup:

**Comment by Vyvy-vi** [comment]
The project looks really great @RasPiPkr  👍 

- As David said, it's great that you're using issues to organise and document the repository.
It would be really great, if you could add issue templates and labels: these would help you prioritise issues that are more essential or of specific areas, and might also help contributors in finding an issue that they would like to work on.|

- To maintain code quality, and make your tasks as a maintainer slightly easier, you could perhaps add a github action to lint and build the project?
   the ones provided by github: https://github.com/RasPiPkr/myHome/actions/new

**Comment by RasPiPkr** [comment]
Great idea, I will look in to it tomorrow.

Thank you for your suggestion.

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/oM8rBNyiwPY

Looks good, some suggestions:
- Use Pull Requests to encourage others to contribute
- Issues to have labels to make it easier for the community to join in
- Maybe have 1 image at the top of the repo (animated gif going through a few images or a demo would be great)
- Label example commands as a quickstart guide section
