### ISSUE TITLE
[REVIEW] karangorania

### ISSUE THREAD

**Issue by karangorania** [EddieHubCommunity/support#5532]
### GitHub Profile Link

https://github.com/karangorania

**Comment by schmelto** [comment]
For a profile review you need to have a custom profile. 

See here a course on how to do this


https://www.eddiejaoude.io/course-github-profile-landing

**Comment by karangorania** [comment]
@schmelto Can you check the profile. I have added.

**Comment by karangorania** [comment]
@schmelto Are you there ?

**Comment by schmelto** [comment]
Like it maybe only use some of the GH stats there are very many on your profile.

**Comment by karangorania** [comment]
noted. I will remove some of them.
