### ISSUE TITLE
Suggestion: Add glossary.md to tips folder 

### ISSUE THREAD

**Issue by ayoubmehd** [EddieHubCommunity/support#557]
# Add glossary.md to [tips](https://github.com/EddieJaoudeCommunity/support/tree/main/tips) folder 
After I watched this [Video](https://www.youtube.com/watch?v=4Zc9ci9L5wY) by Fireship.io, I thought that it is a good idea for my first OpenSource contribution.
A markdown file that contains a list of Programing terms with explanation and code examples if needed, and some additional resources to learn more about it.

### Anonymous Function
An anonymous function is a function that was declared without any named identifier to refer to it.

#### Code Examples
```javascript
window.addEventListener("click", function () {
    // This is An Anonymous Function
})
``` 

#### Additional Resources
https://en.wikipedia.org/wiki/Anonymous_function

**Comment by BOLT04** [comment]
Hi @ayoubmehd 😃, this is a pretty good idea! I think making our glossary and adding it to the tips folder is fine, but we could go beyond that and help a project that already has this type of glossary in place.

I found this project: https://github.com/do-community/developer-glossary, what do you say we contribute to it with your example "Anonymous Function" and perhaps others like asynchronous, etc 😃 ? Then we would add a link to this glossary on the tips command of EddieBot 👍 

PS: I'm sure there are other projects with this type of glossary, the one I mentioned is just an option

**Comment by ayoubmehd** [comment]
Hi @BOLT04, Yeah I think that's better than starting from scratch 👍.

**Comment by mikeysan** [comment]
A very good idea, @ayoubmehd , and thanks, @BOLT04  for the suggestion to contribute to an ongoing repo.

**Comment by eddiejaoude** [comment]
Great team work 💪 , thank you all 👍

**Comment by BOLT04** [comment]
Hi @ayoubmehd 😃, were you able to open a PR for that project's glossary? If so can we close this issue?

**Comment by ayoubmehd** [comment]
I oppened a PR #968, Thank you @BOLT04

**Comment by Vyvy-vi** [comment]
I was wondering since we have this on EddieBot, and were discussing about this, maybe we can have this repo as the place to keep tips and fetch the data from here to EddieBot

**Comment by ayoubmehd** [comment]
@Vyvy-vi I think that's a good idea

**Comment by BOLT04** [comment]
> 
> 
> I was wondering since we have this on EddieBot, and were discussing about this, maybe we can have this repo as the place to keep tips and fetch the data from here to EddieBot

that is a good idea 👍, I believe we discussed this somewhere earlier but I couldn't find any issue mentioning it.
If you want, let's open an issue on EddieBot to discuss the development of that feature @Vyvy-vi 😃.

However, I think this issue could be developed first: https://github.com/EddieHubCommunity/EddieBot/issues/418. So that we could leverage a function to get the list of tips in the support repo, what do you think?

**Comment by eddiejaoude** [comment]
Having it in this repo would mean we would not need to deploy the bot for the latest updates 👍
