### ISSUE TITLE
My Repositories

### ISSUE THREAD

**Issue by grpistoia** [EddieHubCommunity/support#560]
Hi Eddie

Here are 4 projects on GitHub I uploaded this year.

I work full time in IT in complex finance stuff.. and in my spare time I like to create crazy / artistic / uncommon projects to challenge myself and to see what can be achieved with some technologies. From the simplest to the hardest:

1) **Atomic**: This is one of the first games in Smalltalk Pharo. Smalltalk is a great language for education and learning Object Oriented Programming. The game runs in Smalltalk Virtual Machine and therefore runs on Linux, Windows, even on phones.

   Open repository here: [Atomic](https://github.com/grpistoia/Atomic)

2) **Clipified**: (originally called Clippy but I didn't want to get sued by Microsoft)
Is an application that runs on both Windows and Linux, written in Lararuz Pascal. Basically memorises all what you paste on your clipboard, so you can retrieve it later, even after rebooting. It comes with lots of extra tools, such as indenting text, screenshot an area, zoom, alarm and others. For example... you have a list of 1000 numbers you need to single quote and separate with new lines .. you can do that in just 2 clicks.

   Open repository here: [Clipified](https://github.com/grpistoia/Clipified)

3) **SpreadsheetGames**: Here things go wild. I implemented 2 games that run on a Spreadsheet Editor like Excel. The first one is **Sudoku**. The spreadsheet will generate **unique**, **stable** and **valid** Sudoku puzzles. That means.. each of them is different, you can save the file and continue next day, and the puzzles have 1 and only 1 solution. That was a challenge since Excel, Google Docs and LibreOffice do not support recursion (game version available on all those platforms). The game does **not** require any plugin or macros !!! That's right... no macros. Still will display errors and hints in colours and check your answers as you complete.
The second game is a Japanese Nonogram, a newspaper game where you have to decipher an image based on clues. Puzzles are either black & white and coloured.

   Open repository here: [SpreadsheetGames](https://github.com/grpistoia/SpreadsheetGames)

4) **Mathemagics**: A **symbolic Algebra library** implemented using Object Oriented Programming. Similar to Algebra in "mathlab" / "symbolab", just implemented by myself. There is no source code online how to build a system like that, so I thought it was time someone did. This library now supports very complex processes such as Simplification and Derivatives. It even generate codes from a Mathematical expression back into Smalltalk code. It also supports symbols, such as "pi" will print "π".. all extensible.
This is obviously a very complex project, required few months of design and coding. Two examples here:

   `(MathExpression from: 'sin(x)*cos(x+x)/sin(sqr(x)/x) + pi') simplify  ... returns "cos(2·x) + π"`

   `(MathExpression from: 'x*x + ln(x)') derivativeFor: 'x'               ... returns "2·x + 1/x"`

   Open repository here: [Mathemagics](https://github.com/grpistoia/Mathemagics)

Thanks it.
Hope you like them.

GitHub: grpistoia
Gmail: grpistoia@...

**Comment by eddiejaoude** [comment]
Thanks for sharing @grpistoia 👍 - I will review in a future video / live stream

**Comment by eddiejaoude** [comment]
Reviewing your https://github.com/grpistoia/Atomic project in the live stream https://youtu.be/oM8rBNyiwPY

Some of my suggestions
- Using tags (create a reel even if it is a beta release)
- Is there a deployed version? Add deployed or website link to the repo
- Maybe some repo topics with the description 
- Make quickstart more focus, also how do I `Open the playground and run:` to run the command?
- An animated gif could really help show the game in the README
- Add a code of conduct https://github.com/grpistoia/Atomic/community

**Comment by grpistoia** [comment]
Thanks Eddie for the review.

I will add the tag and code of conduct, make sense.

I know you were a bit in a rush.. actually there are 4 complete different projects. Two are games, two are tools, all very different projects.

* Atomic (the one you review) is a game in Pharo / Smalltalk. The "playground" is part of the environment (like the evaluator in Eclipse). There is no runtime .exe file.. is all downloadable directly into the image.
* The other game is built inside the Excel files itself. No macros or plugins!. You can download for Excel or Open Office. Still I made a Sudoku on it.
* Clipified is a tool.. you can download the code and the executable for Windows or Linux.
* Mathemagics is a library .. no executable.. is downloadable in Pharo too. Very complex project. Is like a mini MathLab.

Feel free to have a look at the other projects or previous summary.. it will make more sense.

Thanks again,
Gustavo.
