### ISSUE TITLE
[REVIEW] Alpaca Logger

### ISSUE THREAD

**Issue by gptkrsh** [EddieHubCommunity/support#5695]
### Project link

https://github.com/krshkun/alpaca-logger

**Comment by krshkun** [comment]
This is very new 😂 Lot of contributions to be made

**Comment by theritikchoure** [comment]
Suggestions 

- Create an attractive readme file
- Add a description of the repository in the About section 
- If packages is not needed then hide it

**Comment by gptkrsh** [comment]
thanks for the suggestions, closing this issue since the project has been renamed
