### ISSUE TITLE
[REVIEW] NimishKashyap

### ISSUE THREAD

**Issue by NimishKashyap** [EddieHubCommunity/support#5697]
### GitHub Profile Link

https://github.com/NimishKashyap

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- maybe centre the socials to be the same as everything else
- join EddieHub org 😜 
- profile views are not a good thing to display IMHO

**Comment by BinayakJha** [comment]
Looks good !!

check #5677
