### ISSUE TITLE
[REVIEW] Krish

### ISSUE THREAD

**Issue by krshkun** [EddieHubCommunity/support#5705]
### GitHub Profile Link

@krshkun

**Comment by eddiejaoude** [comment]
Looks good, reviewed on live stream, some suggestions...

- tweet image looks squished
- remove archived repos from pins

**Comment by krupalitrivedi** [comment]
Great profile Krish, here are a few suggestions:

- Add One line or small introduction for yourself
- Add a little bit about yourself in About Me on the left side

It would be helpful if someone could take a look at Krish's profile and let us know if the pictures are squished or not!

![image](https://user-images.githubusercontent.com/99717469/194829998-eee70a0f-3f40-4387-b90f-0e0b7c49ca7d.png)
