### ISSUE TITLE
[REVIEW] <soumdatta81>

### ISSUE THREAD

**Issue by soumdatta81** [EddieHubCommunity/support#5708]
### GitHub Profile Link

https://github.com/soumdatta81

**Comment by eddiejaoude** [comment]
Reviewed on live stream, looks great, some suggestions

- Great to see you halved the banner height already 👍 
- Add your Org to your profile
- Text is very close to the animated image
- Widgets take a lot of height, suggest having them side by side
- Suggest doing some more code reviews for you contributors graph

**Comment by soumdatta81** [comment]
Thanks Eddie for your feedback.
