### ISSUE TITLE
Browser fingerprinting and tracking demo

### ISSUE THREAD

**Issue by ujjwal-kr** [EddieHubCommunity/support#576]
Github repo: https://github.com/ujjwal-kr/ip-sniff
The Demo: https://epictracker.now.sh

- It is a demonstration project of how can I track you using fingerprinting and some automated lookups and stuff.
> - <del> It uses modern Javascript APIs to identify your metadata and keeps the information in a cookie, encrypting it.</del>

Edit-
- It uses modern Javascript APIs to identify your metadata and generates an SHA-1 hash based on it. The hash can be used to further identify the browser even after clearing the cache or using the demo in private browsing mode.

- I may create dummy marketing services to demonstrate the (targeted ads) tracking process close to the real-world.

**Comment by ujjwal-kr** [comment]
A warning: clicking on the demo link may log some of your private information to my server. I have no malicious intentions and this is for open-source and educational purposes. DO NOT click on the demo if you don't want to get doxxed.

**Comment by mikeysan** [comment]
Hey @ujjwal-kr 

Looks like a great project. I may look to adapt it for python at some point (when I get good at python 😃 ). In the meantime, could I suggest a few things please.

I do not see any warning about the information that is gathered when the demo link is clicked. I think for transparency you should include (in the readme) every single data that is collected. 

Also, a note about what you do with the data afterwards should be included. Do you delete it? How long before you delete it? Are you adding it to a database? How secure is that database? Especially, because you hint on several occasions that the information could potentially by used to identify someone.

More importantly, though, a clear list of every information a user is risking passing on you whoever uses your project should be listed in the readme.

**Comment by Vyvy-vi** [comment]
Looks good 👍 
Though, as mikey said more info on what you do with the data and what all is the data stored would be good. 

smh the only info of mine it got correct was:
My OS
My logical processor coresc
olor depth
device dimentions
My bad Intel graphics

**Comment by ujjwal-kr** [comment]
@mikeysan thanks for the feedback!

> Looks like a great project. I may look to adapt it for python at some point (when I get good at python)
Yeah, I mean you can build the backend with a python server, but you will have to use the modern javascript APIs as I did in-
https://github.com/ujjwal-kr/ip-sniff/blob/main/client/index.js.

**Comment by ujjwal-kr** [comment]
yeah, I need to work on the readme, give me some moment for that 😅. I also added some motion tracker info btw :)

**Comment by ujjwal-kr** [comment]
The readme has been updated :)

**Comment by ujjwal-kr** [comment]
I added weather a API 🐦

**Comment by Vyvy-vi** [comment]
xD this would be creepy, if you add images on the top showing weather conditions.

**Comment by mikeysan** [comment]
Test results :) 

Tested on the same VM

![image](https://user-images.githubusercontent.com/13338176/103088719-8e2ae280-45e3-11eb-8048-83595a644184.png)

**Comment by Vyvy-vi** [comment]
I wonder what the display dimensions would say, if I open this in headless?

**Comment by eddiejaoude** [comment]
thanks @ujjwal-kr I will review in a future video to live stream 👍 . I see you got some great feedback already 🤓

**Comment by ujjwal-kr** [comment]
that will be great @eddiejaoude (ed)

**Comment by ujjwal-kr** [comment]
I will be working on VPN detection today, I think I can detect VPN proxies from another country at least 🤔

**Comment by ujjwal-kr** [comment]
I'm adding hashing functions. now I don't have to collect data to track you can I can generate a unique identifier for each config!
https://twitter.com/epicujjwal/status/1350546122423500800

**Comment by mikeysan** [comment]
I look forward to testing this again.

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/oM8rBNyiwPY

Some suggestions
- Use releases / tags
- Use issues to track `todos` and not have them at the bottom of the README
- Suggest moving the warning to the top before the demo link
-
