### ISSUE TITLE
[OTHER]Help!

### ISSUE THREAD

**Issue by padrone1225** [EddieHubCommunity/support#5832]
### Additional information

Hi, this is Tenshi Ota. I am a member of the EddieHub community. I recently joined this community. But I couldn't join the community's Discord. This is because you can't log in to discord.com. So can you invite me to the discord? Help.

_No response_

**Comment by padrone1225** [comment]
Ok.
I have joined this community but I can't join discord.
How can do I?

**Comment by padsalatushal** [comment]
https://discord.com/invite/jZQs6Wu

**Comment by schmelto** [comment]
Did it work?

**Comment by schmelto** [comment]
Feel free to reopen an issue
