### ISSUE TITLE
Review my GitHub profile

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [EddieHubCommunity/support#584]
Hi, 
@eddiejaoude can you please review my GitHub profile and share your valuable feedback.

Thanks in advance,
Shyam Praveen Singh

**Comment by Vyvy-vi** [comment]
for easy reference, link to @ShyamPraveenSingh's README:
https://github.com/ShyamPraveenSingh

**Comment by vinzvinci98** [comment]
I liked the GIFs on your GitHub profile 💯

**Comment by ShyamPraveenSingh** [comment]
> I liked the GIFs on your GitHub profile

Thanks! 
You can get more GIFs from [here](https://giphy.com/l) and even custom make new gifs.

**Comment by Vyvy-vi** [comment]
Thanks for sharing :+1:

**Comment by eddiejaoude** [comment]
Thank you for sharing @ShyamPraveenSingh , I will review in a video or live stream soon 👍 

I have added the label `open source review` so it does not get forgotten.

**Comment by ShyamPraveenSingh** [comment]
> Thank you for sharing @ShyamPraveenSingh , I will review in a video or live stream soon 
> 
> I have added the label `open source review` so it does not get forgotten.

Thank you so much once again!

**Comment by eddiejaoude** [comment]
Thank you for submit for reviewed, reviewed on live stream https://youtu.be/eXqqS6CRTOQ

- animated gif of code looks great, but is it your code?
- animated coder gif might not have the rights to use it?
- you are not part of the `EddieHub` Org 😱 
- 2 repos repeated in README and also pinned repos - could use this space for showing off other work
- lots of green squares, that shows consistency
- I am not a fan of the profile views bagde
- Commits are high, but pull requests, code reviews and issues are low
- Maybe use social icons as links
