### ISSUE TITLE
Review StandNote 

### ISSUE THREAD

**Issue by PragatiVerma18** [EddieHubCommunity/support#585]
Hi @eddiejaoude, please review my open source project - 
## StandNote
Web conferencing and online meetings have become the new work culture nowadays. But somewhere along the lines, we often keep missing the crux of the discussions in these online meetings, and here comes our solution - **StandNote**. It is your easy to use online meeting assistant that backs you up with automated meeting minutes in every conversation. It will help you save time on board meetings, team management, and customer support such that you just focus on the conversation and never miss what’s important.

StandNote also fits into the current online education scenario where most of the classes take place over online platforms like Google Meet and Zoom. We help students with quick and concise notes that help them to revise and memorize the concepts better.

## Links:
- **Chrome Extension**: https://bit.ly/StandNote-Extension 
- **Project Submission**:  https://devfolio.co/submissions/standnote-1
- **Web Application**: https://standnote.netlify.app/

https://user-images.githubusercontent.com/42115530/102979631-56ad2f00-452c-11eb-92d0-25260992d292.mp4

**Comment by Vyvy-vi** [comment]
The project looks really good!
Perhaps you could link to the Github repository of the project too?

Thanks for sharing! 🤓

**Comment by PragatiVerma18** [comment]
> The project looks really good!
> Perhaps you could link to the Github repository of the project too?
> 
> Thanks for sharing! 🤓

Thanks, @Vyvy-vi! Here's the GitHub link: https://github.com/rajat2502/StandNote

**Comment by eddiejaoude** [comment]
The project looks really good & interesting 👍 . I will review in a YT video or live stream in the future to get more eyes on it for you. But for now I will share some thoughts here:

- personally I would not have a branch for each project, I would recommend to create a GitHub Org and a repo for each project (or even a mono repo would be better if you do not want to create an Org)
- branching name casing are not consistent, I know everyone gets excited about react, but it doesn't need to have capitals
- branching name style, the frontend project has it in the name but the other branches do not
- team section is great, maybe show which area each team member focuses on? so if people have questions they know who to ask
- tag/release, I suggest making a release when at a stable point even if beta
- issue section is not being used, if your team use it, the project will be more inclusive and others will join in
- issue + pull request template would be useful 
- GitHub Action to automate tasks - for example linting, creating release, deploying to netlify ...
- some commits use a standard and others do not (many commits with `Update README.md` does not look great)

I hope that helps 🤓

**Comment by PragatiVerma18** [comment]
Thank you so much @eddiejaoude for the review. I and my team will surely make the changes asap. 😄

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/eXqqS6CRTOQ

Here are some of my thoughts:
- looks great, amazing logo
- Missing image in the links section https://github.com/rajat2502/StandNote#links
- branching naming inconsistent (`React-Frontend`, `django`)
- use PRs for all changes
- I think it would be better to use a mono repo style, using branches for different code bases you miss out on features like CodeOwners
