### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by trendy0413** [EddieHubCommunity/support#5910]
### Name

trendy

### Additional Context

I am really exited to join this community.

**Comment by samuel-ma** [comment]
@trendy0413 
Let me know once u get invited into the organization

**Comment by schmelto** [comment]
you should now have got an invitation via mail

**Comment by schmelto** [comment]
@samuel-ma if you want to join the community please open a new issue [here](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)
