### ISSUE TITLE
[BUG] update organization invitation to latest version - Good first issue

### ISSUE THREAD

**Issue by vj-abishek** [EddieHubCommunity/support#5945]
### Description of the bug

The support for node 12 has been deprecated. Update the action to the latest version.

https://github.com/EddieHubCommunity/support/blob/32c51a3d276a4c5702eb45fad9cf6ceb811f1520/.github/workflows/invitation.yml#L10

## Release
https://github.com/vj-abigo/invite-on-label/releases/tag/v1.4

### Project stack or language (e.g. front-end)

github-action

### Working Environment (e.g. operating system, browser, device)

Github

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/43115551/200472930-ef433c22-1201-4b3e-ab9a-0875f75b351d.png)

**Comment by andrito9755** [comment]
Is this issue still open?

**Comment by vj-abishek** [comment]
Yep, it is still open for fix. 

https://github.com/EddieHubCommunity/support/actions/runs/7087933239/job/19289273539#step:2:13

**Comment by andrito9755** [comment]
Hi there,

I've just submitted a pull request addressing the Node.js deprecation issue
in the 'invitation.yml' file. Please review at your convenience.

Thanks,
Anand Bhosle
