### ISSUE TITLE
[REVIEW] type-chef-di

### ISSUE THREAD

**Issue by MaurerKrisztian** [EddieHubCommunity/support#5959]
### Project link

https://github.com/OpenZer0/type-chef-di

**Comment by theritikchoure** [comment]
Some suggestions from my point of view - 

- Write an Attractive Readme file
- Add contributing.md and code_of_conduct.md files
- Add issue template and pull request template

Happy Learning 💚

**Comment by MaurerKrisztian** [comment]
@theritikchoure Thanks for your feedback, I updated the things that you suggested.

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- suggest removing the wiki tab as it is not used
