### ISSUE TITLE
[REVIEW] FaceDetection AttendanceSystem

### ISSUE THREAD

**Issue by aryaraj132** [EddieHubCommunity/support#5975]
### Project link

https://github.com/aryaraj132/FaceDetection-AttendanceSystem

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- suggest using GitHub Actions for linters, tests etc
- issue templates
- use releases when a stable version is available
- suggest not hiding the first image as that looks great

**Comment by aryaraj132** [comment]
Thank you for you feedback ❤️
