### ISSUE TITLE
[REVIEW] thesaravanakumar

### ISSUE THREAD

**Issue by thesaravanakumar** [EddieHubCommunity/support#5977]
### GitHub Profile Link

https://github.com/thesaravanakumar

**Comment by theritikchoure** [comment]
Some suggestions from my point of view - 

- You can use a professional profile photo
- you can remove this 👇 badge, as it always says A+ for every profile
![image](https://user-images.githubusercontent.com/56495602/205425210-ae2c32dc-a6ca-46e6-8224-88a2d1fc38ed.png)

- try to contribute to more open source projects
