### ISSUE TITLE
[REVIEW] @AldrinSeanPereira

### ISSUE THREAD

**Issue by AldrinSeanPereira** [EddieHubCommunity/support#6117]
### GitHub Profile Link

https://github.com/AldrinSeanPereira

**Comment by VishwaS-22** [comment]
Hey @AldrinSeanPereira! Your profile looks good man but you've to contribute more to the OSS projects. Keep contributing.
Thankyou!

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- pin another repo (2 or 4)

**Comment by AldrinSeanPereira** [comment]
Thank you so much Eddie!! 😋🙌
