### ISSUE TITLE
[REVIEW] FrancescoXX

### ISSUE THREAD

**Issue by FrancescoXX** [EddieHubCommunity/support#6137]
### GitHub Profile Link

https://github.com/FrancescoXX

**Comment by eddiejaoude** [comment]
Looks great, here are some suggestions https://www.youtube.com/watch?v=iqIFD02OkVE

- Discord community more clear
- No widgets required
- Join EddieHub to get more points
- Try to do more code reviews, issues and pull request
- Try to do the content creation sections into columns
