### ISSUE TITLE
Creating New Repository "branding" | As per discussion

### ISSUE THREAD

**Issue by SuNiL-Chau** [EddieHubCommunity/support#615]
Creating new repository __"branding"__ for the community branding purpose.

> where our community's artwork, emojis etc. can reside, open for contributions, and suggestions.

Checkout the complete discussion here #599 .

**Comment by eddiejaoude** [comment]
Thank you @SuNiL-Chau for raising 👍

**Comment by eddiejaoude** [comment]
Repo created https://github.com/EddieHubCommunity/Branding
