### ISSUE TITLE
Please review my profile sir

### ISSUE THREAD

**Issue by Keshav04042001** [EddieHubCommunity/support#622]
Hey Dear @eddiejaoude .This is Keshav Agrawal (making a big wish that you remember me).
Sir,Please review my github profile

**Comment by eddiejaoude** [comment]
Thank you for sharing your project 👍 - I will take a look and review in a YouTube video / live stream soon 🤓

**Comment by Keshav04042001** [comment]
Ohh thanks @eddiejaoude  sir for considering me to reply

**Comment by eddiejaoude** [comment]
Thank you for sharing, reviewing on live stream https://youtu.be/eXqqS6CRTOQ 

- Looks really full profile and colourful
- But maybe has too many animations
- The colourful image may effect people with epilepsy 
- I think profile views are not a great thing to show
- Duplication of social badges
- Spotify animation is great, is it live?
