### ISSUE TITLE
GitHub Readme Streak Stats

### ISSUE THREAD

**Issue by DenverCoder1** [EddieHubCommunity/support#625]
Items we can review on a live stream:

- https://github.com/DenverCoder1
- https://github.com/DenverCoder1/github-readme-streak-stats

**Github Readme Streak Stats**
🔥 Stay motivated and show off your contribution streak!
🌟 Display your total contributions, current streak, and longest streak on your GitHub profile README

----

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by Vyvy-vi** [comment]
The project looks amazing! ⭐

**Comment by DenverCoder1** [comment]
Thanks, @Vyvy-vi! Glad you like it :)

**Comment by eddiejaoude** [comment]
Thank you for sharing your project 👍 - I will take a look and review in a YouTube video / live stream soon 🤓

**Comment by DenverCoder1** [comment]
@eddiejaoude Awesome, thanks! 👍

**Comment by vinzvinci98** [comment]
I loved it, even your GitHub profile readme is totally different for me. I want to try some of your features. 

**You deserve a lot of stars too :)**

**Comment by DenverCoder1** [comment]
Thanks, @vinzvinci98!

**Comment by Vyvy-vi** [comment]
I had a question: I have deployed my own version of this on heroku.. but I often notice that every now and then the streak card doesn't embed on my readme. What might be causing this?

**Comment by DenverCoder1** [comment]
@Vyvy-vi I'm not sure. When I check your profile it seems to be working. I'm not sure why it work any differently.

**Comment by eddiejaoude** [comment]
Thanks for sharing, reviewed on live stream https://youtu.be/eXqqS6CRTOQ

- looks good
- image at the top looks good, but takes up a lot of space, what about having the `about me` on the left and the image on the right
- lot of wasted space in the profile, makes the page scroll longer
- duplicate social links for example YouTube in multiple sections
- GitHub stats graph at the bottom to be visible all the time

**Comment by DenverCoder1** [comment]
Thanks so much the review!

I took your feedback into account when redesigning my profile 👍

I also noticed that you've put Streak Stats on your profile, so that's awesome!

Thanks for all that you do for the community!

**Comment by DenverCoder1** [comment]
Hi @eddiejaoude

I was looking forward to getting the Streak Stats repo reviewed, although it's understandable that there wasn't enough time to check both links and I should've made it more clear that the a review of the repo would've been my preference.

Would it be fine to get it reviewed at a later date? It's completely understandable if you'd prefer to check new people's repos instead.

If it's fine, should I open a new issue?

Thanks!

**Comment by eddiejaoude** [comment]
Sure, you can open a new issue 👍
