### ISSUE TITLE
invite me to the GitHub Community Org

### ISSUE THREAD

**Issue by jagadesh-angireddi** [EddieHubCommunity/support#6371]
### What would you like to share?

invite me to the GitHub Community Org

**Comment by eddiejaoude** [comment]
Please raise the correct type of issue, here is the link https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization
