### ISSUE TITLE
Review my GitHub profile

### ISSUE THREAD

**Issue by Utkarsh299-tech** [EddieHubCommunity/support#640]
Hi, @eddiejaoude! Can you please review my GitHub profile as well as my portfolio on a live stream? If yes, then please give your valuable feedback. Thank you in advance!
Items we can review on a live stream:

- GitHub profile: https://github.com/Utkarsh299-tech/
- Open source project
- Portfolio: https://github.com/Utkarsh299-tech/myportfolio
-  https://utkarsh299-tech.github.io/myportfolio/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 - sure I will review it on live stream / video soon

**Comment by Utkarsh299-tech** [comment]
> Thanks for sharing 👍 - sure I will review it on live stream / video soon

Thanks, Eddie! 👍

**Comment by Vyvy-vi** [comment]
Your profile looks good :+1: (the cat jumped me a bit 😂 ). Perhaps the plugins can be formatted without that empty space to the side(up to you, looks okay as it is)?

A few thoughts on the portfolio project
- It would be really great if you had a deployed version of your portfolio site(you could look at github pages)
- Using meaningful commit messages might help contributors and would could portray better image of project in front of recruiters.
- A README(not necessary, _but_  it would help contributors in making edits to your portfolio and in making it better).
- Most of the projects links in `my work` reroute to the main page

**Comment by dumbcoder7** [comment]
I was gonna raise issues on the repo but I see issues are mentioned here itself. Would love to add to the above suggestions. 

- You have added the deployed link in the post but not in the repo. Initialize README, description and add the link there.
- Is the site developed from scratch or picked up from some source? Sorry, I couldn't tell. But I suspected this because the links in the footer direct nowhere. Maybe change that. Also the links and images in the `My Work` section.
- In the `What I Do` section, the quotes and the text should be formatted differently. It is difficult to discern and hence looks longer than needed and motivates the viewer to skip directly.
- Consider adding all html files to a folder.
- Only one massive commit. Eddie is gonna dislike that. Keep improving the project repeatedly.

**Comment by imvisp** [comment]
your profile is really good

here is one point.
-this link has vyvv's github profile,you can change your profile.
![u](https://user-images.githubusercontent.com/75424375/106349840-404a7e00-62f7-11eb-915b-1ac5dbf8dc00.png)

**Comment by Utkarsh299-tech** [comment]
> your profile is really good
> 
> here is one point.
> -this link has vyvv's github profile,you can change your profile.
> ![u](https://user-images.githubusercontent.com/75424375/106349840-404a7e00-62f7-11eb-915b-1ac5dbf8dc00.png)

Oh, thank you for reviewing! Oh, I copied that badge from vyvy's GitHub profile but forgot to add my profile. I'm doing it now :)

**Comment by Utkarsh299-tech** [comment]
> Your profile looks good 👍 (the cat jumped me a bit 😂 ). Perhaps the plugins can be formatted without that empty space to the side(up to you, looks okay as it is)?
> 
> A few thoughts on the portfolio project
> 
> * It would be really great if you had a deployed version of your portfolio site(you could look at github pages)
> * Using meaningful commit messages might help contributors and would could portray better image of project in front of recruiters.
> * A README(not necessary, _but_  it would help contributors in making edits to your portfolio and in making it better).
> * Most of the projects links in `my work` reroute to the main page

Thank you for reviewing my profile. 
* I think I've already deployed my portfolio through GitHub pages. 
 * I will keep that in mind for sure from next time onwards, I will use meaningful commit messages. I added README now. Please check it out. Hoping for your valuable feedback/suggestions.
* Yes, I haven't yet added most of the projects, so they might be rerouting to the main page.
Thank you again :)

**Comment by Utkarsh299-tech** [comment]
> I was gonna raise issues on the repo but I see issues are mentioned here itself. Would love to add to the above suggestions.
> 
> * You have added the deployed link in the post but not in the repo. Initialize README, description and add the link there.
> * Is the site developed from scratch or picked up from some source? Sorry, I couldn't tell. But I suspected this because the links in the footer direct nowhere. Maybe change that. Also the links and images in the `My Work` section.
> * In the `What I Do` section, the quotes and the text should be formatted differently. It is difficult to discern and hence looks longer than needed and motivates the viewer to skip directly.
> * Consider adding all html files to a folder.
> * Only one massive commit. Eddie is gonna dislike that. Keep improving the project repeatedly.

Thank you for reviewing my profile :) 
* I've added README now based on your and others' suggestions and also added deployed link to my portfolio.  
* I have added the tutorial link in README.md from where I've learnt building such a portfolio. Updated the links in the footer to my socials. 
* I will add more and more commits. And try to implement everything you suggested.

**Comment by eddiejaoude** [comment]
Thanks for submitting, reviewed on the live stream https://youtu.be/eXqqS6CRTOQ

Website
- Portfolio looks great, really clean
- Menu could be displayed all the time on a desktop
- logo is very small
- skills text is difficult to read

Repo
- missing first image, `webp` does not work on Safari
- looks good 👍
