### ISSUE TITLE
Review my open source Project

### ISSUE THREAD

**Issue by akshitagupta15june** [EddieHubCommunity/support#643]
Items we can review on a live stream:

- Open-source project: https://github.com/akshitagupta15june/Face-X
- open-source profile: https://github.com/akshitagupta15june
- Part of various open-source programs(Winter of codes) like DWOC , SWOC, NWOC and UACEIT and GSSOC

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 - I will review in a future video / live stream

**Comment by eddiejaoude** [comment]
Review on live stream https://youtu.be/eXqqS6CRTOQ

Feedback
- it is better if merged branches are deleted, this can be automated in settings `Automatically delete head branches`
- use consistent naming conversations
- Installation steps has inline back tics as well as a code block
- missing image at the end of the readme (safari only)

**Comment by akshitagupta15june** [comment]
thanks for the suggestions @eddiejaoude
