### ISSUE TITLE
Review My Github Profile

### ISSUE THREAD

**Issue by SuNiL-Chau** [EddieHubCommunity/support#644]
Hey, @eddiejaoude I know you might be caught up with the things but can u please review my GitHub profile?
If Yes, then waiting for your valuable feedback on it :)

Items we can review on a live stream:

- GitHub profile: https://github.com/SuNiL-Chau

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by dumbcoder7** [comment]
I checked out your README, it's short and crisp so I like it.

Some minor suggestions:

1. There was a lot of blank space below that GitHub cartoon that I feel can be better utilized.

1. Use proper capitalization when mentioning technologies. For eg: `HTML` and `CSS`

1. Consider removing the `Profile Views` tab. It just increments every time somebody refreshes the page (including you) and hence cannot be trusted.

**Comment by eddiejaoude** [comment]
Thanks for submitting 👍 - I will review in a YouTube video / live stream soon 🤓 

Great to see the community giving you feedback already 💪

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/eXqqS6CRTOQ

Looks really good, some thoughts...
- GitHub  profile add social link
- YouTube link does not work
- Banners look great, but take a lot of space
- Maybe show GitHub stats by default
- Maybe try to be a bit more consistent with the green squares 🟩 
- Social ideas color does not seem to match your colour scheme (I could be wrong)
