### ISSUE TITLE
[FEATURE REQUEST] <Search feature to find results>

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/support#6457]
### Description of feature request, idea

A place where users can find view stats on the Linkfree profile

**Comment by AniketNS** [comment]
hello @CBID2 mam, I would like to work on this issue. Can u please guide me?

**Comment by CBID2** [comment]
Hi there @AniketNS! @eddiejaoude came up with this idea.

**Comment by eddiejaoude** [comment]
I think this is in the wrong repo? I will close, if still relevant please recreate on the LinkFree repo with more info
