### ISSUE TITLE
[REVIEW] on behalf of Dean <3

### ISSUE THREAD

**Issue by krshkun** [EddieHubCommunity/support#6459]
### LinkFree profile link

https://linkfree.eddiehub.io/loftwah

**Comment by krshkun** [comment]
This is the last I promise eddie :D they are soooo sooo soooo helpful in the EddieHubCommunity ❤ I just love that they are there. I don't want them to miss here

**Comment by eddiejaoude** [comment]
Looks great 👍 

- maybe use markdown in the bio
- suggest using milestones
