### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by safeeralehsan** [EddieHubCommunity/support#6485]
### Name

Safeer Al Ehsan

### Discord Username (if applicable)

Noodle#7007

### Additional Context

Hi! I found Eddie on LinkedIn. I'm interested in getting into Open Source and Eddie's posts and videos brought me here. I'm hoping to learn and further my development skills as well as connect with people who are on a similar journey. :)

**Comment by AniketNS** [comment]
Hey @safeeralehsan , how can I do that? I would like to do that?

**Comment by safeeralehsan** [comment]
Hey @AniketNS you can do this by raising an issue here: 
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

Followingly, you can go through the steps mentioned in the EddieCommunity git home page to get familiar with what the community is up to. I'd highly recommend joining the Discord server.
