### ISSUE TITLE
List files in readme.md

### ISSUE THREAD

**Issue by MallikarjunHt** [EddieHubCommunity/support#652]
**Description**

A brief description of the question or issue:
lets say i have a directory with multiple folders and each folder contain some files. now i need to display directory structure in `Readme.md` . 

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by MallikarjunHt** [comment]
It would be nice if we have a action to run on every push so that all files are listed properly.
:nerd_face:

**Comment by eddiejaoude** [comment]
Great idea 👍
