### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by bhanuteja1901** [EddieHubCommunity/support#6612]
### Name

bhanuteja

### Additional Context

to learn

**Comment by bhanuteja1901** [comment]
to learn

**Comment by SaptarshiSarkar12** [comment]
@bhanuteja1901 If you have joined or want to join, you may do so. Else this issue needs to be closed.

**Comment by Bhanuteja01** [comment]
Yeah I joined

**Comment by SaptarshiSarkar12** [comment]
Please close this issue then @bhanuteja1901
