### ISSUE TITLE
Issue to review my Open source project on a Python library

### ISSUE THREAD

**Issue by BALaka-18** [EddieHubCommunity/support#676]
Items we can review on a live stream:

- GitHub profile : https://github.com/BALaka-18
- Open source project : https://github.com/BALaka-18/rake_new2

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing Balaka 👍 . I will review in a live stream of video soon 🤓

**Comment by eddiejaoude** [comment]
Looks great 👍 some of my feedback, just point of view.. https://youtu.be/MJ4NOZnug6g

- Username + repo name following different styles
- Add a release for a stable usage
- Lots of branches, suggest deleting merged branches and removing any others not need
- Labels to have a description
- Clean up old / stale PRs
- Quickstart could do with some more details
