### ISSUE TITLE
Review my open source project

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [EddieHubCommunity/support#677]
Items we can review on a live stream:

- GitHub profile  https://github.com/ShyamPraveenSingh
- Open source project  https://github.com/ShyamPraveenSingh/Weather-Forecast-App

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing Shyan 👍 . I will review on a live stream or video soon 🤓

**Comment by ShyamPraveenSingh** [comment]
@eddiejaoude Thank you so much! Will eagerly wait for it.

**Comment by eddiejaoude** [comment]
Looks good, some of my thoughts https://youtu.be/MJ4NOZnug6g

- No releases yet
- Suggest using issues and maybe pull requests
- great to see the screenshot in the README
- A quickstart would help people to know how to use your project
- Use a folder structure
