### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by MitAbhay** [EddieHubCommunity/support#6775]
### Name

Abhay Kumar Mittal

### Discord Username (if applicable)

MitAbhay

### Additional Context

First time I get to know about Eddie by the project Linkfree, it's an amazing project where even beginner can contribute. I have also contributed in this project last week and the way the maintainers and Eddie help me was amazing, that what I love about this awesome community.

**Comment by krshkun** [comment]
Welcome to EddieHub!
