### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by lingaiahdanda** [EddieHubCommunity/support#6776]
### Name

Lingaiah

### Discord Username (if applicable)

dlc#6452

### Additional Context

I came to know EddieHub through krunal's channel and I am interested in opensource development. I like to improve my technical skills via opensource. EddieHub has a  good community. So, I would like to be a part of it.

**Comment by krshkun** [comment]
Welcome to EddieHub
