### ISSUE TITLE
Review my project

### ISSUE THREAD

**Issue by NitishGadangi** [EddieHubCommunity/support#679]
Items we can review on a live stream:

- GitHub profile : https://github.com/NitishGadangi
- Open-source project : https://github.com/NitishGadangi/Privacy-Indicator-App

**Comment by eddiejaoude** [comment]
Thank you for sharing Nitish 👍 . I will review on a live stream or video soon 🤓

**Comment by eddiejaoude** [comment]
Looks good, some of my thoughts https://youtu.be/MJ4NOZnug6g

- Is it time to take another release / tag
- `.idea` folder I think should not be commited
- recent issues do not have label
- maybe split up the README in to a docs folder as it has lots of screenshots
- could some of the screenshots be made into animated gives to reduce the amount
