### ISSUE TITLE
Please review my company's open source project

### ISSUE THREAD

**Issue by mooreds** [EddieHubCommunity/support#681]
Items we can review on a live stream:

- Open source project: https://github.com/fusionauth/fusionauth-jwt

Not sure if you review company OSS, but if you do, would love to know how welcoming/well set up this open source project is.

If you are more aimed at individuals' OSS, totally understand, just thought I'd ask.

**Comment by mikeysan** [comment]
Hi @mooreds 

I had a quick look in my very limited capacity as a newbie to both development and open source. A couple of things stood out to me immediately.
1. JWT - I couldn't find anywhere that tells me what this means. As a result, I couldn't get a full comprehension of what the readme is addressing. I understand that there is a specific target audience, and the readme has me written with that in mind. However,  I would hope that the readme could be written in a way that 'invited' new developers through the door.

2. Missing a  Code of conduct and

3.  Contributing guidelines

I hope that helps

**Comment by eddiejaoude** [comment]
Thanks Dan for submitting 👍 . If it is open source I am happy to review 🤓 . I will do this on a video or live stream soon.

Great feedback @mikeysan 👍 Its awesome to see the community give their point of view too, this is so important  💪

**Comment by eddiejaoude** [comment]
Looks good, some of my thoughts https://youtu.be/MJ4NOZnug6g

- could `CHANGES` be automated
- could `CHANGES` be renamed to `CHANGELOG`
- issue could have labels
- Could the README be split out into a docs folder as quite large
