### ISSUE TITLE
Review my project & profile

### ISSUE THREAD

**Issue by Mayank0255** [EddieHubCommunity/support#686]
Hi, @eddiejaoude! Can you please review my GitHub profile as well as my portfolio? If yes, then please give your valuable feedback. Thank you in advance!

Items we can review on a live stream:

__GitHub profile:__ [Mayank0255](https://github.com/Mayank0255)
__Open source project__: [StackOverflow CLONE](https://github.com/Mayank0255/Stackoverflow-Clone)
__Portfolio__: [Website](https://mayank0255.github.io/)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing Mayank 👍 . Yes I will review on a live stream or video soon 🤓

**Comment by Mayank0255** [comment]
Looking forward to a productive and learning review sir😃

**Comment by eddiejaoude** [comment]
Looks good, some of my thoughts https://youtu.be/MJ4NOZnug6g

- Suggest moving the video demo to the top of the README
- maybe have 1 screenshot higher up in the README and move the rest to a docs folder
- could `sql` data files be moved to a `data` folder to clean up the root
- a release would be useful too
