### ISSUE TITLE
Review my Open Source Projects & Profiles

### ISSUE THREAD

**Issue by praveenscience** [EddieHubCommunity/support#688]
Items we can review on a live stream:

- GitHub profile: [praveenscience (Praveen Kumar)](https://github.com/praveenscience/)
- Open source projects:
    - [Internship-LMS-FrontEnd](https://github.com/praveenscience/Internship-LMS-FrontEnd): We are in the mission of solving a crisis for a lot of small and medium enterprises, who are trying to recruit interns for their projects. This platform aims to onboard new interns, who have applied to the companies and help them understand the process and make the transition smooth.
    - [FullStack-Nov-React](https://github.com/praveenscience/FullStack-Nov-React): Part of Full Stack React course - the React JS part.
    - [Bootstrap-React-Helpers](https://github.com/praveenscience/Bootstrap-React-Helpers): Helpers for the Bootstrap 4 CSS Framework, if you don't want to use ReactStrap, etc.
    - [GfG-Leadstagram](https://github.com/praveenscience/GfG-Leadstagram): This is full stack application to demonstrate how we can use JavaScript for Full Stack Development.
- Portfolio: [Praveen Kumar Purushothaman](https://praveen.science/)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu): Joined and moderating! 😁

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity): Yea, I know! 😅

**Comment by eddiejaoude** [comment]
Thanks for sharing Praveen 👍 . I will review on a live stream or video soon 🤓

**Comment by eddiejaoude** [comment]
Looks good, some of my thoughts https://youtu.be/MJ4NOZnug6g

- Deployed demo url
- A demo video would help too
- The description could be reduced, by moving the mission statement to the README
- Missing `Installation and running`
- Check if works ok in dark mode of GitHub 
- Code of Conduct is needed
- Open source license
