### ISSUE TITLE
Open-Source Project Review

### ISSUE THREAD

**Issue by HarshCasper** [EddieHubCommunity/support#689]
Items we can review on a live stream:

- Project: https://github.com/harshcasper/HelpingHand 
- Significance: AI-powered Assistance and Navigation App for Visually Impaired People
- Achievements: Won the First Prize in MLH Fellowship Sprint 0 Hackathon 

Built with @yashk2000 and @agg-shambhavi

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by eddiejaoude** [comment]
Project looks really good, reviewed on live stream https://youtu.be/djpH43hsOJI

- Readme looks great
- deployment environments looks inactive
- project board looks complete
- creating a Release/tag
