### ISSUE TITLE
Open Source Project Review

### ISSUE THREAD

**Issue by tintindas** [EddieHubCommunity/support#691]
Items we can review on a live stream:

- GitHub profile: [tintindas](https://github.com/tintindas)
- Open source project: [YNWA mailer](https://github.com/tintindas/ynwa-emailer)
- What it does: E-mails you a live countdown timer for your favourite football team's next match.

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by tintindas** [comment]
Great! Can't wait for the video!!!

**Comment by eddiejaoude** [comment]
Looks great, you have recent activity, reviewed on live stream https://youtu.be/djpH43hsOJI

- Contributing.md and Code_of_conduct.md have the same contents, suggest splitting 
- Suggest using issues and pull requests
- `test` script does not need the `exit 1` at the end
