### ISSUE TITLE
[FEATURE REQUEST] <Discord Icon on the HOMEPAGE>

### ISSUE THREAD

**Issue by AdiSuyash** [EddieHubCommunity/support#7000]
### Description of feature request, idea

Replace the Messaging Icon on the Home Page by Discord Icon for people to have more accessibility to join the Discord Server.
Also add it to every place where the social links are given (Attachments Below)

![Screenshot 2023-03-09 212623](https://user-images.githubusercontent.com/116362593/224081803-8817cd0d-f86e-42bf-a951-fbe97102c2a3.png)
![Screenshot 2023-03-09 212800](https://user-images.githubusercontent.com/116362593/224081809-994d36b9-b258-4e8b-82a7-55b04a6d1b86.png)

**Comment by AdiSuyash** [comment]
I want to contribute the issue

**Comment by Pradumnasaraf** [comment]
> I want to contribute the issue

Hey,

That's a great point. The website is not Open Source. So you can't make changes.

**Comment by SaraJaoude** [comment]
Currently the low code platform we use to create and manage the website does not support a Discord icon.  I will look into this.

**Comment by AdiSuyash** [comment]
Thanks for letting me know about this.
