### ISSUE TITLE
GitHub profile & Portfolio review

### ISSUE THREAD

**Issue by AnkushSinghGandhi** [EddieHubCommunity/support#745]
GitHub Profile: https://www.github.com/ankushsinghgandhi
Portfolio: https://ankushsinghgandhi.me
Repo: https://github.com/AnkushSinghGandhi/ankushsinghgandhi.github.io

**Comment by w3bdesign** [comment]
@AnkushSinghGandhi 

Looks good based on what I can see, just a few tips/ideas:

Implement light/dark mode in your portfolio website.

Temporarily remove the project category under "Projects" seeing that it is empty

**Comment by AnkushSinghGandhi** [comment]
Ok I'll try to implement that as well and Thank you : )

**Comment by w3bdesign** [comment]
Test

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by w3bdesign** [comment]
https://github.com/AnkushSinghGandhi/ankushsinghgandhi.github.io/pull/8

**Comment by Prathamkrishna** [comment]
> GitHub Profile: https://www.github.com/ankushsinghgandhi
> 
> Portfolio: https://ankushsinghgandhi.me
> 
> 

damn love your website man!!

**Comment by AnkushSinghGandhi** [comment]
> @AnkushSinghGandhi
> 
> Looks good based on what I can see, just a few tips/ideas:
> 
> Implement light/dark mode in your portfolio website.
> 
> Temporarily remove the project category under "Projects" seeing that it is empty

Going to add some basic projects today.

**Comment by RutvikJ77** [comment]
Great portfolio website 👍. Just so you know there is a typo in developer.

**Comment by AnkushSinghGandhi** [comment]
> Great portfolio website . Just so you know there is a typo in developer.

ohk fixed that

**Comment by eddiejaoude** [comment]
Looks good, using releases too 👍 , reviewed on live stream, here are some feedback from the EddieHub community...

- Bio in the repo could contain more info about you (1 sentence)
- Is a templated used? If yes suggest including info + link to template project
- Recommend using issues

https://youtu.be/djpH43hsOJI
