### ISSUE TITLE
ssh tunnel is communication tunnel by Open ssh protocol

### ISSUE THREAD

**Issue by alexgector1104** [EddieHubCommunity/support#7483]
ssh tunnel is communication tunnel by Open ssh protocol

_Originally posted by @CleverHolmes in https://github.com/EddieHubCommunity/support/discussions/7482#discussioncomment-5950329_

**Comment by CleverHolmes** [comment]
That's not so difficult please contact me

**Comment by schmelto** [comment]
Is this something you want to implement to this repo?
I close the issue for now feel free to reopen.
