### ISSUE TITLE
Review opensource project and profile

### ISSUE THREAD

**Issue by ankushKun** [EddieHubCommunity/support#757]
Hi,
please review my 
GitHub Profile : [https://github.com/ankushKun](https://github.com/ankushKun),
Portfolio Page : [https://ankushKun.github.io](https://ankushKun.github.io)
and 
Opensource project : [https://github.com/ankushKun/weebmax](https://github.com/ankushKun/weebmax)
It is a manga(japanese comic) scraper that scrapes and saves manga in pdf format

Thank You very much ☺️

**Comment by AnkushSinghGandhi** [comment]
awesome

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by schmelto** [comment]
hey @ankushKun for your portfolio may take a look at the accessibility / readability of your text. Due the text is very dark and the background sometimes the text is nearly invisible.

![image](https://user-images.githubusercontent.com/30869493/116775078-0f4a2880-aa61-11eb-88ce-e0ea9034fcd7.png)
![image](https://user-images.githubusercontent.com/30869493/116775081-1a04bd80-aa61-11eb-9402-37aa58665f03.png)

**Comment by schmelto** [comment]
@nhcarrigan think the livestream label is missing here

**Comment by schmelto** [comment]
Some more suggestions from my side lol

* take a look at this page https://github.com/ankushKun/weebmax/community of your open source project
* add a gif or a screenshot
* maybe consider using conventional commits, make more with issues and Pull Requests

**Comment by kaiwalyakoparkar** [comment]
Hey @ankushKun The profile is very good. But I would love to give you some suggestion
- You can put the languages and the GitHub stats side by side to optimize the space
