### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by KaKashi1210** [EddieHubCommunity/support#7578]
### Name

Aditya Dafe

### Discord Username (if applicable)

kakashifr#8596

### Additional Context

Plz invite me to org

**Comment by ShivaniPaswan** [comment]
Hi @KaKashi1210 , 
1. Use can use below [link ](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) to raise an issue & automatically join EddieHub GitHub Organization.
2. Here, you can join discord using this [link](https://discord.com/invite/jZQs6Wu

**Comment by schmelto** [comment]
you are already part of the organization :)
