### ISSUE TITLE
Review project: Graduate Admissions Prediction Web App 

### ISSUE THREAD

**Issue by Agrover112** [EddieHubCommunity/support#759]
A web app made using Python and Stresmlit that predicts chance of admission based on various scores.

- github.com/Agrover112
- https://github.com/Agrover112/Graduate_Admissions_Prediction

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by schmelto** [comment]
@nhcarrigan the livestream review label is missing here :)

**Comment by nhcarrigan** [comment]
ty

**Comment by eddiejaoude** [comment]
Reviewed on the live stream https://youtu.be/S8aiCHR2gzg

Looks really great, some thoughts:
- folder names are not consistent, suggest using 1 style
- suggest having a Code of Conduct
- suggest having a contributing file
- suggest having an issue template
- great to have screenshots in the README
- great to see the project board being used
