### ISSUE TITLE
[BUG] Twice Same Link

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/support#7601]
### Description of the bug

Welcome DM has been Written down two times, but we only required one "Welcome DM"

### Project stack or language (e.g. front-end)

Front-End

### Working Environment (e.g. operating system, browser, device)

Only Remove this below one "Welcome DM", because I think it has been written twice Mistakenly

### Please add screenshots (if applicable)

![image](https://github.com/EddieHubCommunity/support/assets/111564362/be3ebbe9-560a-40f9-b07d-69145718b5f0)

**Comment by utkarsh95-dev** [comment]
Hi can i be assigned this task, if none is working on it??

**Comment by schmelto** [comment]
> Hi can i be assigned this task, if none is working on it??

I assigned you @utkarsh95-dev

**Comment by utkarsh95-dev** [comment]
Hi, I think the issue was in   docs > _layout> sidebar.md Its already resolved, please let me know if this issue still persist in some other part of the code I'll address it right away
