### ISSUE TITLE
Please review my resume 

### ISSUE THREAD

**Issue by mohitrakhade20** [EddieHubCommunity/support#773]
GitHub id : mohitrakhade20 :heart: 
resume is attached 
[Mohit's Resume 2021.pdf](https://github.com/EddieJaoudeCommunity/support/files/5868737/Mohit.s.Resume.2021.pdf)
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by sreekaransrinath** [comment]
I have a couple of tips already - 

- Schooling is mostly unnecessary, college will do
- Display more metrics in each experience
- Certifications are not recommended - use that space to show off something you did!
- Two column resumes are not ATS friendly - maybe switch to a single column template? Here's a neat ATS parser tool - https://itsjafer.com/#/parser
- Remove your photo & DOB, it's mostly unnecessary and sometimes even frowned upon

**Comment by mohitrakhade20** [comment]
Thank You @sreekaransrinath , what do you think @eddiejaoude on this same points

**Comment by sreekaransrinath** [comment]
Added some points :)

**Comment by mohitrakhade20** [comment]
This are really good ping points you analysied 
Thank You @sreekaransrinath 
I will work on it

would love connect with you

**Comment by vinzvinci** [comment]
My suggestion:
- Host your **resume** online, you could do it in your **portfolio**

> Because I don't think everyone wants to download resume specially when you want someone to review your resume.

**Comment by sreekaransrinath** [comment]
> This are really good ping points you analysied
> Thank You @sreekaransrinath
> I will work on it
> 
> would love connect with you

My social profiles are tagged on my github :)

**Comment by sreekaransrinath** [comment]
> My suggestion:
> 
> * Host your **resume** online, you could do it in your **portfolio**
> 
> > Because I don't think everyone wants to download resume specially when you want someone to review your resume.

This is great! You don't even need a website, all you need is an index.html page displaying your resume

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by eddiejaoude** [comment]
Thanks for submitting @mohitrakhade20 and thank you for logging the live stream link and closing 👍
