### ISSUE TITLE
Please review my resume!

### ISSUE THREAD

**Issue by sreekaransrinath** [EddieHubCommunity/support#774]
**Remove all personal data, otherwise the resume will be deleted.**

Removed everything except email ID
Link to my resume - https://sreekaransrinath.github.io/img/SreekaranSrinath_Resume.pdf

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 - I will review in a live stream / video soon 🤓

**Comment by eddiejaoude** [comment]
Link does not work

**Comment by sreekaransrinath** [comment]
> Link does not work

I've been porting things around recently - please find it here @eddiejaoude https://skrn.ml/resume.pdf

**Comment by sreekaransrinath** [comment]
Caught this in the nick of time - I hope it can still be reviewed!

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by eddiejaoude** [comment]
Thanks for submitting @sreekaransrinath  and thank you @nhcarrigan for logging the live stream link and closing 👍
