### ISSUE TITLE
{Test} GitHub over Linkedin [ please visit my profile and follow] (I will close this issue)

### ISSUE THREAD

**Issue by mohitrakhade20** [EddieHubCommunity/support#775]
**Remove all personal data, otherwise the resume will be deleted.**

Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓

**Comment by Vyvy-vi** [comment]
I think this issue was supposed to be closed 🤔

**Comment by eddiejaoude** [comment]
lol oh yes, maybe, I didn't read the title but looked at the label 🤦‍♂️ 

@mohitrakhade20 if this is a test issue please close

**Comment by eddiejaoude** [comment]
I will close because @mohitrakhade20 has their resume here https://github.com/EddieHubCommunity/support/issues/773
