### ISSUE TITLE
Open Source Project Review

### ISSUE THREAD

**Issue by sadok-f** [EddieHubCommunity/support#777]
Items we can review on a live stream:

- Open-source project: https://github.com/flyimg/flyimg : dockerized application can run as a microservice to resize and crop images on the fly.

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by Rahma-AlWadhahi** [comment]
- Good documentation in README
- I think that it would be good to separate those sections into sub markdown files in `docs` folder

**Comment by kaiwalyakoparkar** [comment]
- Make the about section a bit small
- Add  Issue templates
- Add Pull request template
- Add Repository admins accept content reports

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions...
- some badges are broken
- readme is quite long, suggest breaking up (table of contents not required as GitHub provides this feature now)
- love the releases and versioning

**Comment by rohank2502** [comment]
Changes

Link number 5 is broken
Cloud run button size can be reduced
Add dimension units in the whole readme
JetBrains badge is broken
Read me can be broken by add dropdown
Read me can be made short and I liked that explanation is good!
