### ISSUE TITLE
Open source project review

### ISSUE THREAD

**Issue by vj-abishek** [EddieHubCommunity/support#778]
Items we can review on a live stream:

- [Open source project](https://github.com/vj-abishek/airdrop)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream or video soon 🤓

**Comment by vj-abishek** [comment]
Oh no

**Comment by eddiejaoude** [comment]
Sorry @vj-abishek . I will reopen this 🤓

**Comment by schmelto** [comment]
@nhcarrigan can you also add here the livestream label?

**Comment by kaiwalyakoparkar** [comment]
- Add Contributing.md
- Add Issue templates
- Add Pull request template

**Comment by rohank2502** [comment]
-Liked Read Me It looks great and eye-catching!! 
-Like the way, you have made Dropdown in FAQ sections !! 
- Make the `L` of Dark Light mode in Readme capital ( enhancement  ) 

![Screenshot 2021-05-10 215100](https://user-images.githubusercontent.com/76584243/117691699-d38a2e00-b1d9-11eb-9bd4-e09f6fb7f212.png)
-Got this when I Login from Github!

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions
- different environments looks great
- use GitHub Actions more, for example script commands https://github.com/vj-abishek/airdrop/blob/master/package.json#L65
