### ISSUE TITLE
[REVIEW] Deveesh-Shetty GitHub Profile

### ISSUE THREAD

**Issue by Deveesh-Shetty** [EddieHubCommunity/support#7966]
### GitHub Profile Link

https://github.com/Deveesh-Shetty

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream, some suggestions...

- move social badges higher up profile
- try to do more code reviews, issues and pull requests

**Comment by Deveesh-Shetty** [comment]
Thank you for the review! Will try to improve on these factors
