### ISSUE TITLE
[REVIEW] Resume Matcher

### ISSUE THREAD

**Issue by srbhr** [EddieHubCommunity/support#8036]
### Project link

https://github.com/srbhr/Resume-Matcher

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- reduce repo topics
- create releases
- hide packages
- be consistent with naming conventions
- wiki is not used, so hide wiki tab
-

**Comment by srbhr** [comment]
Thank you @eddiejaoude for the review. Live stream was awesome! 🔥🔥🔥
