### ISSUE TITLE
[Review] LinksHub

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/support#8055]
### Project link

https://github.com/rupali-codes/LinksHub

**Comment by eddiejaoude** [comment]
Looks great, reviewed on live stream, some suggestions...

- semver releases
- tables of contents is generated by GitHub already

**Comment by rupali-codes** [comment]
> Looks great, reviewed on live stream, some suggestions...
> 
> * semver releases
> * tables of contents is generated by GitHub already

Thanks @eddiejaoude, looking forward to it!
