### ISSUE TITLE
UNSUBSCRIBE [OTHER]

### ISSUE THREAD

**Issue by AbdulMuhaimin-1** [EddieHubCommunity/support#8091]
### What would you like to share?

Please how do i unsubscribe from the **[EddieHubCommunity/support] Please add me to EddieHub API** mailing list and also the Invite issues, when ever anyone creates an invite, i get a mail. I can remember subscribing to something like that but the mails are too much, please help.

**Comment by schmelto** [comment]
take a look here:
<img width="1382" alt="image" src="https://github.com/EddieHubCommunity/support/assets/30869493/08fffbeb-4f88-434d-8c70-ef1566cef752">

**Comment by AbdulMuhaimin-1** [comment]
Thanks alot...
