### ISSUE TITLE
I am trying to join EddieHub discord but my phone number is not getting verified 

### ISSUE THREAD

**Issue by 2div** [EddieHubCommunity/support#8190]
### What would you like to share?

I am trying to join EddieHub discord but my phone number is not getting verified.

I want to join the community on discord but i cant chat until i confirm my phone number.

First i enter my number and after it ask me are you human ? after i answer the question and it go back to enter your phone form and it wait 3sec and then says " Unable to send sms message  "

kindly advise ?

**Comment by 2div** [comment]
Hi
Thank you for your message.
I am trying to join discord but it is not accepting my phone number and I
can't get sms code .

What should I do? I want to join the discord

**Comment by schmelto** [comment]
did you get in the discord? otherwise I suggest getting in contact with Discord.

**Comment by 2div** [comment]
Yes i did thanks
