### ISSUE TITLE
Please Review My Profiles

### ISSUE THREAD

**Issue by aathikahamed** [EddieHubCommunity/support#822]
Please review my profiles:

- GitHub profile => [link](https://github.com/aathikahamed)
- Portfolio => [link](https://www.aathik.com/)
- Resume => [link](https://docs.google.com/document/d/1KVEuQ7n6Ah2_CEiFnYsbXIUhZVNCD-U1ezaUuxJRH0Y/edit?usp=sharing
)

Feedbacks are much appreciated 😊

**Comment by schmelto** [comment]
Two little things from me:

- change copyright from 2020 to 2021 at your portfolio page
- maybe you can add a link to your university in your profile readme

**Comment by eddiejaoude** [comment]
Thank you @aathikahamed for sharing 👍 , I will review in a live stream / video soon 🤓

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by eddiejaoude** [comment]
Thanks for submitting @aathikahamed  and thank you @nhcarrigan for logging the live stream link and closing 👍
