### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Vijaykv5** [EddieHubCommunity/support#8242]
### Name

Vijay KV

### Discord Username (if applicable)

vijay0599

### Additional Context

I'm not able to join via discord server link to the eddie hub organisation.
Showing below error. May you invite me Up 

<img width="1062" alt="Screenshot 2023-09-29 at 10 55 30 AM" src="https://github.com/EddieHubCommunity/support/assets/94985341/94add869-7381-40c4-8cb3-9343fbe635bf">

**Comment by mehra-sourav** [comment]
You might have received an invitation email, @Vijaykv5  . You can join through there.

**Comment by schmelto** [comment]
Hope you have joined now. If not feel free to reopen
