### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by manogna-chinta** [EddieHubCommunity/support#8257]
### Name

manogna 

### Discord Username (if applicable)

manogna#6792

### Additional Context

In discord ,The assistance needed , To explore more about open source

**Comment by mehra-sourav** [comment]
You might have received an invitation email, @manogna-chinta . You can join through there.

**Comment by manogna-chinta** [comment]
I checked but didn't receive any

**Comment by schmelto** [comment]
you are already part of the org :)
