### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by chryzcodez** [EddieHubCommunity/support#826]
Please I would really love to contribute to this community, I would be happy and glad to invited in as a contributor to this great Github Community Organisation.

- __Name:__ Olanrewaju Alaba

- __Discord Username(if exists):__ chryz_codez#2321

- __Additional Context:__
  - __How did you meet Eddie?__
    I met him virtually indirectly from his YouTube channel based on open source videos and the likes and I also needed to send him a direct message which he replied to, linking me to this great community.

  - __What is the aim of joining this community?__
   I have been learning a lot about open source and I love to help, contribute and raise ideas for the progress of everyone, the society especially.
   I joined this community also to implement what I've learnt along the way and also meet with great talents to move things forward.

**Comment by eddiejaoude** [comment]
The issue was not created with the correct type, so the GitHub action can not invite you. I will add the label manually and let's see if it works

**Comment by eddiejaoude** [comment]
Yay it worked 🎉

**Comment by chryzcodez** [comment]
> Yay it worked 🎉

Yes, Eddie. Am so happy
