### ISSUE TITLE
Application for GH CodeSpaces

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#830]
Hey @eddiejaoude. You said to open a GH Issue for you to try help us getting access to CodeSpaces sooner.

Here is my GH profile: https://github.com/SashoStoichkov

**Comment by eddiejaoude** [comment]
Thanks Alex 👍

**Comment by SashoStoichkov** [comment]
Thank YOU, Eddie 💪🏻 🤓

**Comment by eddiejaoude** [comment]
I will close for now
