### ISSUE TITLE
Please review my GH Profile

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#831]
Items we can review on a live stream:

- GitHub profile: [SashoStoichkov](https://github.com/SashoStoichkov)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓

**Comment by SashoStoichkov** [comment]
Reviewed on live stream - https://youtu.be/eXqqS6CRTOQ?t=2120

**Comment by eddiejaoude** [comment]
Thanks for logging Alex! I will closed if now reviewed 🤓

**Comment by SashoStoichkov** [comment]
I thought I closed it. Sorry, my bad 😅
