### ISSUE TITLE
A Day in a life of a GitHub Star video

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [EddieHubCommunity/support#833]
I like watching Day in a life video on Youtube as it helps to know the person better, So here are some suggestion what you can add in the video:- 
- what you do in a day besides work like spending time with family, going gym, playing with a pet, etc.
- Now how you work in your office, behind the scene 
- Hows your working style 
- Some tips to increase Productivity that you use in your daily life
- How you deal with the meetings, behind the scene 
- how you work on Project

Many things can be added but it's up to you if you are comfortable with it😊

Hey folks if you want some task to be added do comment👇

**Comment by NehaKoppikar** [comment]
I would also like to know about the really complex equipments Eddie uses during the livestreams

**Comment by SashoStoichkov** [comment]
Yeah, setup tour will be very interesting 😍

**Comment by eddiejaoude** [comment]
Thank you all 👍 these sound like great videos, I will do them for sure 👍

**Comment by vj-abishek** [comment]
Waiting for this video 🤩

**Comment by eddiejaoude** [comment]
Cool, this is almost at the top of my list 🤓

**Comment by eddiejaoude** [comment]
I am going to make this a priority before I move to Portugal, then I can do another one in a few months from Portugal to compare 🤓

**Comment by krishdevdb** [comment]
stale-bot 🤦🏻 How about increasing the interval of the stale message, btw the label doesn't match the one specified in the action, there is no pull-req label in the action too!

**Comment by Panquesito7** [comment]
> How about increasing the interval of the stale message

I think 1 month is enough; no more time is needed IMO.

**Comment by Panquesito7** [comment]
I think the `no-issue-activity` label should be removed when someone sends a comment. Just an idea.

**Comment by krishdevdb** [comment]
> I think the `no-issue-activity` label should be removed when someone sends a comment. Just an idea.

the action will trigger after 30 days so how could it remove it?
