### ISSUE TITLE
Review my open source project

### ISSUE THREAD

**Issue by Levminer** [EddieHubCommunity/support#834]
Hi!

Please review my open source project:

https://github.com/Levminer/authme

It's a 2FA cross-platform app for desktop.

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream / video soon 🤓

**Comment by Levminer** [comment]
Still relevant.

**Comment by schmelto** [comment]
Love the project only one thing maybe replace the image with a GIF in the readme :)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Our thoughts
- commit messages could be more descriptive, for example conventional commit message
- `gitignore` should be lowercase
- great use of releases/tags
- screenshot in readme is great, could be higher rest
- project board being used is great, a link to it in the README would be really useful to users

**Comment by Rishit-dagli** [comment]
Another suggestion I have would be to maybe add badges for the Build and CodeQL Actions you are using in the README.

**Comment by vinzvinci** [comment]
​Another suggestion: `Make assets folder to organize those files like js, image and etc.`
