### ISSUE TITLE
Please invite me to eddieHub organization

### ISSUE THREAD

**Issue by kenkirito** [EddieHubCommunity/support#836]
Name:- lakshya mishra
Discord:- kenkirito championa#0833

Please add me to Eddie Hub origination. Really love this community ✌☺ thank you

**Comment by vj-abishek** [comment]
@kenkirito, please use `Invitation to the GitHub Community Organization` issue template for automatic organization invitation. This method takes time, to send invitation

**Comment by eddiejaoude** [comment]
thanks @vj-abishek 👍 

@kenkirito I will add the correct label, and I think the GitHub Action will pick it up and send you an invite
