### ISSUE TITLE
Invalid links in Discord Readme 

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#839]
**Description**

In the Readme channel are invalid links to other channels. 

**Working Environment**

Discord 

**Screenshots**

![Screenshot_20210202_075343.jpg](https://user-images.githubusercontent.com/30869493/106563417-04e4c500-652c-11eb-9bc1-2248db1e3cce.jpg)

[Optional] **Additional Context**

Channels marked with `#invalid-channel`

**Comment by chryzcodez** [comment]
I already wanted to make an issue on this but it is better like this, I think the issue here is due to the change of the name of the community which led to the change of the existed links leading to the community.

- I would make a pull request on than now
  - Removing the existed link in the Gitub community and
  - Adding the new link created for the community

I fee this is what all this is about

**Comment by schmelto** [comment]
> I already wanted to make an issue on this but it is better like this, I think the issue here is due to the change of the name of the community which led to the change of the existed links leading to the community.

That's a good point!

But I think the channel links are only invalid cause @eddiejaoude chnaged the channel structure (added some new deleted old ones) and forgot to modify the Readme.

We could make this within the eddiebot. Checking for new and deleted channels and update the Readme in discord. Don't know it the discord API is capable of this but I'm optimistic.

**Comment by eddiejaoude** [comment]
For the `#readme` channel in Discord, I copy and paste it manually from here https://github.com/EddieHubCommunity/support/blob/main/discord-readme.md

When this markdown file is updated, I can update it on Discord - not sure we need to automate it because it does not often change

**Comment by schmelto** [comment]
> When this markdown file is updated, I can update it on Discord - not sure we need to automate it because it does not often change

@eddiejaoude markdown is updated 🚀

**Comment by eddiejaoude** [comment]
Awesome thanks everyone 👍  I will update the `#readme` channel
