### ISSUE TITLE
Github action text on github mobile app

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#853]
**Description**

Text is not formatted correctly on GitHub mobile app. 

**Working Environment**

Operating System: Android 

Device: Huawei P10 

**Screenshots**

![Screenshot_20210203_165321~2.jpg](https://user-images.githubusercontent.com/30869493/106772783-a3624a80-6640-11eb-9b5b-640cbd15c6d5.jpg)

[Optional] **Additional Context**

May we can change the text to `... Issue and welcome to... `

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Oh good spot, thank you 👍

**Comment by rish-singhal** [comment]
so should we change the text to ... Issue and welcome to...? it seems fine I guess. What do you think @eddiejaoude ? or can there be any other workaround?

**Comment by Nishant123412** [comment]
I think we should just remove the exclamation mark. Makes sense?

**Comment by eddiejaoude** [comment]
What ever is easier to make it correct, will be an improvement 👍 , then we ca tweak further in the future if needed
