### ISSUE TITLE
The Discord invite code is invalid

### ISSUE THREAD

**Issue by jasonberryman** [EddieHubCommunity/support#857]
**Description**

When clicking on any of the Discord links, I receive the message...
`This invite is invalid or you may not have permission to join`

**Working Environment**

Operating System (eg Linux): Mac OS 11.1

Browser (eg. Chrome): Google Chrome Version 88.0.4324.96 (Official Build) (arm64)

Device (eg. Laptop or Phone): Mac Mini (M1, 2020)

**Additional Context**
### Expiration:
Your invite link may have expired. In this case, please contact the server owner and ask them for a new invite.

### Invalid Code:
You may not have a legitimate invite code. Please check your code and try again. Remember that invite codes -are- case sensitive!

### Ban:
You may have been banned from joining this server. Bans are based on IP address, so you would need to contact the server admins and ask them to revoke all bans in their Server Settings. Just because they remove your name, does not mean the invite will work.

### 100 Server Limit:
A user cannot be a member of more than 100 servers. If you are in too many servers, you'll need to leave one before you can join.

**Comment by eddiejaoude** [comment]
oh no, thank you for letting us know. Which link did you click and where?

**Comment by eddiejaoude** [comment]
I tested the link we use in most places, for example the bottom of our website and it seems to work ok https://eddiehubcommunity.github.io

**Comment by jasonberryman** [comment]
https://discord.com/invite/jZQs6Wu

**Comment by jasonberryman** [comment]
Okay. So I opened this in an Incognito Window and it works.  There's clearly an issue at my end.

**Comment by eddiejaoude** [comment]
No worries, it happens to us all 🤓
