### ISSUE TITLE
Review vatsal's GitHub portfolio

### ISSUE THREAD

**Issue by plazzy99** [EddieHubCommunity/support#862]
Items we can review on a live stream:

- GitHub profile : https://github.com/plazzy99
- Open source project 
- Portfolio : https://bit.ly/vatsal-portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 . I will review on a live stream / video soon 🤓

**Comment by galahad42** [comment]
Looks good though I would strongly suggest not to use URL shortener for your portfolio.
URL shorteners make links opaque, which spammers love. The security risk with a shortened URL is you cannot tell where you are going when you click the link, you have to trust the sender. As a result, some organizations teach their employees not to trust shortened URLs, or simply block them at their network gateway.
So it's often not considered a good practice.

**Comment by plazzy99** [comment]
@galahad42 sure i will keep that in mind. Thank you

**Comment by schmelto** [comment]
Bojaa a Notion Page 💪🏼 

**GitHub Profile:**
* love it!
* maybe link `@DSCJSSATEN`, `@bashwomancomm`, ...

**Portfolio:**
* do the color codes mean something?
* It's notion as mentioned above I like it 😄

**Comment by Cahllagerfeld** [comment]
One Icon is not readable in darkmode:
![image](https://user-images.githubusercontent.com/43843195/115270939-1c037e00-a13d-11eb-8956-5d8194ff3488.png)

**Comment by siddharthdayalwal** [comment]
A justified alignment would look better for me! :+1:

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good

- I am not too keen on the profile view counter
- technologies in the banner and tech stack section do not match up, suggest only have 1 place for them
- `@bashwomancomm` `@CodechefJSSATEN` `@DSCJSSATEN` would add more value if it was a clickable link
- great to see you part of many organisations
- Django logo does not show well in dark mode
