### ISSUE TITLE
What more Projects should I make?

### ISSUE THREAD

**Issue by kitarp29** [EddieHubCommunity/support#870]
https://github.com/kitarp29
My list of projects here- https://kitarp29.github.io/onlineCV/beckham/portfolio.html
I am currently working with a startup and learning AWS. It's simply AWSome!

Should I keep making weekend Projects or Should I focus on developing a Product (for the real world users)?
Competitive Programming and Opensource Contribution will be going on for me irrespective of everything

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by schmelto** [comment]
What is a weekend project for you?

**Comment by kitarp29** [comment]
Any Project that is small and interesting. It can be based on an interesting API like WebRTC, etc. Or any idea that excites me.

**Comment by Akshu-on-github** [comment]
Have you tried the Spotify API? It's pretty neat

**Comment by kitarp29** [comment]
That API is no doubt interesting. 
But a Project on that would need me to make a Frontend before deploying. 
And as time has passed I don't enjoy making UI.
Backend stuff and making APIs is much more exciting

**Comment by eddiejaoude** [comment]
I will review on a live stream soon, thank you for sharing 🤓

**Comment by siddharthdayalwal** [comment]
this section looks a bit misaligned to me, may be you can have a look around here and maybe create a proper structure! 

![image](https://user-images.githubusercontent.com/41017419/115272337-e9b54900-a15b-11eb-8b84-75e01bda8d21.png)

**Comment by eddiejaoude** [comment]
Reviewing on live stream https://youtu.be/MrS_jAJ8l0o

Look great 👍 

- progress bar as I scroll is EPIC 💥 
- great to see the project demos, it would be great to see the project code link also
- `checkout my resume` does not seem to work

**Comment by metaverde** [comment]
At the bottom of the second page it should read
"It ain't much, but it's honest work."
The comma is currently misplaced and also the "its" is in the possessive form.
English _is _ hard.

**Comment by kitarp29** [comment]
Thanks a lot, Guys.
I will surely update and do the advised changes soon.
