### ISSUE TITLE
Please review aniketsingh98571 profile on Live Stream.

### ISSUE THREAD

**Issue by aniketsingh98571** [EddieHubCommunity/support#879]
Items we can review on a live stream:

- [aniketsingh98571](https://github.com/aniketsingh98571)
- [HeaLearn](https://github.com/aniketsingh98571/HeaLearn)
- [Portfolio](https://aniketsingh98571.github.io/Web-Portfolio/)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by Akshu-on-github** [comment]
A few things that I'd like to point out:
## Your Profile:
- I like the fact that you've used gifs - it makes it look lively!
- Just a thought, but you could add links to the emojis. It looks like a good place to link to other parts of the profile
  ![image](https://user-images.githubusercontent.com/61582763/107122291-ec263780-68bc-11eb-986b-8e080f5c27d1.png)

- I noticed that some of these icons were transparent while others weren't - choosing icons from the same source improves consistency
  ![image](https://user-images.githubusercontent.com/61582763/107122335-2f80a600-68bd-11eb-81b9-3356aa4dd877.png)

- The images look a bit squished - I'd suggest tweaking the `<img>` width attributes
  ![image](https://user-images.githubusercontent.com/61582763/107121290-9c913d00-68b7-11eb-8712-ac9d203da3c6.png)

## Your Portfolio:
- It's reactive, always a huge plus point in my books. Smooth transitions too, nicely done!

- There's a lot of white space to the sides in some sections compared to others. I noticed inconsistency across the headings too. I'd suggest fixing these up

- I'd also suggest a right-justified paragraph here:
 
  ![image](https://user-images.githubusercontent.com/61582763/107122438-c9e0e980-68bd-11eb-9854-fb3403f7ca02.png)

- The white text seems to blend into the background - I'd suggest a shadow to give it some contrast. Or you use a coloured `<div>` for emphasis
 
  ![image](https://user-images.githubusercontent.com/61582763/107122084-b16fcf80-68bb-11eb-9a95-70de62361cb8.png)

Well, I think I'll stop here for now and leave it to Eddie, but thanks a bunch for sharing your projects for review@

**Comment by aniketsingh98571** [comment]
@Akshu-on-github , thanks for your detailed review I will surely look into it.

**Comment by eddiejaoude** [comment]
Thanks for sharing @aniketsingh98571 . I will review soon 🤓 

Looks like you got some great feedback from @Akshu-on-github 👍

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

- `HeaLearn` header under banner is not needed as it is a duplicate with the banner
- `watchers` badge looks out of place with the others
- animated gif is great, but having the alert about your password from chrome does not look great
- great to see the app screenshots 
- `contributing` file would help get more people involved 
- suggest using releases / tags
- suggest using issues so others can get involved 
- `NODE` folder probably best lower case
-
