### ISSUE TITLE
Help me fix Table Markdown on my GitHub Org. PH

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/support#887]
I was setting up GitHub Org. for my local tech community. Can anyone help me fix this?

> Look on the issues first, pull request is welcome.

**Repo Link:** <a href="https://github.com/surpathcommunity/hacktoberfest-philippines">https://github.com/surpathcommunity/hacktoberfest-philippines</a>
**GitHub Page:** <a href="https://surpathcommunity.github.io/hacktoberfest-philippines/">https://surpathcommunity.github.io/hacktoberfest-philippines/</a>
 
![image](https://user-images.githubusercontent.com/73097560/107144093-c1e38100-6973-11eb-9da4-e72ff66545ac.png)

**Comment by Nitesh-thapliyal** [comment]
Created PR, do  check it☺

**Comment by vinzvinci** [comment]
> Created PR, do check it☺

Sure, thanks!

**Comment by vinzvinci** [comment]
Thanks for help @Nitesh-thapliyal , will close the issues now.

**Comment by eddiejaoude** [comment]
Great team work 👍

**Comment by Nitesh-thapliyal** [comment]
Thank you @eddiejaoude ☺
