### ISSUE TITLE
(Help improve) Building a social platform

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/support#907]
Want to get a green square? Anyone can help improve our project.

<a href="https://github.com/Camel-Riders/RoastR">https://github.com/Camel-Riders/RoastR</a>

Language: Python Django, CSS, HTML

**Comment by eddiejaoude** [comment]
maybe a GitHub Discussion might be better?

**Comment by vinzvinci** [comment]
Hmm yeah that would be better @eddiejaoude. I will close this issues now, and I will improve documentation first before creating GitHub Discussion. Thank you ^_^
