### ISSUE TITLE
Redericting to new tab in readme

### ISSUE THREAD

**Issue by Aanandgupta** [EddieHubCommunity/support#908]
when we are clicking on links in readme how can we direct user to new tab like we do with normal html target=_blank
how could we do it in readme

**Comment by schmelto** [comment]
https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link

.md has no such functionality. You can use html tags.

**Comment by chryzcodez** [comment]
I tried using 'HTML` but it wasn't working

**Comment by schmelto** [comment]
Ok sorry haven't looked correctly 😅 https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank seems there is no target in github readme... may some of you have an other solution

**Comment by Aanandgupta** [comment]
Thank you for your responses but Nothing worked for me

**Comment by Nitesh-thapliyal** [comment]
Why don't you attach the new tab link to the text of the readme😅

**Comment by vinzvinci** [comment]
It won't work maybe because it's **security features of GitHub**, they don't allow that thing to work in markdown.

**Comment by Vyvy-vi** [comment]
I _think_ xhtml might make a way(*investigating further on this)

**Comment by Vyvy-vi** [comment]
Checkout the second "Hello World" over here.. It opens into a new tab. 
https://github.com/Vyvy-vi/Vyvy-vi/blob/main/README.md

**Comment by Aanandgupta** [comment]
How was that possible? which command did you used

**Comment by eddiejaoude** [comment]
@Aanandgupta here is the raw file https://raw.githubusercontent.com/Vyvy-vi/Vyvy-vi/main/README.md
