### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Pulkit0076** [EddieHubCommunity/support#916]
Please invite me to the GitHub Community Organisation.

Name: Pulkit Singh

**Comment by Pulkit0076** [comment]
Thank you, I will join the discord once I am eligible for it :)

Thank you for the support

**Comment by Vyvy-vi** [comment]
Thank you for understanding-!
We are inclusive and want to get people into opensource and help them, regardless of age... but in this case we can't really violate Discord's Terms of Service and COPPA rules :+1:
