### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by swetakb15** [EddieHubCommunity/support#931]
Please invite me to the GitHub Community Organisation.

- #### Name:Sweta Barnwal

- #### Discord Username(if exists):swetakb15#2162

- #### Additional Context:

Hello 
My name is Sweta Barnwal. Currently, I'm pursuing B.tech in the CSE stream from the Indian Institute of Information Technology, Kalyani. I am new to open-source contributions. As of now, I have worked in development with technologies like Frontend, different libraries of python, languages in my box are  C,C++,Java and Python . I explore a new tech field and as of now, I want to concentrate in the field of data structures and algorithm. I am an enthusiastic learner and explorer.

:nerd_face:

**Comment by swetakb15** [comment]
I am getting a 404 error.

**Comment by eddiejaoude** [comment]
hi @swetakb15 , could you be more specific about where you are getting the `404`? The GitHub org got renamed recently, so some links have still not be updated - sorry for the confusion (it was `EddieJaoudeCommunity` but is now `EddieHubCommunity`)

You should still get the invitation. I see your invitation is pending, you can accept it by visiting the [organisation page](http://github.com/EddieHubCommunity) and there should be a message at the top, and you should receive an email with a link too. Any issues let us know

<img width="1333" alt="Screenshot 2021-02-17 at 23 41 04" src="https://user-images.githubusercontent.com/624760/108282665-e6acd500-7179-11eb-977d-c95a65b4d284.png">
