### ISSUE TITLE
Resume Review

### ISSUE THREAD

**Issue by avinashupadhya99** [EddieHubCommunity/support#932]
Hi, it would be really awesome if you could review my resume. Thanks.
[Avinash Upadhyaya's Resume](https://drive.google.com/file/d/1jORsPiy3tqFJbsKCuL8QXkt89ZnqT6bZ/view?usp=sharing)

**Comment by vinzvinci** [comment]
Nice! 

- I suggest, host your resume online like your portfolio because not all prefer to download your resume when you want someone to review it.

**Comment by avinashupadhya99** [comment]
Thanks, I'll do that

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 . I will review on a live stream / video soon

**Comment by nhcarrigan** [comment]
Closing as reviewed on the stream :)

**Comment by eddiejaoude** [comment]
Thanks for submitting @avinashupadhya99  and thank you @nhcarrigan for logging the live stream link and closing 👍

**Comment by avinashupadhya99** [comment]
I don't want to give you another GitHub notification. But thanks a lot for reviewing and the feedback.
