### ISSUE TITLE
Kidney Exchange - Project Review

### ISSUE THREAD

**Issue by siv2r** [EddieHubCommunity/support#942]
Hello Eddie,

After participating in MLH Local Hack Day build through the EddieHub guild, I came to know about this community. It has been an amazing experience. Keep doing these amazing works!!

My GitHub profile - [here](https://github.com/siv2r)

My project link - [here](https://github.com/siv2r/kidney-exchange)
Live - [here](https://ke.iitm.ac.in/kidney-exchange/)

**Note:** You will be required to login to access the features of this project. You can use the following info.
**_username:_** admin1
_**password:**_ kep1

Let me know your thoughts! Also, no need to hold back while reviewing :)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review on a live stream / video soon 🤓

**Comment by Prathamesh-Shanbhag** [comment]
Consider adding an Issues Template as well!

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

- in the repo description suggest adding the live demo link
- suggest creating releases / tags
- if not creating packages, suggest hiding in settings
- if not using wiki suggest hiding in settings 
- commit messages are not consistent, suggest using something like husky to check for commit message format / style
- using issues with labels is great 👍 
- missing code of conduct https://github.com/siv2r/kidney-exchange/community
- screenshot in the readme is great

**Comment by siv2r** [comment]
@eddiejaoude @Prathamesh-Shanbhag Thanks for the review :)
Unfortunately, I missed the live stream this time but watched it later. This community is amazing!
