### ISSUE TITLE
Review My profile.

### ISSUE THREAD

**Issue by rootritesh** [EddieHubCommunity/support#946]
- Portfolio(https://rootritesh.github.io/)
- Github(https://github.com/rootritesh)

**Comment by vinzvinci** [comment]
- I think this should be `open source review` label?
- Add `resume review` label if you have resume linked here
- Improve your GitHub profile by adding GIF or any cool cover photo. You can look-><a href="https://github.com/EddieHubCommunity/awesome-github-profiles">awesome-github-profiles</a><- that you can use for inspiration.
- Change your `social media icon`. It will be cool if it's visible in dark mode.

**Comment by rootritesh** [comment]
Thanks for your reviews.

**Comment by eddiejaoude** [comment]
thanks @vinzvinci I updated the labels 👍 

Thank you for sharing your open source project, I will review on a link stream / video soon 🤓

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

- the animation of the circles look great 💥 
- tech stack pills/button seem clickable but do not do anything - suggest removing the cursor and click state
- great blog post section, suggest having a link to the code from your website
