### ISSUE TITLE
Fixing some links

### ISSUE THREAD

**Issue by TawfikYasser** [EddieHubCommunity/support#961]
**Description**

Fix some links to work with the new community name from `Jaoude` to `Hub`

**Comment by vinzvinci** [comment]
Hi @TawfikYasser. I think you should edit this issue and remove these info. below since you didn't use it.

![image](https://user-images.githubusercontent.com/73097560/108696595-b92aa780-753c-11eb-8f0e-f461787534c4.png)

**Comment by TawfikYasser** [comment]
Okay @V2dha  Thanks
