### ISSUE TITLE
Please review my Professional Portfilio

### ISSUE THREAD

**Issue by PulkitSinghDev** [EddieHubCommunity/support#990]
Hi there,
Please review my professional portfilio:-
- <a href="https://pulkitsinghdev.github.io">Portfolio Website</a>
- <a href="https://github.com/PulkitSinghDev/PulkitSinghDev.github.io">Repository</a>

**Comment by PulkitSinghDev** [comment]
@eddiejaoude sir please review my github profile and let me know how is it ?

**Comment by vinzvinci** [comment]
Wow super cool!!! I loved your portfolio, this is what I want to see ^_^. You motivated me to edit my **`Portfolio`** 
 
Maybe add more features? Like your favorite **`Projects`** (that you can explain to somebody?)

**Comment by PulkitSinghDev** [comment]
Thanks, will surely try to add some of my projects as well :)

**Comment by AmineAML** [comment]
This is impressive, a couple of things I've noticed:
* Freecodecamp icon is broken
* The landing page is a bit laggy when moving your cursor over elements, it can be because of the background animation

**Comment by PulkitSinghDev** [comment]
- 
![image](https://user-images.githubusercontent.com/71369943/109648340-83ab3d00-7b80-11eb-87f6-3242f988ba7e.png) I don't think that free code camp 's icon is broken

 - Would like to tell you that background's image is an gif image and it's not any animation :)
and Thank you so much for your reply

> This is impressive, a couple of things I've noticed:
> 
> * Freecodecamp icon is broken
> * The landing page is a bit laggy when moving your cursor over elements, it can be because of the background animation

**Comment by AmineAML** [comment]
![Pulkit Singh portflio](https://user-images.githubusercontent.com/56970286/109727537-d0a90680-7bb4-11eb-9403-5fca780ed1e7.png)
Oh, okay.....but it may not show for some users

**Comment by eddiejaoude** [comment]
Thanks for sharing, I will review on a live stream soon 👍

**Comment by PulkitSinghDev** [comment]
> Thanks for sharing, I will review on a live stream soon 👍

Thank you so much sir :)

**Comment by jai-dewani** [comment]
Maybe consider checking the console errors, your portfolio is throwing out
> DevTools failed to load SourceMap: Could not load content for https://pulkitsinghdev.github.io/assets/vendor/swiper/swiper-bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE 

Also the highlighting hover feature is not working correctly if I directly more from one card to another

**Comment by PulkitSinghDev** [comment]
Hi everyone, as I have got many bugs in the website, The website will be down for some time and will let you all once it's ready :)

**Comment by Vyvy-vi** [comment]
Why not keep it up :)

**Comment by Vyvy-vi** [comment]
You could work on your site in the meanwhile. Having one kinda helps you out.

**Comment by PulkitSinghDev** [comment]
I have fixed the bugs, is it now working correctly ??

**Comment by Prince-Shaikh** [comment]
The website looks amazing!!
One thing I noticed was the menu bar tilting on hover provides a bad user experience, try something else there?

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/116901582-f66f7d80-abee-11eb-9b26-d2040561bdf0.png)

I would strongly recommend removing these - let your projects speak for your proficiency :)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/116901693-19019680-abef-11eb-99b3-f69860830640.png)

Changing the voice/perspective feels a bit clunky imho

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/116901770-2dde2a00-abef-11eb-9c18-07ea74412484.png)

Buttons overlap here

**Comment by Rahma-AlWadhahi** [comment]
I think that it is a bit distracting when I try to click on one of the navigation bar links and this happens
<img width="901" alt="Screen Shot 2021-05-03 at 20 09 14" src="https://user-images.githubusercontent.com/61970868/116901827-71ff1800-ac4b-11eb-9980-51480ab030c5.png">

**Comment by nhcarrigan** [comment]
I agree with @Rahma-AlWadhahi - interactable elements should not move when I try to interact with them.

**Comment by adityaraute** [comment]
1) That title is too long, maybe shorten it up.
![image](https://user-images.githubusercontent.com/43912470/116901630-c90aea00-ac57-11eb-98b6-46cde7586ecc.png)

2) The tilting menu bar is distracting.

3) Replace 'him' with 'me' or 'Pulkit'
![image](https://user-images.githubusercontent.com/43912470/116901768-f2c41100-ac57-11eb-9c7c-e7765bd8cc6f.png)

4) The tilting is distracting, not the best design choice here. The space in the parantheses is irregular. Figure out a way to not use links as texts.
![image](https://user-images.githubusercontent.com/43912470/116902068-55b5a800-ac58-11eb-87db-77124571c3be.png)


5) Get rid of the blue link.
![image](https://user-images.githubusercontent.com/43912470/116902046-4e8e9a00-ac58-11eb-9363-2e76df4d5154.png)

**Comment by schmelto** [comment]
Taka a look at the mobile view of your website
![image](https://user-images.githubusercontent.com/30869493/116902339-4bd17c00-ac3b-11eb-9915-4380263b5bda.png)

**Comment by Prathamesh-Shanbhag** [comment]
### Some Improvements to consider!
- Since the animation is a gif it becomes choppy on initial load, and also after staying on the website for a long time!
- Maybe consider changing it to a CSS Animation
- Also please improve the mobile responsiveness of the website!

**Comment by eddiejaoude** [comment]
Thank you for sharing, reviewed on live stream https://youtu.be/ugEJ8LBb1r0

**Website**
- audio auto plays, not great UX
- typewriter text for the longer text for example `cloud computer enthusiast` the text bounces to the 2nd line multiple times
- testimonials are great 👍 

**repo**
- looks great: use of releases, description, link, tags 💥 
- filenames are inconsistent, suggest using a single style
- syntax highlighting for the html code

**Comment by Rahma-AlWadhahi** [comment]
> To quote [@adityaraute](https://github.com/EddieHubCommunity/support/issues/990#issuecomment-831367424)

I have heard about this website where you can check the color contrast. [Contrast Ratio](https://contrast-ratio.com/)

**Comment by schmelto** [comment]
> I have heard about this website where you can check the color contrast. [Contrast Ratio](https://contrast-ratio.com/). You can check that to help test the colors before using them in the website.
Testing colors also is implemented into lighthouse (integrated in chromium based browsers)

![image](https://user-images.githubusercontent.com/30869493/116905224-fd25e100-ac3e-11eb-9903-0fd16e978c43.png)

**Comment by krishdevdb** [comment]
Simple Addition To @eddiejaoude's comment:

- The Social Icons Are Not Spaced Up.
- The Icons are hard sized. They stretch up

#### Solution
```css
.icon {
display: flex;
justify-content: space-evenly;
align-items: center;
min-width: 0; // Add A Min Width That Suits The Need.
min-height: 0; // Add A Min Height That Suits The Need.
}
```

**Comment by PulkitSinghDev** [comment]
Thank you so much everyone :)
I will take a look on each and everything you all mentioned and will resolve it as soon as possible :)
